Fee handling Improvement
BlueWallet/BlueWallet pull request #1335
Opened 2020-07-07 13:50 UTC by limpbrains

#477

2020-07-07 14:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/haxkr9hg1uyqwr2y7m7xr41v1m

[download apk](http://filestorage.bluewallet.io:1488/1594130510.apk)

2020-07-07 14:27 UTC, ncoelho commented
couldn't use it on appetize, kind of freezes on the send view
https://appetize.io/app/haxkr9hg1uyqwr2y7m7xr41v1m

<img width="327" alt="Screenshot 2020-07-07 at 16 22 22" src="https://user-images.githubusercontent.com/1238429/86796273-b55e1980-c06e-11ea-94e1-e588a935ecfc.png">

2020-07-07 14:46 UTC, limpbrains commented
To calculate fee I’m creating TX each time something changing in the form.
There is a case when TX can’t be built, for example, when wallet is new and UTXO is empty. How do you think, what show in this case?

2020-07-07 16:47 UTC, ncoelho commented
What is the difference there with the current implementation. There’s a suggestion, that is the “fast” option, at the moment on this use case

2020-07-08 12:09 UTC, limpbrains commented
> What is the difference there with the current implementation. There’s a suggestion, that is the “fast” option, at the moment on this use case. In the current master I mean

You can show fee rate, like 2 sat/byte without creating transaction.
To show fee value, like 123 sats you need to create transaction. 
To create transaction you need: UTXO, proper outputs.

If there are no inputs, outputs, or they are not valid (like there not enoght funds) I can try to create fake set of correct inputs/outpust to create TX and to show somethig to user. Or I can just show 2 sat/byte and what for proper input and then calculate absolute fee value

2020-07-08 12:16 UTC, ncoelho commented
Ah ok. Then in the fee label, it should be the rate or the “label/fast”.
That makes more sense

On Wed, 8 Jul 2020 at 14:10, Ivan <notifications@github.com> wrote:

> What is the difference there with the current implementation. There’s a
> suggestion, that is the “fast” option, at the moment on this use case. In
> the current master I mean
>
> You can show fee rate, like 2 sat/byte without creating transaction.
> To show fee value, like 123 sats you need to create transaction.
> To create transaction you need: UTXO, proper outputs.
>
> If there are no inputs, outputs, or they are not valid (like there not
> enoght funds) I can try to create fake set of correct inputs/outpust to
> create TX and to show somethig to user. Or I can just show 2 sat/byte and
> what for proper input and then calculate absolute fee value
>
> —
> You are receiving this because your review was requested.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/BlueWallet/BlueWallet/pull/1335#issuecomment-655479138>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJOLHOXH3MPQBO3J4ZWDYTR2ROZXANCNFSM4OS2ZRMQ>
> .
>

2020-07-11 12:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/arquc251qwxqgbykpcxenag0z4

[download apk](http://filestorage.bluewallet.io:1488/1594470910.apk)

2020-07-11 14:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zkjr315h2mgefy6jjag2hrndw0

[download apk](http://filestorage.bluewallet.io:1488/1594478371.apk)

2020-07-14 10:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/13ut51abjvcxfwur2feph2ktj4

[download apk](http://filestorage.bluewallet.io:1488/1594721159.apk)

2020-07-23 09:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ng9gq733mm46xxv2bg5k8k64rw

[download apk](http://filestorage.bluewallet.io:1488/1595498247.apk)

2020-07-23 11:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d87t33fv0uj9b6duqgqwbu6qm8

[download apk](http://filestorage.bluewallet.io:1488/1595503500.apk)

2020-07-23 12:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qu1b0r1cq94f6dpxmunphakhkm

[download apk](http://filestorage.bluewallet.io:1488/1595507718.apk)

2020-07-24 16:28 UTC, limpbrains commented
@ncoelho please try this version. Do you think I should bring slider back?

2020-08-01 10:02 UTC, limpbrains commented
<img width="200" alt="Screenshot 2020-08-01 at 12 56 14" src="https://user-images.githubusercontent.com/155891/89099294-de1bc980-d3f6-11ea-8590-a30df171793b.png"><img width="200" alt="Screenshot 2020-08-01 at 12 56 31" src="https://user-images.githubusercontent.com/155891/89099305-eecc3f80-d3f6-11ea-9dd1-389b627deb0f.png"><img width="200" alt="Screenshot 2020-08-01 at 12 57 22" src="https://user-images.githubusercontent.com/155891/89099310-f68be400-d3f6-11ea-8b60-5c7c9fbf2d60.png"><img width="200" alt="Screenshot 2020-08-01 at 12 57 38" src="https://user-images.githubusercontent.com/155891/89099325-11f6ef00-d3f7-11ea-8b97-cb90fb749b40.png"><img width="200" alt="Screenshot 2020-08-01 at 12 58 08" src="https://user-images.githubusercontent.com/155891/89099328-18856680-d3f7-11ea-8a81-088855efff76.png">

2020-08-01 10:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/56t5g1b882rf8c4q0ha979c63w

[download apk](http://filestorage.bluewallet.io:1488/1596276581.apk)

2020-08-24 17:32 UTC, Overtorment requested changes

2020-08-24 17:32 UTC, Overtorment commented on screen/send/details.js
> +    for (const opt of options) {
code comments would be nice

2020-08-24 17:32 UTC, Overtorment commented on screen/send/details.js
> +    for (const opt of options) {
If I got it right, this is a loop that creates 3 dummy TXs just to calculate fees.
my main concern is that each tx creation and signature takes a lot of time (hundreds of milliseconds? seconds?) and the whole user experience will be bad because of that. can we measure it to see whats the impact gona be?
also, maybe passing `skipSigning: true` to `createTransaction` can save some time, not sure

2020-08-24 17:32 UTC, Overtorment commented on screen/send/details.js
> +          if (e.message === 'Not enough balance. Try sending smaller amount' && !flag) {
I feel like this will break once someone decides to change text. maybe, `indexOf('Not enough') !== -1` ?

2020-08-24 17:32 UTC, Overtorment commented on screen/send/details.js
> +            // if the outputs are too big, replace them with dust
why not make all outputs in dummy transactions dust by default?

2020-08-24 17:32 UTC, Overtorment commented
@marcosrdz @ncoelho your thoughts

2020-08-24 18:02 UTC, ncoelho commented
I think the title "fast/slow/medium" should be the visible copy and we should change the "fee" label to "priority".

Like:
Priority___________ fast

2020-08-25 09:24 UTC, limpbrains commented on screen/send/details.js
> +            // if the outputs are too big, replace them with dust
To show more accurate results. Fee depends on amount of the tx output. If we have 100 inputs and create tx with one dust output it will be very different if we try to spend them all.

2020-08-25 09:28 UTC, limpbrains commented on screen/send/details.js
> +    for (const opt of options) {
Good idea. I will try to measure it on my slow Android
Another option is to put calculations inside `requestIdleCallback` and try to `debounce` it

2020-08-25 09:36 UTC, limpbrains commented
> I think the title "fast/slow/medium" should be the visible copy and we should change the "fee" label to "priority".

Sorry I don't quite get it. Are you talking about the first screen?
So it would be:
Priority _____ $4.03 ____ fast ?

2020-08-25 10:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r5qq6dhwc2zz1z732wrmdj20g8

[download apk](http://filestorage.bluewallet.io:1488/1598351077.apk)

2020-08-25 12:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/h10yzj68z4hgbz1t8ar14tx4cr

[download apk](http://filestorage.bluewallet.io:1488/1598358893.apk)

2020-08-25 16:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/46z498zrh0x1ndm9ju9w47g7ww

[download apk](http://filestorage.bluewallet.io:1488/1598371345.apk)

2020-08-27 09:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g6avappur5knwdeqjhx7kkcea8

[download apk](http://filestorage.bluewallet.io:1488/1598519985.apk)

2020-08-27 09:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ruu613xu5zjgg9kxzvar2hxmrr

[download apk](http://filestorage.bluewallet.io:1488/1598521711.apk)

2020-09-01 11:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0f0z7du9hcqx8mh5pkq8rt4h74

[download apk](http://filestorage.bluewallet.io:1488/1598960188.apk)

2020-09-01 15:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xh67gmx18dxhncxj2krdk3q2z8

[download apk](http://filestorage.bluewallet.io:1488/1598975480.apk)

2020-09-01 16:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mt3putgv7a94pgq3fyxdnvd3v4

[download apk](http://filestorage.bluewallet.io:1488/1598977389.apk)

2020-09-02 11:38 UTC, Overtorment commented on screen/send/details.js
> +          const { fee } = wallet.coinselect(
so hows the performance now? is it faster?

2020-09-03 11:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7k9et8x0fvdz6cr2g2crxy772c

[download apk](http://filestorage.bluewallet.io:1488/1599132429.apk)

2020-09-03 12:09 UTC, limpbrains commented on screen/send/details.js
> +          const { fee } = wallet.coinselect(
Still having some performance issues, investigating ...

2020-09-04 08:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e8kfw2p42xbdj1nnfqt4bw9rxw

[download apk](http://filestorage.bluewallet.io:1488/1599207402.apk)

2020-09-04 09:02 UTC, limpbrains commented on screen/send/details.js
> +            // if the outputs are too big, replace them with dust
`message.includes('Not enough')` has beed used

2020-09-04 09:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v07uxcn9cyun2cyu3g0rp1yzew

[download apk](http://filestorage.bluewallet.io:1488/1599211772.apk)

2020-09-09 11:04 UTC, Overtorment requested changes
some code duplication & conflicts.
also, can you pls add `coinselect` to `AbstractWallet`, just for any case?

smth like

```
  coinselect(utxos, targets, feeRate, changeAddress) {
    throw Error('not implemented');
  }
```


tested it on my BIP84 wallet on android, works pretty good. I hope there wont be any issues with other wallet types (like legacy single address p2pkh), we have generalized enough code here.

anyways, lgtm, lets finalize it and merge it.

2020-09-10 12:52 UTC, limpbrains commented on screen/send/details.js
> +        feeUnit: fromWallet.getPreferredBalanceUnit(),
We can't show fee in units of amount, because they can be different for each output. 
I don't know to nicely play this out

2020-09-10 13:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r1t5gmtu6wphc2u1h4jng45r7c

[download apk](http://filestorage.bluewallet.io:1488/1599744392.apk)

2020-09-10 14:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k67fgmjrvg6f7q84ahk3k4jx6m

[download apk](http://filestorage.bluewallet.io:1488/1599749922.apk)

2020-09-10 15:30 UTC, marcosrdz commented
Should we have the fee UI and balance toolbar switch unit along the send amount?

2020-09-10 15:35 UTC, marcosrdz approved these changes

2020-09-10 15:37 UTC, marcosrdz commented
> Should we have the fee UI and balance toolbar switch unit along the send amount? @ncoelho 

Oh nvm...just read a previous comment

2020-09-10 15:37 UTC, ncoelho commented
> Should we have the fee UI and balance toolbar switch unit along the send amount? @ncoelho

No, let's keep it simple. Main doubt at the moment is to explain what this to the user. The point of this change was to focus on the end action - transaction "priority". So let me see on how to change it without cluttering the UI

2020-09-10 18:31 UTC, ncoelho commented
to keep this updated. I'm facing slowdowns on this branch. To replicate, open simulator, go to send screen, close it, go do something else, come back in 5 minutes to the app, it doesn't respond.

2020-09-13 11:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5t1rnh05p9qe688zx40y1hqctc

[download apk](http://filestorage.bluewallet.io:1488/1599996050.apk)

2020-09-14 10:49 UTC, merged

2020-09-14 10:51 UTC, Overtorment commented on screen/send/details.js
> +        feeUnit: fromWallet.getPreferredBalanceUnit(),
had an idea how to play this out. keep a global unit setting for all outputs, which is by default is set to `fromWallet.getPreferredBalanceUnit()`. but as soon as user changes unit on any output - this global unit changes as well, and all fee calculations on all outputs should also be in this unit