ADD: Global Message UI
BlueWallet/BlueWallet pull request #1475
Opened 2020-08-11 23:55 UTC by marcosrdz

2020-08-12 00:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6ej2jcn46a6uaq3upme1u5vg14

[download apk](http://filestorage.bluewallet.io:1488/1597192075.apk)

2020-08-12 17:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zca56kfr6v5u3q07dh88htyrm0

[download apk](http://filestorage.bluewallet.io:1488/1597251792.apk)

2020-08-12 23:38 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n3vccm7aftgyw79urudqrq29hw

[download apk](http://filestorage.bluewallet.io:1488/1597275512.apk)

2020-08-13 00:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5ynh39xbgg9y4x1r9zhen2vuj0

[download apk](http://filestorage.bluewallet.io:1488/1597278483.apk)

2020-08-20 14:32 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hb0908v01149gpcv4r2eadyzf8

[download apk](http://filestorage.bluewallet.io:1488/1597933918.apk)

2020-08-20 16:40 UTC, Overtorment commented
screenshots in this kind of PRs would be helpful

2020-08-20 17:02 UTC, Overtorment requested changes
needs more work

2020-08-20 17:02 UTC, Overtorment commented on components/BlueGlobalMessageContext.js
> +  dismissable: true,
dont see, is there an autohide property somewhere? bubbles should hide automatically by default

2020-08-20 17:02 UTC, Overtorment commented on components/BlueGlobalMessageContext.js
> +  type: null,
types should be described somewhere. basically, we need error, warning, info, success

2020-08-23 19:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y5zdmknp5kjtryhrhqf7v27ucm

[download apk](http://filestorage.bluewallet.io:1488/1598210707.apk)

2020-08-23 23:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qvwg927agg5n2qbhy9k8cw7ygr

[download apk](http://filestorage.bluewallet.io:1488/1598224953.apk)

2020-08-23 23:27 UTC, marcosrdz commented on components/BlueGlobalMessageContext.js
> +  dismissable: true,
they do. lines 36         timeout.current = setTimeout(hide, 3000);

2020-08-23 23:28 UTC, marcosrdz commented on components/BlueGlobalMessage.js
> +    this.context.show({ message: "Importing Wallet..."});
EV is needed for non-React functions. non React functions are unable to read React Context

2020-08-23 23:29 UTC, marcosrdz commented on class/wallet-import.js
> +        EV(EV.enum.GLOBAL_MESSAGES_HIDE);
Hide is there for messages that shouldnt autohide..such as wallet import

2020-08-23 23:29 UTC, marcosrdz commented on class/wallet-import.js
> +        EV(EV.enum.GLOBAL_MESSAGES_HIDE);
Hide is for messages that shouldnt autohide.

2020-08-23 23:32 UTC, marcosrdz commented
![IMAGE 2020-08-23 19:32:34](https://user-images.githubusercontent.com/4793122/90991476-65340b80-e577-11ea-81d6-0d1b55d8c261.jpg)
![IMAGE 2020-08-23 19:32:37](https://user-images.githubusercontent.com/4793122/90991478-66fdcf00-e577-11ea-8bd5-6f497712b64e.jpg)

2020-08-23 23:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b3h9d41k4z11pzmehcu3620t3c

[download apk](http://filestorage.bluewallet.io:1488/1598226923.apk)

2020-08-24 02:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ttg1tztxv5wrzj298wwzmpe830

[download apk](http://filestorage.bluewallet.io:1488/1598237695.apk)

2020-08-24 18:03 UTC, Overtorment commented
e2e failed. probably because tests expect alerts with OK after import. maybe easier to leave them

2020-08-24 18:14 UTC, Overtorment commented on components/BlueGlobalMessage.js
> +    this.context.show({ message: "Importing Wallet..."});
which ones are those? example?

2020-08-28 22:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qx8u071z9ycb5tvp6nxmv9hpng

[download apk](http://filestorage.bluewallet.io:1488/1598653440.apk)

2020-08-29 02:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6k7a4n7r8rtk28xz2g7y30vpmm

[download apk](http://filestorage.bluewallet.io:1488/1598667338.apk)

2020-09-05 01:19 UTC, marcosrdz commented
> e2e failed. probably because tests expect alerts with OK after import. maybe easier to leave them

can something be done so it doesnt look for the alert?

2020-09-05 01:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ztx8c9vtaxxuvz0yau5da5nnd8

[download apk](http://filestorage.bluewallet.io:1488/1599271012.apk)

2020-10-27 02:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/94zrj160unexradwe5whh392x8

[download apk](http://filestorage.bluewallet.io:1488/1603764437.apk)

2021-07-27 10:14 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-07-27 10:34 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-07-27 10:45 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-07-27 10:55 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-07-27 11:10 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-07-27 13:41 UTC, closed without merging

2021-07-27 20:04 UTC, Overtorment commented
im thinking about picking up this PR and implementing message bubbles UI myself, thoughts?

2021-07-28 00:07 UTC, marcosrdz commented
Should be drastically easier now that we implemented cause context

2021-07-28 00:33 UTC, marcosrdz commented
This code was written a very long time ago. Before the implementation of useContext. It will definitely be far easier to reintroduce now and have it talk to any part of the app without having to pass props all over

2021-07-28 05:54 UTC, Overtorment commented
How do we do that?

On Wed, 28 Jul 2021 at 01:33, Marcos Rodriguez Vélez <
***@***.***> wrote:

> This code was written a very long time ago. Before the implementation of
> useContext. It will definitely be far easier to reintroduce now and have it
> talk to any part of the app without having to pass props all over
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/BlueWallet/BlueWallet/pull/1475#issuecomment-887922633>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOTD6LPFINURGGMITGAYI3TZ5F63ANCNFSM4P3YDQ2Q>
> .
>

2021-07-28 14:34 UTC, marcosrdz commented
I can add it to my todo list if you'd like. Should be fairly simple by following:

https://reactjs.org/docs/context.html#consuming-multiple-contexts