Add payjoin take2
BlueWallet/BlueWallet pull request #1481
Opened 2020-08-13 17:51 UTC by Overtorment

2020-08-13 18:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ebyxttj5etvea3v7hy36u2246g

[download apk](http://filestorage.bluewallet.io:1488/1597341843.apk)

2020-08-14 18:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qzt311jvju9ky7gc4kamqh2qyc

[download apk](http://filestorage.bluewallet.io:1488/1597429909.apk)

2020-09-11 20:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j5w777mg0tkdkmeeveq8rug7g0

[download apk](http://filestorage.bluewallet.io:1488/1599856004.apk)

2020-09-13 11:32 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/amgtbqtcb590cbe25ajvuja0tr

[download apk](http://filestorage.bluewallet.io:1488/1599996749.apk)

2020-09-13 13:39 UTC, limpbrains requested changes

2020-09-13 13:39 UTC, limpbrains commented on screen/send/confirm.js
> +                  <Text style={styles.payjoinText}>Payjoin</Text>
should we translate "Payjoin", also some short description of what is Payjoin would be nice

2020-09-13 13:39 UTC, limpbrains commented on screen/send/confirm.js
> +          dismissModal: () => this.props.navigation.dismiss(),
navigation.dismiss() was dropped in react-navigation v5.  How does it works?

2020-09-13 13:39 UTC, limpbrains commented on class/payjoin-transaction.js
> +  async scheduleBroadcastTx(txHex, milliseconds) {
What is `scheduleBroadcastTx` for? I can't find a place where it has been used

2020-09-13 13:39 UTC, limpbrains commented on screen/send/confirm.js
> +  payjoinText: { color: '#81868e', fontSize: 14 },
What about Dark mode, does this color fit?

2020-09-13 13:39 UTC, limpbrains commented on screen/send/details.js
> +        if (Object.prototype.hasOwnProperty.call(parsedBitcoinUri.options, 'pj')) {
Why so complicated? And not `'pj' in parsedBitcoinUri.options`? Probably we need tests for decodeBitcoinUri

2020-09-15 17:09 UTC, Overtorment commented on screen/send/confirm.js
> +                  <Text style={styles.payjoinText}>Payjoin</Text>
kinda wide-used term atm, maybe we will figure out how to translate it later

2020-09-15 17:10 UTC, Overtorment commented on class/payjoin-transaction.js
> +  async scheduleBroadcastTx(txHex, milliseconds) {
`scheduleBroadcastTx` is called from within payjoin-client, as far as I remember

2020-09-15 17:11 UTC, Overtorment commented on screen/send/confirm.js
> +  payjoinText: { color: '#81868e', fontSize: 14 },
@marcosrdz what do we need to do to make this support darkmode?

2020-09-15 17:11 UTC, Overtorment commented on screen/send/details.js
> +        if (Object.prototype.hasOwnProperty.call(parsedBitcoinUri.options, 'pj')) {
valid point. its a leftover from original contributor

2020-09-15 17:15 UTC, marcosrdz commented on screen/send/confirm.js
> +  payjoinText: { color: '#81868e', fontSize: 14 },
I write screens to use hooks. useTheme automatically switches.

2020-09-15 17:15 UTC, marcosrdz commented on screen/send/confirm.js
> +  payjoinText: { color: '#81868e', fontSize: 14 },
BlueCurrentTheme is used for class components

2020-09-17 11:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8yc80w5m3nvbu4dt195g2ffd20

[download apk](http://filestorage.bluewallet.io:1488/1600341540.apk)

2020-09-17 11:49 UTC, Overtorment commented
fyi, payjoin can be teted here: https://btc.donate.kukks.org

2020-09-17 16:34 UTC, Overtorment commented
ok I think its ready for tests @ncoelho @marcosrdz

2020-09-17 17:02 UTC, ncoelho commented
Oh boy! :)

2020-09-18 07:16 UTC, limpbrains approved these changes

2020-09-19 23:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zxu9e6z93drmpbd54hpp4pu2p8

[download apk](http://filestorage.bluewallet.io:1488/1600557773.apk)

2020-09-20 01:15 UTC, marcosrdz approved these changes

2020-09-20 01:38 UTC, marcosrdz commented
> ok I think its ready for tests @ncoelho @marcosrdz 

Should it be enabled by default? Or leave it as is?

2020-09-20 01:44 UTC, marcosrdz commented
> > ok I think its ready for tests @ncoelho @marcosrdz 
> 
> Should it be enabled by default? Or leave it as is?

Maybe have it enabled by default and have the toggle in an "advanced" 3 dot menu option on confirm screen

2020-09-21 17:06 UTC, ncoelho commented
> > ok I think its ready for tests @ncoelho @marcosrdz 
> 
> Should it be enabled by default? Or leave it as is?

I believe we discussed this on the original thread

2020-09-21 19:18 UTC, ncoelho commented
Tested & ACK

2020-09-21 19:19 UTC, ncoelho approved these changes

2020-09-21 19:32 UTC, merged

2020-09-21 23:43 UTC, junderw commented
Reminder: payjoin-client is not BIP compliant yet.