ADD: Disable some Watch app elements when app is not reachable
BlueWallet/BlueWallet pull request #1490
Opened 2020-08-17 01:20 UTC by marcosrdz

2020-08-17 01:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w7vmv6bj4m40udgjjp23j991z8

[download apk](http://filestorage.bluewallet.io:1488/1597627842.apk)

2020-08-17 03:56 UTC, marcosrdz commented
![Simulator Screen Shot - Apple Watch Series 5 - 44mm - 2020-08-16 at 23 55 08](https://user-images.githubusercontent.com/4793122/90356019-1ab50b00-e01c-11ea-9ec0-086ba2c7f7dc.png)

2020-08-17 04:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zzdrhghewjg6eqt24azfmqppag

[download apk](http://filestorage.bluewallet.io:1488/1597637183.apk)

2020-08-17 05:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v45cunw070ah07dxqq0whz4a2w

[download apk](http://filestorage.bluewallet.io:1488/1597640404.apk)

2020-08-17 13:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/md3rm7h0g8a41mknncnv9dtvam

[download apk](http://filestorage.bluewallet.io:1488/1597669840.apk)

2020-08-17 16:08 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jvggggm1pktx3evgb34uw73me0

[download apk](http://filestorage.bluewallet.io:1488/1597680476.apk)

2020-08-18 01:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k529wj3ktycu9wu71ghg01wcjg

[download apk](http://filestorage.bluewallet.io:1488/1597715912.apk)

2020-08-19 02:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m9zxg45xc2u0r54y13p9tmymw0

[download apk](http://filestorage.bluewallet.io:1488/1597804572.apk)

2020-08-19 03:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p2ek7k2d5kh3k0n654cgf12078

[download apk](http://filestorage.bluewallet.io:1488/1597806081.apk)

2020-08-20 10:51 UTC, Overtorment requested changes
ios build on appcenter failed, which is concerning. I rerunned it, lets see

2020-08-20 10:51 UTC, Overtorment commented on WatchConnectivity.ios.js
> +            xpub: wallet.getXpub() ? wallet.getXpub() : wallet.getSecret(),
are you sure that `getXpub` is always available here? you're calling it, maybe its better to check 
`wallet.getXpub ? wallet.getXpub() : ...` ?


`getXpub` is available only on descendants of `AbstractHDWallet` but not `AbstractWallet`

2020-08-20 11:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ngm48whaukdenzn48hd7pge9g4

[download apk](http://filestorage.bluewallet.io:1488/1597922723.apk)

2020-08-20 12:54 UTC, merged