Sidebar
BlueWallet/BlueWallet pull request #1596
Opened 2020-08-30 05:19 UTC by marcosrdz

2020-08-30 05:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yehm9tvrj6eyj2fhpauvdq6jur

[download apk](http://filestorage.bluewallet.io:1488/1598765502.apk)

2020-08-30 06:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/72xfth0468d5j2tqyarqr0my4m

[download apk](http://filestorage.bluewallet.io:1488/1598768077.apk)

2020-08-30 07:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7mf1fbeyxew18rc8vx2h509a30

[download apk](http://filestorage.bluewallet.io:1488/1598771237.apk)

2020-08-30 16:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qw1v459amu8yczpnup33p19p60

[download apk](http://filestorage.bluewallet.io:1488/1598804578.apk)

2020-08-31 00:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vrp9rtbw15qajzbwmfv1g2ttyr

[download apk](http://filestorage.bluewallet.io:1488/1598835100.apk)

2020-08-31 19:02 UTC, Overtorment requested changes
deepscan & ios build failed.
didnt look at the code

2020-08-31 22:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/patgzfppaxc2yzcqbbe5wmc0wr

[download apk](http://filestorage.bluewallet.io:1488/1598914653.apk)

2020-09-01 09:42 UTC, Overtorment requested changes
conflicts. 16 commits. requires tidying up

2020-09-01 12:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n3z6e4d7cp55xjmnb9kbtmfjem

[download apk](http://filestorage.bluewallet.io:1488/1598964798.apk)

2020-09-01 14:10 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q5wpft927f8ktd1xmwyxfc6fyg

[download apk](http://filestorage.bluewallet.io:1488/1598969417.apk)

2020-09-01 14:26 UTC, marcosrdz commented
> conflicts. 16 commits. requires tidying up

conflict fixes. squashed.

2020-09-01 14:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2cwyec3dn4gz5f19354maxhua8

[download apk](http://filestorage.bluewallet.io:1488/1598971038.apk)

2020-09-01 15:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3xdpaugc9yjr83g0zxc28y4mpw

[download apk](http://filestorage.bluewallet.io:1488/1598973999.apk)

2020-09-02 12:42 UTC, Overtorment requested changes
found some bugs on appetize

1)
![image](https://user-images.githubusercontent.com/1913337/91981733-2ba29380-ed21-11ea-9a2a-f921975888c7.png)

2) wallet cards are not updated when wallet is created or deleted.
STR: open appetizer. choose nexus 9; choose android 10; click arrow to tilt the device. open android's OS drawer and click 'auto-rotate'. create a wallet - wallet is created, but there is no wallet's card on the left:


![image](https://user-images.githubusercontent.com/1913337/91982414-1f6b0600-ed22-11ea-8855-a37bd8a1b353.png)

2020-09-02 12:42 UTC, Overtorment commented on android/app/src/main/res/values-sw600dp/bools.xml
> +    <bool name="portrait_only">false</bool>
wtf is dis

2020-09-02 12:42 UTC, Overtorment commented on screen/wallets/drawerList.js
> +const DrawerList = props => {
did you alter any refresh logic here?

2020-09-02 12:42 UTC, Overtorment commented on screen/wallets/list.js
> +    BlueApp.getTransactions(null, 10);
wtf

2020-09-02 12:42 UTC, Overtorment commented on screen/wallets/drawerList.js
> +    console.log('wallets/list redrawScreen()');
not up-to-date console log

2020-09-02 12:42 UTC, Overtorment commented on screen/wallets/drawerList.js
> +    // have to unsubscribe on unmount and resubscribe again on mount.
so whats the navigation stack here?
we used to have: first walletsList opened, and then walletTransactions opened, and always one screen was displayed, the other one - not, so the one who is being displayed is exclusively subscribes to REMOTE_TRANSACTIONS_COUNT_CHANGED event and fetches transactions for current wallet if its fired.

and now? wheres the drawerList in all this..?

2020-09-02 12:42 UTC, Overtorment commented on screen/wallets/drawerList.js
> +    console.log('wallets/list componentDidMount');
not up-to-date console log

2020-09-02 12:44 UTC, Overtorment commented
@ncoelho you approve this layout for tablet/desktop?

2020-09-02 12:47 UTC, marcosrdz commented on android/app/src/main/res/values-sw600dp/bools.xml
> +    <bool name="portrait_only">false</bool>
its how you determine on android if the device's resolution is enough to handle splitview or not

2020-09-02 12:48 UTC, marcosrdz commented on screen/wallets/drawerList.js
> +const DrawerList = props => {
no pull to refresh on drawerlist. thats on lists.js

2020-09-02 12:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yywgbj96zpjf5xeeyr5n2ze2qw

[download apk](http://filestorage.bluewallet.io:1488/1599051558.apk)

2020-09-02 13:02 UTC, ncoelho commented
Layout wise yes, would like to test it on macOS first

2020-09-02 14:17 UTC, ncoelho commented
Problems I found:

Lightning receive screen, CTA is unaligned 
<img width="719" alt="Screenshot 2020-09-02 at 16 12 10" src="https://user-images.githubusercontent.com/1238429/91994794-4f70d400-ed37-11ea-9803-bf9b9594882f.png">

Scan on lightning is giving a blank/black screen
<img width="978" alt="Screenshot 2020-09-02 at 16 12 28" src="https://user-images.githubusercontent.com/1238429/91994792-4f70d400-ed37-11ea-8522-bc853efa5687.png">

Onchain send screen is algo misaligned, I suspect it is related with batching
<img width="737" alt="Screenshot 2020-09-02 at 16 13 29" src="https://user-images.githubusercontent.com/1238429/91994785-4e3fa700-ed37-11ea-8122-3a2033daebaf.png">

If I have a lightning wallet open and tap on the onchain wallet, it doesn't open:
<img width="972" alt="Screenshot 2020-09-02 at 16 13 03" src="https://user-images.githubusercontent.com/1238429/91994790-4ed83d80-ed37-11ea-8453-cce7e6ce1e1c.png">

The sidebar is a bit small, I will give a 320px size
<img width="291" alt="Screenshot 2020-09-02 at 16 17 15" src="https://user-images.githubusercontent.com/1238429/91995182-c6a66800-ed37-11ea-9cb5-b5ac68f478e9.png">

2020-09-03 00:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8kfzdqyag06461cedkc89hkmec

[download apk](http://filestorage.bluewallet.io:1488/1599092125.apk)

2020-09-03 00:42 UTC, marcosrdz commented
> Problems I found:
> 
> 
> 
> Lightning receive screen, CTA is unaligned 
> 
> <img width="719" alt="Screenshot 2020-09-02 at 16 12 10" src="https://user-images.githubusercontent.com/1238429/91994794-4f70d400-ed37-11ea-9803-bf9b9594882f.png">
> 
> 
> 
> Scan on lightning is giving a blank/black screen
> 
> <img width="978" alt="Screenshot 2020-09-02 at 16 12 28" src="https://user-images.githubusercontent.com/1238429/91994792-4f70d400-ed37-11ea-8522-bc853efa5687.png">
> 
> 
> 
> Onchain send screen is algo misaligned, I suspect it is related with batching
> 
> <img width="737" alt="Screenshot 2020-09-02 at 16 13 29" src="https://user-images.githubusercontent.com/1238429/91994785-4e3fa700-ed37-11ea-8122-3a2033daebaf.png">
> 
> 
> 
> If I have a lightning wallet open and tap on the onchain wallet, it doesn't open:
> 
> <img width="972" alt="Screenshot 2020-09-02 at 16 13 03" src="https://user-images.githubusercontent.com/1238429/91994790-4ed83d80-ed37-11ea-8453-cce7e6ce1e1c.png">
> 
> 
> 
> The sidebar is a bit small, I will give a 320px size
> 
> <img width="291" alt="Screenshot 2020-09-02 at 16 17 15" src="https://user-images.githubusercontent.com/1238429/91995182-c6a66800-ed37-11ea-9cb5-b5ac68f478e9.png">
> 
> 

Check with latest DMG. 320 is the default width

2020-09-03 02:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cr1566vxu76qm2gkbphymf2fr4

[download apk](http://filestorage.bluewallet.io:1488/1599101969.apk)

2020-09-03 08:04 UTC, ncoelho commented
Bugs not found on latest build 👍

2020-09-03 08:05 UTC, ncoelho approved these changes

2020-09-03 13:51 UTC, limpbrains approved these changes

2020-09-04 01:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/35yptdz1xq707tczf2fyxyfejg

[download apk](http://filestorage.bluewallet.io:1488/1599181345.apk)

2020-09-04 02:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3u2bbp2jder859xgjrz5x5jzrw

[download apk](http://filestorage.bluewallet.io:1488/1599185689.apk)

2020-09-04 13:12 UTC, marcosrdz commented on screen/wallets/drawerList.js
> +    // have to unsubscribe on unmount and resubscribe again on mount.
remote tx count changed listeners is now in drawerList. All the other ones are listening to the tx count

2020-09-05 01:12 UTC, marcosrdz commented
@Overtorment  re-review when you get the chance

2020-09-05 01:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2zkqzetw23e0updc8473hmrhdr

[download apk](http://filestorage.bluewallet.io:1488/1599270325.apk)

2020-09-07 03:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6g496p3qepe53nkvk8j2rxafnw

[download apk](http://filestorage.bluewallet.io:1488/1599447648.apk)

2020-09-07 16:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4qxg41abpb549twbcbzndevtcg

[download apk](http://filestorage.bluewallet.io:1488/1599495846.apk)

2020-09-08 14:13 UTC, Overtorment requested changes
can you elaborate more how drawerList works? whats the navigation stack? who calls whom? who being inside whom?

also, pls fix conflicts

2020-09-08 14:23 UTC, marcosrdz commented on Navigation.js
>  // import { createAppContainer } from '@react-navigation/native';
Most likely accidental when doing autocomplete.

2020-09-08 14:26 UTC, marcosrdz commented
> can you elaborate more how drawerList works? whats the navigation stack? who calls whom? who being inside whom?
> 
> also, pls fix conflicts

DrawerList is this: https://reactnavigation.org/docs/drawer-based-navigation

we assign it as 'permanent' so it behaves like a split view controller we see on iPadOS. It will always be mounted. it's width will be determined by the device real estate. if it has enough width, it'll be set to the default 320 width, otherwise..its set to 0.
All stacks "behave independently" but are able to communicate to each other via navigate calls.

2020-09-08 14:31 UTC, Overtorment approved these changes
lgtm. I want to test it on my device first, and then lets merge

2020-09-08 15:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tmvy5vm20yn33b455xxktwymcc

[download apk](http://filestorage.bluewallet.io:1488/1599577221.apk)

2020-09-08 16:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z19xxqvfh42a8q5unpqa3e1pn4

[download apk](http://filestorage.bluewallet.io:1488/1599580876.apk)

2020-09-08 16:06 UTC, merged