REF: Use In-App browser on iOS
BlueWallet/BlueWallet pull request #1642
Opened 2020-09-05 00:47 UTC by marcosrdz

2020-09-05 01:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zte6e36zy61azk5dtt9cm2qfpg

[download apk](http://filestorage.bluewallet.io:1488/1599268696.apk)

2020-09-07 11:44 UTC, Overtorment requested changes
this did not solve apple pay on ios, and I don't see a reason to merge this.

2020-09-07 14:55 UTC, Overtorment commented on screen/wallets/transactions.js
> +        .then(_value => InAppBrowser.open(uri, { dismissButtonStyle: 'done' }))
can you hide all this InAppBrowser business inside buy-bitcoin screen? that's the only purpose of that screen,
and its bad that all associated complexity is leaking outside (in transactions screen in this case). what if we will decide to place 'buy bitcoin' button in other places? we would have to copy-paste all this logic

2020-09-07 19:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p4nmwhamzne2h04g547utub414

[download apk](http://filestorage.bluewallet.io:1488/1599505312.apk)

2020-09-08 10:29 UTC, Overtorment approved these changes
looks much cleaner now. lets distribute & test build and merge

2020-09-08 10:29 UTC, Overtorment commented on screen/lnd/scanLndInvoice.js
> +                    <View style={styles.payButtonContainer}>
wtf

2020-09-08 10:29 UTC, Overtorment commented on screen/wallets/transactions.js
> +    BuyBitcoin.navigate(this.state.wallet);
good enough

2020-09-08 10:29 UTC, Overtorment commented on screen/wallets/transactions.js
> +    BuyBitcoin.navigate(this.state.wallet);
I hope its not breaking some RN best practices

2020-09-08 10:47 UTC, ncoelho approved these changes

2020-09-08 12:10 UTC, marcosrdz commented on screen/lnd/scanLndInvoice.js
> +                    <View style={styles.payButtonContainer}>
Lint. Single space

2020-09-08 13:43 UTC, merged