FIX: If user has approved notifications, send hash from watch.
BlueWallet/BlueWallet pull request #1643
Opened 2020-09-05 08:34 UTC by marcosrdz

2020-09-05 08:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ty4qje6cghaxqegan2r2an3xc8

[download apk](http://filestorage.bluewallet.io:1488/1599295556.apk)

2020-09-05 10:54 UTC, Overtorment requested changes

2020-09-05 10:54 UTC, Overtorment commented on WatchConnectivity.ios.js
> +          if (notifications.alreadyConfigured) {
`alreadyConfigured` is not exported, so it will always be false.
you probably need `if (await notifications.isNotificationsEnabled()) {`  
(or `getPushToken`)

2020-09-05 17:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/838pha567ezkq797xad13q5500

[download apk](http://filestorage.bluewallet.io:1488/1599326629.apk)

2020-09-06 09:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/85eegt8wu164eqa71cf3qffebc

[download apk](http://filestorage.bluewallet.io:1488/1599384375.apk)

2020-09-06 13:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/855qm378gfd8zpeqjudtcx6f54

[download apk](http://filestorage.bluewallet.io:1488/1599400459.apk)

2020-09-06 14:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tp6eae1ukq7cy5243yeybypk90

[download apk](http://filestorage.bluewallet.io:1488/1599401378.apk)

2020-09-07 11:34 UTC, Overtorment approved these changes

2020-09-07 11:35 UTC, merged