ADD: Arabic language
BlueWallet/BlueWallet pull request #1720
Opened 2020-09-09 13:34 UTC by Overtorment

2020-09-09 13:53 UTC, Overtorment commented
uploaded files to transifex

2020-09-09 14:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/61jyyv7u8kjgv5zkk5490r8bz8

[download apk](http://filestorage.bluewallet.io:1488/1599661020.apk)

2020-09-09 17:05 UTC, limpbrains requested changes

2020-09-09 17:05 UTC, limpbrains commented on ios/fastlane/metadata/ar-SA/keywords.txt
> -bitcoin,wallet,bitcoin wallet,blockchain,btc,cryptocurrency,buy bitcoin,samourai,electrum,ethereum
inverted commas o_0

2020-09-10 09:54 UTC, merged

2020-09-10 09:55 UTC, Overtorment commented on ios/fastlane/metadata/ar-SA/keywords.txt
> -bitcoin,wallet,bitcoin wallet,blockchain,btc,cryptocurrency,buy bitcoin,samourai,electrum,ethereum
I fixed them to regular commas, but not sure if that is correct O_o