REF: Wallets List uses React Hooks
BlueWallet/BlueWallet pull request #1762
Opened 2020-09-13 05:58 UTC by marcosrdz

2020-09-13 06:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vp5jjkpujabtratf16j4zyhkm0

[download apk](http://filestorage.bluewallet.io:1488/1599980052.apk)

2020-09-14 03:05 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2hr51xrwu03ahkdp8u54cgjwvg

[download apk](http://filestorage.bluewallet.io:1488/1600052743.apk)

2020-09-14 08:20 UTC, limpbrains requested changes

2020-09-14 08:20 UTC, limpbrains commented on screen/wallets/list.js
>    };
You probably don't need this since you have useWindowDimensions, just calculate isLargeScreen in render function
```
const { width } = useWindowDimensions();
const isLargeScreen = ...
```

2020-09-14 08:20 UTC, limpbrains commented on screen/wallets/list.js
> +  );
Can you please describe what are you trying to archive here? Why creating callback when inside you are still calling  redrawScreen which is dynamically created in render function?

2020-09-14 10:46 UTC, Overtorment requested changes

2020-09-14 10:46 UTC, Overtorment commented on class/wallet-gradient.js
> +WalletGradient.createWallet = () => {
i think you could just have it as static method in class

2020-09-14 10:46 UTC, Overtorment commented on WatchConnectivity.ios.js
> +    if (installed) {
+1

2020-09-14 10:46 UTC, Overtorment commented on WatchConnectivity.ios.js
> +  getIsWatchAppInstalled().then(installed => {
i prefer async/await as  pure promise `then` eventually leads to nesting hell (remember callback hell before promises?)

2020-09-14 15:51 UTC, marcosrdz commented on screen/wallets/list.js
> +    Platform.OS === 'android' ? isTablet() : Dimensions.get('window').width >= Dimensions.get('screen').width / 3 && isTablet(),
Need it for ('screen') since useWindowDimensions is for ('width')

2020-09-14 15:57 UTC, marcosrdz commented on WatchConnectivity.ios.js
> +  getIsWatchAppInstalled().then(installed => {
Don't want the watchapp process hang the app for any reason.

2020-09-14 15:57 UTC, marcosrdz commented on class/wallet-gradient.js
> +WalletGradient.createWallet = () => {
Done

2020-09-14 16:04 UTC, limpbrains commented on screen/wallets/list.js
> +    Platform.OS === 'android' ? isTablet() : Dimensions.get('window').width >= Dimensions.get('screen').width / 3 && isTablet(),
For screen sure, `Dimensions.get('window').width` can be replaced

2020-09-14 16:10 UTC, marcosrdz commented on screen/wallets/list.js
> +    Platform.OS === 'android' ? isTablet() : Dimensions.get('window').width >= Dimensions.get('screen').width / 3 && isTablet(),
Done

2020-09-14 16:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qj87uk4pnfx2fp6q93wxee8vdc

[download apk](http://filestorage.bluewallet.io:1488/1600101292.apk)

2020-09-18 00:09 UTC, marcosrdz commented on screen/wallets/list.js
> +  );
useFocusEffect expects useCallback. @Overtorment  might have an explanation behind redrawSceen. These functions will be removed once we move the wallets to be called from useContext. But for now, im simply keeping existing code.

2020-09-18 00:11 UTC, marcosrdz commented on screen/wallets/list.js
>    };
Some components such as the carousel dont update automatically (you see this on ipad/desktop), onLayout is used to mitigate  this.

2020-09-18 00:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zh8w9ec09ga0v2t2k327aq41d4

[download apk](http://filestorage.bluewallet.io:1488/1600388982.apk)

2020-09-18 06:58 UTC, limpbrains commented on screen/wallets/list.js
> +  );
Didn't know about useFocusEffect+useCallback, ok

2020-09-18 07:00 UTC, limpbrains approved these changes

2020-09-19 14:10 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ckjfumn14a59ugmmf5ue5frb64

[download apk](http://filestorage.bluewallet.io:1488/1600524629.apk)

2020-09-21 17:50 UTC, Overtorment commented
I want to write more e2e tests prior to merging large-scale refactorings

2020-10-05 22:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qqr4v61f00fden6gzzdap0hypg

[download apk](http://filestorage.bluewallet.io:1488/1601937647.apk)

2020-10-06 10:22 UTC, Overtorment approved these changes
btw wheres that code that is supposed to prevent drawerList from doing the same stuff that list does when the screen is small?

2020-10-06 10:28 UTC, Overtorment commented
conflicts

2020-10-07 10:36 UTC, ncoelho approved these changes

2020-10-07 11:35 UTC, Overtorment commented
conflict

2020-10-07 22:57 UTC, marcosrdz commented
> conflict

resolved.

2020-10-07 23:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x33ev61njq8ybzqvkrjx7u5pzc

[download apk](http://filestorage.bluewallet.io:1488/1602112279.apk)

2020-10-08 16:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gve11vtk6g01rc2zhjgkhug7z4

[download apk](http://filestorage.bluewallet.io:1488/1602173621.apk)

2020-10-08 17:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gahyb1v6j7pqbkwt13tgmq57er

[download apk](http://filestorage.bluewallet.io:1488/1602176781.apk)

2020-10-08 20:03 UTC, merged