REF: Success screen uses hooks
BlueWallet/BlueWallet pull request #1831
Opened 2020-09-18 00:43 UTC by marcosrdz

2020-09-18 00:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nuh2pyc3ca5fmxxnvgn0fyj9em

[download apk](http://filestorage.bluewallet.io:1488/1600390562.apk)

2020-09-18 06:54 UTC, limpbrains approved these changes

2020-09-18 06:54 UTC, limpbrains commented on screen/send/success.js
> +            {loc.send.create_fee}: {fee} {BitcoinUnit.BTC}
This will not work for right to left languages. The whole string should be composed using `loc.formatString` with fee and unit as params

2020-09-19 12:40 UTC, Overtorment requested changes
conflicts

2020-09-19 12:44 UTC, marcosrdz commented
> conflicts
fixed

2020-09-19 13:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g13bmxe82gtt17tczf3uycq0pr

[download apk](http://filestorage.bluewallet.io:1488/1600523863.apk)

2020-09-19 23:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/njp348v57ca7n1hqqc8bujdrdc

[download apk](http://filestorage.bluewallet.io:1488/1600558670.apk)

2020-09-21 17:47 UTC, merged