Wip multisig
BlueWallet/BlueWallet pull request #1923
Opened 2020-09-24 20:53 UTC by Overtorment

2020-09-24 21:05 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dykeef3gdt8hhukepmke36z5wg

[download apk](http://filestorage.bluewallet.io:1488/1600981513.apk)

2020-09-24 21:21 UTC, Overtorment commented
@junderw can you pls take a look as well? initial multisig implementation

2020-09-24 21:22 UTC, Overtorment commented
![image](https://user-images.githubusercontent.com/1913337/94201749-57dea980-feb4-11ea-92bc-06f351098595.png)

![image](https://user-images.githubusercontent.com/1913337/94201779-61681180-feb4-11ea-81cd-8fcf07833590.png)

2020-09-25 05:05 UTC, junderw requested changes
A lot of code quality changes and a few consistency changes.

2020-09-25 05:05 UTC, junderw commented on class/wallets/multisig-hd-wallet.js
> +    if (targets.length === 1 && targets[0] && !targets[0].value) {
If you ever want to support OP_RETURN outputs you should allow value === 0...

This check should be

targets[0].value === undefined

Or null, depending on what you use to demark max

2020-09-25 11:19 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +    this._m = +m;
cast to number

2020-09-25 11:21 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +    return this._derivationPath === "m/48'/0'/0'/2'";
coldcard  uses m/48 as well, and a few others (like cobo/specter-diy)

2020-09-25 11:21 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +    return this._derivationPath === "m/45'";
noted

2020-09-25 11:23 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +    if (index === 0) throw new Error('cosigners indexation starts from 1');
I have a feeling that once I start writing UI code, this will make more sense, as it will be perfectly aligned with what is displayed to user, like, "dear user, please make first signature" or "you have 2-of-3 multisig, please provide key number 1"

2020-09-25 11:24 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +      hdNode.derive(0);
oh it is not needed?  Ill remove it (luckily I have testcases for invalid xpub as well)

2020-09-25 11:28 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +    this._m = +m;
yeah probably not most useful here

2020-09-25 11:34 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +    if (path) this._cosignersCustomPaths[index] = path;
hmm. how do you even validate path? is it always `m/x(/y)` ? is there something in bitcoinjs that can accept path and throw an exception if its complete bs? maybe

```
    const root = bitcoin.bip32.fromSeed(seed);
    const child = root.derivePath(path)
```

2020-09-25 11:37 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +  _getInternalAddressByIndex(index) {
noted.

2020-09-25 11:39 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +  static ckccXfp2fingerprint(xfp) {
I took it from electrum's json. `ckcc_xfp. not even sure what it stands for (apart of fp)

https://github.com/sparrowwallet/sparrow/blob/master/src/test/resources/com/sparrowwallet/sparrow/io/electrum-multisig-wallet.json

2020-09-25 11:41 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +    ).toUpperCase();
probably described in spec somewhere. I took test vectors from real life, for example, `64392470` ->  `168DD603`

2020-09-25 11:41 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +      ret += 'Format: unknown\n';
not acceptable, but left here for debug purposes (if we will have issues around that later)

2020-09-25 11:44 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +        : Buffer.from(MultisigHDWallet.seedToFingerprint(cosigner), 'hex');
hmm, makes sense, since we indeed have a global `this._cosignersFingerprints`.
but is this a costly operation?

2020-09-25 11:48 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +      xpub = this.constructor._zpubToXpub(xpub);
noted

2020-09-25 11:49 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +      // not needed by coldcard, apparently..?
noted.

2020-09-25 11:49 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +      outputData.witnessScript = p2shP2wsh.redeem.redeem.output;
noted.

2020-09-25 14:24 UTC, limpbrains commented on class/wallets/multisig-hd-wallet.js
> +    if (index === 0) throw new Error('cosigners indexation starts from 1');
If I was writing UI code, I still would prefer normal indexing from 0. Otherwise, it is confusing

2020-09-25 18:21 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +    if (path) this._cosignersCustomPaths[index] = path;
apparently yes, smth like this can be used to validate path:


```
    const root = bitcoin.bip32.fromSeed(Buffer.alloc(32));
    const child = root.derivePath('trololo');
```

2020-09-26 00:42 UTC, junderw commented on class/wallets/multisig-hd-wallet.js
> +    ).toUpperCase();
The spec of what? BIP32 fingerprint is just 4 bytes... why does it need to be represented as an integer and why is that integer read as a little endian value?

Is this a COBO specific thing?

2020-09-27 10:20 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +    ).toUpperCase();
electrum: https://github.com/sparrowwallet/sparrow/blob/master/src/test/resources/com/sparrowwallet/sparrow/io/electrum-multisig-wallet.json

```
"ckcc_xfp": 3503269483,
```

2020-09-27 10:53 UTC, junderw commented on class/wallets/multisig-hd-wallet.js
> +        : Buffer.from(MultisigHDWallet.seedToFingerprint(cosigner), 'hex');
yes, it involves EC multiplying, so it's slow.

but just in principle, any logic fork that says "if cache exists, use it. If not, calculate it but DON'T cache it for next time" doesn't make sense imo.

So I would say to add to cache.

2020-09-28 11:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/efywzkhppqy5ypp11dbf7e2yu8

[download apk](http://filestorage.bluewallet.io:1488/1601293390.apk)

2020-09-29 19:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/t2f0wp1dqfc34wuqnwk7w0yuf4

[download apk](http://filestorage.bluewallet.io:1488/1601407850.apk)

2020-09-30 07:53 UTC, limpbrains requested changes

2020-09-30 07:53 UTC, limpbrains commented on screen/wallets/details.js
> +            )}
Please don't forget about internationalization. 
I understand now everything requires translation, like derivation path

2020-09-30 17:05 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rwkuxed09f22uw8f3kmp6gkwvm

[download apk](http://filestorage.bluewallet.io:1488/1601485534.apk)

2020-09-30 23:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n0fdk1g88juwdtp3dt4x61z1h8

[download apk](http://filestorage.bluewallet.io:1488/1601506798.apk)

2020-10-01 16:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xbr1mu4ha8a9zwcykeafqpcaa4

[download apk](http://filestorage.bluewallet.io:1488/1601569022.apk)

2020-10-01 17:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/95dbd6x915puwen46gbdnkcfbr

[download apk](http://filestorage.bluewallet.io:1488/1601571811.apk)

2020-10-01 18:14 UTC, limpbrains requested changes

2020-10-01 18:14 UTC, limpbrains commented on screen/send/psbtMultisig.js
> +  const wallet = BlueApp.getWallets().find(w => w.getID() === walletId);
Can this be a bottleneck ? To calculate wallet id there is sha256 over seed. I don't know is it fast? Because you are doing this on each component render
You can use `useMemo` hook to optimize this.

2020-10-01 18:14 UTC, limpbrains commented on screen/send/psbtMultisig.js
> +            <BlueButtonLink title="Cancel" onPress={() => setIsModalVisible(false)} />
please translate `Cancel`

2020-10-02 14:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nxtd5bbc01nactc08n82z9xkwg

[download apk](http://filestorage.bluewallet.io:1488/1601649824.apk)

2020-10-02 17:47 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8jrft3x1rmwphupybbm9fdkx3g

[download apk](http://filestorage.bluewallet.io:1488/1601660827.apk)

2020-10-02 19:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4tme4hkem0d51v4d6zk6p2gx9c

[download apk](http://filestorage.bluewallet.io:1488/1601667694.apk)

2020-10-03 09:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/peav8qtpeb0hgxydvfnnhv94u4

[download apk](http://filestorage.bluewallet.io:1488/1601718470.apk)

2020-10-03 20:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rz8wby6fy321yh5qdn1pfr9tv4

[download apk](http://filestorage.bluewallet.io:1488/1601757270.apk)

2020-10-03 21:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z83q4pdgek58rbq298d89eepf8

[download apk](http://filestorage.bluewallet.io:1488/1601759376.apk)

2020-10-04 00:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fmtgzd9rqkadv6wu6aj89ghdar

[download apk](http://filestorage.bluewallet.io:1488/1601769592.apk)

2020-10-04 01:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2mpwhx3fh3cm61hjut9w27dwxw

[download apk](http://filestorage.bluewallet.io:1488/1601773613.apk)

2020-10-04 06:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kxhj0re2g3x722zyf9pvqm1aag

[download apk](http://filestorage.bluewallet.io:1488/1601792261.apk)

2020-10-04 07:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nuy2n71d198jeggg2wg7xh4rkc

[download apk](http://filestorage.bluewallet.io:1488/1601796052.apk)

2020-10-05 12:44 UTC, Overtorment commented on screen/send/psbtMultisig.js
> +  const wallet = BlueApp.getWallets().find(w => w.getID() === walletId);
sha256 is fast, compared to privkey->pubkey computations which imply ECC multiply. but render is not happening too often, right? only when smth is changed?

2020-10-05 12:46 UTC, Overtorment commented on components/SquareButton.js
> +}
i tried to rewire it in hooks and failed miserably

2020-10-05 14:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8t95j660jaz283ar99m71trmbr

[download apk](http://filestorage.bluewallet.io:1488/1601907201.apk)

2020-10-05 20:02 UTC, marcosrdz approved these changes

2020-10-05 21:25 UTC, merged

2020-10-05 21:26 UTC, Overtorment commented
good enough for technical release. we can polish later

2020-10-06 07:16 UTC, limpbrains commented on screen/send/psbtMultisig.js
> +  const wallet = BlueApp.getWallets().find(w => w.getID() === walletId);
Right