Ops bump payjoin dep
BlueWallet/BlueWallet pull request #1937
Opened 2020-09-29 09:32 UTC by Kukks

Supersedes #1926 in that the tests now succeed, passes the payment script to the payjoin client and also checks if BIP21 signals that the server has output substitution disabled.

2020-09-29 10:35 UTC, junderw commented
ummm... we might delete that branch.

please don't use it.

at the very least use a commit hash.

ideally we should publish to npm.

2020-09-29 11:04 UTC, junderw commented
Please use `"payjoin-client": "1.0.0-beta",` as the dependency.
You can install via npm with `npm install [--save|--save-dev] payjoin-client@beta`

2020-10-02 15:53 UTC, Overtorment commented
bad news, payjoin client now uses some methods in `URLSearchParams` that are not supported in react-native runtime (but probably supported in nodejs cli, so its hard to test for it, tests will pass).
In particular, this one is throwing  `node_modules/react-native/Libraries/Blob/URL.js` :

```
// Small subset from whatwg-url: https://github.com/jsdom/whatwg-url/tree/master/lib
// The reference code bloat comes from Unicode issues with URLs, so those won't work here.
export class URLSearchParams {
...
  set(name, value) {
    throw new Error('not implemented');
  }
...
```

can you pls rewrite it so `URLSearchParams` is not used?



![image](https://user-images.githubusercontent.com/1913337/94942925-dba91f00-04ce-11eb-9fdf-89a524f9e474.png)

2020-10-02 15:57 UTC, Kukks commented
> bad news, payjoin client now uses some methods in `URLSearchParams` that are not supported in react-native runtime (but probably supported in nodejs cli, so its hard to test for it, tests will pass).
> In particular, this one is throwing `node_modules/react-native/Libraries/Blob/URL.js` :
> 
> ```
> // Small subset from whatwg-url: https://github.com/jsdom/whatwg-url/tree/master/lib
> // The reference code bloat comes from Unicode issues with URLs, so those won't work here.
> export class URLSearchParams {
> ...
>   set(name, value) {
>     throw new Error('not implemented');
>   }
> ...
> ```
> 
> can you pls rewrite it so `URLSearchParams` is not used?
> 
> ![image](https://user-images.githubusercontent.com/1913337/94942925-dba91f00-04ce-11eb-9fdf-89a524f9e474.png)

What if you included a polyfill: https://github.com/ungap/url-search-params ?

2020-10-02 16:26 UTC, Overtorment commented
> > bad news, payjoin client now uses some methods in `URLSearchParams` that are not supported in react-native runtime (but probably supported in nodejs cli, so its hard to test for it, tests will pass).
> > In particular, this one is throwing `node_modules/react-native/Libraries/Blob/URL.js` :
> > ```
> > // Small subset from whatwg-url: https://github.com/jsdom/whatwg-url/tree/master/lib
> > // The reference code bloat comes from Unicode issues with URLs, so those won't work here.
> > export class URLSearchParams {
> > ...
> >   set(name, value) {
> >     throw new Error('not implemented');
> >   }
> > ...
> > ```
> > 
> > 
> > can you pls rewrite it so `URLSearchParams` is not used?
> > ![image](https://user-images.githubusercontent.com/1913337/94942925-dba91f00-04ce-11eb-9fdf-89a524f9e474.png)
> 
> What if you included a polyfill: https://github.com/ungap/url-search-params ?

extra dep from random nobody on interwebz. plus might require some work just to make in work in RN.
feels like your use-case can just be monkey coded..?

2020-10-02 16:30 UTC, junderw commented
Isn't this............ exactly why we made the payjoin client composable?

You can write your own requester class and pass it in instead...

2020-10-02 16:31 UTC, junderw commented
https://github.com/bitcoinjs/payjoin-client/blob/9241a826768b673f8d371f2d60db975d4139cccf/src/request.js#L35-L67

2020-10-02 16:33 UTC, junderw commented
If you look at the requester we provide it's trivial to re-implement using whatever request library react works with.

It's one of the reasons why we made the class interface so simple: IPayjoinRequester

https://github.com/bitcoinjs/payjoin-client/blob/9241a826768b673f8d371f2d60db975d4139cccf/src/request.d.ts#L20-L29

2020-10-02 16:36 UTC, Overtorment commented
> https://github.com/bitcoinjs/payjoin-client/blob/9241a826768b673f8d371f2d60db975d4139cccf/src/request.js#L35-L67

looks like Ill just need to copy-paste it completely, and pass it to payjoin client only to get rid this utils call:

```
    } else {
      this.payjoinRequester = new request_1.PayjoinRequester(
        utils_1.getEndpointUrl(opts.payjoinUrl, opts.payjoinParameters),
      );
    }
```

its the `utils.getEndpointUrl()` that is using `new URL()` and calling `.set()`
feels hacky.

2020-10-02 16:36 UTC, junderw commented
Actually, on second thought you just need to pass in `customFetch` (It's the second optional opt for the requester)

2020-10-02 16:37 UTC, junderw commented
Oh I see. It's not a problem with the async code but the URL parsing...

ugh, I hate JavaScript.

2020-10-02 16:40 UTC, junderw commented
This should be fixed by rewriting getEndpointUrl to not use standard Url...

Does querystring standard library play well with react?

2020-10-02 16:41 UTC, junderw commented
This needs to be fixed on the payjoin-client end and can not be fixed via composing.

2020-10-02 16:42 UTC, Overtorment commented
> This should be fixed by rewriting getEndpointUrl to not use standard Url...
> 
> Does querystring standard library play well with react?

its a roulette, hard to tell in advance. you code, with tests, everything works perfectly, and then falls apart in RN 

![image](https://user-images.githubusercontent.com/1913337/94948109-af919c00-04d6-11eb-976c-a4f92cbe2029.png)

2020-10-02 16:52 UTC, junderw commented
I added some comments to the PR on the payjoin-client repo.

2020-10-03 01:34 UTC, junderw commented
I published a new version `1.0.0-beta2` under the same `beta` tag to npm.

2020-10-05 11:31 UTC, Overtorment commented
![image](https://user-images.githubusercontent.com/1913337/95074112-e39ed400-0705-11eb-9ccc-3ee7e7bedda5.png)

2020-10-05 11:32 UTC, Overtorment commented
can `encodeURIComponent` be used instead?

2020-10-09 17:28 UTC, Overtorment commented
https://github.com/bitcoinjs/payjoin-client/pull/3

2020-10-14 11:38 UTC, Overtorment requested changes
``` 
screen/send/confirm.js#L5
'getEndpointUrl' is defined but never used   
```

otherwise lgtm. 
now Im going to test the build and do an actual payjoin

2020-10-14 12:55 UTC, Overtorment commented
everything worked well
![image](https://user-images.githubusercontent.com/1913337/95991565-d334da80-0e24-11eb-90ee-ef66d20563ea.png)

2020-10-14 15:41 UTC, Overtorment commented on package.json
> +    "payjoin-client": "git+https://github.com/bitcoinjs/payjoin-client.git#bip78",
when will this be released?

2020-12-01 17:04 UTC, Overtorment commented
pj dep bumped in other PR.
@Kukks, do I need to port smth from this branch? 

for example, currently we dont have `payjoinOutputSubstitutionDisabled` or `payjoinVersion`.

also, things seem to work even without `getEndpointUrlFunc()` which is a bit weird, no..?

2020-12-01 17:04 UTC, closed without merging