Electbackup
BlueWallet/BlueWallet pull request #1939
Opened 2020-09-30 01:57 UTC by marcosrdz

2020-09-30 02:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jc9gntgz9tzcexbpnqm5y4zzfr

[download apk](http://filestorage.bluewallet.io:1488/1601431855.apk)

2020-09-30 03:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/etatcndt52thhwa0nqt890mng8

[download apk](http://filestorage.bluewallet.io:1488/1601435386.apk)

2020-09-30 07:33 UTC, limpbrains requested changes

2020-09-30 07:33 UTC, limpbrains commented on class/wallets/abstract-wallet.js
> +      } else if (parsedSecret && parsedSecret.keystore && parsedSecret.keystore.xpub) {
`?.` would be nice

2020-09-30 07:33 UTC, limpbrains commented on class/deeplink-schema-match.js
> +  }
Please write a test for it in `deeplink-schema-match.test.js`

2020-09-30 07:36 UTC, limpbrains commented
@marcosrdz can you please write a few words of what this PR does. As I understand it is possible to create electrum backup is `.psbt` and extract seed from it, am I right?

2020-09-30 18:27 UTC, marcosrdz commented
> @marcosrdz can you please write a few words of what this PR does. As I understand it is possible to create electrum backup is `.psbt` and extract seed from it, am I right?

updated description

2020-10-01 18:15 UTC, limpbrains requested changes
Please tests at least

2020-10-07 11:34 UTC, Overtorment requested changes

2020-10-07 11:34 UTC, Overtorment commented on ios/Podfile.lock
> +COCOAPODS: 1.9.3
downgrade. is it ok?

2020-10-07 11:34 UTC, Overtorment commented on screen/send/ScanQRCode.js
> -        if (fileParsed.keystore.ckcc_xfp) {
i think I refactored all that mess in master. 
long story short, it doesn't belong here. import code is grouped in other place

2020-10-07 11:34 UTC, Overtorment commented on class/wallets/abstract-wallet.js
> +      if (parsedSecret && parsedSecret.keystore && parsedSecret.keystore.secret) {
tbh i dont remember why we have some import code in abstractwallet class.
anyway, it is mostly watch-only stuff (like, fancy wallet descriptor format `[8cce63f8/84h/0h/0h]zpub6s2RJ9qAEBW8Abhojs6LyDzF7gttcDr6EsR3Umu2aptZBb45e734rGtt4KqsCMmNyR1EEzUU2ugdVYez2VywQvAbBjUSKn8ho4Zk2c5otkk` )

not sure electrum backup stuff belongs here.

2020-10-07 11:34 UTC, Overtorment commented on screen/send/ScanQRCode.js
> -        if (fileParsed.keystore.ckcc_xfp) {
`ScanQRCode.js` is only for scaning qr / opening file and returning its contents

2020-10-07 11:34 UTC, Overtorment commented on class/deeplink-schema-match.js
> +  }
+1. tests are needed. we now have `tests/unit/fixtures/` where you can example backup file if you need

2020-11-24 09:34 UTC, ncoelho commented
This one is super useful @marcosrdz

2020-11-25 03:15 UTC, marcosrdz commented
> This one is super useful @marcosrdz

@Overtorment  didnt the multisig work include being able to import electrum backup files?

2020-11-25 11:55 UTC, Overtorment commented
no, import code is inside multisig wallet class, so if its single sig it wont impor tit

2021-02-08 05:03 UTC, closed without merging