Usecontext WIP
BlueWallet/BlueWallet pull request #1982
Opened 2020-10-14 14:49 UTC by marcosrdz

2020-10-14 15:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wza3y8f43xdw9b9mgw0kbhywrm

[download apk](http://filestorage.bluewallet.io:1488/1602689275.apk)

2020-10-14 23:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hu79pvdjj6zm1wyh56t2d2cmcw

[download apk](http://filestorage.bluewallet.io:1488/1602718791.apk)

2020-10-15 00:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8xmnevvhr4cpxz2tcxcyhg7knr

[download apk](http://filestorage.bluewallet.io:1488/1602723103.apk)

2020-10-15 01:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4x6ery8k19kyjdnpkv56rhddcc

[download apk](http://filestorage.bluewallet.io:1488/1602726439.apk)

2020-10-15 02:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/257y8gtp2q0e8z7f9ncw2pxhv8

[download apk](http://filestorage.bluewallet.io:1488/1602727626.apk)

2020-10-15 03:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kpb16eedee6xdfvjg2rxr25tj8

[download apk](http://filestorage.bluewallet.io:1488/1602731509.apk)

2020-10-15 04:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p9zvkupf86agcjgbpv8m59buqm

[download apk](http://filestorage.bluewallet.io:1488/1602734482.apk)

2020-10-15 12:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zf0z43v8a4a2pn09z9z4m0b8zg

[download apk](http://filestorage.bluewallet.io:1488/1602764442.apk)

2020-10-15 14:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/162azfw1gq6gkapfgr63x8gm3r

[download apk](http://filestorage.bluewallet.io:1488/1602770615.apk)

2020-10-15 15:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ux886qmymzu3f69hzdrbx87tt0

[download apk](http://filestorage.bluewallet.io:1488/1602776792.apk)

2020-10-15 17:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qmrz7kcxf150fp5hznc3ewr9jc

[download apk](http://filestorage.bluewallet.io:1488/1602781910.apk)

2020-10-16 02:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1mfvbhy7u0xhucubgvfy6mzrhg

[download apk](http://filestorage.bluewallet.io:1488/1602814310.apk)

2020-10-16 02:32 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ph1ze4f2drw7kcreg3jcbhr0u4

[download apk](http://filestorage.bluewallet.io:1488/1602815515.apk)

2020-10-16 04:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bpank73d9gavu93f6fkgkw88u0

[download apk](http://filestorage.bluewallet.io:1488/1602822859.apk)

2020-10-16 06:35 UTC, limpbrains submitted a review, later dismissed
Great work! This approach of using context to get fresh data from wallets feels more react than weird events system. 

Do you think there could be performance issues, since now you can have a few components subscribed to all changes?

The way a few classes like `DeeplinkSchemaMatch` or `WalletImport` where refactored feels odd. Because you add methods to react components and put business logic inside them. 
Idea to bound everything using react API feels weird to me. It is possible to archive something like this using EventEmitter somewhere inside `BlueApp`. I prefer keep react UI and business logic separated.

2020-10-16 08:49 UTC, marcosrdz commented
> Great work! This approach of using context to get fresh data from wallets feels more react than weird events system. 
> 
> 
> 
> Do you think there could be performance issues, since now you can have a few components subscribed to all changes?
> 
> 
> 
> The way a few classes like `DeeplinkSchemaMatch` or `WalletImport` where refactored feels odd. Because you add methods to react components and put business logic inside them. 
> 
> Idea to bound everything using react API feels weird to me. It is possible to archive something like this using EventEmitter somewhere inside `BlueApp`. I prefer keep react UI and business logic separated. 

Xcode is reporting a lower consumption of memory. And the app behaves faster. The "business logic" will be moved to useReducer later.
I also have to place those items in the "DOM" so they have access to the context and are able to answer to state changes instantly anywhere(look at watchconnectivity for example). With this change, i can work with my wallets and every change gets synced to my watch through hooks..and this is all without blueapp being aware of that component.

2020-10-16 12:31 UTC, Overtorment requested changes
my main concern is whethere my IDE gona understand code correctly and provide code navigation & code completion.

for example, that `this.context` provides a bunch of functions from BlueApp


or that in  `const { txMetadata, wallets } = useContext(BlueStorageContext);` 
`wallets` is an array of AbstractWallet


I havent tested it with my IDE yet, but in case it wont recognize it. is there a way to make a typehints for ide? 
for example, you might notice that i have things like
`const BlueApp: AppStorage = require('../../BlueApp');` 
or 
```
    /** @type {AbstractHDElectrumWallet|WatchOnlyWallet} */
    const wallet = this.state.fromWallet;
```


PS. e2e fails

2020-10-16 12:31 UTC, Overtorment commented on class/wallet-import.js
> +    return false;
can be reduced to  `return !!wallet`

2020-10-16 12:31 UTC, Overtorment commented on class/wallet-import.js
> +    if (WalletImport.isWalletImported(w.getSecret())) {
comparing secrets is not enough, you need to compare IDs as well
(for example, multisig wallet takes provided secret and transfors it in internal representation. and  `getSectret` outputs it in different format, so technically different secrets could still create same wallets with proper equal IDs)

2020-10-16 12:31 UTC, Overtorment commented on screen/settings/GeneralSettings.js
> +  const [adancedIsModeEnabled, setAdancedModeIsEnabled] = useState(false);
mindfuck with names. can it be improved?

2020-10-16 12:31 UTC, Overtorment commented on tests/integration/notifications.test.js
> +const { default: BlueNotifications } = require('../../blue_modules/notifications');
unnecessary rename

2020-10-16 22:44 UTC, marcosrdz commented on BlueComponents.js
> +    await this.context.saveToDisk();
this.context is defined in React.Component. Just like a setState and props

2020-10-16 22:44 UTC, marcosrdz commented on blue_modules/BlueStorage.js
> +    txMetadata = BlueApp.tx_metadata;
Lint was complaining it tx_metadata

2020-10-16 22:45 UTC, marcosrdz commented on blue_modules/BlueStorage.js
> +  const getHodlHodlContracts = BlueApp.getHodlHodlContracts;
Thats correct. Any function or property that needs exposure should be defined here

2020-10-16 22:45 UTC, marcosrdz commented on blue_modules/events.js
> -function EV(eventName, arg, isExclusive) {
The end of an era

2020-10-17 05:19 UTC, marcosrdz commented on App.js
> +import BlueNotifications from './blue_modules/notifications';
i placed the notification code inside a function so i can pass a props to it..i renamed it back to notifications.

2020-10-17 05:26 UTC, marcosrdz commented on screen/settings/GeneralSettings.js
> +  const [adancedIsModeEnabled, setAdancedModeIsEnabled] = useState(false);
changed to isAdancedModeSwitchEnabled

2020-10-17 05:30 UTC, marcosrdz commented
>    /** @type {AbstractHDElectrumWallet|WatchOnlyWallet} */
>     const wallet = this.state.fromWallet;



> my main concern is whethere my IDE gona understand code correctly and provide code navigation & code completion.
> 
> for example, that `this.context` provides a bunch of functions from BlueApp
> 
> or that in `const { txMetadata, wallets } = useContext(BlueStorageContext);`
> `wallets` is an array of AbstractWallet
> 
> I havent tested it with my IDE yet, but in case it wont recognize it. is there a way to make a typehints for ide?
> for example, you might notice that i have things like
> `const BlueApp: AppStorage = require('../../BlueApp');`
> or
> 
> ```
>     /** @type {AbstractHDElectrumWallet|WatchOnlyWallet} */
>     const wallet = this.state.fromWallet;
> ```
> 
> PS. e2e fails

Those never had autocomplete for me. Your IDE recognizes those but VS Code doesnt. I'll have to check.

2020-10-17 06:47 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z7gpnvez4ef18j20dr36na3vwm

[download apk](http://filestorage.bluewallet.io:1488/1602917265.apk)

2020-10-17 13:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9d5k0m4v1nxck96tm3kh8aj46m

[download apk](http://filestorage.bluewallet.io:1488/1602942586.apk)

2020-10-17 15:05 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/adjtw04zhquaf5xvtmy0tfrxjg

[download apk](http://filestorage.bluewallet.io:1488/1602947106.apk)

2020-10-17 16:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/72y4b4x4wxvjzeuj6haf7eem2r

[download apk](http://filestorage.bluewallet.io:1488/1602953169.apk)

2020-10-18 03:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5h2zbve416z3vdp8zthny0xgm4

[download apk](http://filestorage.bluewallet.io:1488/1602993369.apk)

2020-10-19 02:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kvgw9x6qm1mrdffmwjur8xbmv8

[download apk](http://filestorage.bluewallet.io:1488/1603073624.apk)

2020-10-19 03:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wv4gec0czc80a6tyz7k827qtf8

[download apk](http://filestorage.bluewallet.io:1488/1603077303.apk)

2020-10-19 03:29 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b1mcayu1x8kjpbt8jdr3fg4d84

[download apk](http://filestorage.bluewallet.io:1488/1603078133.apk)

2020-10-19 13:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e8kypefadbe9tx0rcmjw020xtm

[download apk](http://filestorage.bluewallet.io:1488/1603113186.apk)

2020-10-19 14:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v50fgqx18v4n2kt2w7arp7ema0

[download apk](http://filestorage.bluewallet.io:1488/1603118041.apk)

2020-10-20 02:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5rz79ucb7zdgh0m2ffatuuqtq4

[download apk](http://filestorage.bluewallet.io:1488/1603159489.apk)

2020-10-20 03:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cuxukh0nt030fj0tn1pqmcz4m8

[download apk](http://filestorage.bluewallet.io:1488/1603164998.apk)

2020-10-20 04:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/09wn52aba4vh8a1gtguunuh3dg

[download apk](http://filestorage.bluewallet.io:1488/1603167932.apk)

2020-10-20 15:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mqx4rpcz1ncq8yt5fr4mb36hbg

[download apk](http://filestorage.bluewallet.io:1488/1603207465.apk)

2020-10-20 19:12 UTC, Overtorment submitted a review, later dismissed
ok if @ncoelho has no objections and cant find any bugs we can merge it

2020-10-21 09:27 UTC, ncoelho commented
Weird behaviour

<img src="https://user-images.githubusercontent.com/1238429/96700948-ef39fe00-1387-11eb-82fb-5ad3764092e2.gif" width="300px">

2020-10-21 09:34 UTC, ncoelho commented
Weird first load

<img src="https://user-images.githubusercontent.com/1238429/96701756-db42cc00-1388-11eb-849a-7fa256a28f9c.gif" width="300px">

2020-10-21 09:41 UTC, ncoelho commented
Wallet creation doesn't go to latest wallet

<img src="https://user-images.githubusercontent.com/1238429/96702683-e9451c80-1389-11eb-85c5-2fb3d4b32597.gif" width="300px">

2020-10-21 09:48 UTC, ncoelho commented
transactions.js is not triggering a refresh after doing a transaction. 

☝️ this is a blocker...

2020-10-21 14:11 UTC, marcosrdz commented
> Wallet creation doesn't go to latest wallet
> 
> <img alt="" width="300px" src="https://user-images.githubusercontent.com/1238429/96702683-e9451c80-1389-11eb-85c5-2fb3d4b32597.gif">

Fixed

2020-10-21 14:12 UTC, marcosrdz commented
> Weird behaviour
> 
> <img alt="" width="300px" src="https://user-images.githubusercontent.com/1238429/96700948-ef39fe00-1387-11eb-82fb-5ad3764092e2.gif">

Fixed

2020-10-21 14:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hq2nzzf87h3jrtu1j9hwu6h85g

[download apk](http://filestorage.bluewallet.io:1488/1603290827.apk)

2020-10-21 18:43 UTC, ncoelho commented
> > Wallet creation doesn't go to latest wallet
> > <img alt="" width="300px" src="https://user-images.githubusercontent.com/1238429/96702683-e9451c80-1389-11eb-85c5-2fb3d4b32597.gif">
> 
> Fixed

tACK. This looks good

2020-10-21 18:48 UTC, ncoelho commented
> > Weird behaviour
> > <img alt="" width="300px" src="https://user-images.githubusercontent.com/1238429/96700948-ef39fe00-1387-11eb-82fb-5ad3764092e2.gif">
> 
> Fixed

I still see the bad loading on the listing, at least on onchain wallets.

<img src="https://user-images.githubusercontent.com/1238429/96768846-3a7afd80-13d6-11eb-99e2-2e94ed818c7e.gif" width="300px">

2020-10-21 23:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n526y0cym7nu74j5e3j5uttv5g

[download apk](http://filestorage.bluewallet.io:1488/1603321859.apk)

2020-10-23 00:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yb3ve0tqhxec6jwj4tet3mx7hg

[download apk](http://filestorage.bluewallet.io:1488/1603412031.apk)

2020-10-23 01:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6n7cwu81hcdfxr59qbrn011q0r

[download apk](http://filestorage.bluewallet.io:1488/1603415909.apk)

2020-10-23 20:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yw7w57tj5fp49e8a0umnq25020

[download apk](http://filestorage.bluewallet.io:1488/1603483314.apk)

2020-10-23 22:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e49gjyv0d58xhafqh1tc07502g

[download apk](http://filestorage.bluewallet.io:1488/1603490524.apk)

2020-10-23 23:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k44gwr04dt8tza31dzwdhzy8br

[download apk](http://filestorage.bluewallet.io:1488/1603495128.apk)

2020-10-24 00:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qepqt5pg3emubq2twz1c3ypkm4

[download apk](http://filestorage.bluewallet.io:1488/1603501001.apk)

2020-10-24 17:20 UTC, merged