support lnurl fallback scheme.
BlueWallet/BlueWallet pull request #1993
Opened 2020-10-18 14:50 UTC by fiatjaf

There was partial support mixed in with the code but it didn't work actually.
This PR also uses the `Lnurl` class to replace some old code in the lnurl-withdraw handler.

2020-10-22 19:14 UTC, Overtorment approved these changes
lgtm

2020-10-22 22:57 UTC, junderw commented on class/lnurl.js
> +    var res = /^(http.*[&?]lightning=)?((lnurl)([0-9]{1,}[a-z0-9]+){1})/.exec(bodyOfText.toLowerCase());
```js
var res = /^(?:http.*[&?]lightning=)?(lnurl1[02-9ac-hj-np-z]+)/.exec(bodyOfText.toLowerCase());
if (res) {
  return res[1];
}
```

1. Add ?: to the beginning of () to make a non-capturing group.
2. No need for () around lnurl
3. lnurl is bech32, the separator is 1, not "unlimited numbers"
4. lnurl is bech32, this is a limited set of characters `[02-9ac-hj-np-z]` and not "alphanumerical"
5. {1} is meaningless, so is the group it modifies
6. Since lnurl is now the first captured group, we return res[1] not res[2]

2020-10-22 22:57 UTC, junderw commented on class/lnurl.js
> +    var res = /^(http.*[&?]lightning=)?((lnurl)([0-9]{1,}[a-z0-9]+){1})/.exec(bodyOfText.toLowerCase());
Also, You can verify the regex for bech32 with this code using the const alphabet from bech32 library

```js
const bech32 = 'qpzry9x8gf2tvdw0s3jn54khce6mua7l';
let lastLetter = '';
console.log(
  bech32
    .split('')
    .sort()
    .reduce((final, c, idx) => {
      if (final === '') return c;
      if (idx === bech32.length - 1) return final + c;
      const endLetter = final.slice(-1);

      if (endLetter !== '-') {
        lastLetter = endLetter;
        if (lastLetter.codePointAt(0) === c.codePointAt(0) - 1) {
          lastLetter = c;
          return final + '-';
        } else {
          return final + c;
        }
      } else {
        if (lastLetter.codePointAt(0) === c.codePointAt(0) - 1) {
          lastLetter = c;
          return final;
        } else {
          return final + lastLetter + c;
        }
      }
    }, '')
);
```

2020-10-22 23:03 UTC, junderw commented on class/lnurl.js
> +    var res = /^(http.*[&?]lightning=)?((lnurl)([0-9]{1,}[a-z0-9]+){1})/.exec(bodyOfText.toLowerCase());
regex is hated by most programmers because if you take the normal dev approach of "fiddle around with it until one test case works" has about a 99.999999999% chance of having a bug in it, because regex is complicated, and user provided strings can be anything (usually unforseen as to how crazy the strings can become)

plus regex is hard to parse in your brain when reading the code.

I worked on translation assistance software for years... I also hate regex. lol

2020-10-22 23:04 UTC, junderw requested changes
The regex comments I made

2020-10-22 23:07 UTC, junderw commented on class/lnurl.js
> +    var res = /^(http.*[&?]lightning=)?((lnurl)([0-9]{1,}[a-z0-9]+){1})/.exec(bodyOfText.toLowerCase());
That being said, no guarantee my suggestion has no bugs in it. :-P

2020-10-22 23:35 UTC, Overtorment commented
There is a saying. Once programmer has a problem and he thinks, okay I can
solve it with regexp, starting from that moment he has 2 problems kek

On Fri, 23 Oct 2020 at 00:07, Jonathan Underwood <notifications@github.com>
wrote:

> *@junderw* commented on this pull request.
> ------------------------------
>
> In class/lnurl.js
> <https://github.com/BlueWallet/BlueWallet/pull/1993#discussion_r510506551>
> :
>
> > @@ -20,9 +20,9 @@ export default class Lnurl {
>    }
>
>    static findlnurl(bodyOfText) {
> -    var res = /,*?((lnurl)([0-9]{1,}[a-z0-9]+){1})/.exec(bodyOfText.toLowerCase());
> +    var res = /^(http.*[&?]lightning=)?((lnurl)([0-9]{1,}[a-z0-9]+){1})/.exec(bodyOfText.toLowerCase());
>
> That being said, no guarantee my suggestion has no bugs in it. :-P
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/BlueWallet/BlueWallet/pull/1993#discussion_r510506551>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOTD6JJNKLSK3G75G7BOE3SMC3LRANCNFSM4SVEGHPQ>
> .
>

2020-10-26 17:24 UTC, Overtorment commented
@fiatjaf are you going to work on this?

2020-10-26 18:54 UTC, fiatjaf commented
For some reason I thought @junderw's review was already a fix. I've copied his regex now. It seems to work. I trust it because he guaranteed his suggestion has no bugs.

2020-10-26 22:17 UTC, junderw approved these changes
> he guaranteed his suggestion has no bugs.

LOL, no. I did not guarantee anything such as that.

But I do guarantee it has LESS bugs that what was originally there. :-)

2020-10-27 00:25 UTC, fiatjaf commented
![2020-10-26-212525_683x651_scrot](https://user-images.githubusercontent.com/1653275/97242137-c83d5b00-17d1-11eb-8a73-7c36567a51c9.png)

You can't deny this.

2020-10-27 01:03 UTC, junderw commented
> You can't deny this.

Yes I can. I could deny it by saying someone logged into my account to write that comment.

Whether the deniable is credible or not is another question. :-P

2020-10-27 01:07 UTC, junderw commented
(Not to mention that anyone who has a basic understanding of regex and how most developers perceive regex that sees someone say "I guarantee my regex has no bugs" can deduce with high certainty that they are being sarcastic. (even without the ":-P" at the end))

2020-10-27 03:39 UTC, fiatjaf commented
Sorry, I faked the screenshot, I thought it would be funny and you would notice it (or maybe you did, but other people reading may be confused).

Never trust a screenshot!

2020-10-28 01:01 UTC, marcosrdz approved these changes

2020-10-28 05:40 UTC, limpbrains approved these changes

2020-10-28 12:30 UTC, merged