ADD: ui to create multisig
BlueWallet/BlueWallet pull request #2001
Opened 2020-10-20 10:16 UTC by Overtorment

2020-10-20 10:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tffycbx50xzw3epderc88115m4

[download apk](http://filestorage.bluewallet.io:1488/1603190024.apk)

2020-10-20 15:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4p23588pc65nxhtv33v6pqr6ur

[download apk](http://filestorage.bluewallet.io:1488/1603208652.apk)

2020-10-21 11:20 UTC, limpbrains commented
Are you going to change this wallet type selector?
<img width="200" alt="image" src="https://user-images.githubusercontent.com/155891/96711808-d0972f80-13a6-11eb-9e69-81d547e2ccd5.png">

Create button doesn't fit on Android despite the fact that there is enough space (Nexus 5 on appetize0
<img width="200" alt="image" src="https://user-images.githubusercontent.com/155891/96711665-975ebf80-13a6-11eb-8f6d-28d6fb6292b7.png"> <img width="200" alt="image" src="https://user-images.githubusercontent.com/155891/96711890-f290b200-13a6-11eb-98e2-a5d4f47824ed.png">

After key is generated I'm pressing "view" xpub opens very slowly. Why is that ?
On dark theme I can't read "This is cosigner's xpub"

Create is very long. For some time Create button keeps disabled, but at the end it becomes enabled. Better keep it disabled.

Need to be aligned
<img width="200" alt="image" src="https://user-images.githubusercontent.com/155891/96712881-76976980-13a8-11eb-942c-2dd2ce217df8.png">

2020-10-21 11:25 UTC, ncoelho commented
@limpbrains Yes, the entire UI needs polish and some rework. Let's focus on functionality for now.

2020-10-21 11:42 UTC, limpbrains approved these changes

2020-10-21 11:42 UTC, limpbrains commented on class/multisig-cosigner.js
> +        this._valid = true;
I think `return` should be here, after `this._valid = true;`. Why do you need to try coldcard if cobo import was successful?

2020-10-21 11:42 UTC, limpbrains commented on BlueComponents.js
> +          <Text style={{ color: colors.hdborderColor, fontWeight: 'bold' }}>Multisig Vault</Text>
translate please

2020-10-21 16:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0a7aq17k3ukz7f96mmbrq0q9h8

[download apk](http://filestorage.bluewallet.io:1488/1603297444.apk)

2020-10-21 20:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7yb9xeqhz1efj763z85f5jegfr

[download apk](http://filestorage.bluewallet.io:1488/1603311655.apk)

2020-10-21 23:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zcmkgyakkv5m80m6az4hugzerc

[download apk](http://filestorage.bluewallet.io:1488/1603322596.apk)

2020-10-22 11:44 UTC, Overtorment commented
added `loading` state to second step when its creating a ms. removed `fetchBalance` so its faster.
made `view key` to work with cached value which is filled when key is generated.

2020-10-22 12:36 UTC, limpbrains approved these changes

2020-10-22 13:09 UTC, limpbrains requested changes

2020-10-22 13:09 UTC, limpbrains commented on screen/wallets/addMultisig.js
> +  filterText: { fontSize: 16, color: 'gray' },
All `BlueCurrentTheme.colors` should come from `useTheme` inside render function

2020-10-22 13:09 UTC, limpbrains commented on screen/wallets/addMultisig.js
> +    backgroundColor: BlueCurrentTheme.colors.elevated,
same

2020-10-22 13:25 UTC, marcosrdz commented on screen/wallets/addMultisig.js
> +  filterText: { fontSize: 16, color: 'gray' },
Fixed.

2020-10-22 13:25 UTC, marcosrdz commented on screen/wallets/addMultisig.js
> +    backgroundColor: BlueCurrentTheme.colors.elevated,
fixed.

2020-10-22 13:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1fd8qfzk02wwbdzm6t1y8c3wag

[download apk](http://filestorage.bluewallet.io:1488/1603374044.apk)

2020-10-23 01:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/khvtbacuna2qa7k2ew583rg1r8

[download apk](http://filestorage.bluewallet.io:1488/1603415061.apk)

2020-10-23 11:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vc42ncnxz0ju93r4dd9t9hhwm0

[download apk](http://filestorage.bluewallet.io:1488/1603453865.apk)

2020-10-23 18:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7yuw0j9g5t9ffxkbyeueqf3er4

[download apk](http://filestorage.bluewallet.io:1488/1603479197.apk)

2020-10-24 22:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/db7w7vdafk96k23g83wpdndpc8

[download apk](http://filestorage.bluewallet.io:1488/1603578481.apk)

2020-10-24 23:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ntzhu1ph9713gfm4xvb2x9fb5c

[download apk](http://filestorage.bluewallet.io:1488/1603583422.apk)

2020-10-25 11:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wd2fhwd8z2pnp5arnhe9gw9aug

[download apk](http://filestorage.bluewallet.io:1488/1603626103.apk)

2020-10-26 01:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7xxefvb37b310jpah78d6x88j4

[download apk](http://filestorage.bluewallet.io:1488/1603674805.apk)

2020-10-26 01:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j62k3tk2ptnk5bqhu99y0d6e50

[download apk](http://filestorage.bluewallet.io:1488/1603676874.apk)

2020-10-26 02:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mhb8fu6h13ecanenym6yvcpekc

[download apk](http://filestorage.bluewallet.io:1488/1603678944.apk)

2020-10-26 03:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8ppqh4dw035jjz1x04qmnpk710

[download apk](http://filestorage.bluewallet.io:1488/1603681939.apk)

2020-10-26 03:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dtccm5d3cp7yvcadjmtf5g6wdg

[download apk](http://filestorage.bluewallet.io:1488/1603683366.apk)

2020-10-26 04:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fx7z1rf735evk2mdckd1eq9tww

[download apk](http://filestorage.bluewallet.io:1488/1603685962.apk)

2020-10-26 13:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/da1p5cw0cuzxrgr0mrr7e5uvp4

[download apk](http://filestorage.bluewallet.io:1488/1603718887.apk)

2020-10-27 01:20 UTC, marcosrdz approved these changes

2020-10-27 01:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gthwc8bjmattqdmqrzjkf304cc

[download apk](http://filestorage.bluewallet.io:1488/1603763731.apk)

2020-10-27 08:06 UTC, limpbrains requested changes

2020-10-27 23:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wqz57xthbxrmfw5tfta4gzf4hc

[download apk](http://filestorage.bluewallet.io:1488/1603839811.apk)

2020-10-27 23:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vym4dumurz389ev4bc2we638v4

[download apk](http://filestorage.bluewallet.io:1488/1603840598.apk)

2020-10-28 01:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nachmekv18wcdbhdgw86vdc36w

[download apk](http://filestorage.bluewallet.io:1488/1603849503.apk)

2020-10-28 02:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/77qpkm8rnrrdbdb99vk41wvph4

[download apk](http://filestorage.bluewallet.io:1488/1603853774.apk)

2020-10-28 19:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6q5xacr2jhk0a98zyj4hj8rc6m

[download apk](http://filestorage.bluewallet.io:1488/1603912525.apk)

2020-10-28 22:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6cf6xemuzf21h5krk7t2ccd1ww

[download apk](http://filestorage.bluewallet.io:1488/1603922575.apk)

2020-10-28 22:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7z75m4qa4kg6tdgcqdanc5pue4

[download apk](http://filestorage.bluewallet.io:1488/1603925071.apk)

2020-10-29 02:58 UTC, marcosrdz commented on screen/wallets/viewEditMultisigCosigners.js
> +  const format = tempWallet.getFormat();
@Overtorment

2020-10-29 03:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wqz6u73206u0qtvm6jq12zru5m

[download apk](http://filestorage.bluewallet.io:1488/1603941736.apk)

2020-10-29 10:12 UTC, Overtorment commented on screen/wallets/viewEditMultisigCosigners.js
> +    goBack();
goBack() wont work here, it navigates back to details of the wallet that doesnt exist anymore, since we deleted it and recreated a new one with a new ID

2020-10-29 10:37 UTC, Overtorment commented on screen/wallets/addMultisig.js
> +};
I dont know how to do that so made it this way

2020-10-29 10:41 UTC, Overtorment commented on screen/wallets/viewEditMultisigCosigners.js
> +  const format = tempWallet.getFormat();
@marcosrdz refactored it with `useRef`.
long story short, you cant edit global wallet object cause its the object thats used in the app. so to save new wallet you have to create a new object instance, and when user presses  `save` - replace it

2020-10-29 12:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7ebrwkpekb17eze3cr4hb45rkm

[download apk](http://filestorage.bluewallet.io:1488/1603974006.apk)

2020-10-29 17:21 UTC, Overtorment commented
can you guys review again? I intend to merge it, and do a silent release, so its easier to test. 
vault button becomes visible through a backdoor: tap 15 times on btc button

2020-10-29 18:07 UTC, limpbrains approved these changes

2020-10-29 18:13 UTC, marcosrdz commented on components/DynamicQRCode.js
> +  };
This component is not used by itself. Its inside a view with other options such as Sharing the qr data to other apps.

2020-10-29 18:14 UTC, marcosrdz approved these changes

2020-10-29 21:09 UTC, Overtorment commented on components/DynamicQRCode.js
> +  };
but basically yes, blank screen. this should never happen tho (until it does kek)

2020-10-29 21:09 UTC, Overtorment commented on screen/wallets/addMultisigStep2.js
> +        if (existingCosigner[0] === cosigner.getXpub()) return alert('This cosigner is already imported');
oops that one was missed

2020-10-29 21:13 UTC, marcosrdz commented on components/DynamicQRCode.js
> +  };
Yeah. But the app would crash without this onError handled. Not the best approach but better than a crash

2020-10-29 21:13 UTC, merged

2020-10-29 21:22 UTC, limpbrains commented on components/DynamicQRCode.js
> +  };
I mean, you can show some error with `alert` to not to left user uninformed of what is going on

2020-10-29 21:31 UTC, marcosrdz commented on components/DynamicQRCode.js
> +  };
Yup. That will be addressed.