Coin control
BlueWallet/BlueWallet pull request #2006
Opened 2020-10-22 13:36 UTC by limpbrains

2020-10-22 13:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ba5pkn92k02f3hg8u30ju68gbw

[download apk](http://filestorage.bluewallet.io:1488/1603374868.apk)

2020-10-23 10:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gcnx8wddq7gvhjhcxwnegx14j8

[download apk](http://filestorage.bluewallet.io:1488/1603449651.apk)

2020-10-23 11:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f7r5292t9kh4q4jgqmp16qytbc

[download apk](http://filestorage.bluewallet.io:1488/1603450873.apk)

2020-10-25 07:47 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dfkjk44kqkddyv8k9j78zhbqf4

[download apk](http://filestorage.bluewallet.io:1488/1603612026.apk)

2020-10-25 08:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1k3zwdrbuujzk5cvzfan993zhc

[download apk](http://filestorage.bluewallet.io:1488/1603613775.apk)

2020-10-25 09:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f8d1354ttcxfuh78pxbhykxycm

[download apk](http://filestorage.bluewallet.io:1488/1603617334.apk)

2020-10-25 10:29 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5rvjn9bw1ubx0r3ckjqmpgxuu0

[download apk](http://filestorage.bluewallet.io:1488/1603621738.apk)

2020-10-26 11:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/02thmahgf7h1fqxr1j33rhb57g

[download apk](http://filestorage.bluewallet.io:1488/1603710867.apk)

2020-10-26 20:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1gcjnzh7hzuuvagueuxyu0pc2g

[download apk](http://filestorage.bluewallet.io:1488/1603742368.apk)

2020-10-27 01:35 UTC, marcosrdz requested changes

2020-10-27 01:35 UTC, marcosrdz commented on screen/send/coinControl.js
> +      <FlatList data={utxo} renderItem={renderItem} keyExtractor={item => `${item.txid}:${item.vout}`} />
Probably missing style. Switching appearance leads me to believe that.

2020-10-27 01:35 UTC, marcosrdz commented on screen/send/coinControl.js
> +    <ListItem bottomDivider onPress={onPress}>
container style?

2020-10-27 09:43 UTC, ncoelho commented
Testing... 
I like the color associated with the transaction, makes it easier to associate the utxos to previous behaviour.

Bugs:
- Labels are not updating for individual utxos, but they update with the transaction label change. Should be, if the transaction has a label, use that to populate the data. If the user changes the individual utxo label, that should be the label seen.
- I believe with the useContext change we should the see the "freeze" update in realtime.
- The utxo order was updated with the label change. I believe the list order should be based on the block height the utxo was created. So older utxos on the bottom, newer on the top.

Will keep testing

2020-10-28 08:47 UTC, limpbrains commented
> * Labels are not updating for individual utxos, but they update with the transaction label change. Should be, if the transaction has a label, use that to populate the data. If the user changes the individual utxo label, that should be the label seen.
> 
> * I believe with the useContext change we should the see the "freeze" update in realtime.

All fixed, also now showing Address instead of txid:vout on utxo list

2020-10-28 09:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xmw9wjfj98qx03x48u29bwdae0

[download apk](http://filestorage.bluewallet.io:1488/1603875618.apk)

2020-10-28 09:45 UTC, limpbrains commented on screen/send/coinControl.js
> +      <FlatList data={utxo} renderItem={renderItem} keyExtractor={item => `${item.txid}:${item.vout}`} />
Thanks, I've fixed the dark appearance

2020-10-28 10:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n5jh07wdh26dd820mnkddh1z5m

[download apk](http://filestorage.bluewallet.io:1488/1603880134.apk)

2020-10-29 09:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z5h8zf697dz5hrvyj5qm4ey96c

[download apk](http://filestorage.bluewallet.io:1488/1603962266.apk)

2020-10-29 20:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qyvy2v9bxj50tgx9wdpt9z43zm

[download apk](http://filestorage.bluewallet.io:1488/1604004976.apk)

2020-10-30 06:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ntp93xvbxzvh3r32rc0vr3u0g4

[download apk](http://filestorage.bluewallet.io:1488/1604040877.apk)

2020-10-30 07:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5egyqaaz2twd05vfknvxkj65q0

[download apk](http://filestorage.bluewallet.io:1488/1604044640.apk)

2020-11-03 08:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kddapm2nj5vcm70fv2mpmzvtqg

[download apk](http://filestorage.bluewallet.io:1488/1604393642.apk)

2020-11-03 13:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r740y1qzfqx5raag8y7p01r0zr

[download apk](http://filestorage.bluewallet.io:1488/1604410728.apk)

2020-11-04 16:45 UTC, limpbrains commented
* e2e test is ready
* I'm thinking about implementing multi-select on coin control screen in next iteration

`screen/send/confirm.js` and `screen/send/create.js` now always have `recipients` with calculated `value` because I'm grabbing `outputs` from `wallet.createTransaction(` instead of raw `outputs`

2020-11-04 16:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rh7yjzv3t1cmwqfy67cycc53ac

[download apk](http://filestorage.bluewallet.io:1488/1604509029.apk)

2020-11-06 04:47 UTC, marcosrdz commented
@limpbrains  Deepscan report.

2020-11-06 04:57 UTC, marcosrdz approved these changes

2020-11-06 06:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/76nnx73h127rawbphtgryx0f0m

[download apk](http://filestorage.bluewallet.io:1488/1604645007.apk)

2020-11-06 07:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rzfqjhbrcxtzbh1muj9ewubet0

[download apk](http://filestorage.bluewallet.io:1488/1604647792.apk)

2020-11-06 10:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bp4n5aty379a0hbdb64g8whnbc

[download apk](http://filestorage.bluewallet.io:1488/1604659463.apk)

2020-11-06 16:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dpbe33kyc9rqvbkdbqqx5zxk18

[download apk](http://filestorage.bluewallet.io:1488/1604678817.apk)

2020-11-07 19:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ak7fm1f8h9t81m7g1vr7xb1tcc

[download apk](http://filestorage.bluewallet.io:1488/1604778941.apk)

2020-11-08 22:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4pamba40ymhcfun8vw1pt9z94m

[download apk](http://filestorage.bluewallet.io:1488/1604873719.apk)

2020-11-09 08:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vzdjuczf1aqu8qyu22xy4znaqc

[download apk](http://filestorage.bluewallet.io:1488/1604911281.apk)

2020-11-09 09:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vbwknhjvetav7p2ymgtvx0p4br

[download apk](http://filestorage.bluewallet.io:1488/1604914756.apk)

2020-11-09 10:52 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ncbchkx12cdah8uqa4ktqp4hxg

[download apk](http://filestorage.bluewallet.io:1488/1604919128.apk)

2020-11-10 07:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xz357qgy9puwzf42fwh31cgb9g

[download apk](http://filestorage.bluewallet.io:1488/1604992523.apk)

2020-11-11 05:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ee7x2w3dqtr8yr8axxkck710u8

[download apk](http://filestorage.bluewallet.io:1488/1605071452.apk)

2020-11-11 20:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v54dfmg453z7c4260r4tz2z5jc

[download apk](http://filestorage.bluewallet.io:1488/1605124806.apk)

2020-11-12 00:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rpn7a5bkdw66bd2e3g0mt7pu10

[download apk](http://filestorage.bluewallet.io:1488/1605142502.apk)

2020-11-15 05:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/h8cav3vmf6xrw1f391x85652u0

[download apk](http://filestorage.bluewallet.io:1488/1605417516.apk)

2020-11-17 21:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3j0u2k1tx1paau6x05t1k1mtp0

[download apk](http://filestorage.bluewallet.io:1488/1605648311.apk)

2020-11-18 14:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9tp3zyfbn39qgqhvm7fxjpakpc

[download apk](http://filestorage.bluewallet.io:1488/1605710738.apk)

2020-11-19 15:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uhdrpfzmmnwartrxga096f4gy0

[download apk](http://filestorage.bluewallet.io:1488/1605799574.apk)

2020-11-19 17:32 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/60d51c3kfqv8v6aufm9h8v7fj8

[download apk](http://filestorage.bluewallet.io:1488/1605807116.apk)

2020-11-19 21:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1d1aafmvmqthf9h1hkr6t4qrmr

[download apk](http://filestorage.bluewallet.io:1488/1605819611.apk)

2020-11-20 02:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f0gy2j1nwzn7e26gre4kbrn6ng

[download apk](http://filestorage.bluewallet.io:1488/1605841030.apk)

2020-11-20 17:11 UTC, Overtorment requested changes
mostly okayish

2020-11-20 17:11 UTC, Overtorment commented on class/wallets/legacy-wallet.js
> +    return false;
shouldnt it be `this.getAddress() === address` ?
since single-address wallets send change to themselves

2020-11-20 17:11 UTC, Overtorment commented on BlueComponents.js
> +    <TouchableOpacity testID="CopyToClipboard" onPress={() => Clipboard.setString(stringToCopy)}>
this testID is not used..?

2020-11-20 17:11 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.js
> +  getUtxo({ frozen = false } = {}) {
why args in object? lets use plain func arguments.
plus, naming could be better. looks like it shoul be smth like `filterOutFrozen` or `respectFrozen` or smth. description in jsdoc would be nice

2020-11-22 07:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tpq7v6m831zwrt3e93hbxhmb9w

[download apk](http://filestorage.bluewallet.io:1488/1606029618.apk)

2020-11-22 07:43 UTC, limpbrains commented on class/wallets/abstract-wallet.js
> +  setUTXOMetadata(txid, vout, opts) {
added

2020-11-22 07:43 UTC, limpbrains commented on class/wallets/abstract-wallet.js
> +    this.utxoMetadata = {};
fixed

2020-11-22 07:48 UTC, limpbrains commented on class/wallets/abstract-hd-electrum-wallet.js
> +  getUtxo({ frozen = false } = {}) {
I think it makes function call more readable. 
`.getUtxo(true)` vs `.getUtxo({respectFrozen: true})`
Also, it allows not to think about arguments' order in future refactorings. For optional arguments this approach looks better, IMO
But here I'm ok with `.getUtxo(true)`

2020-11-22 07:51 UTC, limpbrains commented on class/wallets/hd-legacy-p2pkh-wallet.js
> -
My error, I thought it is a duplicate, fixed

2020-11-22 07:55 UTC, limpbrains commented on screen/send/details.js
> +      recipients,
Because `Confirm` screen designed not to show change outputs. 
Without filtering regular tx with 2 outputs, one regular and one change, looks like send many with 2 outputs

2020-11-22 08:15 UTC, limpbrains commented on screen/send/coinControl.js
> +import _debounce from 'lodash/debounce';
fixed

2020-11-22 08:20 UTC, limpbrains commented on class/wallets/legacy-wallet.js
> +  // Check if address is a Change address. Needed for Coin control.
fixed

2020-11-22 08:22 UTC, limpbrains commented on class/wallets/legacy-wallet.js
> +    return false;
In this case every incoming tx will be marked as a change.
The proper way would be to check both inputs and outputs for `this.getAddress()`, but it gets complicated here. So I thought LegacyWallets are not used offen and it's ok not to detect change UTXO for them

2020-11-22 08:24 UTC, limpbrains commented on screen/send/confirm.js
> +        for (const recipient of recipients) {
All recipients are now have `value` field calculated during `createTransaction` so I should work

2020-11-22 08:37 UTC, limpbrains commented on tests/e2e/bluewallet.spec.js
> +    await element(by.id('refreshTransactions')).tap();
Nice catch! It was lost somewhere during syncing with master, I've recovered it

2020-11-22 08:43 UTC, limpbrains commented on screen/send/details.js
> +                canUseAll={fromWallet.allowSendMax() && fromWallet.getBalance() > 0}
agree, fixed

2020-11-22 08:43 UTC, limpbrains commented on screen/send/details.js
> +                canUseAll={fromWallet.allowSendMax() && fromWallet.getBalance() > 0}
agree, fixed

2020-11-22 09:19 UTC, limpbrains commented on class/wallets/abstract-hd-electrum-wallet.js
> +      ret = ret.filter(({ txid, vout }) => !this.getUTXOMetadata(txid, vout).frozen);
Added some test to hd-segwit-bech32-wallet.test.js

2020-11-22 09:25 UTC, limpbrains commented on screen/send/psbtWithHardwareWallet.js
> +              <Text testID="PSBTHex" style={styles.hidden}>
I wanted to do this too, but when you create PSBT in watch-only wallet you don't have this screen.
I know that @ncoelho knows that and have a plan to add it

2020-11-22 10:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nwt2huwx2ynzjh1hqt45nmj68c

[download apk](http://filestorage.bluewallet.io:1488/1606040330.apk)

2020-11-22 12:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/c0mqur423dxj8peutxwrccqayg

[download apk](http://filestorage.bluewallet.io:1488/1606047375.apk)

2020-11-22 13:32 UTC, limpbrains commented
@Overtorment I've fixed all the issues, please take a look again

2020-11-23 03:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rreyc2erf4gp50gam000f44rxm

[download apk](http://filestorage.bluewallet.io:1488/1606100507.apk)

2020-11-23 03:32 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mqgb47ehp2pqyvz26mpzpbw0kc

[download apk](http://filestorage.bluewallet.io:1488/1606102340.apk)

2020-11-23 18:18 UTC, Overtorment commented on screen/send/details.js
> +      recipients,
pls revert this change, I like it the way it is (to glance at my tx before I broadcast it, and specifically check change output).
if you really want to do something about it - we pass fromWallet, so you should be able to mark change on the next screen using `weOwnAddress`

2020-11-23 18:35 UTC, Overtorment commented on screen/send/details.js
> +      recipients,
ok nvm that, talked with @ncoelho

2020-11-23 18:36 UTC, Overtorment approved these changes

2020-11-23 19:03 UTC, marcosrdz approved these changes

2020-11-23 19:04 UTC, merged

2020-11-23 19:04 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!