Contextpush
BlueWallet/BlueWallet pull request #2010
Opened 2020-10-23 14:23 UTC by marcosrdz

2020-10-23 14:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jq8bhmzjp8eqtygpwnzd69wear

[download apk](http://filestorage.bluewallet.io:1488/1603463803.apk)

2020-10-23 16:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yer3ub1upjnvtkx37732ckyw3w

[download apk](http://filestorage.bluewallet.io:1488/1603471372.apk)

2020-10-24 02:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y54qf1e86j02zgbwzkq2cv78ym

[download apk](http://filestorage.bluewallet.io:1488/1603506468.apk)

2020-10-26 15:29 UTC, Overtorment requested changes
can you pls fix conflicts?

2020-10-26 15:53 UTC, Overtorment commented
linting & deepscan

2020-10-26 18:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2ud47h6jquh56k6b5brja4xdfg

[download apk](http://filestorage.bluewallet.io:1488/1603736059.apk)

2020-10-29 17:33 UTC, Overtorment requested changes
minor changes. 

cant validate the logic  change till I test it myself, so lets just merge and test on real devices

2020-10-29 17:33 UTC, Overtorment commented on screen/wallets/transactions.js
> +              Linking.openURL('https://bluewallet.current.io/marketplace/');
oops

2020-10-29 17:33 UTC, Overtorment commented on blue_modules/notifications.js
> +
`'Platform' is defined but never used`

2020-10-29 18:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dvr0ztc8gngkv513rh28rv5fxw

[download apk](http://filestorage.bluewallet.io:1488/1603996603.apk)

2020-10-29 22:10 UTC, Overtorment commented on package.json
> +    "react-native-push-notification": "6.1.2",
i remember i was reading changelog for this package a while ago, and it said something that after update I would have to mess with configuring notification channel on android, which I kinda dont wana do unless really have to

2020-10-29 22:11 UTC, Overtorment commented on blue_modules/notifications.js
> +          notification.finish(PushNotificationIOS.FetchResult.NewData);
alright, whats this then?

2020-11-04 22:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7g0w395eebrqfdvv8vcb3jngxr

[download apk](http://filestorage.bluewallet.io:1488/1604530189.apk)

2020-11-04 23:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/33fkk0cm6q4q40fnza3qqy38dg

[download apk](http://filestorage.bluewallet.io:1488/1604533734.apk)

2020-11-05 02:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/btevyn4tknvajdque3jdbve2vm

[download apk](http://filestorage.bluewallet.io:1488/1604541667.apk)

2020-11-06 03:38 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qt4e2qk5a25zneym6z1x63f19g

[download apk](http://filestorage.bluewallet.io:1488/1604633888.apk)

2020-12-01 21:59 UTC, Overtorment commented
@marcosrdz are you going to work on this? Im eager to close it

2020-12-01 22:00 UTC, marcosrdz commented
> @marcosrdz are you going to work on this? Im eager to close it

Close it. Doesnt work well with ios

2020-12-01 22:10 UTC, closed without merging