FIX: BRD wallet with segwit
BlueWallet/BlueWallet pull request #2131
Opened 2020-11-13 17:14 UTC by limpbrains

At some point in BRD started to generate bech32 change addresses.  It is also possible to enable segwit for a wallet and it will generate bech32 addresses for incoming transactions.

Idea of this patch find index where wallet was switched to segwit and alter address generation scheme.

* During initial scan in `fetchBlance()` find derive path (index) at which BRD was switched to segwit. For external and internal addresses
* save these indexes to `_external_segwit_index` and `_internal_segwit_index`
* `_getExternalAddressByIndex` will return legacy address if index < than `_external_segwit_index` and Bech32 if not. Same for `_getInternalAddressByIndex`. This will make them backward compatible. 

I was able to recover balance and tx history of my BRD wallet using this branch.

Question: 
* Should I alter `getXpub`? Probably the wallet can show Xpub if it still generates Legacy external addresses and then Zpub if is has been switched to segwit. Or this can lead to confusion and it is better not to show xpub at all for BRD?

2020-11-13 17:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nxfr0nerkdbmwwzxnh9e4jgv38

[download apk](http://filestorage.bluewallet.io:1488/1605288442.apk)

2020-11-13 17:34 UTC, limpbrains commented
Tests are failing because HD_MNEMONIC_BREAD has 0 balance. To make this test useful, we need to put some funds on it, create a couple tx (so it has some bech32 change), activate segwit and receive some more funds. Then put final balance in the brd integration test

2020-11-18 18:26 UTC, Overtorment requested changes
good job on this. the only thing missing is createTransaction(). right now it will generate invalid signatures if there are mixed utxos (legacy + segwit), but I guess it can be done in separate PR. 

as for xpub, yeah I think once wallet is switched to segwit, its technically correct to provide zpub instead of xpub, but in reality, will potentially output a wallet with a huge gap, and most likely other software wont be able to find any balance on that zpub.
so maybe keep it as it is, xpub..?

2020-11-18 18:26 UTC, Overtorment commented on tests/unit/hd-legacy-breadwallet.test.js
> +  assert.ok(hdBread._getInternalAddressByIndex(1).startsWith('bc1'));
check that `_getExternalAddressByIndex(0)` still starts with `0`

2020-11-18 18:32 UTC, Overtorment commented
not sure what to do with integration test. is it worth it to make it?

2020-11-19 07:32 UTC, limpbrains commented on class/wallets/hd-legacy-breadwallet-wallet.js
> +  _external_segwit_index = null; // eslint-disable-line camelcase
Yes, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields
This is how you can init public class field

2020-11-19 07:33 UTC, limpbrains commented on class/wallets/hd-legacy-breadwallet-wallet.js
> +    const pubkey = _node.derive(node).derive(index).publicKey;
fixed

2020-11-19 07:34 UTC, limpbrains commented on tests/unit/hd-legacy-breadwallet.test.js
> +  assert.ok(hdBread._getInternalAddressByIndex(1).startsWith('bc1'));
added

2020-11-19 07:37 UTC, limpbrains commented on class/wallets/hd-legacy-breadwallet-wallet.js
> +        const [nextFreeExternalLegacy, nextFreeInternalLegacy] = await Promise.all([
Yes, works fine. Let's keep it this way for now and see how it will work

2020-11-19 08:12 UTC, limpbrains commented
> not sure what to do with integration test. is it worth it to make it?

I believe this wallet is quite different from others so it is worth testing it.
Can you put some funds on `HD_MNEMONIC_BREAD` and make a few transactions, so it has a few different outputs as I've described earlier? Or you can share it with me and I will donate a few sats.
Also I want to create test for `createTransaction()` since it should be different

2020-11-19 09:25 UTC, limpbrains commented
> right now it will generate invalid signatures if there are mixed utxos (legacy + segwit), but I guess it can be done in separate PR.

Can you please explain a little bit more? I want to fix it here, where should I search for a problem

2020-11-19 20:17 UTC, Overtorment commented
lets create a brand new brd wallet. this old wallet has a lot of txs on it, it will import painfully slow. plus segwit was never activated on it.
so go ahead, create a brand new brd wallet (legacy), donate some sats, then switch to native segwit and donate some sats again.
we can then use new seed in place of HD_MNEMONIC_BREAD.

once donated, you can use its utxo in unit test.


to make createTransaction work for mixed utxo set, look into
`AbstractHDElectrumWallet._addPsbtInput`
when I was making createTransaction for HD segwit and HD legacy I refactored it so the difference boils down to the implementation of `_addPsbtInput` in class, so see how `HDLegacyP2PKHWallet._addPsbtInput` is implemented.
maybe the job is not hard at all, you just need to call appropriate `_addPsbtInput` method (segwit or legacy) for each UTXO input being added to transaction

2020-11-20 17:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3fc2gy0eb65urpcqr9e3cz184w

[download apk](http://filestorage.bluewallet.io:1488/1605892845.apk)

2020-11-22 16:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j5cmdgdg3f3d5z9kpt182jum0c

[download apk](http://filestorage.bluewallet.io:1488/1606061068.apk)

2020-11-23 18:52 UTC, Overtorment commented on tests/integration/hd-legacy-breadwallet.test.js
> +  assert.strictEqual(wallet.getBalance(), 70884);
оглянуться не успеешь как это будет стоить МИЛЛИОНЫ 😂

2020-11-23 20:01 UTC, limpbrains commented on tests/integration/hd-legacy-breadwallet.test.js
> +  assert.strictEqual(wallet.getBalance(), 70884);
пфффффф
![rollercoaster](https://user-images.githubusercontent.com/155891/100009260-aee2fb00-2ddf-11eb-9750-d702ac3d81c7.gif)

2020-11-26 06:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/krwg38kr8hte88zm5g6nk1gc6m

[download apk](http://filestorage.bluewallet.io:1488/1606372594.apk)

2020-11-26 11:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hy6qvy5ak42ntr3d8j7nrk58k4

[download apk](http://filestorage.bluewallet.io:1488/1606390920.apk)

2020-11-26 13:59 UTC, Overtorment commented on tests/integration/hd-legacy-breadwallet.test.js
> +  const { tx } = wallet.createTransaction(
to check that your transaction works 100% you need to broadcast it, thus, spend it.
this is when you might want to back up `getUtxo()` and move tx creation test from integration to unit test

2020-11-26 14:23 UTC, limpbrains commented on tests/integration/hd-legacy-breadwallet.test.js
> +  const { tx } = wallet.createTransaction(
Yeah, that's why I haven't finished this PR yet, still testing all the things and it is quite hard with high fees.
If I spend this UTXO, then my first test will be broken.
I thought maybe find a place on the internet where I can test tx without broadcasting it. `bitcoin-cli testmempoolaccept` would do the trick. 
Maybe create another BRD wallet for this unittest?
What do you think?

2020-11-26 14:25 UTC, limpbrains commented on class/wallets/hd-legacy-breadwallet-wallet.js
> +    if (input.address.startsWith('bc1')) {
@Overtorment Do you think this is OK? I couldn't find a better way to identify bitcoin address type

2020-11-26 14:32 UTC, Overtorment commented on tests/integration/hd-legacy-breadwallet.test.js
> +  const { tx } = wallet.createTransaction(
first test is to just fetch balance, frankly, its trivial. 

so  there are 2 options: 

1) compose complex enough utxo (include several kinds, native segwit, legacy), create spending transaction, get txhex, and write a unit test that checks that this txhex is returned. if txhex is broadcasted okay - great success! you have a working code thats covered with test.  then replenishing some sats on addresses and fixing 1st test is trivial.

2) same, but dont broadcast. instead, make a build for yourself and play around with a _different_ brd wallet, make sure you can send, this is how you will know everything works.

3)  trust `testmempoolaccept` works. lets review & release, if it cant send users will report kek

2020-11-26 14:33 UTC, Overtorment commented on class/wallets/hd-legacy-breadwallet-wallet.js
> +    if (input.address.startsWith('bc1')) {
its ok

2020-11-26 15:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/66hn0j6r52x1f654gewnear3wr

[download apk](http://filestorage.bluewallet.io:1488/1606403606.apk)

2020-11-26 15:22 UTC, limpbrains commented
I believe it is ready to be merged. I successfully tested it on with my BRD and was able to spend from both legacy and bench32 wallets in one tx
I'm going to test more when mempool will clear

2020-11-26 15:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3166uh2c86k4c01fk24apxyaqr

[download apk](http://filestorage.bluewallet.io:1488/1606404805.apk)

2020-11-26 17:17 UTC, Overtorment requested changes
issue with `this.node0`

2020-11-26 17:17 UTC, Overtorment commented on class/wallets/hd-legacy-breadwallet-wallet.js
> +      _node = this.node0 || (this.node0 = bitcoinjs.bip32.fromBase58(this.getXpub()).derive(node));
such structures wont survide saveToDisk/loadFromDisk and might even fuck it up  (for real RN environment).
theres a parent `prepareForSerialization()` method which cleans them up, but they must be named prefixed with `_`

2020-11-26 17:17 UTC, Overtorment commented on class/wallets/hd-legacy-breadwallet-wallet.js
> +    }
theres a hacky way to reuse code from other classes. I did it once like this:

```
    const hd = new HDSegwitBech32Wallet();
    return hd.getTransactions.apply(this);
```

i dont know other ways to do this in js. you might want to consider it

2020-11-27 06:29 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kfcax46qbjfnfd1rftae9cxph4

[download apk](http://filestorage.bluewallet.io:1488/1606458572.apk)

2020-11-27 07:16 UTC, limpbrains commented on class/wallets/hd-legacy-breadwallet-wallet.js
> +      _node = this.node0 || (this.node0 = bitcoinjs.bip32.fromBase58(this.getXpub()).derive(node));
fixed

2020-11-27 07:16 UTC, limpbrains commented on class/wallets/hd-legacy-breadwallet-wallet.js
> +    }
Done, looks not so bad as I thought it would

2020-11-27 07:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4cwbkaxw0nwnevy1vegcm26j98

[download apk](http://filestorage.bluewallet.io:1488/1606461998.apk)

2020-11-27 12:59 UTC, Overtorment approved these changes

2020-11-27 13:42 UTC, merged