ADD: Show alert on Android if storage access is denied.
BlueWallet/BlueWallet pull request #2196
Opened 2020-11-23 13:55 UTC by marcosrdz

2020-11-23 14:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r9p56kpgfzpeu4tn0y7ytafr5c

[download apk](http://filestorage.bluewallet.io:1488/1606140905.apk)

2020-11-23 14:19 UTC, Overtorment requested changes

2020-11-23 14:19 UTC, Overtorment commented on blue_modules/fs.js
> +      Alert.alert(loc.send.permission_storage_title, loc.send.permission_storage_denied_message, [
this is generalized function to write to file. dont mention the transaction, only something like "we dont have enough permissions to save file". 
and use this generalized text everywhere else in this pr

2020-11-23 14:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6tbfd0tq871zz1u0zakyak778c

[download apk](http://filestorage.bluewallet.io:1488/1606142666.apk)

2020-11-24 09:27 UTC, ncoelho approved these changes

2020-11-24 16:17 UTC, Overtorment approved these changes

2020-11-24 16:18 UTC, merged

2020-11-24 16:18 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

2020-11-24 18:02 UTC, marcosrdz commented on screen/send/psbtWithHardwareWallet.js
> -        saveToFiles: isDesktop,
isDesktop is needed to determine if its catalina or big sur. if its catalina, use launchCamera, if its big sur use ScanQRcode