OPS: updated payjoin dep
BlueWallet/BlueWallet pull request #2203
Opened 2020-11-24 16:11 UTC by Overtorment

2020-11-24 16:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pg8j21t87jw38hu44d0vb599fc

[download apk](http://filestorage.bluewallet.io:1488/1606235724.apk)

2020-11-25 06:13 UTC, limpbrains requested changes

2020-11-25 06:13 UTC, limpbrains commented on screen/send/confirm.js
> +  }
You just take the first value from the recipients list and evaluate the outputscript.  are you sure that this is the destination address?
Looks like this function doesn't match it's description.

2020-11-25 11:39 UTC, Overtorment commented on screen/send/confirm.js
> +  }
pretty sure. in payjoin, there is only one destination. in batch send payjoin wont work.
plus, I tested it on real payjoin-enabled server  https://btc.donate.kukks.org

2020-11-25 13:56 UTC, merged

2020-11-25 13:56 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!