REF: TransactionStatus Hooks
BlueWallet/BlueWallet pull request #2225
Opened 2020-11-30 03:26 UTC by marcosrdz

2020-11-30 03:38 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6jfkcvkktnajjw84z2vzj70q4m

[download apk](http://filestorage.bluewallet.io:1488/1606707508.apk)

2020-11-30 09:48 UTC, limpbrains approved these changes

2020-11-30 10:37 UTC, ncoelho commented
No bump/cancel buttons appeared on making a transaction

2020-11-30 17:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kfeqdkcpvgtv1ngk3t7x3gctmr

[download apk](http://filestorage.bluewallet.io:1488/1606756634.apk)

2020-12-01 03:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/271rgvxaqr77m3cq8c2q8ck90c

[download apk](http://filestorage.bluewallet.io:1488/1606791656.apk)

2020-12-01 15:05 UTC, Overtorment requested changes
pls double check that RBF & CPFP work
otherwise lgtm

2020-12-01 15:39 UTC, ncoelho commented
<img width="349" alt="Screenshot 2020-12-01 at 16 38 39" src="https://user-images.githubusercontent.com/1238429/100761936-bdd73800-33f3-11eb-9a82-e2ce1ce6b5a3.png">
<img width="350" alt="Screenshot 2020-12-01 at 16 38 29" src="https://user-images.githubusercontent.com/1238429/100761949-c16abf00-33f3-11eb-814a-90586a2142ee.png">

2020-12-01 15:41 UTC, ncoelho requested changes
Can't RBF

2020-12-02 05:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6n95wxvwpbx4p3ytqyjra5mp28

[download apk](http://filestorage.bluewallet.io:1488/1606887952.apk)

2020-12-02 06:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u79369a18988mzzxjw3rxnjuyc

[download apk](http://filestorage.bluewallet.io:1488/1606888804.apk)

2020-12-02 20:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q4f0n3xkq0hnjtuc552urr5g6r

[download apk](http://filestorage.bluewallet.io:1488/1606942584.apk)

2020-12-03 13:12 UTC, Overtorment approved these changes
lgtm. tested RBG & CPFP on testflight build, worked as expected. @ncoelho your turn

2020-12-03 14:03 UTC, limpbrains approved these changes

2020-12-03 14:03 UTC, limpbrains commented on screen/transactions/transactionStatus.js
> +  const [tx, setTX] = useState();
Same here, I believe `useMemo` is better that `useRef` for `wallet` and `tx`. But that's not really important

2020-12-03 15:08 UTC, ncoelho approved these changes

2020-12-03 15:29 UTC, merged

2020-12-03 15:29 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!