REF: LN Create Invoice Hook
BlueWallet/BlueWallet pull request #2247
Opened 2020-12-03 01:38 UTC by marcosrdz

2020-12-03 01:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d20auueez1xb2v7ed68rdhu420

[download apk](http://filestorage.bluewallet.io:1488/1606960547.apk)

2020-12-03 13:02 UTC, Overtorment approved these changes
lgtm. tested a bit on appetize - receive worked as expected (didnt test lnurl withdrawal tho)

2020-12-03 13:54 UTC, limpbrains approved these changes

2020-12-03 13:54 UTC, limpbrains commented on screen/lnd/lndCreateInvoice.js
> +  const wallet = useRef(
I think `useMemo` is a better because you don't need to write `.current` and you don't need to create a separate effect to change its value. 

Also, useEffect fires after render and if you change ref there, the component will not be re-rendered. Not sure about this,

2020-12-03 15:15 UTC, ncoelho requested changes
- Scan button colors are wrong on light mode
- Wallet denomination is not reflected on creation screen

2020-12-04 00:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/c62jx82z72cq5byfpkmmn85hx0

[download apk](http://filestorage.bluewallet.io:1488/1607042111.apk)

2020-12-04 09:39 UTC, ncoelho approved these changes

2020-12-04 09:39 UTC, merged

2020-12-04 09:39 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!