REF: navigation styles
BlueWallet/BlueWallet pull request #2264
Opened 2020-12-04 17:21 UTC by limpbrains

Redoing #2246

2020-12-04 17:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4qccu5aq6rveqhnyvwb0t4ggx4

[download apk](http://filestorage.bluewallet.io:1488/1607103667.apk)

2020-12-04 20:21 UTC, Overtorment commented
is this redy for review & merge?

2020-12-04 21:05 UTC, Overtorment approved these changes
i glanced, lgtm, but I know nothing about react navigation

2020-12-05 05:29 UTC, limpbrains commented
> is this ready for review & merge?

Yes it does

2020-12-05 05:44 UTC, marcosrdz requested changes
LNDViewinvoice is the only screen i seem to find missing the change..or at least its not showing the proper options such as the no back title, back arrow colors and title.

2020-12-05 06:37 UTC, limpbrains commented
fixed

2020-12-05 06:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ftzb69tf283mw61ag7ycr0dm5m

[download apk](http://filestorage.bluewallet.io:1488/1607150930.apk)

2020-12-05 15:24 UTC, marcosrdz approved these changes

2020-12-08 06:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hamjw0kav4qppf2mwdzbx2afxm

[download apk](http://filestorage.bluewallet.io:1488/1607410513.apk)

2020-12-08 08:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7w963xx9ec70ea1brmgyrzxdd0

[download apk](http://filestorage.bluewallet.io:1488/1607416203.apk)

2020-12-13 09:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zbu1q3c00nrzfgk8juc4jzcmwm

[download apk](http://filestorage.bluewallet.io:1488/1607850158.apk)

2020-12-14 11:53 UTC, Overtorment requested changes

2020-12-14 11:53 UTC, Overtorment commented on screen/wallets/addMultisigHelp.js
>  import { SafeBlueArea, BlueNavigationStyle, BlueLoading } from '../../BlueComponents';
```
screen/wallets/addMultisigHelp.js#L4
'BlueNavigationStyle' is defined but never used
```

2020-12-14 17:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1ejnxq9fwhc1eg2rqhyv4yb338

[download apk](http://filestorage.bluewallet.io:1488/1607965776.apk)

2020-12-16 17:39 UTC, Overtorment commented
is it ready for merge?
also, mind the conflicts

2020-12-16 17:40 UTC, Overtorment commented
if its a risky change, lets distribute the build via testflight and give it some proper testing

2020-12-16 20:23 UTC, limpbrains commented
I believe it is ready. I will test it once again tomorrow and let's merge!

2020-12-16 20:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wnqcrkrdaknnn9kd19whmvrd7c

[download apk](http://filestorage.bluewallet.io:1488/1608150875.apk)

2020-12-17 14:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ep4ad9ucwu73mn7k2bd8y83jvw

[download apk](http://filestorage.bluewallet.io:1488/1608215226.apk)

2020-12-18 14:24 UTC, Overtorment approved these changes
lgtm. merge after @ncoelho blessing

2020-12-19 07:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dgykkznkwveckvjq767h4c6v14

[download apk](http://filestorage.bluewallet.io:1488/1608361759.apk)

2020-12-19 07:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kwuw1bqgd2r4537ujgt6dwnh6w

[download apk](http://filestorage.bluewallet.io:1488/1608364750.apk)

2020-12-19 08:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z67yzg99yzy88njz3ba68z84nm

[download apk](http://filestorage.bluewallet.io:1488/1608367806.apk)

2020-12-19 09:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wchbz971br6ct3qfam5a9fxdr4

[download apk](http://filestorage.bluewallet.io:1488/1608371892.apk)

2020-12-19 11:48 UTC, limpbrains commented
There were problems with e2e tests. Now they are passing. But now regular tests are failing. I don't know why. I think the PR is ready to be merged

2020-12-23 08:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/89t3cngquk2wmv1udtb0nx1dp4

[download apk](http://filestorage.bluewallet.io:1488/1608711608.apk)

2020-12-24 19:46 UTC, marcosrdz commented
Conflicts

2020-12-24 20:52 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gy4qc7jghh4xz0emjxhz2nu9ec

[download apk](http://filestorage.bluewallet.io:1488/1608843150.apk)

2020-12-25 01:01 UTC, marcosrdz commented
lol conflicts again

2020-12-25 06:54 UTC, limpbrains commented
> lol conflicts again

yeah, it was a bad idea to resort imports in this PR

2020-12-25 07:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dgfppkfufeb97ra62x3ub1je7c

[download apk](http://filestorage.bluewallet.io:1488/1608879847.apk)

2020-12-25 16:21 UTC, Overtorment commented
@ncoelho

2020-12-25 16:32 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r3zvw3av0jn6jz81mzg40j8168

[download apk](http://filestorage.bluewallet.io:1488/1608913934.apk)

2021-01-03 09:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bvjv8k1547g1emd05zahn8x598

[download apk](http://filestorage.bluewallet.io:1488/1609665445.apk)

2021-01-05 07:17 UTC, limpbrains commented
Let's merge it

2021-01-05 07:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7cr3ebwm0dv20w63qw7e7f6g68

[download apk](http://filestorage.bluewallet.io:1488/1609831790.apk)

2021-01-05 13:41 UTC, ncoelho commented
<img width="325" alt="Screenshot 2021-01-05 at 13 39 31" src="https://user-images.githubusercontent.com/1238429/103652924-b4de0700-4f5b-11eb-84c1-44a49c16ddb5.png">

2021-01-05 16:01 UTC, Overtorment commented
@ncoelho if you also submit review with "changes requested", PR developer will have a chance to fix issues and then re-request a review and you will receive a notification about it

2021-01-05 16:09 UTC, ncoelho commented on screen/wallets/viewEditMultisigCosigners.js
> +  title: loc.multisig.view_edit_cosigners_title,
Title not reflected

2021-01-05 19:06 UTC, limpbrains commented
@ncoelho 
thanks, fixed!

2021-01-05 19:38 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9r1dgm4nhrwgyy0dkgtuh18w8r

[download apk](http://filestorage.bluewallet.io:1488/1609875501.apk)

2021-01-05 19:43 UTC, ncoelho approved these changes

2021-01-05 20:06 UTC, merged