Scanlndhook
BlueWallet/BlueWallet pull request #2267
Opened 2020-12-05 05:21 UTC by marcosrdz

2020-12-05 05:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jhxqum7z0qj4e46d976hccy0rm

[download apk](http://filestorage.bluewallet.io:1488/1607147139.apk)

2020-12-07 16:00 UTC, Overtorment requested changes

2020-12-07 16:07 UTC, marcosrdz commented on screen/lnd/scanLndInvoice.js
> +  const { navigate, dangerouslyGetParent, setParams, pop } = useNavigation();
Its there. Line 73.

2020-12-07 16:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y7wqceguhbj75233rbpj2h1x4m

[download apk](http://filestorage.bluewallet.io:1488/1607359194.apk)

2020-12-07 17:33 UTC, limpbrains approved these changes

2020-12-07 18:11 UTC, Overtorment commented on screen/lnd/scanLndInvoice.js
> +  const { navigate, dangerouslyGetParent, setParams, pop } = useNavigation();
ok I see code that handles errof if there is no ln wallets.
but where is the code that chooses first found ln wallet if walletID not passed or we could not find anything by walletID?

2020-12-07 18:20 UTC, marcosrdz commented on screen/lnd/scanLndInvoice.js
> +  const { navigate, dangerouslyGetParent, setParams, pop } = useNavigation();
Line 42.

2020-12-07 22:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n5h7fur47qnd5vzbnpkp616674

[download apk](http://filestorage.bluewallet.io:1488/1607379638.apk)

2020-12-07 22:33 UTC, Overtorment approved these changes

2020-12-08 18:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/reqmbd189bkf91qmpae1tc0a48

[download apk](http://filestorage.bluewallet.io:1488/1607453570.apk)

2020-12-09 00:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dp7gcz6nmecq453thpfa6tj45r

[download apk](http://filestorage.bluewallet.io:1488/1607472235.apk)

2020-12-11 04:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8x1tb4arf3fjhwt1d0ke9f2wpr

[download apk](http://filestorage.bluewallet.io:1488/1607659764.apk)

2020-12-11 23:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gjfw0499jr59c6yt4354vgzpp0

[download apk](http://filestorage.bluewallet.io:1488/1607730238.apk)

2020-12-12 01:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/54dpqf6qy1hatz0frr9dpdc028

[download apk](http://filestorage.bluewallet.io:1488/1607736996.apk)

2020-12-12 06:47 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/t4z2kh0bfhxnj1nbmau12286em

[download apk](http://filestorage.bluewallet.io:1488/1607755633.apk)

2020-12-12 08:15 UTC, merged