ADD: lightning (lndhub) can now work with .onion urls
BlueWallet/BlueWallet pull request #2295
Opened 2020-12-08 23:10 UTC by Overtorment

2020-12-08 23:16 UTC, marcosrdz approved these changes

2020-12-08 23:22 UTC, Overtorment commented
tor will kick in if lndhub uri is .onion uri
to make tor work for all uris (for testing purposes) here's the patch:


```
diff --git a/class/wallets/lightning-custodian-wallet.js b/class/wallets/lightning-custodian-wallet.js
index 9862f131..871fc737 100644
--- a/class/wallets/lightning-custodian-wallet.js
+++ b/class/wallets/lightning-custodian-wallet.js
@@ -79,7 +79,7 @@ export class LightningCustodianWallet extends LegacyWallet {
       baseURI: this.baseURI,
     });
 
-    if (this.baseURI.indexOf('.onion') !== -1) {
+    if (true || this.baseURI.indexOf('.onion') !== -1) {
       this._api = new Torsbee({
         baseURI: this.baseURI,
       });
```

2020-12-08 23:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qmdw5rgk85m3167r24ut0v77t8

[download apk](http://filestorage.bluewallet.io:1488/1607471428.apk)

2020-12-09 13:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1mmr6q6m3njqpe2zz2trbnj3g4

[download apk](http://filestorage.bluewallet.io:1488/1607520606.apk)

2020-12-09 14:20 UTC, gabidi commented on blue_modules/torsbee.js
> +      if (options?.headers['Content-Type'] === 'application/json') {
btw this is done automatically by the lib. If content-type is json it sets a 'json' field in the response body so you don't have to manually base64 decode the byte payload.
https://github.com/Sifir-io/react-native-tor/blob/main/android/src/main/java/com/reactnativetor/TorAsyncTask.kt#L87-L93
https://github.com/Sifir-io/react-native-tor/blob/main/src/index.tsx#L207-L218

2020-12-13 16:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2tzqx98zzjzm254tuypbyx7c2g

[download apk](http://filestorage.bluewallet.io:1488/1607877925.apk)

2020-12-22 20:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k9qm9606frhegw7xuwvt6qejwm

[download apk](http://filestorage.bluewallet.io:1488/1608667846.apk)

2020-12-22 20:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/95d6641r05uayrwb9h07nugm4w

[download apk](http://filestorage.bluewallet.io:1488/1608669076.apk)

2020-12-22 21:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pqdwvy4nn9kap3dfyqy08nazm4

[download apk](http://filestorage.bluewallet.io:1488/1608670904.apk)

2020-12-22 21:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/und0kdxw2jhxvqhjfzj8jttrq4

[download apk](http://filestorage.bluewallet.io:1488/1608673198.apk)

2020-12-23 03:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2kykqkza8hu8dc3nqqqhhvm1rg

[download apk](http://filestorage.bluewallet.io:1488/1608693651.apk)

2020-12-23 05:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/50h2yggbjdymcnut3xyhzd3wnc

[download apk](http://filestorage.bluewallet.io:1488/1608701176.apk)

2020-12-23 16:32 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/72h7zvzbnb766wfekwzt9pq29w

[download apk](http://filestorage.bluewallet.io:1488/1608741125.apk)

2020-12-23 17:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uwvfkg9mxvkvg7601c18f0crtg

[download apk](http://filestorage.bluewallet.io:1488/1608745015.apk)

2020-12-24 02:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5wykum3gtqbf5zbjbctagdxcf8

[download apk](http://filestorage.bluewallet.io:1488/1608777638.apk)

2020-12-24 17:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qfta093w1kahg7gghqz15vmeb8

[download apk](http://filestorage.bluewallet.io:1488/1608831646.apk)

2020-12-25 14:05 UTC, godSaysHODL commented
do i have to be running Orbot for this to work? Pasted in my http://.onion:3000 for my lndhub in 'Lightning Settings' on this latest APK, it appears to spin a loading circle without finishing connection

2020-12-25 15:24 UTC, godSaysHODL commented
Does this work for .onion with a :port after it? having trouble with mine URI in latest APK in this PR

(works on tor browser, spinning circle endlessly on Bluewallet when trying to import.)
Test URI here for debugging: 

![image](https://user-images.githubusercontent.com/14336691/103137901-19f34c00-4682-11eb-9b2f-0aa64afa7a86.png)

2021-01-08 19:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3hjupb6817gjn6vbjvq6r0a924

[download apk](http://filestorage.bluewallet.io:1488/1610133078.apk)

2021-01-08 19:29 UTC, Overtorment commented
lndhub & electrum through TOR should now work (tested on android only).
@godSaysHODL I was able to connect to your node and create myself a lightning wallet there:

![image](https://user-images.githubusercontent.com/1913337/104056053-bb80ae80-51e7-11eb-8592-607fda084622.png)

2021-01-08 19:52 UTC, godSaysHODL commented
> lndhub & electrum through TOR should now work (tested on android only).
> @godSaysHODL I was able to connect to your node and create myself a lightning wallet there:
> 
> ![image](https://user-images.githubusercontent.com/1913337/104056053-bb80ae80-51e7-11eb-8592-607fda084622.png)

Fantastic news OT!! This and the deeplink qr code release together are gonna be ABSOLUTE fire for "Uncle Jims" everywhere

2021-01-08 19:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5uj94w17aa1r5tkt124tndqbh0

[download apk](http://filestorage.bluewallet.io:1488/1610135683.apk)

2021-01-08 20:45 UTC, godSaysHODL commented
> ♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫
> 
> [android in browser] https://appetize.io/app/5uj94w17aa1r5tkt124tndqbh0
> 
> [download apk](http://filestorage.bluewallet.io:1488/1610135683.apk)

Currently getting a white screen of death while launching this build
![Screenshot_20210108-124344](https://user-images.githubusercontent.com/14336691/104062432-58732580-51af-11eb-9a1a-5d485486b0f5.png)

2021-01-08 22:51 UTC, gabidi commented
Not sure if related, but i'll leave this here if it helps:
https://github.com/Sifir-io/react-native-tor/issues/14

2021-01-09 12:04 UTC, Overtorment commented
White screen suggests that android code works fine, no crashes, and the problem somewhere in the javascript thread.
@limpbrains @marcosrdz any thoughts on this?

2021-01-09 12:12 UTC, ncoelho commented
01-09 12:11:51.498 E/AndroidRuntime( 2218): FATAL EXCEPTION: main
01-09 12:11:51.498 E/AndroidRuntime( 2218): Process: io.bluewallet.bluewallet, PID: 2218
01-09 12:11:51.498 E/AndroidRuntime( 2218): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "dl_iterate_phdr" referenced by "/data/app/~~c6gx_uzRRRrBpeQtQOaq5w==/io.bluewallet.bluewallet-GMHYjCRr392TiC_nXOVikQ==/lib/arm64/libsifir_android.so"...

2021-01-09 12:16 UTC, ncoelho commented
Interesting enough, it does not happen on all devices. builds ok on a Galaxy S20. Example above was from pixel 5


<img width="1162" alt="Screenshot 2021-01-09 at 12 14 29" src="https://user-images.githubusercontent.com/1238429/104091311-79ea1500-5274-11eb-9c1c-d9d203e72f2e.png">

2021-01-09 12:18 UTC, Overtorment commented
but when it happens, you dont get a while screen? app just doesn't launch? (or insta crashes)

2021-01-09 12:26 UTC, ncoelho commented
Ok this is not deterministic, now it installed on S20 without errors.

<img width="1191" alt="Screenshot 2021-01-09 at 12 23 49" src="https://user-images.githubusercontent.com/1238429/104091527-d7329600-5275-11eb-8ef7-61cc9bd4bd9e.png">

2021-01-09 12:28 UTC, ncoelho commented
> but when it happens, you dont get a while screen? app just doesn't launch? (or insta crashes)

It seems to crash immediately

2021-01-09 12:32 UTC, gabidi commented
This error is resolved by issue linked above. 
Proguard rules need to be updated to not to strip out code from the binaries react native tor uses
> Fails to build on pixel 4 and 5
> 
> 
> 
> ```
> 
> 01-09 12:11:51.498 E/AndroidRuntime( 2218): FATAL EXCEPTION: main
> 
> 01-09 12:11:51.498 E/AndroidRuntime( 2218): Process: io.bluewallet.bluewallet, PID: 2218
> 
> 01-09 12:11:51.498 E/AndroidRuntime( 2218): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "dl_iterate_phdr" referenced by "/data/app/~~c6gx_uzRRRrBpeQtQOaq5w==/io.bluewallet.bluewallet-GMHYjCRr392TiC_nXOVikQ==/lib/arm64/libsifir_android.so"...
> 
> ```
> 
> 
> 
> <img width="1212" alt="Screenshot 2021-01-09 at 12 15 31" src="https://user-images.githubusercontent.com/1238429/104091343-ae5dd100-5274-11eb-8e08-ab5c3dd8099d.png">
> 
>

2021-01-09 12:34 UTC, Overtorment commented
thanks @gabidi will apply that. 
so that sorts out instacrash in some cases, but not the white screen of death. that one still needs investigation

2021-01-09 12:39 UTC, godSaysHODL commented
> > Fails to build on pixel 4 and pixel 5

Yeah mine is getting the white screen on pixel 3A running grapheneOS, and I havent been able to install any of the latest builds to overwrite it

2021-01-10 22:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8gxxkn1u4f9ggf3pn2bwm3c728

[download apk](http://filestorage.bluewallet.io:1488/1610318661.apk)

2021-01-10 23:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g1unxru5kbn7bzu7pebkcwh2v8

[download apk](http://filestorage.bluewallet.io:1488/1610319782.apk)

2021-01-11 02:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/56h4x6ufw54bgkzu4j6gcwd480

[download apk](http://filestorage.bluewallet.io:1488/1610333862.apk)

2021-01-11 03:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4a3j2ejjqutmeb6ewbrayacqnc

[download apk](http://filestorage.bluewallet.io:1488/1610334752.apk)

2021-01-11 12:02 UTC, Overtorment commented
@marcosrdz did you just add commits that do not belong to this branch?

2021-01-11 12:33 UTC, Overtorment commented on screen/settings/electrumSettings.js
> +      { text: loc._.cancel, onPress: () => console.log('Cancel Pressed'), style: 'cancel' },
so you optimized it, removed `electrum_clear_alert_cancel`. but you didn't remove it from language files

2021-01-11 14:20 UTC, Overtorment commented
> @marcosrdz did you just add commits that do not belong to this branch?

my bad, everything seems to be in orded

2021-01-11 14:20 UTC, Overtorment commented
added proguard rules exception (should help with instacrash). cleaned up localizations

2021-01-11 14:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pmz1jgvw7zth72k7vdg9k0ph94

[download apk](http://filestorage.bluewallet.io:1488/1610376853.apk)

2021-01-11 16:03 UTC, godSaysHODL commented
> added proguard rules exception (should help with instacrash). cleaned up localizations

Awesome gonna test this build out now and cross my fingers 🙂

2021-01-11 16:09 UTC, godSaysHODL commented
> gonna test this build out now and cross my fingers 🙂

Dang it put me on the white screen of death again. Haha luckily everytime there is fresh master merge I can restore usability outside of this TOR branch

2021-01-11 16:11 UTC, marcosrdz commented
> > gonna test this build out now and cross my fingers 🙂
> 
> 
> 
> Dang it put me on the white screen of death again. Haha luckily everytime there is fresh master merge I can restore usability outside of this TOR branch 
> 
> 
> 
> Thank God for GlaDOS bot 

Are you able to replicate this using the android Emulator?

2021-01-11 16:15 UTC, godSaysHODL commented
> > > gonna test this build out now and cross my fingers 🙂
> > 
> > 
> > Dang it put me on the white screen of death again. Haha luckily everytime there is fresh master merge I can restore usability outside of this TOR branch
> > Thank God for GlaDOS bot
> 
> Are you able to replicate this using the android Emulator?

No. It may be related to grapheneOS. Are there any new google services or notification dependencies in this build?

2021-01-11 16:21 UTC, marcosrdz commented
> > > > gonna test this build out now and cross my fingers 🙂
> > > 
> > > 
> > > Dang it put me on the white screen of death again. Haha luckily everytime there is fresh master merge I can restore usability outside of this TOR branch
> > > Thank God for GlaDOS bot
> > 
> > 
> > Are you able to replicate this using the android Emulator?
> 
> No. It may be related to grapheneOS. Are there any new google services or notification dependencies in this branch?

No. Nothing new that is google related. Any chance you can run this branch on your device in debug mode?

2021-01-11 16:24 UTC, godSaysHODL commented
> > > > > gonna test this build out now and cross my fingers 🙂
> > > > 
> > > > 
> > > > Dang it put me on the white screen of death again. Haha luckily everytime there is fresh master merge I can restore usability outside of this TOR branch
> > > > Thank God for GlaDOS bot
> > > 
> > > 
> > > Are you able to replicate this using the android Emulator?
> > 
> > 
> > No. It may be related to grapheneOS. Are there any new google services or notification dependencies in this branch?
> 
> No. Nothing new that is google related. Any chance you can run this branch on your device in debug mode?

I'd be very glad to, but ill need some help learning how to be honest.

2021-01-11 17:14 UTC, Overtorment commented
cant reproduce white screen.
I install release APK from releases page on emulator https://github.com/BlueWallet/BlueWallet/releases/tag/v6.0.2
create couple of wallets.
then I install latest build from glados in this PR and launch. it starts okay, all wallets are there, no issues

2021-01-11 21:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wxtxgxt0b2306veppunnr70q98

[download apk](http://filestorage.bluewallet.io:1488/1610401454.apk)

2021-01-11 22:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uwg3uebv19exv3k0mb32pzr6rm

[download apk](http://filestorage.bluewallet.io:1488/1610404043.apk)

2021-01-11 22:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/722djexj3w6a52yr3tf4975jbc

[download apk](http://filestorage.bluewallet.io:1488/1610405363.apk)

2021-01-12 17:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9vp2ev1ujugee14fb2e47q7vew

[download apk](http://filestorage.bluewallet.io:1488/1610470970.apk)

2021-01-13 13:26 UTC, godSaysHODL commented
Okay I installed Android Studio and debugged latest package on my GrapheneOS pixel 3A. This is the large cluster of errors that seems sus:

`2021-01-13 05:18:50.630 17163-17163/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.bluewallet.bluewallet, PID: 17163
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "dl_iterate_phdr" referenced by "/data/app/~~2Z3GZuVVc9r7SAckqrFGcA==/io.bluewallet.bluewallet-UHb1RODHTD6HK-KSgaMTHQ==/lib/arm64/libsifir_android.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.reactnativetor.TorPackage.<init>(TorPackage.kt:15)
        at com.facebook.react.PackageList.getPackages(PackageList.java:139)
        at io.bluewallet.bluewallet.MainApplication$1.getPackages(MainApplication.java:26)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:77)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
        at io.bluewallet.bluewallet.MainApplication.onCreate(MainApplication.java:47)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6715)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ExecInit.main(ExecInit.java:48)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
2021-01-13 05:18:50.631 17163-17163/? E/AndroidRuntime: Error reporting crash
    java.lang.RuntimeException: Bad file descriptor
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:550)
        at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5208)
        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:158)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
2021-01-13 05:18:50.683 1004-1027/? I/ActivityManager: Process io.bluewallet.bluewallet (pid 17163) has died: fg  TOP 
`

2021-01-13 13:31 UTC, godSaysHODL commented
It probably makes more sense in screenshot form. If there is more I can do, let me know.

![image](https://user-images.githubusercontent.com/14336691/104458752-9c27af80-5560-11eb-8492-b96504aea1c3.png)

2021-01-13 13:59 UTC, Overtorment commented
@godSaysHODL thanks! this looks like an issue from mentioned https://github.com/Sifir-io/react-native-tor/issues/14
and I patched against that,  see diff in `android/app/proguard-rules.pro` are you sure you on the _latest_ build from this PR..?
@gabidi can you please take a look..?


also, @godSaysHODL, this issue you posted implied build insta-crashes? 
and you said you're getting white screen of death? in case of white screen, look for javascript errors in the log.

also, in Android  Studio you can press this button: 
![image](https://user-images.githubusercontent.com/1913337/104461399-31e62d80-55a7-11eb-92c1-4c1057c8094a.png)
(its AVD manager), create a device emulator and launch it there, and see if you can replicate the issue.
(installing APKs on emulator is easy, I usually do it from console by running `adb install /home/overtorment/Downloads/tor.apk`)

2021-01-13 14:08 UTC, godSaysHODL commented
> @godSaysHODL thanks! this looks like an issue from mentioned [Sifir-io/react-native-tor#14](https://github.com/Sifir-io/react-native-tor/issues/14)
> and I patched against that, see diff in `android/app/proguard-rules.pro` are you sure you on the _latest_ build from this PR..?
> @gabidi can you please take a look..?
> 
> also, @godSaysHODL, this issue you posted implied build insta-crashes?
> and you said you're getting white screen of death? in case of white screen, look for javascript errors in the log.
> 
> also, in Android Studio you can press this button:
> ![image](https://user-images.githubusercontent.com/1913337/104461399-31e62d80-55a7-11eb-92c1-4c1057c8094a.png)
> (its AVD manager), create a device emulator and launch it there, and see if you can replicate the issue.
> (installing APKs on emulator is easy, I usually do it from console by running `adb install /home/overtorment/Downloads/tor.apk`)

I'm certain that I ran the latest apk that GlaDOS posted.

 It is getting this error, and repeating it many times in the code. It may be instacrashing from what it looked like in that error, but the application does not close completely and leaves this white screen up until manually ending.

 I will attempt what you are saying.

I may get in the discord and stream my attempts at debugging if that helps in a little bit

2021-01-13 16:24 UTC, Overtorment commented
bluewallet:setlndhuburl?url=http%3A%2F%2Fg45wix2qhsxtoz2k675ikmlt5ypmcoz4nyhy44teku7amb7vqoh7jyyd.onion%3A3000

![image](https://user-images.githubusercontent.com/1913337/104479768-b80c6f00-55bb-11eb-87a0-fab164cd4e43.png)


bluewallet:setelectrumserver?server=v7gtzf7nua6hdmb2wtqaqioqmesdb4xrlly4zwr7bvayxv2bpg665pqd.onion%3A50001%3At

![image](https://user-images.githubusercontent.com/1913337/104479803-c22e6d80-55bb-11eb-9afa-0c86657b427e.png)


(scannable from main screen)

2021-01-13 17:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dx6kh4vhf8trug80kc6e0uc9hc

[download apk](http://filestorage.bluewallet.io:1488/1610560121.apk)

2021-01-13 18:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/80j6e7drdr6pqwn811p16candr

[download apk](http://filestorage.bluewallet.io:1488/1610564040.apk)

2021-01-13 23:52 UTC, gabidi commented
hmmm that's interesting. I didn't get a chance to test on a grapheneOS android, dont have access to one..
Did any other user using it on a *real* (not simulator) 'stock/retail' android device experience this error after applying Proguard rules patch ?

I should have some time this weekend, will take a look at this and help in whatever way I can.

2021-01-14 13:12 UTC, Overtorment commented
I did some testing, and it apperas that its Android 11 is to blame.  
I tested on BrowserStack AppLive and they have only 2 devices with android11, google pixel 4 and pixel 5. 
they both crash with `java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "dl_iterate_phdr" referenced by "/data/app/~~Np6qHVj6ro1IOj9v3yihig==/io.bluewallet.bluewallet-YEHnO7kBCWdAOP9tScsieA==/lib/arm64/libsifir_android.so"...`

PS. browserstack claims that its real physical devices, _not_ emulation

2021-01-14 13:16 UTC, Overtorment commented
PPS. looks like our proguard is disabled

2021-01-14 15:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n8gnqrctt918kwymng30ff8mg4

[download apk](http://filestorage.bluewallet.io:1488/1610638619.apk)

2021-01-14 19:23 UTC, gabidi commented
> I did some testing, and it apperas that its Android 11 is to blame.
> I tested on BrowserStack AppLive and they have only 2 devices with android11, google pixel 4 and pixel 5.
> they both crash with `java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "dl_iterate_phdr" referenced by "/data/app/~~Np6qHVj6ro1IOj9v3yihig==/io.bluewallet.bluewallet-YEHnO7kBCWdAOP9tScsieA==/lib/arm64/libsifir_android.so"...`
> 
> PS. browserstack claims that its real physical devices, _not_ emulation

That's very helpful to debug this weekend. Will do some testing on the models mentioned. Thanks!

2021-01-15 17:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/71p74u1t78g92c1g0bqbnzfn5r

[download apk](http://filestorage.bluewallet.io:1488/1610730349.apk)

2021-01-15 21:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uac4ukugy0p7mf994d1t625wwc

[download apk](http://filestorage.bluewallet.io:1488/1610746100.apk)

2021-01-15 22:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w5j8aarzjxgyc7y1adz690m44g

[download apk](http://filestorage.bluewallet.io:1488/1610749297.apk)

2021-01-17 12:52 UTC, gabidi commented
https://github.com/Sifir-io/react-native-tor/pull/17
Please try a build based on this branch and let me know.
Note: TargetSdk has been updated to 30 as per android guidelines, more details in issue:
https://github.com/Sifir-io/react-native-tor/issues/14#issuecomment-761701029

2021-01-18 07:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y7wjmry5p0b5qxj432ntktjf1r

[download apk](http://filestorage.bluewallet.io:1488/1610955280.apk)

2021-01-18 11:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qeegpytykggu1r9mp2p4rtx8gw

[download apk](http://filestorage.bluewallet.io:1488/1610968168.apk)

2021-01-18 12:02 UTC, Overtorment commented
ok, latest build with fixes from @gabidi seems to work okay on android11/browserstack

2021-01-18 13:00 UTC, godSaysHODL commented
It works!!! just made a new account via TOR on my Graphene phone 😁.

2021-01-18 14:55 UTC, Overtorment commented
cool. electrum should work as well, but it won't reconnect if the connection is lost, you would need to restart the app to fix the connection.
waiting for https://github.com/Sifir-io/react-native-tor/issues/16 to fix that

2021-01-18 16:06 UTC, gabidi commented
Yep will try to get to the timeout fix this week.

2021-01-18 16:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cfaadj3djh7m4cf4vamqakxrc0

[download apk](http://filestorage.bluewallet.io:1488/1610988024.apk)

2021-01-19 18:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dqmhj4wn40ywht7x3z53h15x50

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1611080673.apk)

2021-01-21 13:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ttp7rhj4npaq2q48ww2eemytdg

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1611234877.apk)

2021-01-21 14:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nn2tmca54yn3p6d3j9fubgy4qg

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1611241160.apk)

2021-01-22 16:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x4cpv0ruat0gxudq54gk26nheg

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1611334092.apk)

2021-01-24 05:11 UTC, shesek commented
This is super cool, nicely done!

Now that BlueWallet can connect through a SOCKS proxy, would it be easy to allow configuring other non-Tor SOCKS proxies as well?

2021-01-30 04:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x0hc1x0y8zvgpj1atyemvq7gyw

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1611981168.apk)

2021-02-22 14:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/41y09nyjuchz6y0fxyax2ca1g8

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1614005764.apk)

2021-03-11 17:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] 

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1615483425.apk)

2021-03-11 17:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dje54wqm7vqnkr7a5qky27vhw0

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1615484960.apk)

2021-03-11 22:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ntxw7bp1r1ukjxtktv4qxc1ueg

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1615501370.apk)

2021-03-12 19:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/07ru6akm3z26ey1vjzg2r8pf28

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1615576646.apk)

2021-03-12 23:05 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/49r7zg4fhvf7294dtgt4px3x2w

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1615590294.apk)

2021-03-17 17:05 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hq2zb0a7wzkj8uqyma2rfc6m6m

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1616000741.apk)

2021-03-17 17:28 UTC, godSaysHODL commented
Really like the TOR settings menu in the recent updates of this. Works great

2021-03-17 19:22 UTC, godSaysHODL commented
> @godSaysHODL can you pls test a bit and give your feedback? particularly, when there is no network for some time. I'm working on better reconnects with TOR

Will do. Also I'm having a problem with importing a TOR lndhub wallet. It says wallet import successful, and shows the wallet in the orange square, but then to the right there is still an "importing wallet" square with the spinning circle. The wallet fails to actually import even though it shows up successfully

2021-03-17 20:15 UTC, Overtorment commented
@godSaysHODL how did you import the wallet through TOR? 
did you have a wallet export that is in format `lndhub://xxx:yyy@TODADDRESS.onion`  ?

because by default app wont work through tor

2021-03-17 20:51 UTC, godSaysHODL commented
> @godSaysHODL how did you import the wallet through TOR?
> did you have a wallet export that is in format `lndhub://xxx:yyy@TODADDRESS.onion` ?
> 
> because by default app wont work through tor

So I have a regular lndhub account on my node that is accessible through lndhub://xxx:yyy@http:nodewebsite.com:port

And I switched the it over to lndhub://xxx:yyy@http://TORADDRESS.onion:3000

2021-03-17 23:06 UTC, Overtorment commented
> And I switched the it over to lndhub://xxx:yyy@http://TORADDRESS.onion:3000
did it work okay?

2021-03-17 23:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/428nft6kwcyafc6nbxfwzuqte4

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1616023692.apk)

2021-03-17 23:38 UTC, godSaysHODL commented
> > And I switched the it over to lndhub://xxx:yyy@http://TORADDRESS.onion:3000
> 
> did it work okay?

Yes everything seems to be working well. Just freezing occasionally when TOR is on and I have to wallet restart

Pixel 4A 5G

2021-03-17 23:41 UTC, Overtorment commented
@godSaysHODL are you using electrum through TOR or only lndhub ?

2021-03-18 01:07 UTC, godSaysHODL commented
> @godSaysHODL are you using electrum through TOR or only lndhub ?

Not using Electrum. Just LNDhub. It's freezing fairly often now actually

2021-03-18 08:04 UTC, limpbrains commented
@Overtorment Testing on iOS. 

regular (not tor) connection is broken. `electrum-client/lib/client.js` throws `unknown protocol` because 
protocol === 443, options === electrum3.bluewallet.io

2021-03-18 08:33 UTC, Overtorment commented
> @Overtorment Testing on iOS and android
> 
> 
> 
> regular (not tor) connection is broken. `electrum-client/lib/client.js` throws `unknown protocol` because 
> 
> protocol === 443, options === electrum3.bluewallet.io

That's npm cache.
Run with npm run -- --reset-cache

2021-03-18 14:40 UTC, limpbrains commented
- disable Wi-Fi
- launch app
- enable Wi-Fi
- tor connected
- lots of `Can't get callback` messages 

Also logs looks like there are 2 connections. See double `started tor` or `connected`

<img width="300" alt="image" src="https://user-images.githubusercontent.com/155891/111644537-fec35300-8810-11eb-88ef-f5da74ece0d4.png">

2021-03-18 15:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2jbyaa6xyrakzezu8gnde6hyhm

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1616081243.apk)

2021-03-19 11:29 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/eacbc7ma9rdbh112pwx6zb7jbr

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1616153384.apk)

2021-03-19 12:34 UTC, Overtorment commented
@limpbrains can you pls take a look again?
also can you please review all the code around electrum & sockets? this became such a mindfuck that I need a second oppinion

2021-03-19 14:17 UTC, limpbrains commented
- tor enabled
- wallet imported
- trying to refresh transactions
- got end of stream warning and `Attempted to remove more Tor listeners than added` error

<img width="300" alt="image" src="https://user-images.githubusercontent.com/155891/111793985-d56cfa80-88d6-11eb-9616-685e5e5cb343.png">

maybe when you get EOF tor socket error you don't need to close it, cause it is already dead?

2021-03-19 15:07 UTC, limpbrains requested changes

2021-03-19 15:07 UTC, limpbrains commented on screen/settings/torSettings.js
> +    <SafeBlueArea forceInset={{ horizontal: 'always' }} style={styles.root}>
No need for style or forceInset for SafeBlueArea

2021-03-19 15:09 UTC, limpbrains commented
Are you going to keep Settings/Network/ TOR settings screen ? Or it is only for debug?

2021-03-19 15:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/t4tka7r4k43grtuzkwy40n8nh0

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1616169292.apk)

2021-03-19 19:53 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +    } else {
for onion we reset electrum server for ios widgets to one of the defaults one (ios widgets connect to electrum on their own, and cant do TOR), otherwise os widgets use same electrum server as user provided

2021-03-19 19:54 UTC, Overtorment commented on blue_modules/torrific.js
> +      (async () => {
good catch

2021-03-19 20:22 UTC, Overtorment commented on blue_modules/torrific.js
> +      (async () => {
ok we have a promise inside because tor socket connect  provides a callback, and we need to resolve promise only after we sent data to socket and read correct response

2021-03-19 20:22 UTC, Overtorment commented on blue_modules/torrific.js
> +          const target = 'v7gtzf7nua6hdmb2wtqaqioqmesdb4xrlly4zwr7bvayxv2bpg665pqd.onion:50001';
no, random public

2021-03-19 20:25 UTC, Overtorment commented on blue_modules/torrific.js
> +    }
well shit. now i dont know whether to rewrite or not, since it does the job

2021-03-19 20:27 UTC, Overtorment commented on blue_modules/torrific.js
> +      this._listeners[event] = [];
its a safeguard which afair i could not reproduce in real usage.  usually we expect only one subscriber per event, and if something extraordinary happened (which should not have) - we nuke all listeners of that event (one)

2021-03-19 20:41 UTC, Overtorment commented on screen/settings/torSettings.js
> +    <SafeBlueArea forceInset={{ horizontal: 'always' }} style={styles.root}>
fixed

2021-03-19 20:42 UTC, Overtorment commented on screen/settings/torSettings.js
> +    <SafeBlueArea forceInset={{ horizontal: 'always' }} style={styles.root}>
i want to keep tor settings page, mostly for debug and a few tech-savvy users, but i don't want to waste time on prettifying it and moving strings to localization

2021-03-19 20:58 UTC, Overtorment commented
> * tor enabled
> * wallet imported
> * trying to refresh transactions
> * got end of stream warning and `Attempted to remove more Tor listeners than added` error

could not reproduce on first try. but anyway, doesn't seem to do any harm.
afair if I did not close previous socket, i could not create a new one _at all_.

2021-03-19 21:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4zpbdne440w0y8bw4uwhxz2r60

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1616188717.apk)

2021-03-19 21:41 UTC, Overtorment commented
@godSaysHODL can you pls test latest build and give your blessing for a merge? i think its in okayish state

@limpbrains if you have some spare time, can you mess with all that reconnect stuff on your own and see if it can be improved? I need a fresh look on this

2021-03-19 22:13 UTC, godSaysHODL commented
> @godSaysHODL can you pls test latest build and give your blessing for a merge? i think its in okayish state

Latest build still freezing up within a minute of TOR starting on my Pixel 4a

Does not freeze when using normal connection to same LNDhub.

2021-03-19 22:46 UTC, gabidi commented
> > @godSaysHODL can you pls test latest build and give your blessing for a merge? i think its in okayish state
> 
> Latest build still freezing up within a minute of TOR starting on my Pixel 4a
> 
> Does not freeze when using normal connection to same LNDhub. Using myNodeBTC

@godSaysHODL When you say freezing is the app responsive or just doesn't respond to any tap?
 Also if there's an area you can normally scroll by swiping  (List of Transactions, List of Wallets, etc..) on the screen the app is frozen on, is the scroll list still responsive to your swipes or that is frozen too ?
Strange questions, but if that's the case your facing it's nasty bug I came across in the past that's related to the JS engine used by React Native.

2021-03-22 11:57 UTC, Overtorment commented
@gabidi I did experience some freezes too. when it happened UI was frozen completely, nothing is even tapable

2021-03-22 15:44 UTC, godSaysHODL commented
> > > @godSaysHODL can you pls test latest build and give your blessing for a merge? i think its in okayish state
> > 
> > 
> > Latest build still freezing up within a minute of TOR starting on my Pixel 4a
> > Does not freeze when using normal connection to same LNDhub. Using myNodeBTC
> 
> @godSaysHODL When you say freezing is the app responsive or just doesn't respond to any tap?
> Also if there's an area you can normally scroll by swiping (List of Transactions, List of Wallets, etc..) on the screen the app is frozen on, is the scroll list still responsive to your swipes or that is frozen too ?
> Strange questions, but if that's the case your facing it's nasty bug I came across in the past that's related to the JS engine used by React Native.

Normally everything has been frozen if already inside a menu, but when on the main screen I can still move some of the scroll boxes like switching between wallets. It doesn't respond to any taps though

2021-03-22 17:13 UTC, gabidi commented
> Normally everything has been frozen if already inside a menu, but when on the main screen I can still move some of the scroll boxes like switching between wallets. It doesn't respond to any taps though. The odd part is the freezing only happens when connected to TOR as my main network setting so I suspect it is related.

Yeah that sounds like that bug. 
@Overtorment I've come across this bug when using and coding Bridged native modules (PGP, Tor , BDK ..)
Basically when ever the native module is called  the UI thread silently panics at random instances (you can see that in the log) and it stops responding to taps. Strangely thought Scroll Views continue to respond to swipe gestures... 

After weeks of debugging (literally) I solved the issue by upgrading to [React native v8](https://github.com/Kudo/react-native-v8) engine for the apps I've worked on.  After that never saw the bug again... Added bonus is it's much more memory efficient and faster than stock and even Hermes.

Side note: Besides apps I've worked on,  Zeus wallet also had similar issue of freezing after integrating the Tor library, and after (updating their wallet to v8)[https://github.com/ZeusLN/zeus/pull/394/commits/91b08b3d1fa373779747bb4f4c429306ace6025d]  (relatively straight forward diff) it fixed the issue right away.
Hope that help.

2021-03-22 17:54 UTC, Overtorment commented
@gabidi we don't have any freezes with other binary modules, only with `react-native-tor`.
i think you can reliably reproduce it if you take my function for echo test and start calling it like 10 times in a row. wild guess, the problem is somewhere with locks in tor module.

ps. i don't like `react-native-v8` because it feels hacky, its future is uncertain, and its not widely adopted in the wild.

2021-03-30 16:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/54871qfg2crctwtm679b4ckn1r

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1617122979.apk)

2021-03-31 07:55 UTC, gabidi commented
@Overtorment Sorry in the delay in replying, not much free time lately.
If you're against upgrading to V8 the best debugging suggestion I can make is to enable React Native's [Spy mode](https://gist.github.com/klaytonfaria/d6a0f628c986e6453b4d5ef09f2f0488) for the native bridge and log the messages going back and forth between the UI thread and the native side, if something is spamming the bridge or hanging then you can easily figure out from the logs what's causing your UI/Main thread to hang if it's related to that.
In regards to Tor locks, all REST requests are done on [separate exectutor threads](https://github.com/Sifir-io/react-native-tor/blob/feature/socket-timeouts/android/src/main/java/com/reactnativetor/TorModule.kt#L140-L146) and callback to resolve the promise when completed. I'm not Android/Kotlin expert by a long shot but I don't think that would lock up the JS thread. Also I don't really get any freezing in the the example App (which doesn't use V8 but is a very simple app and isn't likely to have alot of messaging going back  and forth between JS/Native via the bridge.
Hope that helps and let me know if I can assist.

2021-04-02 11:25 UTC, Overtorment commented
@gabidi i was able to replicate freezes occasionally by launching my test method I provided several times in a row. like, up to 10 times and you might get a freeze. can you try that..?
if REST requests are via separate threads, what about tor socket reads/writes? i think we had only freezes with them, not with REST.


and FYI, i was recently coding another react-native extension in kotlin, and i was 100% getting UI feezes on main android app when my module method didn't return in time. like, if I had some thing heavy to execute before returning data in kotlin's `promise.resolve(data);` whole UI was frozen.
so looks like by default this native module's biz is not working asynchoniosly as one would expect. weird

2021-04-02 11:27 UTC, Overtorment commented
@gabidi  oh and i will try spy-mode, thanks! can you meanwhile try this trick to try to reproduce freezes..? thanks!

2021-04-02 16:31 UTC, gabidi commented
@Overtorment  Sure, should have some time this weekend to to do this.
Just to confirm the test method you're talking about is the one in [this comment](https://github.com/Sifir-io/react-native-tor/pull/25#issuecomment-803148249) correct ?

2021-04-11 09:20 UTC, BtcContributor commented
Hi guys!
Any update on that? May I help with this?
I think community of people that wants to run their own node really deserves it :)

2021-04-19 19:38 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jvuynqbgyn8vj944mma7e5j0a8

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1618861125.apk)

2021-04-19 20:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ue1q72qx4kfmdc15j0vu90gjf0

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1618864649.apk)

2021-04-20 14:03 UTC, zanderisrael commented
Lest goo!

2021-04-20 20:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/na7prd5m57wnwzmx6uftbu4p7c

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1618951309.apk)

2021-04-21 13:29 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xekgzjmzmxnx5mr8wky34qt1u4

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1619011731.apk)

2021-04-22 07:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/evkjge9uyzvzbzn2decz0ndut8

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1619075683.apk)

2021-04-22 17:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/af777tn0hvdb1ygxekwbgnjyb4

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1619113971.apk)

2021-04-22 19:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ykwhv3bq8wn1wj2h8f1u9qwwrm

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1619119129.apk)

2021-04-23 11:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z68qehfzmq2wehkqxf1pz15yrc

[download apk](http://filestorage.bluewallet.io:1488/tor4lndhub-1619178473.apk)

2021-04-23 14:56 UTC, merged