FIX: Was unable to import key on macOS
BlueWallet/BlueWallet pull request #2308
Opened 2020-12-09 21:21 UTC by marcosrdz

2020-12-09 21:52 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/86zgpwfaqfajnzxx2402x3eham

[download apk](http://filestorage.bluewallet.io:1488/1607550716.apk)

2020-12-10 17:50 UTC, Overtorment requested changes

2020-12-10 17:50 UTC, Overtorment commented on screen/send/psbtMultisigQRCode.js
> +import RNFS from 'react-native-fs';
can we hide all that RNFS and document picker biz inside `../../blue_modules/fs` ?

2020-12-10 17:50 UTC, Overtorment commented on screen/send/psbtMultisigQRCode.js
> +          handleImportFileButtonPressed();
better naming for those 3 methods would be helpful, e.g. `takePhotoMacos` & `choosePhotoMacos`

2020-12-10 17:50 UTC, Overtorment commented on screen/send/psbtMultisigQRCode.js
> +    }
`else` for `(Platform.OS === 'ios')` not handled? can it be an android tablet?

2020-12-10 17:50 UTC, Overtorment commented on screen/send/psbtMultisigQRCode.js
> +    ImagePicker.launchImageLibrary(
maybe imagepicker biz should also be abstracted and hidden in a dedicated module, e.g.  `blue_modules/imagepicker`
or maybe in existing `blue_modules/fs`

2020-12-10 17:50 UTC, Overtorment commented on screen/wallets/addMultisigStep2.js
> +
same actionsheet, same biz with documentpicker, iamgepigcker etc.
DRY.
see my prev comment about blue_modules

2020-12-11 03:29 UTC, marcosrdz commented
@Overtorment  moved code to fs.

2020-12-12 18:27 UTC, Overtorment approved these changes

2020-12-12 18:27 UTC, Overtorment commented on blue_modules/fs.js
> +module.exports.takePhotoWithImagePickerAndReadPhoto = takePhotoWithImagePickerAndReadPhoto;
noice. clean

2020-12-12 18:27 UTC, Overtorment commented on screen/wallets/addMultisigStep2.js
> +
`showActionSheet` is duplicated in 2 places.  at least its simple enough to read
doest it make sense to move it to `fs`..?
you decide on this. for now its good enough.

2020-12-12 18:33 UTC, marcosrdz commented on screen/wallets/addMultisigStep2.js
> +
Different screens have different action sheet items. its the only reason i kept it this way.

2020-12-12 18:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cv4jgvwp646kzp184ydt5abxw8

[download apk](http://filestorage.bluewallet.io:1488/1607798595.apk)

2020-12-13 10:07 UTC, ncoelho approved these changes

2020-12-13 10:07 UTC, merged

2020-12-13 10:07 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!