ADD: Dark mode support and Clear button for Is it my address
BlueWallet/BlueWallet pull request #2319
Opened 2020-12-10 16:50 UTC by marcosrdz

2020-12-10 17:31 UTC, Overtorment requested changes

2020-12-10 17:31 UTC, Overtorment commented on loc/en.json
> +    "no_wallet_owns_address": "None of the available wallets own the provided address.",
broken json

2020-12-10 17:31 UTC, Overtorment commented on loc/en.json
> +    "check_address": "Check address",
btw lets make `enter_address` a placeholder in text input instead of standalone text

2020-12-10 17:35 UTC, Overtorment commented
![image](https://user-images.githubusercontent.com/1913337/101808284-11413880-3b0e-11eb-9c68-3e308f6d4c59.png)

2020-12-10 17:47 UTC, Overtorment approved these changes
lgtm

2020-12-10 19:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nwh5t1qc396w6f04kv6cr8fpzr

[download apk](http://filestorage.bluewallet.io:1488/1607628405.apk)

2020-12-11 20:57 UTC, Overtorment commented
conflict

2020-12-11 21:10 UTC, marcosrdz commented
> conflict

resolved

2020-12-11 21:13 UTC, Overtorment requested changes
linting failed

2020-12-11 21:15 UTC, marcosrdz commented
> linting failed

resolved

2020-12-11 22:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7vjyc2xf7m8gnfnd0rx8r5ytpw

[download apk](http://filestorage.bluewallet.io:1488/1607727290.apk)

2020-12-12 18:49 UTC, merged