OPS: Use new Image Picker
BlueWallet/BlueWallet pull request #2321
Opened 2020-12-10 17:40 UTC by marcosrdz

2020-12-10 17:54 UTC, Overtorment requested changes
looks like unit tests fail because old `react-native-image-picker` mock is no good for the new one

2020-12-10 18:07 UTC, Overtorment commented on __mocks__/react-native-image-picker.js
> +// Mock the ImagePickerManager native module to allow us to unit test the JavaScript code
capt. obvious comments kek

2020-12-10 18:08 UTC, Overtorment commented on __mocks__/react-native-image-picker.js
> +global.beforeEach(() => {
I think this belongs in `tests/setup.js ` but ok

2020-12-10 18:08 UTC, Overtorment approved these changes

2020-12-10 23:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4ue458eh4vax8ay2hwg00z8y68

[download apk](http://filestorage.bluewallet.io:1488/1607643749.apk)

2020-12-11 23:22 UTC, merged

2020-12-11 23:22 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!