REF: Updating en.json
BlueWallet/BlueWallet pull request #2322
Opened 2020-12-10 19:19 UTC by mcsaeid

Since there were multiple merges, many of the changes were undone, including punctuation marks, capitalization, etc. But this is everything—nearly perfect.

2020-12-11 21:12 UTC, Overtorment requested changes

2020-12-11 21:12 UTC, Overtorment commented on loc/en.json
> +    "sats": "satoshis.",
no, sats are sats

2020-12-11 21:12 UTC, Overtorment commented on loc/en.json
> +    "create_password_explanation": "Password for the fake storage should not match the password for your main storage.",
this probably breaks e2e tests. need to adjust spec file accordingly

2020-12-11 21:12 UTC, Overtorment commented on loc/en.json
> +    "electrum_settings_explain": "Leave blank to use default settings.",
user literally has to clean up input fields to revert to default settings. is that ok..?

2020-12-11 21:12 UTC, Overtorment commented on loc/en.json
> +    "groundcontrol_explanation": "GroundControl is a free, open-source push notifications server for Bitcoin wallets. You can install your own GroundControl server and put its URL here to not rely on
in this case to use defautl groundcontrol __server__

2020-12-11 21:12 UTC, Overtorment commented on loc/en.json
> +    "passwords_do_not_match": "Passwords do not match.",
also probably breaks e2e tests

2020-12-11 21:12 UTC, Overtorment commented on loc/en.json
> +    "wrapped_segwit_title": "Best Compatibility",
this is the screen where its used, are you sure it must be capitalized here?

![image](https://user-images.githubusercontent.com/1913337/101954973-e8e03980-3bf4-11eb-98d9-984d2f1d5955.png)

2020-12-11 21:12 UTC, Overtorment commented on loc/en.json
> +    "ms_help_text": "A wallet with multiple keys, for increased security or sharing accounts",
"shared custody" is kinda commonly used term in this multisig monkey biz

2020-12-11 21:12 UTC, Overtorment commented on loc/en.json
> +    "freeze": "Frozen",
also probably breaks e2e, tests are looking for string "Freeze". probably needs code readjustment so frozen UTXO has its own localization key

2020-12-11 21:23 UTC, mcsaeid commented on loc/en.json
> +    "sats": "satoshis.",
Got it. The way I was going about it was “sats” should be the norm currency (when showing the balance), but in the case of messages and everyday conversation—for instance, here, “Please pay [x] satoshis.”—we would opt for satoshis instead of sats. No worries, though. Sats **is** great.

2020-12-11 21:24 UTC, mcsaeid commented on loc/en.json
> +    "create_password_explanation": "Password for the fake storage should not match the password for your main storage.",
Can you point out what I should usually look out for and change in the _bluewallet.spec.js_ file so that these breaks don’t happen in the future? I am trying to get the hang of it. Thanks.

2020-12-11 21:27 UTC, mcsaeid commented on loc/en.json
> +    "electrum_settings_explain": "Leave blank to use default settings.",
Exactly. If the user wishes to use the default settings, they have to _leave_ the field _blank_ before proceeding. I have seen it being used in other apps and instances in general, but I also did a quick search before making the change just to make sure. I believe _leave blank_ is the standard term to go with.

2020-12-11 21:28 UTC, mcsaeid commented on loc/en.json
> +    "groundcontrol_explanation": "GroundControl is a free, open-source push notifications server for Bitcoin wallets. You can install your own GroundControl server and put its URL here to not rely on
Perfect. I will re-edit this accordingly to make it more clear and understandable. Thank you.

2020-12-11 21:29 UTC, mcsaeid commented on loc/en.json
> +    "passwords_do_not_match": "Passwords do not match.",
Got it. So, I should make sure the spec file has the same changes as this current file, right?

2020-12-11 21:32 UTC, mcsaeid commented on loc/en.json
> +    "wrapped_segwit_title": "Best Compatibility",
There is no must here in this case, but since these can be categorized as semi-titles, I thought it would look better if they were all capitalized. One thing that I am sure about is the acronyms in the parentheses. Because every letter represents a larger entity/word, all acronyms must be written capitalized, e.g. P2WSH or P2SH.

2020-12-11 21:33 UTC, mcsaeid commented on loc/en.json
> +    "ms_help_text": "A wallet with multiple keys, for increased security or sharing accounts",
Got it. Let me change it back.

2020-12-11 21:34 UTC, mcsaeid commented on loc/en.json
> +    "freeze": "Frozen",
Yeah. Is that something I can look for and change? In the end, it should be “frozen.” I even checked Electrum to make sure.

2020-12-11 21:47 UTC, mcsaeid commented
I believe I made the necessary changes. Let me know what you think when you get a chance.

2020-12-12 18:37 UTC, Overtorment commented on loc/en.json
> +    "freeze": "Frozen",
should be 'frozen', but code uses same loc key for several places, so that's a bumer.

2020-12-12 18:40 UTC, Overtorment commented on loc/en.json
> +    "create_password_explanation": "Password for the fake storage should not match the password for your main storage.",
![image](https://user-images.githubusercontent.com/1913337/101992207-65345480-3ca9-11eb-809e-8da8d7fc7dea.png)
look for something like

![image](https://user-images.githubusercontent.com/1913337/101992217-79785180-3ca9-11eb-9333-7b69f0141042.png)

2020-12-12 18:42 UTC, Overtorment requested changes
e2e + conflicts

2020-12-12 19:38 UTC, mcsaeid commented
> 
> 
> e2e + conflicts

So, if I got it right, I should fix the spec.json file but do it in the same PR. How can I do that? I apprecaite the help.

2020-12-12 21:31 UTC, mcsaeid commented on loc/en.json
> +    "freeze": "Frozen",
How does changing the code for this particular case work? Do you need find all the instances and correct them (as easy as that), or do you have to do/add something additional?

2020-12-14 11:55 UTC, Overtorment commented
> > e2e + conflicts
> 
> So, if I got it right, I should fix the spec.json file but do it in the same PR.

yes, looks like you've succeeded

2020-12-14 11:56 UTC, Overtorment approved these changes
lgtm

2021-02-04 09:01 UTC, mcsaeid commented
Any thoughts on how to prevent the tests from failing? These may require more coding knowledge than I currently have. @limpbrains @Overtorment

2021-02-09 11:42 UTC, limpbrains commented
in bluewallet.spec.js
`No, and don't ask me again` should be changed to `No, and don’t ask me again`

2021-02-09 14:59 UTC, ncoelho approved these changes

2021-02-09 16:41 UTC, merged