ADD: CoinControl multiselect
BlueWallet/BlueWallet pull request #2337
Opened 2020-12-12 17:51 UTC by limpbrains

- show number of confirmations in Output Modal
- allow to select a few outputs and Freeze/Unfreeze/Use them

2020-12-12 17:53 UTC, Overtorment approved these changes
lgtm

2020-12-12 17:59 UTC, marcosrdz requested changes

2020-12-12 17:59 UTC, marcosrdz commented on screen/send/coinControl.js
> +  const cs = useColorScheme();
useColorScheme? You can access colors directly and it will select the correct one based on the theme.

2020-12-12 18:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u3xdjbw2dcuzuccc6f6fn5b5p0

[download apk](http://filestorage.bluewallet.io:1488/1607796957.apk)

2020-12-13 08:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/865dqptmaf5dc9mgpmq1w6hu5r

[download apk](http://filestorage.bluewallet.io:1488/1607846532.apk)

2020-12-13 10:05 UTC, marcosrdz approved these changes

2021-01-04 19:02 UTC, merged