ADD: ability to set electrum server or lndhub via deeplink or by scan…
BlueWallet/BlueWallet pull request #2354
Opened 2020-12-14 20:12 UTC by Overtorment

…ning a QR from main screen

it is now possible to open a specific deeplink to set electrum or lndhub.
spec: https://github.com/BlueWallet/BlueWallet/wiki/Deeplinking
deeplinks: `bluewallet:setelectrumserver?server=electrum1.bluewallet.io%3A443%3As` & `bluewallet:setlndhuburl?url=https%3A%2F%2Flndhub.herokuapp.com`
(added them to the bottom of https://bluewallet.io/testpage/)

scanning QRs from main screen will also work, for example:
![image](https://user-images.githubusercontent.com/1913337/102130276-8f704880-3e48-11eb-9ef3-e2d897fe0b7c.png)
(`bluewallet:setelectrumserver?server=electrum1.bluewallet.io%3A443%3As`)

![image](https://user-images.githubusercontent.com/1913337/102130136-5b952300-3e48-11eb-97d5-f58eb5aad00b.png)

2020-12-14 20:19 UTC, marcosrdz requested changes

2020-12-14 20:19 UTC, marcosrdz commented on screen/settings/lightningSettings.js
> +    if (params?.url) {
Place in useEffect(() => {] , [params?.url])

2020-12-14 20:23 UTC, Overtorment commented on screen/settings/lightningSettings.js
> +    if (params?.url) {
Im not familiar with that part. what is it for?

2020-12-14 20:25 UTC, marcosrdz commented on screen/settings/lightningSettings.js
> +    if (params?.url) {
It fires whatever is inside useEffect whenever the object values inside the array change. Very useful if you are already on that screen before tapping on a deeplink. Look at scanLndInvoice for an example

2020-12-14 20:27 UTC, marcosrdz commented on screen/settings/lightningSettings.js
> +    if (params?.url) {
Line 98.

2020-12-14 20:29 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uxnwfuxut147ekd4byp16vwrjr

[download apk](http://filestorage.bluewallet.io:1488/1607977735.apk)

2020-12-16 14:05 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jcd4pt8m3q9wc9v87ac53b26mr

[download apk](http://filestorage.bluewallet.io:1488/1608127537.apk)

2020-12-24 15:53 UTC, limpbrains approved these changes

2020-12-24 17:44 UTC, marcosrdz approved these changes

2020-12-24 17:45 UTC, merged

2020-12-24 17:45 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

2021-01-08 12:13 UTC, godSaysHODL commented
You are such a boss, OT

Appreciate this one