REF: BlueUseAllFundsButton hooks
BlueWallet/BlueWallet pull request #2385
Opened 2020-12-18 22:10 UTC by marcosrdz

2020-12-18 22:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/a69n1mvntpn8zfdvfu2rp8729w

[download apk](http://filestorage.bluewallet.io:1488/1608331318.apk)

2020-12-19 07:03 UTC, limpbrains requested changes

2020-12-19 07:03 UTC, limpbrains commented on BlueComponents.js
>    };
I don't think defining proptypes in render function is a good idea. Same for `BlueUseAllFundsButton.InputAccessoryViewID` constant.

2020-12-19 08:45 UTC, limpbrains approved these changes

2020-12-19 09:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5fguxffvjccr6fyknx4c1rvgqc

[download apk](http://filestorage.bluewallet.io:1488/1608368595.apk)

2020-12-19 20:34 UTC, Overtorment requested changes
conflict

2020-12-19 20:56 UTC, marcosrdz commented
> conflict

resolved

2020-12-19 21:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vvgmzr625uupu23jb4enw093wc

[download apk](http://filestorage.bluewallet.io:1488/1608413014.apk)

2020-12-22 17:27 UTC, limpbrains approved these changes

2020-12-22 17:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f5y3g42gcz784zka8412m09yx8

[download apk](http://filestorage.bluewallet.io:1488/1608659114.apk)

2020-12-25 16:26 UTC, Overtorment requested changes
conflicts

2020-12-25 17:16 UTC, marcosrdz commented
> conflicts

resolved

2020-12-25 17:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wpmfw291u13bz0erbf32546h9m

[download apk](http://filestorage.bluewallet.io:1488/1608917642.apk)

2021-01-04 15:24 UTC, Overtorment requested changes
conflicts

2021-01-04 15:33 UTC, marcosrdz commented
> conflicts

addressed.

2021-01-04 15:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/et57f0wgmt0630gfj26mxvxqu0

[download apk](http://filestorage.bluewallet.io:1488/1609775496.apk)

2021-01-04 18:52 UTC, Overtorment approved these changes

2021-01-04 18:53 UTC, merged

2021-01-04 18:53 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!