FIX: missing i18n
BlueWallet/BlueWallet pull request #2408
Opened 2020-12-21 17:59 UTC by limpbrains

Fixing #2301

2020-12-21 18:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0u5rr4wrpeaupdwgncp72jkbvg

[download apk](http://filestorage.bluewallet.io:1488/1608576793.apk)

2020-12-22 11:14 UTC, Overtorment requested changes

2020-12-22 11:14 UTC, Overtorment commented on BlueComponents.js
> +                value={amount === BitcoinUnit.MAX ? loc.units.MAX : parseFloat(amount) >= 0 ? amount : undefined}
not sure about this one. I think we have MAX as a reserve constant by which we determine if user wants to send all. so in other languages sendMax might just break. needs verifying

2020-12-22 11:47 UTC, limpbrains commented on BlueComponents.js
> +                value={amount === BitcoinUnit.MAX ? loc.units.MAX : parseFloat(amount) >= 0 ? amount : undefined}
This line doesn't change internal `state.amount`, it changes its representation in TextInput. I've checked, works fine even with russian МАКС in `loc.units.MAX`

2020-12-24 17:40 UTC, marcosrdz requested changes
Lint

2020-12-24 18:25 UTC, limpbrains commented
@marcosrdz synced with master fixed the lint

2020-12-24 19:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wduyph1a9h450xgwmp4bw6mqww

[download apk](http://filestorage.bluewallet.io:1488/1608836847.apk)

2020-12-24 19:31 UTC, marcosrdz approved these changes

2020-12-25 13:27 UTC, Overtorment approved these changes

2020-12-25 13:28 UTC, merged

2020-12-25 13:28 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!