Ref: Add warning to LN
BlueWallet/BlueWallet pull request #2439
Opened 2020-12-29 15:04 UTC by ncoelho

2020-12-29 15:06 UTC, ncoelho commented
<img width="331" alt="Screenshot 2020-12-29 at 15 05 08" src="https://user-images.githubusercontent.com/1238429/103293250-64a8f700-49e7-11eb-87a7-2d2830b36121.png">

2020-12-29 15:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/45m8b693enuyg9819v75zfft38

[download apk](http://filestorage.bluewallet.io:1488/1609255011.apk)

2020-12-29 16:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vyzk0h0ra1q1pbnhaf5zx383f0

[download apk](http://filestorage.bluewallet.io:1488/1609261057.apk)

2020-12-29 22:57 UTC, marcosrdz requested changes

2020-12-29 22:57 UTC, marcosrdz commented on loc/en.json
> +    "text_lnd2": "Don't use it to store funds.",
Change Wording

2020-12-29 23:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3qcadt3bbedq63db2jpbz9dm8c

[download apk](http://filestorage.bluewallet.io:1488/1609284127.apk)

2021-01-03 17:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rw35830ucdzu0d8xv16phgbvhc

[download apk](http://filestorage.bluewallet.io:1488/1609695399.apk)

2021-01-03 17:37 UTC, marcosrdz approved these changes

2021-01-04 11:44 UTC, Overtorment requested changes

2021-01-04 11:44 UTC, Overtorment commented on loc/en.json
> +    "text_lnd2": "Don't use it for large amounts.",
i dont like this line. also, apple might object, they hate everything that hints that software is beta, for testing etc

2021-01-04 16:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q7fmaza8925ga1eqkp5cpmzxvg

[download apk](http://filestorage.bluewallet.io:1488/1609777878.apk)

2021-01-05 14:50 UTC, Overtorment approved these changes

2021-01-05 14:50 UTC, merged

2021-01-05 14:50 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!