Fix multisig
BlueWallet/BlueWallet pull request #2460
Opened 2021-01-04 17:35 UTC by Overtorment

2021-01-04 17:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w1kck1h2c7ax8n689dzecwfx0c

[download apk](http://filestorage.bluewallet.io:1488/1609782600.apk)

2021-01-04 19:04 UTC, marcosrdz requested changes

2021-01-04 19:04 UTC, marcosrdz commented on screen/wallets/viewEditMultisigCosigners.js
> +    fs.writeFileAndExport(exportFilename, exportString).finally(() => setIsLoading(false));
Needs timeout for loading indicator

2021-01-04 19:46 UTC, Overtorment commented on screen/wallets/viewEditMultisigCosigners.js
> +    fs.writeFileAndExport(exportFilename, exportString).finally(() => setIsLoading(false));
maybe better remove loading indicator? fs operation is very fast here

2021-01-05 07:15 UTC, limpbrains approved these changes

2021-01-05 14:49 UTC, marcosrdz approved these changes

2021-01-05 15:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/519btv8dukv2yx9ufc06u9t5yr

[download apk](http://filestorage.bluewallet.io:1488/1609859215.apk)

2021-01-05 15:30 UTC, merged

2021-01-05 15:30 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!