FIX: Bug: when connected to custom Lndhub, create new ln wallet -> ba…
BlueWallet/BlueWallet pull request #2494
Opened 2021-01-13 16:35 UTC by marcosrdz

…ckup screen doesnt include this custom server

2021-01-13 16:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ufdk9q1am94mvk7gjdzt2t46cr

[download apk](http://filestorage.bluewallet.io:1488/1610556705.apk)

2021-01-13 17:34 UTC, Overtorment requested changes

2021-01-13 17:34 UTC, Overtorment commented on screen/wallets/pleaseBackupLNDHub.js
> +  const secret =
nein. you just need to do `.getSecret()` it already includes code that appends custom server

2021-01-13 17:49 UTC, marcosrdz commented on screen/wallets/pleaseBackupLNDHub.js
> +  const secret =
addressed.

2021-01-13 18:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qhph9u6p3fwpew8vnpav7rgq9g

[download apk](http://filestorage.bluewallet.io:1488/1610562007.apk)

2021-01-14 12:43 UTC, Overtorment approved these changes

2021-01-15 15:38 UTC, ncoelho approved these changes

2021-01-15 15:39 UTC, merged

2021-01-15 15:39 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!