REF: Handoff Component
BlueWallet/BlueWallet pull request #2507
Opened 2021-01-19 03:40 UTC by marcosrdz

2021-01-19 03:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/43a35ae05tanu4r025qauv7y8c

[download apk](http://filestorage.bluewallet.io:1488/refhandoff-1611028374.apk)

2021-01-19 07:41 UTC, limpbrains requested changes

2021-01-19 07:41 UTC, limpbrains commented on blue_modules/handoff.ios.js
> +HandoffComponent.STORAGE_KEY = 'HandOff';
`HandoffComponent.STORAGE_KEY` is the same as `AppStorage.HANDOFF_STORAGE_KEY` but it's never used.

2021-01-19 12:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u8q71m94krakwtd1j224uy5dpm

[download apk](http://filestorage.bluewallet.io:1488/refhandoff-1611059198.apk)

2021-01-19 17:57 UTC, limpbrains approved these changes

2021-01-22 16:13 UTC, Overtorment requested changes

2021-01-22 16:13 UTC, Overtorment commented on blue_modules/handoff.ios.js
> +import Handoff from 'react-native-handoff';
feels like this file should be in `components/`

2021-01-22 16:35 UTC, marcosrdz commented on blue_modules/handoff.ios.js
> +import Handoff from 'react-native-handoff';
done

2021-01-22 16:57 UTC, Overtorment approved these changes

2021-01-22 17:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m1af7wcxw4906yuk16jxznafk8

[download apk](http://filestorage.bluewallet.io:1488/refhandoff-1611334906.apk)

2021-01-24 20:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nh30dm0zutdn64th5463hudnpm

[download apk](http://filestorage.bluewallet.io:1488/refhandoff-1611521086.apk)

2021-01-25 02:14 UTC, merged