TST:  e2e: watch-only -> receive (& receive with amount)
BlueWallet/BlueWallet pull request #2525
Opened 2021-01-24 00:40 UTC by marcosrdz

2021-01-24 00:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/24cgbg3thgy6w5jczkhpmhega8

[download apk](http://filestorage.bluewallet.io:1488/TSTwatchonly-1611449610.apk)

2021-01-25 16:56 UTC, Overtorment requested changes

2021-01-25 16:56 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> +  it('can import zpub as watch-only, go to transactions list, go into Receive modal, and set custom amount. Dismiss modal and go to WalletsList.', async () => {
can it be a part of other testcase? 
every testcase and wallet import takes a lot of time on CI

2021-01-25 16:56 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> +    await yo('BlueCopyTextToClipboard');
get the resulting bip21 string and verify it as well

2021-01-25 16:56 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> +    await device.pressBack();
this is only needed if after it comes another test in the same testcase

2021-01-28 06:08 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0dwawk0ue3k17a88rwd2ypae94

[download apk](http://filestorage.bluewallet.io:1488/TSTwatchonly-1611814098.apk)

2021-01-28 09:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tda8f3ctyg4c14n13zv019qn78

[download apk](http://filestorage.bluewallet.io:1488/TSTwatchonly-1611824861.apk)

2021-01-28 10:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1188zn16jefdc9wqb243netbmw

[download apk](http://filestorage.bluewallet.io:1488/TSTwatchonly-1611828240.apk)

2021-01-28 20:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7ed6f70c2yjr5mtceucfu4cayg

[download apk](http://filestorage.bluewallet.io:1488/TSTwatchonly-1611864453.apk)

2021-01-29 15:56 UTC, Overtorment approved these changes

2021-01-29 15:56 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> +    await expect(element(by.text('bitcoin:bc1qtc9zquvq7lgq87kzsgltvv4etwm9uxphfkvkay?amount=1&label=Test'))).toBeVisible();
gj

2021-01-29 15:58 UTC, merged

2021-01-29 15:58 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!