OPS: Idle timer
BlueWallet/BlueWallet pull request #2543
Opened 2021-01-29 16:42 UTC by marcosrdz

2021-01-29 16:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tyfuu03wtfhjde7wcymwb0g08m

[download apk](http://filestorage.bluewallet.io:1488/idle-1611939437.apk)

2021-01-29 18:14 UTC, Overtorment requested changes

2021-01-29 18:14 UTC, Overtorment commented on package.json
> +    "react-native-idle-timer": "git+https://github.com/BlueWallet/react-native-idle-timer.git#8587876d68ab5920e79619726aeca9e672beaf2b",
dont we need to somehow call this..?

2021-01-29 18:17 UTC, Overtorment commented
it makes sense disabling sleep ONLY during import procedure. 
phone should lock if just idle for security reasons

2021-01-29 20:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pge1wqb4k5v3kjp82r339yuxyw

[download apk](http://filestorage.bluewallet.io:1488/idle-1611953881.apk)

2021-01-30 20:00 UTC, Overtorment approved these changes

2021-01-30 20:01 UTC, merged

2021-01-30 20:01 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!