PSBT Cosign WIP
BlueWallet/BlueWallet pull request #2557
Opened 2021-02-01 07:31 UTC by limpbrains

2021-02-01 07:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gb4nm6amj1upf6wuqmbc20j280

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-psbt-sign-1612165428.apk)

2021-02-01 08:01 UTC, limpbrains commented
@Overtorment I'm thinking of how to test it. Let's create 3 wallets. `HDLegacyP2PKHWallet`, `HDSegwitP2SHWallet` and `HDSegwitBech32Wallet`. And one transaction to use UTXO from all of them, then try to sign this psbt using them one by one. In the result it should be new valid transaction.

2021-02-01 11:02 UTC, ncoelho commented
tACK, worked well for me.

Some inconsistencies with the current PSBTs and signing flows:
1- Sing button is located on send > top right options (I would prefer to keep it there for now)
2- On current PSBT signed screen we show the "hex string" and not the QR code. Should we change it to QR as well on the other? The QR code + share button, seems to be the more elegant GUI.

2021-02-01 17:40 UTC, Overtorment requested changes

2021-02-01 17:40 UTC, Overtorment commented on screen/send/psbtSign.js
> +      setTxHex(tx.toHex());
instead of reimplementing broadcast, can we reuse `send/confirm` screen, so we make our send flow more unified?

![image](https://user-images.githubusercontent.com/1913337/106493473-150b8e80-64b1-11eb-88e3-63afb6f54181.png)

2021-02-01 17:40 UTC, Overtorment commented on screen/send/psbtSign.js
> +  const exportPSBT = async () => {
exportPSBT we could move to this screen:

![image](https://user-images.githubusercontent.com/1913337/106493678-5dc34780-64b1-11eb-8e97-a8de0796b0f4.png)

so if this screen received not only txhex but also psbt - provide option to export it

2021-02-01 17:40 UTC, Overtorment commented on screen/wallets/details.js
> +                HDSegwitP2SHWallet.type,
i propose covering it with feature flag instead, like `AbstractWallet.allowCosignPsbt()`
and implement it only for BIP84, otherwise scope of work is a bit too much

2021-02-01 17:40 UTC, Overtorment commented on screen/wallets/details.js
> +                  <SecondButton onPress={navigateToPsbtSign} title={loc.send.psbt_sign} />
should not be here, better do it like MS: send->menu->Sign a transaction

![image](https://user-images.githubusercontent.com/1913337/106494236-14272c80-64b2-11eb-8e6e-da980f61f7e3.png)

2021-02-01 17:40 UTC, Overtorment commented on screen/send/psbtSign.js
> +      setTxHex(tx.toHex());
so, we have an e2e test that covers same action BUT from the other side: `'can import zpub as watch-only, import psbt, and then scan signed psbt'`

it imports zpub, creates transaction, and renders QR. counterparty that should sign in this scenario is specterDIY or CoboVault. 
in this ticket we are teaching BW to act as specterdiy or cobovault, right?
so after BW signs it, this QR should be readable by BW:
![image](https://user-images.githubusercontent.com/1913337/106495598-d0cdbd80-64b3-11eb-8e83-f8e5d7115bea.png)
and other device that will actually read it, has this on screen:

![image](https://user-images.githubusercontent.com/1913337/106495699-f064e600-64b3-11eb-8101-e966efbd3227.png)

(user is supposed to click 'scan signed transaction' button).
will it work..?





SO, i propose, on this screen:
![image](https://user-images.githubusercontent.com/1913337/106495850-19857680-64b4-11eb-886e-028206563eec.png)

leave only QR (possibly make it animated..? we have a component for that), and leave other button, which will lead to
`send/confirm`

2021-02-01 17:41 UTC, Overtorment commented
also, needs unit test (at the very least, we can use seed for `zpub6rDWXE4wbwefeCrHWehXJheXnti5F9PbpamDUeB5eFbqaY89x3jq86JADBuXpnJnSvRVwqkaTnyMaZERUg4BpxD9V4tSZfKeYh1ozPdL1xK` ), and probably e2e

2021-02-06 13:29 UTC, limpbrains commented on class/wallets/abstract-hd-electrum-wallet.js
> +      if (inp.finalScriptSig || inp.finalScriptWitness || inp.partialSig) sigsHave++;
I think of it this way: you can have 3 offline wallets and want to create one tx to spend all the funds from them. In this case somewhere in the middlie of signing process you will have a PBST with 3 inputs and only 2 of them will be signed

2021-02-06 16:40 UTC, limpbrains commented on screen/send/psbtSign.js
> +      setTxHex(tx.toHex());
agree

2021-02-06 17:08 UTC, limpbrains commented on screen/send/psbtSign.js
> +  const exportPSBT = async () => {
not sure about this. Looks like I can break something

2021-02-06 17:09 UTC, limpbrains commented
https://user-images.githubusercontent.com/155891/107124702-8afb6580-68b6-11eb-8271-88cd19a30161.mov

>  2- On current PSBT signed screen we show the "hex string" and not the QR code. Should we change it to QR as well on the other? The QR code + share button, seems to be the more elegant GUI.

Agree, will do it in another PR

2021-02-06 17:11 UTC, limpbrains commented
https://user-images.githubusercontent.com/155891/107124702-8afb6580-68b6-11eb-8271-88cd19a30161.mov

What do you guys think of this one? If everything is ok, I will start working on e2e test

2021-02-06 17:14 UTC, ncoelho commented
Is that a send to many (batch) example?

2021-02-06 17:17 UTC, limpbrains commented
@ncoelho no

2021-02-06 17:30 UTC, limpbrains commented
Example has 2 outputs. One of them is change. But on details page both are shown. I think this is correct behavior.

Imagine having 2 wallets and creating one tx using UTXOs from both of them. 
Now you need to sign this tx. If I try to guess change output and hide it from Details screen, then it will depend on signing order. And Details screen will be different in each case.

2021-02-06 17:32 UTC, limpbrains commented
Do you think I should move "Coin control" and "Sign a transaction" to the top of actions list?
"Add Recipient" and "Remove Recipient" are the most used options here

2021-02-06 17:44 UTC, ncoelho commented
I understand that. But the job of a wallet is to transform outputs in a user/human understandable GUI.

I expect to see the balance I'm sending plus the fee, independently of the number of outputs the transaction is generating. And we can't assume the user knows what change is (that's a big assumption). Change should just be/stay in my wallet in a transparent way.

This is the logic that happens in all transactions flow. We can improve the verify screen with all information, but the confirmation screen should not show outputs. 

Balance + address + fee on the confirm screen. User then can verify or send.

2021-02-06 17:58 UTC, ncoelho commented
> Do you think I should move "Coin control" and "Sign a transaction" to the top of actions list?
> "Add Recipient" and "Remove Recipient" are the most used options here

For now I will just try to make as similar as the multisig setup as possible. We do need to "redesign" this screens for consistency later, bug let's make them work first. In multisig you have:
1- use full balance
2- import transaction
3- sign transaction

Here you are adding the sign transaction with both importing and scanning, which should be the correct behaviour. So as 2nd option is fine. Leave coin control in the end for now.

2021-02-06 20:58 UTC, limpbrains commented
> I understand that. But the job of a wallet is to transform outputs in a user/human understandable GUI.
> 
> I expect to see the balance I'm sending plus the fee, independently of the number of outputs the transaction is generating. And we can't assume the user knows what change is (that's a big assumption). Change should just be/stay in my wallet in a transparent way.
> 
> This is the logic that happens in all transactions flow. We can improve the verify screen with all information, but the confirmation screen should not show outputs. 
> 
> Balance + address + fee on the confirm screen. User then can verify or send.
> 
> 
> 


Can you please elaborate on what exactly you want me to do. I see 2 options:
- try to find change output and show correct info on Confirm. Will work most of the time. 
- hide Confirm, because we can't show it correctly, user should rely on tools where PSBT was created. It could be BW on another device or HW

2021-02-08 11:45 UTC, ncoelho commented
I create a PSBT, imported it to the wallet with the seed. And land on a screen to sign the transaction. Am I doing something wrong?

I would expect to land on the screen with the transaction signed, ready to copy or broadcast.

https://user-images.githubusercontent.com/1238429/107215114-2b629e80-6a0b-11eb-98c4-cb1409ddcefd.mov

2021-02-08 12:04 UTC, limpbrains commented
@ncoelho It can't sign any inputs. Strange. Can't reproduce this. Are you sure psbt was created using zpub from the wallet you are trying to sign tx?

2021-02-08 13:05 UTC, ncoelho commented
> @ncoelho It can't sign any inputs. Strange. Can't reproduce this. Are you sure psbt was created using zpub from the wallet you are trying to sign tx?

Sorry my mistake. Imported the wrong psbt file on that video. Worked for me now.

2021-02-08 14:29 UTC, ncoelho commented
Transaction signed with the seed, gives QR with HEX. QR is imported to online watch-only to broadcast, doesn't recognize HEX. Something is wrong on the flow right? We are giving HEX and watch-only is expecting PSBT?


https://user-images.githubusercontent.com/1238429/107232905-44c31500-6a22-11eb-834f-5d66181ffcab.mov

2021-02-08 15:19 UTC, limpbrains commented
@ncoelho 
I'm not familiar with this flow. 
https://github.com/BlueWallet/BlueWallet/blob/52f1bdfe6baddb08b11f074ed214a6119c34146b/screen/send/details.js#L897
It says 
**this looks like NOT base64, so maybe its transaction's hex**
**we dont support it in this flow**

May be we should? cc @Overtorment 

When you generate PSBT there is a "Scan Signed Transaction" button. It works fine.

2021-02-08 15:21 UTC, limpbrains commented
2 questions
- probably we should change text "This wallet is not being used in conjunction with a hardware wallet. Would you like to enable hardware wallet use?" to something like "This wallet is not being used in conjunction with an offline signing. Would you like to enable it now?
- do you think we should move this feature under Anvanced? In order not to overload the interface.

2021-02-08 15:33 UTC, ncoelho commented
> 2 questions
> 
> * probably we should change text "This wallet is not being used in conjunction with a hardware wallet. Would you like to enable hardware wallet use?" to something like "This wallet is not being used in conjunction with an offline signing. Would you like to enable it now?
> * do you think we should move this feature under Anvanced? In order not to overload the interface.

Yes, the text should be changed.
I can keep it for now

2021-02-09 09:11 UTC, limpbrains commented on class/wallets/abstract-hd-electrum-wallet.js
> +      // }
@Overtorment I copy-pasted this from multisig cosign function. This never worked for me in tests. Always throws `Need one bip32Derivation masterFingerprint to match the HDSigner fingerprint` error. 
Can you please take a look? Maybe I should remove this ?

2021-02-16 15:58 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.js
> +      if (inp.finalScriptSig || inp.finalScriptWitness || inp.partialSig) sigsHave++;
how is transactino crafted? adding inputs one by one?

2021-02-16 16:22 UTC, Overtorment commented
> on

no, PSBT was specifically invented so developers would not have to pass hex around.
txhex doesn't have necessary metadata so parsing it to sign it would be a guesswork/bruteforce prone to errors

2021-02-16 22:46 UTC, Overtorment requested changes
i like how it works in general, tested it on my devices.
but requires some refactoring. 
ill probably work on this branch myself.

2021-02-16 22:46 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.js
> +      // }
yeah, would be nice to make signInputHD work, and keep the fallback as well (pls add comments)

2021-02-16 22:46 UTC, Overtorment commented on class/wallets/abstract-wallet.js
> +  allowCosignPsbt() {
noice

2021-02-16 22:46 UTC, Overtorment commented on tests/unit/cosign.test.js
> +});
i like the approach. solid test

2021-02-16 22:46 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.js
> +      // }
heres how psbt's input data looks like when BW crafts it (having only Zpub):

![image](https://user-images.githubusercontent.com/1913337/108129574-4fc31880-70a6-11eb-8807-407d14b7a6a9.png)

2021-02-16 22:46 UTC, Overtorment commented on screen/send/details.js
> +        this.props.navigation.navigate('PsbtSign', {
screen `PsbtSign` is not necessary. 
first, you could cosign transaction right on that screen (dont forget to set isLoading) - similar to how its done in `importTransactionMultisigScanQr` on the same screen.
and then, if you have a txhex - navigate to  `send/create` and pass an option that along with multiline input with txhes should also be rendered _animated_  qr (dynamicqrcode, bc-ur encoded). boom! code reuse. flow unification

2021-02-17 08:15 UTC, limpbrains commented on tests/e2e/bluewallet.spec.js
> -  it.skip('can encrypt storage, and decrypt storage, but this time the fake one', async () => {
yes, fixed

2021-02-17 08:22 UTC, limpbrains commented on tests/unit/cosign.test.js
> +
Good idea, done

2021-02-17 08:36 UTC, limpbrains commented on screen/wallets/details.js
> +  Platform,
reverted

2021-02-17 08:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e6dkbakynrb5ekjc1ru5vzjazc

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-psbt-sign-1613552210.apk)

2021-02-17 10:02 UTC, limpbrains commented on screen/send/details.js
> +        this.props.navigation.navigate('PsbtSign', {
Screen unification is a good thing. I just thoungt send/details is already overloaded

2021-02-17 10:21 UTC, limpbrains commented
> i like how it works in general, tested it on my devices.
> but requires some refactoring.
> ill probably work on this branch myself.

Sure, you are welcome!

I'm trying to generate a correct fingerprint using:
```js
  const seed = bip39.mnemonicToSeed(process.env.HD_MNEMONIC);
  const root = HDNode.fromSeed(seed);
  const child = root.derivePath(path);
  const fp = child.fingerprint
```

and use this fingerprint in `psbt.addInput`

but `psbt.signInputHD` still doesn't work for me with the same error

2021-02-17 18:45 UTC, Overtorment commented
@limpbrains i simplified it. removed unnecessary screen. drawback is that I had to remove the flow with some inputs being unsigned (class still supports it, so we can bring it back in UI anytime - we just need a use case for it).
I reused `send/Confirm` screen, but screwed up with react markup so visually its a bit broken. 
I also uncommented `signInputHD` and added a testcase that tests it.

2021-02-17 19:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g27n5d4p7trn6xv549ftkntc30

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-psbt-sign-1613591900.apk)

2021-02-17 21:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ca3gum34pr7v3x9wv6exhr6w84

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-psbt-sign-1613599094.apk)

2021-02-17 22:32 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6fka51ckypn5hdtergjjgec6rr

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-psbt-sign-1613601148.apk)

2021-02-18 08:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jkbnww58qqaufkwc5h6g3ctr5w

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-psbt-sign-1613638609.apk)

2021-02-18 10:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j7nxg4nf4z2t6g2bk5aueg3vdc

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-psbt-sign-1613642587.apk)

2021-02-18 11:38 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xg8rzn7bye5j8mwck1ftfrbx7c

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-psbt-sign-1613648285.apk)

2021-02-18 12:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/32vde681zvm7yfk2u8hy735xvw

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-psbt-sign-1613649764.apk)

2021-02-18 13:37 UTC, merged