ADD:  Standard wallet type Electrum JSON import
BlueWallet/BlueWallet pull request #2577
Opened 2021-02-06 04:18 UTC by marcosrdz

2021-02-06 15:52 UTC, Overtorment requested changes

2021-02-06 15:52 UTC, Overtorment commented on screen/wallets/import.js
> -              Keyboard.dismiss();
is this intentional? i liked how it worked before

2021-02-06 15:52 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +    if (json && json.wallet_type && json.wallet_type !== 'standard') {
what does this `standard` stands for?

2021-02-06 15:52 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +    if (json && json.wallet_type && json.wallet_type !== 'standard') {
i just noticed that coldcard skeleton export has this

2021-02-06 15:52 UTC, Overtorment commented on class/wallets/abstract-wallet.js
> +      let parsedSecret;
wheres the testcase for this..?

2021-02-07 04:18 UTC, marcosrdz commented on screen/wallets/import.js
> -              Keyboard.dismiss();
Yup. when you tap clear, it dismisses the keyboard. making the user tap the textview again instead of being able to type after press.

2021-02-07 04:19 UTC, marcosrdz commented on class/wallets/multisig-hd-wallet.js
> +    if (json && json.wallet_type && json.wallet_type !== 'standard') {
standard is the electrum value for single sig wallets. multi sig would have "2of3" for example

2021-02-07 04:21 UTC, marcosrdz commented on class/wallets/abstract-wallet.js
> +      let parsedSecret;
can import coldcard/electrum compatible JSON skeleton wallet, and create a tx with master fingerprint


^ this covers it afaik

2021-02-07 07:56 UTC, limpbrains approved these changes

2021-02-07 13:43 UTC, Overtorment commented on class/wallets/abstract-wallet.js
> +      let parsedSecret;
what I meant is that you need to add a testcase for this specific feature you implemented in this PR

2021-02-07 13:43 UTC, Overtorment requested changes
add a unit test

2021-02-08 05:00 UTC, marcosrdz commented on class/wallets/abstract-wallet.js
> +      let parsedSecret;
Added.

2021-02-08 16:03 UTC, ncoelho approved these changes

2021-02-09 14:20 UTC, Overtorment approved these changes

2021-02-09 14:21 UTC, merged

2021-02-09 14:21 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!