ADD: lightning LND full node
BlueWallet/BlueWallet pull request #2615
Opened 2021-02-12 15:40 UTC by Overtorment

2021-02-12 15:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/73pv1d1vre2bu4t63z4wpfj650

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1613145376.apk)

2021-02-12 16:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p87j5m5jj2acbgwb0qhyzh449m

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1613148108.apk)

2021-02-12 16:43 UTC, Overtorment commented
btw @ncoelho colors im using is `  static lndWallet = ['#8532a1', '#833170'];`
now is a good time to change them if you want

2021-02-15 09:22 UTC, limpbrains requested changes

2021-02-15 09:22 UTC, limpbrains commented on screen/send/details.js
>      const wallets = context.wallets.filter(wallet => wallet.type !== LightningCustodianWallet.type && wallet.allowSend());
Looks like you need to filter out all `OFFCHAIN` wallets here

2021-02-15 16:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jguewp3hvqurqgfj0nu6n7qaj4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1613406920.apk)

2021-02-24 22:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xpwg09e0ey7m41a1r5rwu0yjr8

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1614204762.apk)

2021-02-25 20:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dd6rx0nz7x06ddbbjg1rkrjtt4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1614284721.apk)

2021-02-26 16:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5zwrewcf7zqk6h2wzut43wzd48

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1614357536.apk)

2021-02-26 17:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/44gw9gw8tcfddp0kvhtr3xp7dc

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1614362349.apk)

2021-02-28 06:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qde67m82ak0uvnkvyw1m7uee30

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1614495205.apk)

2021-03-01 06:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bryw89jeuk6zcn32224t694vn4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1614578601.apk)

2021-03-04 13:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w05ep56p2x290waur0cha1j7ur

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1614864933.apk)

2021-03-05 02:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mmy3unqfxukp12tgh3kyb74f3w

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1614911305.apk)

2021-03-05 03:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9u6j9670x1k7avf8nntcd5wner

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1614913956.apk)

2021-03-05 14:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7c1z27c0ywv23b5pkujhcf77pc

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1614954788.apk)

2021-03-05 17:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jf6pjy5mh0z8vhxuhw5b48z2bm

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1614965608.apk)

2021-03-06 04:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d6p54qrnh21wkbt9dba0bcj2r8

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615003367.apk)

2021-03-06 04:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qyy9r8uk1ez21wx4p9j4f1rd70

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615006489.apk)

2021-03-08 01:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7vh23dn16r8cy3q7mg1m2q1ddg

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615168082.apk)

2021-03-08 13:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f2rgz89zctkbnu0x8kqw08xcb8

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615210914.apk)

2021-03-09 03:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2vm8cy6evftz7w71uaaqugx8v0

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615259933.apk)

2021-03-09 04:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kenxdutg4w9azxgndj020e4q64

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615265376.apk)

2021-03-09 05:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/978jaa3mpgq1b1r88h47kjkpxm

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615268136.apk)

2021-03-09 20:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jxpbm68mw7wpe3q8e3xzdk9uec

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615321686.apk)

2021-03-10 06:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ez1nfamar54ncznbn0k7k5bp80

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615357292.apk)

2021-03-10 23:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v8517gnj35u9f90xkdvza27jv4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615418758.apk)

2021-03-11 01:52 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cckmf88d5k0he194p972x9v98w

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615427512.apk)

2021-03-11 04:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/09phcb2p896ztxm7fazp8unwcc

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615438174.apk)

2021-03-12 18:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q6mzz7x0k047m3hxypwndeyb5w

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615575490.apk)

2021-03-12 23:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5cftvaw1hc3ngewx13fm2bym8m

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615591693.apk)

2021-03-14 03:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nqrd3uutyj4yvnf5t0d1y9v85m

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615691547.apk)

2021-03-15 22:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xu9c329vxp4fdcckhtwyjrq9hm

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615848232.apk)

2021-03-16 14:47 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1v4b0td07evk9c119krf3mpu0m

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1615906039.apk)

2021-03-18 14:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b1mpr2835f5kfb4tzt114u7v40

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616079266.apk)

2021-03-19 12:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2ujqmvpu00gx7mqac4pz4fdjqw

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616158602.apk)

2021-03-19 15:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/310x2h4t3cz1arphp88uh69www

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616168212.apk)

2021-03-20 02:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vn42tfh41xgbkfv15kdbezud1m

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616206898.apk)

2021-03-20 03:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vj7rmqd6m451ykwfjgd1ex20ac

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616211805.apk)

2021-03-20 05:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/az3f9xpna55fnn0hqc35k3k3yw

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616219377.apk)

2021-03-21 05:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jg2dxvcehu6kuaetdwkt2gpmdm

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616303723.apk)

2021-03-22 14:10 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cgtr8bugqumk8yt4h5zur3vhar

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616422234.apk)

2021-03-22 18:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/agaqc3h9af8q0emdd6em2puwk8

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616439529.apk)

2021-03-24 18:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d7vc4czf4mpr765zn292vyu0xw

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616610383.apk)

2021-03-25 04:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vmq5000tcqh1k4nav05uxc11rc

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616647346.apk)

2021-03-25 06:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uvkq0zujvr02xqd2b8fjewfhtr

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616652724.apk)

2021-03-25 14:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pjgcfrvvedbgbvbdxb2g53r5k4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616681459.apk)

2021-03-26 01:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wk9xjtjh0vhxt3f9tt6dfj102r

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616721768.apk)

2021-03-26 15:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hff14jcknv6kvmky8pj792ndfg

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616771198.apk)

2021-03-27 09:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4y3utp2p0v82vxj9fxehpbevew

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616839137.apk)

2021-03-27 19:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ap8vcaacbwkar4dkneumek08km

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616874364.apk)

2021-03-29 02:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/twq597tpgyzpk059ddvkjr3kyg

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616986670.apk)

2021-03-29 04:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b7bv41a5tkh8uaxhr2177g74fc

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616992220.apk)

2021-03-29 05:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2vz2y8uy37ytuw28duk8qb5y8c

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616995084.apk)

2021-03-29 05:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d9etbvvguvp011f6wt9jqdzhdg

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1616996925.apk)

2021-03-31 02:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vtcz18ny4ua8xhy40hv9vbur8r

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1617158682.apk)

2021-03-31 03:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ak5mgwfwu6zmav29wq9k82hyrm

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1617161390.apk)

2021-04-02 15:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tt2wgghj8q06fu39gqwgrtbpe0

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1617377160.apk)

2021-04-03 01:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xvy7ae5mumgrquzxd3cjcg5q48

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1617412791.apk)

2021-04-06 01:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rjrdyjfgv6papm449x2g7xgcyr

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1617670983.apk)

2021-04-07 20:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x5agxz1qq1fabhra21vgxqx2wr

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1617827955.apk)

2021-04-08 00:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kmrnt6dhn64yhgr82ne5e5rvp8

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1617841665.apk)

2021-04-09 00:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/twek09771fxntuzvz3wm8bcwn8

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1617929498.apk)

2021-04-09 01:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gz6mvw3vduqx2zx4e95ebpm40m

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1617932497.apk)

2021-04-09 02:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x7tbtzgqcn0t06f2kf69t8j0h0

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1617937116.apk)

2021-04-09 23:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cwgjt217zu02684ae40txjebmr

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618012457.apk)

2021-04-10 00:52 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dvmyqbhpedj255x8bfz0fxfxfw

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618015899.apk)

2021-04-10 05:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yh7amcpyxv4znp6vp3204qm17m

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618032027.apk)

2021-04-10 05:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/knabpmucwuvtptt77x3w7dp960

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618034133.apk)

2021-04-10 07:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d1w7vmmqm6ch0nhy75990jbhk8

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618039513.apk)

2021-04-10 08:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2f0ctufp5eu6c8gkvxuehqrm6w

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618043209.apk)

2021-04-10 17:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0j9eg37q9j0gckg1vmwkp5dkgc

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618076472.apk)

2021-04-11 02:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8mzfumf2d0rparv9wjkcccp90r

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618109024.apk)

2021-04-11 21:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fp9r5pwp6kat42nthz1uc96j10

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618177441.apk)

2021-04-11 22:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/36e3m7c4khphe2ec1weqkhpfpc

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618178816.apk)

2021-04-11 22:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k4f8xv8z9v166rm5r2q6d38384

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618179888.apk)

2021-04-12 06:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fmchx3yz7gj86mgu2rz6cg0n4g

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618209315.apk)

2021-04-12 15:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/t8jjkc96tkc5e7g5nkf4d9tddg

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618240374.apk)

2021-04-12 16:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/frmqdxpm6112d0ky0drpkm1rh4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618245850.apk)

2021-04-12 20:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/un4uzu5gb3dtc2et62tzvux22m

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618259594.apk)

2021-04-13 04:32 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qy6ufg0c6npg3thk6dku721vv8

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618288334.apk)

2021-04-13 18:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qnnq06cf4fr7v8tmywjrpmk02g

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618340002.apk)

2021-04-13 20:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f8ed21nbnk7htzwncc353xde40

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618345158.apk)

2021-04-13 20:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dd28w4bt3p8vq11kgudhxqbqbc

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618346772.apk)

2021-04-13 21:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dv6hcjp00qcd9m3fumqcn6mx0c

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618349137.apk)

2021-04-13 22:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5ymmv4208c8d4qygr8whjdkqdw

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618352227.apk)

2021-04-14 06:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kqgt8azv69wvbc4k4a3ukzkvvm

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618380348.apk)

2021-04-14 16:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1h7qr7yeubevem1zec1p48rfw8

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618416799.apk)

2021-04-14 21:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k0hhf660f1et76fp9adufjj4f0

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618434042.apk)

2021-04-15 14:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kn54h74c3q396pvfade77mvarm

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618498179.apk)

2021-04-15 16:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0bjrxggn3y3pyebc03d2u56v24

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618503263.apk)

2021-04-15 22:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w84hcng9mhwxdmwq7fhy7tm524

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618524966.apk)

2021-04-16 03:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/huradzj2dmaxe2db5n5a1g97j0

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618543881.apk)

2021-04-16 17:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8ak05nhcnunkfyt9agatfxb1u4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618593694.apk)

2021-04-17 14:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5uaer0wfx0ncuwm61913wuy2w8

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618670103.apk)

2021-04-17 16:52 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mjcvm59phh46t9j6h1k22v21c4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618678342.apk)

2021-04-18 00:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r5zqmhrpqzrcnue5q9fyv7126r

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618706049.apk)

2021-04-18 01:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ha9pg42vj7b95v1xmh59mau9mg

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618708752.apk)

2021-04-18 02:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5rh28uv5z8cbcfg7r4jxvcaffm

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618712159.apk)

2021-04-18 15:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8guy6698zxrqzwymrj3re6mbnr

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618760674.apk)

2021-04-19 21:32 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n6yhxg88f7w5w0c2udx3eqnjzw

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618867908.apk)

2021-04-20 04:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jbnjkjexc86cnq16qnp4t1e6h0

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618893446.apk)

2021-04-21 03:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hqcdwy066pgp3zn31a7chkgtv0

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1618977177.apk)

2021-04-21 16:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8uqq2yrk0weeeyaw7g1mx90rpw

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1619022416.apk)

2021-04-22 07:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e7vh1a95t5y41kgr5v8vrxyft0

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1619075722.apk)

2021-04-22 17:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g7a99wbmwyx6m1yefwtpbh0zgm

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1619112834.apk)

2021-04-23 18:05 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n5mvkm2perw9a719emkjh99vpr

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1619201134.apk)

2021-04-25 19:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j69cu00pmkubnxrxu5ewb1cabw

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1619377903.apk)

2021-04-28 04:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2ex8thytk2n9xph83x66rd6zt8?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1619584753.apk)

2021-04-29 02:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ctpj04p53rpz1zq6f9hrp3j7yr?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1619663214.apk)

2021-04-29 03:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u4x3x8cw8vwj9yjb765jnvugb0?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1619665244.apk)

2021-04-29 03:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5619tra7kqavwznmu89tdy41ew?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1619667180.apk)

2021-05-01 20:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0m3x42ya7n5pfbejqtkyjp80mr?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1619900393.apk)

2021-05-03 17:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q0ab22u9v47hruhjf5md7aytw0?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1620064401.apk)

2021-05-04 04:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ck3a8qaxyg3np2dax1dx6uefu0?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1620100964.apk)

2021-05-04 18:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cbzf3na94zax88vmpwdrn10b4r?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1620152218.apk)

2021-05-05 17:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9k4z21tw4m5phr5k8haa19egbc?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1620236722.apk)

2021-05-06 03:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rne4db7t5am2utfr1vky8w75j0?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1620271226.apk)

2021-05-11 14:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3h8rhqjxb42uv52923cuy62n2g?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1620743162.apk)

2021-05-15 03:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3cgcrur4gt13g8gh7mqxyjcver?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1621049925.apk)

2021-05-16 23:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yn67x6f6r3dfkjd2nhjamx5u6c?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1621206997.apk)

2021-05-17 21:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7ezj1yangxtf73d3162ank37q8?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1621285727.apk)

2021-05-18 15:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yr53d7zujxvxmpu7aqrkdvfkjm?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1621353530.apk)

2021-05-20 02:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/avxparwpqy0h5tdfk1g1phfcjg?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1621477793.apk)

2021-05-20 15:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/38hgn6xe9hwpje4ytkhjxhf15m?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1621525418.apk)

2021-05-22 19:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hn56knxf1znwvj26wpuyx837uw?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1621711988.apk)

2021-05-29 04:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bzn0drdbbuehey0qpryjpw84aw?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1622264178.apk)

2021-06-05 23:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x3dgycq4jkhhekcj6kd8vkbttc?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1622937168.apk)

2021-06-07 13:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u4g6pyxjvkczwbyanmv6bhhvb4?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-rn-lnd-1623070885.apk)

2021-07-27 10:34 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-07-27 10:45 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-07-27 10:55 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-07-27 11:10 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-07-28 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-07-29 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-07-30 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-09-11 04:31 UTC, xanoni commented
I can haz?

2021-09-11 12:16 UTC, Overtorment commented
theres better alternative (based onn rust-lightning) on the way

2022-11-11 14:54 UTC, closed without merging