REF: load from disk
BlueWallet/BlueWallet pull request #2617
Opened 2021-02-12 23:38 UTC by Overtorment

2021-02-13 00:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bbzztexzwb8j675uy38c8yzfkm

[download apk](http://filestorage.bluewallet.io:1488/ref-load-from-disk-1613176947.apk)

2021-02-13 03:16 UTC, marcosrdz requested changes

2021-02-13 03:16 UTC, marcosrdz commented on class/app-storage.js
> +      const realm = await this.getRealm();
We should reset the realm storage if this fails. It could get corrupted forcing wallets to not load even though they are two separate things

2021-02-13 12:40 UTC, Overtorment commented on class/app-storage.js
> +      const realm = await this.getRealm();
elaborate

2021-02-13 13:08 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/69w3x8kym7hp20bcd5b3gc9few

[download apk](http://filestorage.bluewallet.io:1488/ref-load-from-disk-1613221682.apk)

2021-02-13 19:45 UTC, marcosrdz commented on class/app-storage.js
> +      const realm = await this.getRealm();
So lets say the user is playing around with APKs and installs a release with an older realm than the one in the last APK installed. Realm will not be able to handle the downgrade of db, we should call 

deleteAll() so the Realm db is reset. Right now theres no catch for it..it just becomes unusable cause the code doesnt proceed to other actions

2021-02-14 14:27 UTC, Overtorment commented on class/app-storage.js
> +      const realm = await this.getRealm();
its unrelated to this ticket. 
it falls into category "what if i install a really outdated build that wont work with current db format". frankly, this is not our problem, no one ever promised forward compatibility

2021-02-20 16:07 UTC, marcosrdz approved these changes

2021-02-21 08:48 UTC, limpbrains approved these changes

2021-02-21 08:49 UTC, merged

2021-02-21 08:49 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!