REF: send/details to func component, move Address and Amount Inputs out of BlueComponents
BlueWallet/BlueWallet pull request #2630
Opened 2021-02-16 09:54 UTC by limpbrains

plan:
- e2e tests

2021-02-16 10:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/46tuv3r5pqa7q3qeryc5udqc14

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1613470313.apk)

2021-02-18 13:51 UTC, Overtorment commented
it would be best to make e2e first (for batch send as well), then do a refactor, and use e2e tests for acceptance.
its an important screen.

2021-02-18 14:09 UTC, Overtorment requested changes
hard to review such big changes. especially when a bunch of e2e fails.
maybe its better to start with separate PRs to increase coverage of that screen (don't forget batching)

2021-02-22 08:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3am442n83y0ba3ugfdav4wbynm

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1613982805.apk)

2021-02-22 09:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6fzz3pcapjc6cy8nrmmv0mzb5c

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1613986610.apk)

2021-02-22 10:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uex2kt80gqawuk9qvw5pkauu2g

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1613988792.apk)

2021-02-22 12:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mvk3ttp1j72ay4ha5gtgrjm6n4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1613997270.apk)

2021-02-22 12:53 UTC, limpbrains commented
> hard to review such big changes. especially when a bunch of e2e fails.
> maybe its better to start with separate PRs to increase coverage of that screen (don't forget batching)

Will do in #1904

2021-02-23 08:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9mc3upjrd6vdtcrnr9c99n8h2c

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1614070439.apk)

2021-02-23 09:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4gfdxym1fuvgh2by3ax3r3fjjr

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1614072645.apk)

2021-02-23 11:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/50h3gqk76ptad3vegrzyftzryw

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1614080387.apk)

2021-02-23 17:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mqk5kgepm0hmq7pmxy7j1ggnr4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1614100909.apk)

2021-02-25 10:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3zc28a86tgz9xyk222k655t0jr

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1614247603.apk)

2021-02-25 11:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z7bg0x8tmjrxthe9rkgd2ybzkw

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1614251559.apk)

2021-02-25 13:10 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/h1g28yn21txn14bq5nybzzrva4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1614258636.apk)

2021-02-25 14:31 UTC, limpbrains commented on screen/send/details.js
> +        */}
@marcosrdz I've replaced this hack with width from `useWindowDimensions`. Can I keep it or should I use the original approach with onLayout={this.onLayout}?

2021-02-25 14:32 UTC, marcosrdz commented on screen/send/details.js
> +        */}
onLayout is needed for desktop and tablets. useWindowDimensions does not work well with those devices. It returns inaccurate dimensions

2021-02-25 15:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b5r7na26g3c65ekw2yrdu0r438

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1614267957.apk)

2021-02-25 16:14 UTC, limpbrains commented
Ready for review and merge

2021-02-25 16:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z2vh6v38b14v6r3cgfn59mc29m

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1614270470.apk)

2021-02-26 18:15 UTC, marcosrdz commented
@limpbrains  conflicts

2021-02-26 20:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3fuzcadhpdjdxgzqhdecek916c

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1614370515.apk)

2021-02-27 00:38 UTC, marcosrdz requested changes

2021-02-27 00:38 UTC, marcosrdz commented on screen/send/details.js
> +      Alert.alert(loc.send.details_wallet_before_tx);
Alerts should have a title instead of using the message as the title. Especially for macOS.

2021-02-27 00:42 UTC, marcosrdz requested changes
send/details.js screen is not listening for deeplinks. (such as deepLinkPSBT). 
Perhaps addresses should be a useRoute.params instead of useState? That way the screen updates if a bitcoin address is deeplinked in while this modal is open

2021-02-28 07:30 UTC, limpbrains commented on screen/send/details.js
> +      Alert.alert(loc.send.details_wallet_before_tx);
fixed

2021-02-28 07:41 UTC, limpbrains commented on screen/send/details.js
> +        */}
fixed

2021-02-28 07:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kv2015cap1d5nm3m72vmxnx29c

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-new-send-1614498589.apk)

2021-02-28 07:54 UTC, limpbrains commented
> send/details.js screen is not listening for deeplinks. (such as deepLinkPSBT).
> Perhaps addresses should be a useRoute.params instead of useState? That way the screen updates if a bitcoin address is deeplinked in while this modal is open

I can see `deepLinkPSBT` is used in `psbtWithHardwareWallet.js`. So when you open psbt file BW launches `PsbtWithHardwareWallet`. How does this relates with sendDetails? 

If this is some kind of new feature, let's add it in separate PR, because the longer we will develop this one, the harder it will be to sync all new changes.

2021-03-02 23:45 UTC, marcosrdz approved these changes

2021-03-03 14:48 UTC, Overtorment approved these changes
gj. its nice to have refactoring thats also covered by tests

2021-03-03 14:48 UTC, Overtorment commented on package.json
> +    "e2e:release-test": "detox test -c android.emu.release --record-videos all --take-screenshots all --headless --loglevel trace",
is it gona stay with us forever?

2021-03-03 14:49 UTC, merged

2021-03-03 14:49 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

2021-03-03 14:50 UTC, Overtorment commented
merged. lets continue testing on real builds