Minor Updates to the en.json
BlueWallet/BlueWallet pull request #2664
Opened 2021-02-22 15:18 UTC by mcsaeid

2021-02-22 15:45 UTC, limpbrains commented
It could be both XPUB or public key (address)

2021-02-22 15:54 UTC, mcsaeid commented
I see. Well, the text can reflect that, clarifying that you can both enter a public key _or_ an extended public key, and both will work. If you think that is a good idea, I can re-edit and add more clarification. Personally, I have used XPUBs way more than single public keys.

2021-02-22 17:24 UTC, Overtorment requested changes

2021-02-22 17:24 UTC, Overtorment commented on loc/en.json
> +    "import_explanation": "Write here your mnemonic, private key, WIF, or anything you’ve got. BlueWallet will do its best to guess the correct format and import your wallet. If an extended public ke
technically not correct, regular bitcoin addresses also supported

2021-02-22 19:20 UTC, mcsaeid commented on loc/en.json
> +    "import_explanation": "Write here your mnemonic, private key, WIF, or anything you’ve got. BlueWallet will do its best to guess the correct format and import your wallet. If an extended public ke
Correct. I reverted it to the original but added XPUB in there as well. I believe it adds clarification. Regular addresses are not the only way to create watch-only wallets. Let me know what you think.

2021-02-22 19:50 UTC, Overtorment approved these changes

2021-02-22 21:06 UTC, marcosrdz approved these changes

2021-02-24 17:27 UTC, ncoelho approved these changes

2021-02-24 19:01 UTC, mcsaeid commented on loc/en.json
> +    "import_explanation": "Write here your mnemonic, private key, WIF, or anything you’ve got. BlueWallet will do its best to guess the correct format and import your wallet. If an extended public ke
I actually like this, and I think it makes more sense. Check this out:

“Write here your mnemonic **phrase**, **public or** private key, WIF, or anything you’ve got. BlueWallet will do its best to guess the correct format and import your wallet. If **an extended public key (XPUB)** is entered, we will add it as a watch-only wallet.”

2021-02-25 09:55 UTC, ncoelho commented on loc/en.json
> +    "import_explanation": "Write here your mnemonic, private key, WIF, or anything you’ve got. BlueWallet will do its best to guess the correct format and import your wallet. If an extended public ke
I found it very wordy, and can be stressful. More important than being technically correct, is being concise. Imagine you are user that wants to recover his wallet from seed (that is the main function of this feature), does not understand bitcoin pretty well, and suddenly we are talking about "XPUB". 

We don't need to explain everything it supports and be support precise about extended public keys, or like "electrum format", "bread format", "Aezeed", "lndhub uri" ... The idea you want to pass to the receptor is "ok, got it, it is here I need to write what I have". Let's keep it simple, that's would be my suggestion.

Like:
_Write your seed words, public key, WIF, or anything you’ve got. BlueWallet will do its best to guess the correct format and import your wallet._

If you can make it shorter, better.

2021-02-25 10:38 UTC, mcsaeid commented on loc/en.json
> +    "import_explanation": "Write here your mnemonic, private key, WIF, or anything you’ve got. BlueWallet will do its best to guess the correct format and import your wallet. If an extended public ke
My initial thought was that you wanted it to be technically correct, hence including the public and private keys. Of course, shorter is better, although not too short. With the number of new people coming in every day, user confusion is the last one would want.

2021-02-25 20:34 UTC, Overtorment commented
@ncoelho merge?

2021-02-25 20:39 UTC, ncoelho commented
Merge

![image](https://user-images.githubusercontent.com/1238429/109214193-d3b98680-77b1-11eb-9aa2-ae33748e52bd.gif)

2021-02-25 20:39 UTC, ncoelho approved these changes

2021-02-26 15:52 UTC, merged