ADD: No Network Connection alert
BlueWallet/BlueWallet pull request #2667
Opened 2021-02-23 02:52 UTC by marcosrdz

2021-02-23 02:52 UTC, marcosrdz commented
<img width="325" alt="Screen Shot 2021-02-22 at 9 51 40 PM" src="https://user-images.githubusercontent.com/4793122/108797058-45969380-7558-11eb-9de8-ce7a4ddc691f.png">

2021-02-23 03:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hjk2491a3a8k6wfrf7876q5m24

[download apk](http://filestorage.bluewallet.io:1488/netinfo-1614049894.apk)

2021-02-23 03:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2tf99ynvzfpr3vz0futufbbmqm

[download apk](http://filestorage.bluewallet.io:1488/netinfo-1614051406.apk)

2021-02-23 17:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1tnd26h4vyhbznwek8x94z9fyr

[download apk](http://filestorage.bluewallet.io:1488/netinfo-1614099753.apk)

2021-02-23 22:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zc4v08y9berrytp9grnhtcd83c

[download apk](http://filestorage.bluewallet.io:1488/netinfo-1614118148.apk)

2021-02-24 00:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dahygbfp9p11wtb71zymmewja4

[download apk](http://filestorage.bluewallet.io:1488/netinfo-1614126973.apk)

2021-02-24 12:15 UTC, Overtorment requested changes

2021-02-24 12:15 UTC, Overtorment commented on BlueComponents.js
> +    (props.disableOnNoNetworkAvailable === true && isConnected === false) ||
this is overengineered.
whats the difference between isConnected and isInternetReachable ?
what difference does it make if internet is not reachable, but isConnected - user still cant do what he wanted so he doesn't give a shit if it isConnected

2021-02-24 12:15 UTC, Overtorment commented on BlueComponents.js
> +        (props.networkMustBeReachable && isConnected === false) || (props.internetMustBeReachable && isInternetReachable === false)
overengineered. plus `internetMustBeReachable` is not even used

2021-02-24 12:15 UTC, Overtorment commented on loc/en.json
> +    "no_network_available_description": "A network connection was not found. In order to proceed please verify your connection settings."
maybe use less formal language?

2021-02-24 12:15 UTC, Overtorment commented on loc/en.json
> +    "no_network_available_description": "A network connection was not found. In order to proceed please verify your connection settings."
@ncoelho

2021-02-24 12:15 UTC, Overtorment commented on BlueComponents.js
> +import { useNetInfo } from '@react-native-community/netinfo';
shit another dep...

2021-02-24 13:23 UTC, marcosrdz commented on BlueComponents.js
> +    (props.disableOnNoNetworkAvailable === true && isConnected === false) ||
isConnected means that they are connected to a network with no internet access but can communicate to a node that might have internet. IsInternetReachable means that the user has to have Internet access

2021-02-24 13:24 UTC, marcosrdz commented on BlueComponents.js
> +        (props.networkMustBeReachable && isConnected === false) || (props.internetMustBeReachable && isInternetReachable === false)
Its there for a scenario in which its required

2021-02-24 13:25 UTC, marcosrdz commented on BlueComponents.js
> +import { useNetInfo } from '@react-native-community/netinfo';
Thats the nature of React Native. Everything is separate. But this is official from the RN community. Not some unknown third party

2021-02-24 15:02 UTC, marcosrdz commented on BlueComponents.js
> +    (props.disableOnNoNetworkAvailable === true && isConnected === false) ||
For example...lets say u have a device which is blocked from accessing the Internet, but is able to access the local network (your node).

2021-02-25 06:46 UTC, limpbrains approved these changes
I agree that `internetMustBeReachable` can be removed since it is unlikely that it will be needed

2021-02-25 09:09 UTC, marcosrdz commented on BlueComponents.js
> +    (props.disableOnNoNetworkAvailable === true && isConnected === false) ||
Removed

2021-02-25 09:10 UTC, marcosrdz commented
> I agree that `internetMustBeReachable` can be removed since it is unlikely that it will be needed

Removed.

2021-02-25 09:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w3k141pzk6j26qk7wa00ftzf7r

[download apk](http://filestorage.bluewallet.io:1488/netinfo-1614244982.apk)

2021-02-25 09:42 UTC, ncoelho commented on loc/en.json
> +    "no_network_available_description": "A network connection was not found. In order to proceed please verify your connection settings."
Looks ok to me. Just make sure we need another string for "network connection". There's already 2 of them, a "network" and "network error". Probably we can reuse "network error". Let's be careful on adding strings.

2021-02-25 20:36 UTC, marcosrdz commented on loc/en.json
> +    "no_network_available_description": "A network connection was not found. In order to proceed please verify your connection settings."
Its not really a "network error". Its the lack of network. No processing has been attempted for it
To be fall under error

2021-02-25 22:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kmv7r2uax91vtca1j30z1evt04

[download apk](http://filestorage.bluewallet.io:1488/netinfo-1614291234.apk)

2021-02-26 18:12 UTC, marcosrdz commented on loc/en.json
> +    "no_network_available_description": "A network connection was not found. In order to proceed please verify your connection settings."
Changed to loc.errors.network

2021-02-26 19:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9400n6bwf720b9uku72taru894

[download apk](http://filestorage.bluewallet.io:1488/netinfo-1614366017.apk)

2021-02-27 16:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k75t278dadyma1d3x0hdu7yza0

[download apk](http://filestorage.bluewallet.io:1488/netinfo-1614443719.apk)

2021-02-27 22:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k2nu0b6euryz3vzytj1g0a02mg

[download apk](http://filestorage.bluewallet.io:1488/netinfo-1614466157.apk)

2021-03-10 14:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j4f3cmxyvmqz2jqa6a2mw4jjgr

[download apk](http://filestorage.bluewallet.io:1488/netinfo-1615385673.apk)

2021-03-10 15:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/khmkh8aqbtnqp0gkm93yp8wzyc

[download apk](http://filestorage.bluewallet.io:1488/netinfo-1615388426.apk)

2021-03-15 11:38 UTC, ncoelho approved these changes

2021-03-18 01:07 UTC, marcosrdz commented
@Overtorment

2021-03-30 10:07 UTC, ncoelho commented
conflits

2021-04-02 12:42 UTC, Overtorment commented
at this point i think this is overengineered, brings too little on the table, and adds complexity i don't want to deal with.

2021-04-02 12:42 UTC, closed without merging