FIX: TypeError: undefined is not an object (evaluating 'O.current.get…
BlueWallet/BlueWallet pull request #2681
Opened 2021-02-24 15:03 UTC by marcosrdz

…ID')

2021-02-24 16:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/75yw7zep5d775de2znt2emcn98

[download apk](http://filestorage.bluewallet.io:1488/2631-1614182554.apk)

2021-02-24 19:50 UTC, Overtorment requested changes

2021-02-24 19:50 UTC, Overtorment commented on screen/transactions/transactionStatus.js
> +      setSelectedWallet(wallet.current?.getID());
deepscan legitematly bitchin.
also, im not sure, is that okay to call hook conditionally here..?

2021-02-25 02:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3hk5213bjybb95g69uk50en150

[download apk](http://filestorage.bluewallet.io:1488/2631-1614218533.apk)

2021-02-25 20:32 UTC, Overtorment approved these changes

2021-02-25 20:32 UTC, merged

2021-02-25 20:32 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!