TST: settings screens test
BlueWallet/BlueWallet pull request #2736
Opened 2021-03-01 10:23 UTC by limpbrains

closes #1903

2021-03-01 10:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/92xpg4xkr7fxgg8zzpk4w7e4r8

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-settings-test-1614595302.apk)

2021-03-02 21:55 UTC, marcosrdz commented
Travis fails

2021-03-03 14:06 UTC, Overtorment requested changes
lgtm, but needs to handle emu that has no google services

2021-03-03 14:06 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> +    await device.pressBack();
this might not be available on all devices, as we check whether notification service is supported on android device, and don't show this settings. so, on some  emu it will work, on some - not, depending if emu was set with google services or not.

i suggest check visibility of notification settings - wrap it in try-catch, and if exception was caught - set a flag that this block should not be executed

2021-03-04 07:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8wu6xkzrjunafq2vz03b4djty0

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-settings-test-1614842352.apk)

2021-03-04 09:15 UTC, limpbrains commented on tests/e2e/bluewallet.spec.js
> +    await device.pressBack();
fixec

2021-03-04 13:25 UTC, Overtorment approved these changes

2021-03-04 13:29 UTC, marcosrdz approved these changes

2021-03-04 13:30 UTC, merged

2021-03-04 13:30 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!