FIX: recipients index
BlueWallet/BlueWallet pull request #2756
Opened 2021-03-04 14:26 UTC by limpbrains

- Fixes white screen when remove last of 3 recipients on android
- Add key for addresses array so that FlatList shows correct animations
- Fixes track of current recipient index in Component store. Recepient remove now correctly removes active element, not the last one.

closes #2362

2021-03-04 14:28 UTC, marcosrdz approved these changes
Ahhh...the beauty of useState not updating. Classic

2021-03-04 14:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2w88duhxzp72kequ7hpw0u22kc

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sendmany-index-1614869952.apk)

2021-03-04 19:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ehc94fec4euqn77j8j6xmhkbg8

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sendmany-index-1614885653.apk)

2021-03-05 07:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5w8wky1mypbbvwvm6hpfv9pmk0

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sendmany-index-1614928966.apk)

2021-03-08 17:56 UTC, limpbrains commented
@Overtorment merge it, it's ready

2021-03-12 13:57 UTC, Overtorment requested changes
lgtm but theres a question about swapped test

2021-03-12 13:57 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> +  it('can encrypt storage, and decrypt storage, but this time the fake one', async () => {
muted test swapped.
why? what did you find?

2021-03-12 14:01 UTC, limpbrains commented on tests/e2e/bluewallet.spec.js
> +  it('can encrypt storage, and decrypt storage, but this time the fake one', async () => {
It's just a stupid error, fixed

2021-03-12 14:24 UTC, Overtorment approved these changes

2021-03-12 15:29 UTC, merged

2021-03-12 15:30 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!