FIX: Remove custom styles applied to SafeBlueArea, and their defs
BlueWallet/BlueWallet pull request #2792
Opened 2021-03-14 15:14 UTC by phrazzld

Issue this PR is intended to fix:
https://github.com/BlueWallet/BlueWallet/issues/1226

2021-03-15 12:11 UTC, limpbrains requested changes
Hi!
Looks like I've made a mistake when created #1226! Actually if you provide style to `SafeBlueArea` they will override original component style `{ flex: 1, backgroundColor: colors.background }`. Sorry!  🤦‍♂️ (maybe `SafeBlueArea` has been changed since then?)

So not all styles could be removed from `SafeBlueArea`, only those who duplicate original 
`{ flex: 1, backgroundColor: colors.background }`

Also, I see that in a lot of places `SafeBlueArea` used. with `forceInset={{ horizontal: 'always' }}`, but this property also set in original component, this is definitely can be removed

2021-03-15 14:07 UTC, phrazzld commented
Thanks for the clarification @limpbrains! 

I'll take another pass with all that in mind. I'll also set up Android Studio on my machine so I can run those e2e tests locally and catch failures before pushing breaking commits.

2021-03-17 00:51 UTC, phrazzld commented
"Things get worse before they get better" update:

1. More tests are failing now than before I added non-redundant custom styles back to `SafeBlueArea` instances.

2. I'm having trouble getting my local Android Studio setup to run the end-to-end tests properly.

Regarding (1), I'm pretty confused by the DeepScan output, considering I didn't edit the `BlueComponents.js` file at all. As for the end-to-end tests, I'm not sure what's causing their failures. I'm inclined to revert everything and introduce changes one file at a time as a sort of guess-and-check solution, but I'd rather do that locally than push a commit for each changed file to trigger the automated build checks.

Which brings me to problem (2): I don't have a ton of Android Studio experience, and it's starting to show. I followed the steps in the README to get the project running, but it didn't quite get me to a successful local end-to-end test run. 

Anyone have any ideas? I'm going to hold off on running my guess-and-check playbook for a day or two while I try to debug my local environment, but if I can't figure out a way to run these tests locally or manually QA these changes more effectively I think I have to push changes file-by-file and lean on the build pipeline to isolate the problem.

Error message running `npm run e2e:release-test` locally:
<img width="893" alt="Screen Shot 2021-03-16 at 20 33 42" src="https://user-images.githubusercontent.com/788415/111397209-1bd41680-8697-11eb-9862-275934169276.png">


(Likely too many) details about my Android Studio AVD configuration:
```
Name: Pixel_4_API_29

CPU/ABI: Google Play Intel Atom (x86)

Path: /Users/phaedrus/.android/avd/Pixel_4_API_29.avd

Target: google_apis_playstore [Google Play] (API level 29)

Skin: pixel_4

SD Card: 512M

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_4

hw.lcd.width: 1080

hw.initialOrientation: Portrait

image.androidVersion.api: 29

tag.id: google_apis_playstore

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: Pixel 4 API 29

hw.gpu.mode: auto

hw.ramSize: 1536

PlayStore.enabled: true

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 2280

vm.heapSize: 256

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images/android-29/google_apis_playstore/x86/

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: Pixel_4_API_29

hw.lcd.density: 440

hw.arc: false

hw.device.hash2: MD5:6b5943207fe196d842659d2e43022e20

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google Play

runtime.network.latency: none

disk.dataPartition.size: 2G

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
```

2021-03-17 05:36 UTC, limpbrains commented
- Ignore DeepScan, if often shows irrelevant errors.
- Unfortunately, you can't run all e2e tests, because some of them requires env secrets. But all of them will run by GitHub actions when you update the PR.
- to run e2e tests you need to have a AVD with name "Pixel_API_29_AOSP". Try to rename your existing "Pixel_4_API_29" or create a new one. There is a script in repo `tests/e2e/detox-prepare-android-emu.sh` that can help you with it.

2021-03-17 05:43 UTC, limpbrains requested changes

2021-03-17 05:43 UTC, limpbrains commented on screen/lnd/lndViewAdditionalInvoiceInformation.js
> +    <SafeBlueArea style={stylesHook.root}>
This will not work. If you provide new styles to `SafeBlueArea` they are not merged with existing, but overlaps them. So here `{flex: 1}` will be lost.

2021-03-17 05:46 UTC, limpbrains commented
Did you manage to run your local copy in developer mode? It will be much more useful than e2e tests.

2021-03-18 01:36 UTC, phrazzld commented on screen/lnd/lndViewAdditionalInvoiceInformation.js
> +    <SafeBlueArea style={stylesHook.root}>
Refactored `SafeBlueArea` implementation to merge styles, should ensure `{ flex: 1, backgroundColor: colors.background }` unless either of those styles are explicitly overridden (most common case appearing to be `backgroundColor: colors.elevated`)

2021-03-18 01:42 UTC, phrazzld commented
@limpbrains thank you for the notes regarding the automated checks. Seems like doing a cursory sanity check locally and then leaning on them ultimately is the way to go.

Didn't run my local copy in developer mode. (I assume you mean for Android Studio?) Will keep that in mind for future changes though.

Tests other than DeepScan are passing. Just curious, what is the utility of DeepScan when it has such a high false positive rate? I imagine there is one I'm not familiar with, or it would be removed from the automated checks.

2021-03-18 06:10 UTC, limpbrains commented on screen/lnd/lndViewAdditionalInvoiceInformation.js
> +    <SafeBlueArea style={stylesHook.root}>
Looks good

2021-03-18 06:24 UTC, limpbrains commented
> Didn't run my local copy in developer mode. (I assume you mean for Android Studio?) Will keep that in mind for future changes though.

I mean android emulator, which is part of Android Studio
`npx react-native start`
`npx react-native run-android`

> Tests other than DeepScan are passing. Just curious, what is the utility of DeepScan when it has such a high false positive rate? I imagine there is one I'm not familiar with, or it would be removed from the automated checks.

It can't correctly handle whatever error is new or old. And shows `1 new and 1 fixed issues`, but still often show correct errors

2021-03-18 06:25 UTC, limpbrains approved these changes

2021-03-18 11:14 UTC, Overtorment approved these changes
lgtm

2021-03-18 11:16 UTC, Overtorment commented
lets run full tests & bulds here: https://github.com/BlueWallet/BlueWallet/pull/2812

2021-03-20 19:38 UTC, Overtorment commented
so whats the verdict? @limpbrains @marcosrdz 
all tests passed in https://github.com/BlueWallet/BlueWallet/pull/2812

2021-03-20 19:51 UTC, limpbrains commented
Approved

2021-03-20 19:57 UTC, marcosrdz approved these changes

2021-03-22 11:54 UTC, merged

2021-03-22 11:54 UTC, Overtorment commented
gj!

2021-03-22 14:04 UTC, phrazzld commented
Woo! Thanks for the help everybody. Looking forward to working some non "good first issue" issues now