ADD: Hierarchy Navigator Screen
BlueWallet/BlueWallet pull request #2837
Opened 2021-03-23 21:16 UTC by jaonoctus

Solves #990

2021-03-26 10:20 UTC, ncoelho commented
Tested, definitely some things missing. I would suggest to not make this a huge PR and effort in general, to break it down by functionality, so one feature doesn't block the other and we can keep working on it as we go. 

For instance, for first release we should aim to:
1. List of addresses
2. Retrieve new addresses
3. Incorporate sign/verify from the other PR

wdyt?

2021-04-02 12:40 UTC, Overtorment commented
i think splitting things in several PRs is a good idea, so we can deliver faster.

just

> List of addresses
> Retrieve new addresses

is good enough for initial release. @jaonoctus maybe you can deliver that in a separate PR so we can review it & merge..?

2021-04-02 12:57 UTC, jaonoctus commented
@Overtorment @ncoelho sure!

2021-04-06 14:36 UTC, limpbrains requested changes
Take a look at package-lock.json it was completely rewritten. It should be removed from PR

Overall it works good, let's merge it!

2021-04-06 14:36 UTC, limpbrains commented on screen/wallets/addresses.js
> +      const singleAddressTypes = ['legacy', 'segwitP2SH', 'segwitBech32'];
please use `LegacyWallet.type` instead of string

2021-04-06 14:36 UTC, limpbrains commented on screen/wallets/addresses.js
> +      const isWatchOnlyHD = wallet.type === 'watchOnly' && wallet._hdWalletInstance !== undefined;
watch-only wallet has `wallet.isHd()` for similar purposes

2021-04-06 17:16 UTC, jaonoctus commented on components/addresses/AddressTypeBadge.js
> +      },
![image](https://user-images.githubusercontent.com/7918067/113751499-62d78980-96e2-11eb-928f-3882b98ecb0e.png)

:sweat_smile: will fix it

2021-04-07 10:36 UTC, ncoelho commented
Can't see the text for change/receive on iOS

<img width="351" alt="Screenshot 2021-04-07 at 12 35 41" src="https://user-images.githubusercontent.com/1238429/113853353-dab6ba00-979d-11eb-9d98-d7ca7f4b2c8a.png">

2021-04-07 19:21 UTC, jaonoctus commented on screen/wallets/addresses.js
> +      const isWatchOnlyHD = wallet.type === 'watchOnly' && wallet._hdWalletInstance !== undefined;
@limpbrains some wallet types return this:

![image](https://user-images.githubusercontent.com/7918067/113921582-90910100-97bc-11eb-9549-72e98f16fb17.png)

- `wallet.type`: `HDsegwitBech32`

2021-04-07 19:28 UTC, limpbrains commented on screen/wallets/addresses.js
> +      const isWatchOnlyHD = wallet.type === 'watchOnly' && wallet._hdWalletInstance !== undefined;
Yeah. This is for watch-only wallet only

2021-04-07 22:25 UTC, jaonoctus commented
## Light mode

![image](https://user-images.githubusercontent.com/7918067/113942034-998ecc00-97d6-11eb-958c-992a927b6dd5.png)

## Dark mode

![image](https://user-images.githubusercontent.com/7918067/113942151-c511b680-97d6-11eb-8b61-523941c63cc0.png)

2021-04-08 13:45 UTC, Overtorment requested changes

2021-04-08 13:45 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.js
> +    const balance = await BlueElectrum.getBalanceByAddress(address);
wrong. user won't expect any network work in hierarchy navigator screen.
balance for each address is in
```
    this._balances_by_external_index = {}; //  0 => { c: 0, u: 0 } // confirmed/unconfirmed
    this._balances_by_internal_index = {};
```

for  HD wallets, or simply `this.getBalance()`  for single-address wallets

2021-04-08 13:45 UTC, Overtorment commented on screen/wallets/addresses.js
> +        if (type === 'receive') {
whats this `'receive'`? looks like a magic constant, which is a bad practice

2021-04-08 13:45 UTC, Overtorment commented on screen/wallets/addresses.js
> +        if (type === 'receive') {
bool would probably be better, just like in derivation path its either 0 or 1 to identify external/internal, so `type` could be renamed to `isInternal` where false indicates receive aka external address, and true indicated change aka internal

2021-04-08 13:45 UTC, Overtorment commented on screen/wallets/addresses.js
> +  const [latestIndex, setLatestIndex] = useState(5);
where this 5 comes from? 
HD wallets have
```
    this.next_free_address_index
    this.next_free_change_address_index
```

so its safe to render all addresses up to those indexes.

there is also `this.gap_limit`, so you can even render all addresses up to `(this.next_free_address_index + this.gap_limit)`, but rendering anything above that will allow user to shoot himself in the foot, as BW wont be able to find transactions/balances for everything above gaplimit. this is btw how HD all wallets work, this is not specific to bluewallet.

2021-04-08 13:45 UTC, Overtorment commented on Navigation.js
> +const WalletAddressesStack = createStackNavigator();
im really bad at this, but... @limpbrains @marcosrdz do we need another navigator for just a single screen?

2021-04-08 13:45 UTC, Overtorment commented on screen/wallets/details.js
> +              {wallet.type !== LightningCustodianWallet.type && (
lets try using  `(wallet instanceof AbstractHDElectrumWallet)` here

2021-04-08 13:45 UTC, Overtorment commented on screen/wallets/details.js
> +        walletId: wallet.getID(),
`walletId` -> `walletID`

2021-04-08 13:46 UTC, marcosrdz commented on Navigation.js
> +const WalletAddressesStack = createStackNavigator();
We do if it is its own modal

2021-04-08 13:52 UTC, Overtorment commented on Navigation.js
> +const WalletAddressesStack = createStackNavigator();
so is it good here?

2021-04-08 13:58 UTC, marcosrdz commented on Navigation.js
> +const WalletAddressesStack = createStackNavigator();
Yup

2021-04-08 22:35 UTC, jaonoctus commented on class/wallets/abstract-hd-electrum-wallet.js
> +    const balance = await BlueElectrum.getBalanceByAddress(address);
@Overtorment `watchOnly` wallet does not have those functions.

```
console.log(wallet._balances_by_external_index); // undefined
console.log(wallet._balances_by_internal_index); // undefined
```

2021-04-08 22:38 UTC, jaonoctus commented on class/wallets/abstract-hd-electrum-wallet.js
> +    const balance = await BlueElectrum.getBalanceByAddress(address);
nvm. 

I can use `wallet._hdWalletInstance._balances_by_external_index` instead.

2021-04-08 23:12 UTC, jaonoctus commented on screen/wallets/details.js
> +              {wallet.type !== LightningCustodianWallet.type && (
will not work for `[LegacyWallet.type, SegwitP2SHWallet.type, SegwitBech32Wallet.type]`

2021-04-09 15:45 UTC, Overtorment commented on screen/wallets/details.js
> +              {wallet.type !== LightningCustodianWallet.type && (
but do they need address explorer tho? those are single-address wallets

2021-04-09 15:55 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.js
> +    const balance = await BlueElectrum.getBalanceByAddress(address);
btw its a good idea to create a getter method for those, so internal representation is concealed from outer code.
watchOnly class already has some getters that pass-through calls to internal `wallet._hdWalletInstance` if needed

2021-04-09 15:58 UTC, jaonoctus commented on screen/wallets/details.js
> +              {wallet.type !== LightningCustodianWallet.type && (
For upcoming features. `Sign/Verify` will be moved to this screen, for example.

That said, what about `wallet instanceof AbstractHDElectrumWallet || wallet instanceof LegacyWallet`?

2021-04-09 16:06 UTC, Overtorment commented on screen/wallets/details.js
> +              {wallet.type !== LightningCustodianWallet.type && (
hmm. id prefer for single-address wallets to have a separate sign/verify button on walletDetails screen.
address explorer is a feature that is specific to HD wallets, and it would require a bunch of ugly code hacks to make this screen work with single-address wallets.
anyway, don't worry about it too much, industry consensus is that single-address wallets are deprecated.

btw `wallet instanceof AbstractHDElectrumWallet || wallet instanceof LegacyWallet` makes no sense, our hierarchy is not very well thought through,  `AbstractHDElectrumWallet` is a direct descendant of `LegacyWallet`

2021-04-09 19:15 UTC, jaonoctus commented on screen/wallets/addresses.js
> +  const [latestIndex, setLatestIndex] = useState(5);
Initially only 5 receiving (external) and 5 change (internal) addresses will be rendered.

And when the user clicks on the "load more" btn, 5 more addresses of each will be added to the list.

Its an arbitrary value, tho

2021-04-10 00:39 UTC, marcosrdz requested changes

2021-04-10 00:39 UTC, marcosrdz commented on components/addresses/AddressItem.js
> +            {loc.formatString(loc.addresses.address_balance, { balance: item.balance })}
Use formatBalance

2021-04-10 00:39 UTC, marcosrdz commented on screen/wallets/addresses.js
> +    }
npm run lint:fix

2021-04-10 20:14 UTC, Overtorment requested changes

2021-04-10 20:14 UTC, Overtorment commented on screen/wallets/addresses.js
> +    balance = getAllBalance(wallet._balances_by_internal_index[index]);
will not work for watch-only. i sugggest making a wrapper gettet function, similar to `WatchOnlyWallet._getInternalAddressByIndex()`

2021-04-10 20:14 UTC, Overtorment commented on screen/wallets/addresses.js
> +const fetchAddress = ({ wallet, index, isInternal }) => {
i personally not a fan of passing arguments to function as object.
traditional arguments work just fine, and any modern IDE typehints and autocomplete etc

also pls rename `fetchAddress` to smth like `getAddress`, historically we use "fetch" for something that does async network work

2021-04-10 23:11 UTC, jaonoctus commented on screen/wallets/addresses.js
> +    balance = getAllBalance(wallet._balances_by_internal_index[index]);
@Overtorment it is working, actually.

https://github.com/BlueWallet/BlueWallet/blob/f605fb04cd914627d0bd22fe0212c59e5c15dfc1/screen/wallets/addresses.js#L79

2021-04-10 23:15 UTC, jaonoctus commented on screen/wallets/addresses.js
> +const fetchAddress = ({ wallet, index, isInternal }) => {
The `fetch..` name is because I was making async calls before. Forgot to rename it after the refactor

2021-04-13 14:14 UTC, Overtorment commented
running tests here https://github.com/BlueWallet/BlueWallet/pull/2954

2021-04-13 17:15 UTC, Overtorment approved these changes
tests pass. lgtm. 
@marcosrdz @limpbrains your move

2021-04-13 18:15 UTC, marcosrdz commented on components/addresses/AddressTypeBadge.js
> +import { Badge } from 'react-native-elements';
Some devices fail to render the text with this RN Elements badge component. Look at electrumSettings.js for a similar implementation

2021-04-13 18:18 UTC, marcosrdz commented on screen/wallets/addresses.js
> +      return <FlatList data={addresses} renderItem={item => <AddressItem {...item} balanceUnit={balanceUnit} />} />;
Add content container style with background color.

2021-04-13 18:18 UTC, marcosrdz requested changes

2021-04-13 18:18 UTC, marcosrdz commented on screen/wallets/addresses.js
> +      <View style={styles.loading}>
Add  style with background color.

2021-04-13 18:25 UTC, jaonoctus commented on components/addresses/AddressTypeBadge.js
> +import { Badge } from 'react-native-elements';
@marcosrdz i'm using it as it is on the coin control screen.

https://github.com/BlueWallet/BlueWallet/blob/ac0c6eed549888e5fc54f29e756d58766ecc35cf/screen/send/coinControl.js#L3

https://github.com/BlueWallet/BlueWallet/blob/ac0c6eed549888e5fc54f29e756d58766ecc35cf/screen/send/coinControl.js#L43-L50

2021-04-13 18:26 UTC, jaonoctus commented on components/addresses/AddressTypeBadge.js
> +import { Badge } from 'react-native-elements';
So I need to change it to something like this, right?

https://github.com/BlueWallet/BlueWallet/blob/ac0c6eed549888e5fc54f29e756d58766ecc35cf/screen/settings/electrumSettings.js#L223-L227

2021-04-13 19:36 UTC, marcosrdz commented on components/addresses/AddressTypeBadge.js
> +import { Badge } from 'react-native-elements';
Yup. Some OnePlus devices have custom fonts that prohibitS that Badge component from rendering reliably. A workaround is to just use a view and give it a border radius

2021-04-13 19:38 UTC, marcosrdz commented on components/addresses/AddressTypeBadge.js
> +import { Badge } from 'react-native-elements';
<img width="391" alt="Screen Shot 2021-04-13 at 3 38 34 PM" src="https://user-images.githubusercontent.com/4793122/114610801-5026fc80-9c6e-11eb-9c3b-6dd3d4e8449a.png">


Example

2021-04-14 14:35 UTC, limpbrains commented
@jaonoctus better way to truncate text for addresses list #2959

2021-04-14 17:01 UTC, limpbrains approved these changes
Need to start work on the next version and implement all the missing features from original issue

2021-04-14 17:10 UTC, jaonoctus commented
@limpbrains surething!

2021-04-14 17:15 UTC, jaonoctus commented on screen/wallets/addresses.js
> +      return <FlatList data={addresses} renderItem={item => <AddressItem {...item} balanceUnit={balanceUnit} />} />;
What bg color?

2021-04-15 13:01 UTC, Overtorment commented
@marcosrdz verdict..?

2021-04-15 13:01 UTC, marcosrdz approved these changes

2021-04-15 13:04 UTC, Overtorment commented
is it still WIP..?

2021-04-15 13:05 UTC, ncoelho commented
Just polishing some details and styling. Or just merge and I will do that on from master

2021-04-15 13:07 UTC, merged