add support for USD pegged currencies ANG AWG
BlueWallet/BlueWallet pull request #2850
Opened 2021-03-25 16:10 UTC by pointbiz

The Caribbean has many currencies pegged to the USD. I'm adding support specifically for two Dutch Caribbean currencies ANG and AWG. I'm promoting the use of BlueWallet heavily in Curacao and it's much easier mentally for retailers and consumers to think in terms of florins than USD.

You can see the fixed rate of 1.79 for both currencies on Wikipedia.
https://en.wikipedia.org/wiki/Netherlands_Antillean_guilder
https://en.wikipedia.org/wiki/Aruban_florin

2021-03-25 16:17 UTC, marcosrdz commented
Needs to be applied to FiatUnits.plist and FiatUnit.swift

2021-03-25 17:09 UTC, pointbiz commented
OK. I updated the FiatUnits.plist to make "rateKey" mandatory so there is a unique key now that pegged currencies rely on USD for the endPointKey. The dictionary structure is different in swift from JS so I had to make that change.

I updated FiatUnit.swift to put a new condition for the pegged currencies but I'm not familiar with swift and not confident in my syntax.

I also modified the lambda query to search on rateKey instead of endPointKey because rateKey is unique.

I'm nervous that the file using FiatUnit.swift for selecting a new preferred currency needs to look at rateKey instead of endPointKey but I couldn't find anywhere that needed that change.

2021-03-26 01:04 UTC, marcosrdz requested changes

2021-03-26 01:04 UTC, marcosrdz commented on ios/WalletInformationWidget/Widgets/Shared/Fiat/FiatUnit.swift
> +  } else if fixedRate != nil {
Use let fixedRate = fixedRate

2021-03-26 01:04 UTC, marcosrdz commented on ios/WalletInformationWidget/Widgets/Shared/Fiat/FiatUnit.swift
>      guard let rateKey = rateKey, let rateDict = json[rateKey] as? [String: Any], let rateDouble = rateDict["price"] as? Double, let lastUpdated = json["timestamp"] as? Int else {
Compiler throwing error here

2021-03-26 16:55 UTC, pointbiz commented on ios/WalletInformationWidget/Widgets/Shared/Fiat/FiatUnit.swift
> +  } else if fixedRate != nil {
OK. I see let returns nil or not nil. I've made the change as you specified.

2021-03-26 16:55 UTC, pointbiz commented on ios/WalletInformationWidget/Widgets/Shared/Fiat/FiatUnit.swift
>      guard let rateKey = rateKey, let rateDict = json[rateKey] as? [String: Any], let rateDouble = rateDict["price"] as? Double, let lastUpdated = json["timestamp"] as? Int else {
OK. I misunderstood guard. I see all the statements must return booleans. I've fixed it.

2021-03-29 12:51 UTC, limpbrains commented
@pointbiz 
Sorry, I don't see why you need to add extra logic for these currencies. Both ANG and AWG are supported by coindesk API. You can just add them to the list and that is all.

2021-03-29 16:31 UTC, limpbrains commented
I've added ANG and AWG in #2857

2021-03-29 17:08 UTC, pointbiz commented
> I've added ANG and AWG in #2857

I didn't realize Coindesk supported those 2 currencies. So, the extra logic doesn't make sense now that I know that. 

@limpbrains  Thank you! Please post your donation address, so I can thank you that way too. 

I'll close this PR soon.

2021-03-29 17:33 UTC, limpbrains commented
> @limpbrains Thank you! Please post your donation address, so I can thank you that way too.
> 
`bc1q7xpn77t9l0c2tgjfsq82kv3y5g3569s6j5p8zc` thanks !

2021-03-29 17:57 UTC, closed without merging