ADD: SLIP39 wallet and unit tests
BlueWallet/BlueWallet pull request #2899
Opened 2021-04-02 15:58 UTC by limpbrains

2021-04-06 13:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8g2dn176z5jhgn0aymrnqt7uvr

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1617717043.apk)

2021-04-08 17:45 UTC, Overtorment requested changes

2021-04-08 17:45 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.js
> +  static seedToFingerprint(seed) { // TODO
something is not finished here..?

2021-04-08 17:45 UTC, Overtorment commented on class/wallets/abstract-hd-wallet.js
> +    const seed = bip39.mnemonicToSeed(mnemonic);
redundant declaration

2021-04-08 17:45 UTC, Overtorment commented on class/wallets/abstract-wallet.js
> +  allowXPub() {
`s/allowXPub/allowXpub`

2021-04-08 17:45 UTC, Overtorment commented on class/wallets/hd-aezeed-wallet.js
> +  allowXPub() {
looks like you only need to return false in `abstract-wallet.js` and return true in `abstract-hd-electrum-wallet.js`

2021-04-08 17:45 UTC, Overtorment commented on class/wallets/slip39-wallets.js
> +    const seed = Buffer.from(master);
redundant declaration

2021-04-08 17:45 UTC, Overtorment commented on class/wallets/slip39-wallets.js
> +  _getSeed = SLIP39Mixin._getSeed;
ok thats smart. traits in js

2021-04-08 17:45 UTC, Overtorment commented on package.json
> +    "react-native-crypto": "2.2.0",
im almost onboard with this and removing blue modules crypto, but i need to do some experiments on this first

2021-04-08 17:45 UTC, Overtorment commented on screen/wallets/details.js
> -              {(wallet.type === HDLegacyBreadwalletWallet.type ||
hmm, why the list is so small? should include at least electrum seed format as well

2021-04-08 17:45 UTC, Overtorment commented on tests/unit/slip39-wallets.test.js
> +});
do you have an empty SSS wallet..? adding a testcase to `tests/integration/import.test.js` wouldn't hurt

2021-04-08 17:45 UTC, Overtorment commented on package.json
> +    "postinstall": "rn-nodeify --install buffer,events,process,stream,util,inherits,fs,path,assert,crypto --hack; npm run releasenotes2json; npm run podinstall; npx jetify",
feels like `shim.js` should be committed as well

2021-04-08 18:31 UTC, Overtorment commented
also, whats wrong with e2e and appetize..?

2021-04-09 13:50 UTC, limpbrains commented on class/wallets/abstract-hd-wallet.js
> +    const seed = bip39.mnemonicToSeed(mnemonic);
No, it is different for BIP39 and for SLI39 wallets

2021-04-09 13:50 UTC, limpbrains commented on class/wallets/slip39-wallets.js
> +    const seed = Buffer.from(master);
No, it is different for BIP39 and for SLI39 wallets

2021-04-09 13:53 UTC, limpbrains commented on class/wallets/hd-aezeed-wallet.js
> +  allowXPub() {
I like the way it is now. Not a single `allow` in `abstract-hd-electrum-wallet.js`, all `allow` are explicitly for specific wallet types, not in general classes

2021-04-09 13:59 UTC, limpbrains commented on package.json
> +    "postinstall": "rn-nodeify --install buffer,events,process,stream,util,inherits,fs,path,assert,crypto --hack; npm run releasenotes2json; npm run podinstall; npx jetify",
It wasn't changed, maybe I'm missing something?

2021-04-09 14:00 UTC, limpbrains commented on class/wallets/abstract-wallet.js
> +  allowXPub() {
fixed

2021-04-09 14:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mma5fn912hnp2cr6yrvnky4p60

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1617977760.apk)

2021-04-09 14:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/eek2xp62we80f2mkv5ufny5ngr

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1617980354.apk)

2021-04-09 15:27 UTC, Overtorment commented on package.json
> +    "postinstall": "rn-nodeify --install buffer,events,process,stream,util,inherits,fs,path,assert,crypto --hack; npm run releasenotes2json; npm run podinstall; npx jetify",
iirc after you change postinstall script rn-nodeify creates/modifyes shim.js.
check out its logs, sometimes it writes to console that it could not modify shim.js because of smth and that has to be done manually.
my memory is blurry here, last time i messed with it was 2 years ago

2021-04-09 15:28 UTC, Overtorment commented on class/wallets/slip39-wallets.js
> +    const seed = Buffer.from(master);
whats redundant is:

```
const seed = Buffer.from(master);
return seed;
```

could be 

```
return Buffer.from(master);
```

not a deal breaker tho

2021-04-09 15:42 UTC, Overtorment requested changes
appetize/e2e still crash on launch

2021-04-09 15:42 UTC, Overtorment commented on class/app-storage.js
> +  SLIP39SegwitP2SHWallet,
btw, we have colors for each wallet (`class/wallet-gradient.js`)
i assume for SLIP39 wallets colors should be the same as for their class parents..?

2021-04-09 15:42 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.js
> +   * @param seed {string} Mnemonic seed phrase
is this correct..?
i think instead of {string} it should be `@param seed {Buffer} Buffer object with seed`

2021-04-11 08:43 UTC, limpbrains commented on class/wallets/abstract-hd-wallet.js
> +    const seed = bip39.mnemonicToSeed(mnemonic);
fixed

2021-04-11 08:44 UTC, limpbrains commented on class/wallets/slip39-wallets.js
> +    const seed = Buffer.from(master);
fixed, let's reduce entropy in this world

2021-04-11 08:47 UTC, limpbrains commented on class/app-storage.js
> +  SLIP39SegwitP2SHWallet,
fixed

2021-04-11 08:48 UTC, limpbrains commented on class/wallets/abstract-hd-electrum-wallet.js
> +   * @param seed {string} Mnemonic seed phrase
fixed

2021-04-11 08:49 UTC, limpbrains commented on tests/unit/slip39-wallets.test.js
> +});
Added tests

2021-04-11 08:51 UTC, limpbrains commented on screen/wallets/details.js
> -              {(wallet.type === HDLegacyBreadwalletWallet.type ||
will work on this in #2941

2021-04-11 09:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dw6vnmkqtc16534hua7r0cqfnr

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1618132876.apk)

2021-04-11 18:32 UTC, limpbrains commented
> appetize/e2e still crash on launch

Apparently, slip39 depends on `BigInt`. It is available in RN on iOS, but not on Android.

I've moved slip39 lib to blue_modules, now Babel transpiles it and because of `@babel/plugin-syntax-bigint` it work.

But now tests are failing.

I think I'm going to fork slip39, replace `BigInt` with `bignumber.js`.

2021-04-13 12:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ggmf14ajx4dp0rgm5dkkdb2kzm

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1618317288.apk)

2021-04-13 14:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wveg48rrjtr0h1wmrzta6mx57r

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1618324774.apk)

2021-04-13 17:18 UTC, Overtorment commented
moving it to `blue_modules` and doing all the patches there is a solid way to go.
you could even add unit tests to test specifically slip39 - to make sure it works. and even add it to selftest page to check it in runtime

2021-04-13 17:22 UTC, Overtorment commented
e2e still fails btw

2021-04-14 12:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/833x0mqux5un9yzwmxxep9fj9c

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1618404583.apk)

2021-04-14 13:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x9wfb1qacwy621axv4uerv9bj0

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1618406205.apk)

2021-04-14 13:29 UTC, limpbrains commented
I don't think I should change original src of slip39 to pass DeepScan or LGTM bot.

With all changes that I've made to slip39 it now doesn't require full `crypto` support. I can rollback `react-native-crypto` thing, or should we keep it ?

2021-04-14 13:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ntkubz25zkx5566u5wu2qfa5e8

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1618407453.apk)

2021-04-15 13:14 UTC, Overtorment commented
what does your heart tell you? lets give `react-native-crypto` a chance?

ps. conflicts

2021-04-15 18:01 UTC, limpbrains commented
> what does your heart tell you? lets give `react-native-crypto` a chance?

Yes, let's keep it

2021-04-15 18:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zuu0uryb27k5kf1tf30vxtmxc8

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1618511123.apk)

2021-04-19 10:30 UTC, Overtorment commented
conflicts

2021-04-19 16:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/a9j20kn13yfc2ecwdk99maugr4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1618849226.apk)

2021-04-28 11:56 UTC, Overtorment approved these changes

2021-04-28 11:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j45tvu2cbu6q9f63wb0g2erff8?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1619610988.apk)

2021-04-28 14:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/66rpxhq0q6f9b9nkweuh7bzk2g?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sss-1619620873.apk)

2021-04-28 15:32 UTC, merged

2021-04-28 15:32 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!