FIX: Check Bech32 uppercase address
BlueWallet/BlueWallet pull request #2911
Opened 2021-04-04 19:02 UTC by jaonoctus

Fix #2910 

![image](https://user-images.githubusercontent.com/7918067/113518827-0dbf3a80-955f-11eb-8dc0-60f6bcd6378d.png)

2021-04-05 09:30 UTC, limpbrains approved these changes

2021-04-05 11:39 UTC, marcosrdz approved these changes

2021-04-05 13:04 UTC, Overtorment requested changes
also, missing basic unit tests, for both bech32 HD (BIP84 & aezeed) and bech32 single-address

2021-04-05 13:04 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.js
> +    if (this.type === 'HDsegwitBech32') {
its better to check for  `this.segwitType === 'p2wpkh'`. to great solution, but its a bit more reliable constant.


a bit similar how its done in `sign/verify` functionality:

```
signMessage(message, address) {
    const wif = this._getWIFbyAddress(address);
    if (wif === null) throw new Error('Invalid address');
    const keyPair = bitcoin.ECPair.fromWIF(wif);
    const privateKey = keyPair.privateKey;
    const options = this.segwitType ? { segwitType: this.segwitType } : undefined;
```

2021-04-05 13:04 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.js
>    }
same change is needed for single-address wallets: `LegacyWallet.weOwnAddress()`

2021-05-19 12:28 UTC, limpbrains approved these changes

2021-05-19 15:52 UTC, merged