ADD: AOPP
BlueWallet/BlueWallet pull request #2915
Opened 2021-04-05 16:25 UTC by limpbrains

2021-04-05 16:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2hz84zme6796j1xn8681u7ddj8

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-aopp-1617641005.apk)

2021-04-05 17:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n903umayme5r019xj2twgun6vr

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-aopp-1617645394.apk)

2021-04-05 18:28 UTC, lclc commented on tests/integration/aopp.test.js
> +      'aopp:?v=0&msg=I+confirm+that+this+Bitcoin+%28BTC%29+address+is+controlled+by+Mary+Lewis%2C+Poststrasse+22%2C+Zug%2C+Switzerland.+Unique+Identifier%3A+8a85f9623bbb172b&asset=btc&format=any&call
Please use testing.21analytics.ch instead, thanks!

`https%3A%2F%2Ftesting.21analytics.ch%2Fproofs%2Fb4d5f518-315c-4360-9f18-d90beab5b2e9`

`'aopp:?v=0&msg=I+confirm+that+this+Bitcoin+%28BTC%29+address+is+controlled+by+Mary+Lewis%2C+Poststrasse+22%2C+Zug%2C+Switzerland.+Unique+Identifier%3A+8a85f9623bbb172b&asset=btc&format=any&callback=https%3A%2F%2Ftesting.21analytics.ch%2Fproofs%2Fb4d5f518-315c-4360-9f18-d90beab5b2e9',`

2021-04-06 08:55 UTC, lclc commented on tests/integration/aopp.test.js
> +  // these tests depends on unstable https://testing.aopp.group/ so we don't want to run chem all the time
Small detail but they depend on https://testing.21analytics.ch/.   

https://testing.aopp.group/ is just a static webpage delivered by GitLab pages.

2021-04-06 09:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4czxgxpmgkqzggpbq60avkcg74

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-aopp-1617699634.apk)

2021-04-06 11:07 UTC, limpbrains commented on tests/integration/aopp.test.js
> +  // these tests depends on unstable https://testing.aopp.group/ so we don't want to run chem all the time
Noted

2021-04-06 11:07 UTC, limpbrains commented on tests/integration/aopp.test.js
> +      'aopp:?v=0&msg=I+confirm+that+this+Bitcoin+%28BTC%29+address+is+controlled+by+Mary+Lewis%2C+Poststrasse+22%2C+Zug%2C+Switzerland.+Unique+Identifier%3A+8a85f9623bbb172b&asset=btc&format=any&call
Fixed

2021-04-06 11:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q1d9fma18h112vezbcu2epezqr

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-aopp-1617708834.apk)

2021-04-06 20:58 UTC, lclc commented
Two tiny things:

1. The title "SelectWallet" should probably be "Select Wallet"
2. The other title "Select address" should probably also be TitleCase like the rest of the Window titles -> "Select Address"

2021-04-07 15:47 UTC, limpbrains commented
> Two tiny things:
> 
>     1. The title "SelectWallet" should probably be "Select Wallet"
> 
>     2. The other title "Select address" should probably also be TitleCase like the rest of the Window titles -> "Select Address"

fixed, thanks for testing!

2021-04-07 20:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hjy1mywwrhypuea9jcfaham210

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-aopp-1617829076.apk)

2021-04-08 11:08 UTC, toxeus commented on screen/wallets/signVerify.js
>        const newSignature = wallet.signMessage(message, address);
IIUC to make this work with AOPP segwit signatures the `options` variable needs to be set to `undefined`
https://github.com/BlueWallet/BlueWallet/blob/4b7081ccb6b47ce353c47c4a355914bdbafd2c3a/class/wallets/legacy-wallet.js#L516
as described in https://github.com/bitcoinjs/bitcoinjs-message#about-electrum-segwit-signature-support

2021-04-09 15:30 UTC, limpbrains commented on screen/wallets/signVerify.js
>        const newSignature = wallet.signMessage(message, address);
Correct. But I'm not sure what type of signature should BlueWallet generate by default.
I think since we are using `bitcoinjs-message` we should stick with their defaults.
Anyway to increase AOPP adoption, you need to try both variants on a backend.

2021-04-09 16:28 UTC, toxeus commented on screen/wallets/signVerify.js
>        const newSignature = wallet.signMessage(message, address);
The "electrum signature type" is the one bitcoin core [uses too](https://github.com/bitcoinjs/bitcoinjs-message/pull/29#issuecomment-686063300). So currently, BlueWallet signatures are not compatible with bitcoin core's. 

I read that trezor supports both signature types by now because they wanted to be compatible with bitcoin core. Which means that everyone is supporting "electrum signature types" but not the trezor one.

Because AOPP is brand new I would really like to keep this ambiguity out of the protocol and just stick with the "electrum signature types". I hope that you can see the value of having a clean protocol. I'm aware that the spec is not clear on that but I'm happy to propose a commit for that.

(I'm using "electrum signature types" here to be consistent with the `bticoinjs-message` terminology. To me, those are just bitcoin core message signatures)

2021-04-09 20:40 UTC, Overtorment requested changes

2021-04-09 20:40 UTC, Overtorment commented on screen/wallets/aopp.js
> +    navigation.navigate('SelectWalletAOPP', {
can you plz port `helpers/select-wallet.js` from https://github.com/BlueWallet/BlueWallet/pull/2615 instead ? 
i thought we deliver this lnd branch faster, but apparently not.

2021-04-09 20:40 UTC, Overtorment commented on screen/wallets/signVerify.js
>        const newSignature = wallet.signMessage(message, address);
@limpbrains maybe we should introduce "electrum/bitcoincore compatible format" checkbox on sign/verify screen so user could choose..? and ofcourse when signature is requested by aopp - only produce aopp compatible signature (don't even show the checkbox)

2021-04-09 20:40 UTC, Overtorment commented on screen/wallets/signVerify.js
> +        const aopp = new AOPP(params.aoppURI);
maybe lets ask user's confirmation on this?
`helpers/confirm.js`  from https://github.com/BlueWallet/BlueWallet/pull/2615

posting data to 3rd party server is a dangerous aperation.

2021-04-09 20:40 UTC, Overtorment commented on screen/wallets/aopp.js
> +    navigation.navigate('SignVerify', {
why navigate to signVerify when we have the wallet, we have the address, we could sign right on the spot? no changes to `screen/wallets/signVerify.js ` necessary

2021-04-09 20:40 UTC, Overtorment commented on screen/wallets/aopp.js
> +    const addresses = wallet.getAllExternalAddresses();
a suggestion: we could just choose an address, use `getAddressAsync()`. that would be next free address,  user would not have to even think about it.
aopp is for receive only, right..? so user would not be able to potentially reuse address.
this screen would become simpler.

2021-04-09 20:40 UTC, Overtorment commented on tests/integration/aopp.test.js
> +});
noice. i love tests

2021-04-09 20:41 UTC, Overtorment commented
i missed this when reading the spec. is there a scenario when server already knows our address, and we just need to find appropriate wallet that owns this address and do the signature with it..?

2021-04-11 18:40 UTC, toxeus commented
@Overtorment wrote:
> i missed this when reading the spec. is there a scenario when server already knows our address, and we just need to find appropriate wallet that owns this address and do the signature with it..?

@limpbrains had some [interesting ideas](https://github.com/BlueWallet/BlueWallet/issues/2861#issuecomment-814025887) for such scenarios that I think are worthwhile taking a closer look. However, for the initial version the goal is to have a narrow scope such that the effort is minimized on the wallet side to allow for quick adoption. Hence, those scenarios are candidates for an upcoming version.

2021-04-12 13:00 UTC, limpbrains commented on screen/wallets/aopp.js
> +    navigation.navigate('SignVerify', {
Because we need to show user what is he actually signing.

2021-04-12 13:42 UTC, limpbrains commented on screen/wallets/aopp.js
> +    navigation.navigate('SelectWalletAOPP', {
done

2021-04-12 14:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/30tvadjkh04pk3hz70bggvbqxc

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-aopp-1618236132.apk)

2021-04-12 14:05 UTC, limpbrains commented on screen/wallets/signVerify.js
> +        const aopp = new AOPP(params.aoppURI);
Agree, done

2021-04-12 14:20 UTC, limpbrains commented on screen/wallets/signVerify.js
>        const newSignature = wallet.signMessage(message, address);
@Overtorment 
I feel like we should switch to "electrum" format by default.
what do you think ?

2021-04-12 14:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d7jp6jczy5yjz87r9pcntyt8xm

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-aopp-1618237404.apk)

2021-04-12 15:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7jumhuhvrbh3cqx2hh6ycmfk40

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-aopp-1618242361.apk)

2021-04-14 13:32 UTC, limpbrains commented
Let's merge it.

2021-04-15 13:21 UTC, Overtorment commented on screen/wallets/aopp.js
> +    navigation.navigate('SignVerify', {
"I like cocks"

2021-04-15 13:23 UTC, Overtorment commented on screen/wallets/signVerify.js
>        const newSignature = wallet.signMessage(message, address);
@limpbrains whatever you feel is right, I'm not good with sign/verify topic. id say default should be whats the majority of software supports..?

2021-04-15 13:28 UTC, Overtorment requested changes
mostly lgtm. just conflicts

2021-04-15 13:28 UTC, Overtorment commented on screen/wallets/aopp.js
> +          case 'p2wpkh':
btw, this could be a static constant in `AOPPClient`

2021-04-15 13:28 UTC, Overtorment commented on screen/wallets/aopp.js
> +          case 'p2wpkh':
or whole switch-case handled by `AOPPClient`. and unit tested

2021-04-15 17:46 UTC, limpbrains commented on screen/wallets/aopp.js
> +          case 'p2wpkh':
fixed

2021-04-15 18:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0f3z34g1d6cc52n8xdbkhu6xcw

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-aopp-1618510008.apk)

2021-04-17 12:17 UTC, merged