REF: Android file save
BlueWallet/BlueWallet pull request #3090
Opened 2021-05-05 03:08 UTC by marcosrdz

2021-05-05 03:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2wrkfdwdc52jvvkt1q7mehv7uw?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/filesaveandroid-1620185189.apk)

2021-05-05 03:38 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/41xmxngay4m2jpvq7wjfkft63m?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/filesaveandroid-1620185916.apk)

2021-05-05 06:35 UTC, limpbrains requested changes
Also `loc.send.permission_storage_denied_message` ?

2021-05-05 06:35 UTC, limpbrains commented on blue_modules/fs.js
> -      buttonNeutral: loc.send.permission_storage_later,
I guess these locale strings are no longer needed and can be removed from `en.json` ?

2021-05-05 06:35 UTC, limpbrains commented on blue_modules/fs.js
> -      buttonNeutral: loc.send.permission_storage_later,
Also `loc.send.permission_storage_denied_message`

2021-05-05 10:11 UTC, Overtorment approved these changes
lgtm

2021-05-05 13:44 UTC, limpbrains approved these changes

2021-05-05 13:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k6n1vymzgjrnkk8xu772g756x8?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/filesaveandroid-1620222334.apk)

2021-05-09 13:46 UTC, Overtorment commented
@marcosrdz conflicts

2021-05-09 13:49 UTC, marcosrdz commented
> @marcosrdz conflicts

fixed

2021-05-09 14:06 UTC, Overtorment commented
aaaaaand now all the tests failed

2021-05-11 14:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cvc5ge0bg4fdaw0tzu3hqnyu1r?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/filesaveandroid-1620742915.apk)

2021-07-24 09:45 UTC, Overtorment commented
this was never approved by @ncoelho so it never got merged and now it has conflicts.
a good example of forgotten PR @marcosrdz

2021-07-24 12:50 UTC, closed without merging

2021-07-24 12:51 UTC, marcosrdz commented
RN Document Picker recently included folder selection for Android. I have a local branch using this approach in preference to this approach