Upgrade eslint and all plugins
BlueWallet/BlueWallet pull request #3109
Opened 2021-05-06 13:43 UTC by limpbrains

- upgrade eslint and plugins
- upgrade flow-bin. Do we need it? Can I remove it?
- move them to dev dependencies
- review eslint config
- fix new reported errors

2021-05-06 13:55 UTC, limpbrains commented on screen/send/confirm.js
>    }
@Overtorment 
please, review here

2021-05-06 14:58 UTC, Overtorment commented on screen/send/confirm.js
>    }
hmm, maybe I used a cycle here just to play it safe. r u sure you want this change?

2021-05-06 15:24 UTC, Overtorment requested changes
mostly lgtm

2021-05-06 15:24 UTC, Overtorment commented on screen/lnd/browser.js
> +    const id = Math.random();
`this code has no use in RN, it gets copypasted in webview injected code`

2021-05-06 15:24 UTC, Overtorment commented on screen/lnd/browser.js
> +    const id = Math.random();
if you decide to fix it on line 131 as well don't forget to check that lapp browser is working and injecting everything correctly

2021-05-06 15:28 UTC, Overtorment commented
i thought we cannot get rid of `flow` because its hardwired or smth..? @marcosrdz can you clarify on this one?
if we can throw it away - lets do it.


and if we start messing with lint config... how about increasing print width and reformatting the whole project..? in a separate or of course.
i have `"printWidth": 230` in GroundControl repo and it looks pretty nice

2021-05-07 05:56 UTC, limpbrains commented on screen/send/confirm.js
>    }
Without it eslint shows `Invalid loop. Its body allows only one iterations` error.
I think this is ok, since there is check for empty `recipients` list in componentDidMount
```js
if (!this.state.recipients || !this.state.recipients.length) alert('Internal error: recipients list empty (this should never happen)');
```

2021-05-07 06:01 UTC, limpbrains commented on screen/lnd/browser.js
> +    const id = Math.random();
reverted

2021-05-07 06:05 UTC, limpbrains commented
> and if we start messing with lint config... how about increasing print width and reformatting the whole project..? in a separate or of course.
> i have `"printWidth": 230` in GroundControl repo and it looks pretty nice

I don't really like this idea. It is already hard to work with the code on a laptop without external monitor :)

2021-05-07 06:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k826cf4nbxfagdxj0jjfyap3a0?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-eslint-1620368419.apk)

2021-05-07 10:03 UTC, Overtorment commented
> > and if we start messing with lint config... how about increasing print width and reformatting the whole project..? in a separate or of course.
> > i have `"printWidth": 230` in GroundControl repo and it looks pretty nice
> 
> Personally I don't really like this idea. It is already hard to work with the code on a laptop without external monitor :)

weird. i got 1920x1080 on my Linux laptop, and working with groundcontrol repo feels nice. can you just try checking out that repo to see how it feels? maybe its not that bad

2021-05-07 10:04 UTC, Overtorment requested changes
conflicts. otherwise lgtm

2021-05-08 06:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wn8dnk17bqk2077nk72rj4eqxg?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-eslint-1620456912.apk)

2021-05-08 10:51 UTC, Overtorment approved these changes

2021-05-08 11:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dtbzd9bbz5azm9pt6f420426d4?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-eslint-1620471841.apk)

2021-05-08 15:15 UTC, marcosrdz approved these changes

2021-05-08 15:15 UTC, merged

2021-05-08 15:15 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!