ADD: add passphrase support to wallets
BlueWallet/BlueWallet pull request #3157
Opened 2021-05-14 16:22 UTC by limpbrains

Questions: 
- do I need to refactor `HDAezeedWallet` to store password as other hd wallets, in this.passphrase? I don't like the idea to store passphrase in the same string, divided by colon.
- could wallets with passphrase be used in Multisig?

2021-05-14 16:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mv60juggct26rkh6405fj1a07r?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-passphrase-1621010345.apk)

2021-05-17 19:29 UTC, jaonoctus approved these changes
tACK

```
HDLegacyElectrumSeedP2PKHWallet
    ✓ can use mnemonic with passphrase (4 ms)
Legacy HD (BIP44)
    ✓ can use mnemonic with passphrase (4 ms)
Bech32 Segwit HD (BIP84)
    ✓ can use mnemonic with passphrase (6 ms)
HDSegwitElectrumSeedP2WPKHWallet
    ✓ can use mnemonic with passphrase (6 ms)
P2SH Segwit HD (BIP49)
    ✓ can use mnemonic with passphrase (4 ms)
SLIP39 wallets tests
    ✓ SLIP39LegacyP2PKHWallet can use passphrase (15 ms)
    ✓ SLIP39SegwitP2SHWallet can use passphrase (7 ms)
    ✓ SLIP39SegwitBech32Wallet can use passphrase (8 ms)
```

2021-05-17 19:32 UTC, jaonoctus commented
@limpbrains  will you include the `setPassphrase` function on the [import screen](https://github.com/BlueWallet/BlueWallet/blob/44522b45af4f1850cb7e85d0d634075ae905d8cd/screen/wallets/import.js) later?

2021-05-18 17:33 UTC, limpbrains commented
> @limpbrains will you include the `setPassphrase` function on the [import screen](https://github.com/BlueWallet/BlueWallet/blob/44522b45af4f1850cb7e85d0d634075ae905d8cd/screen/wallets/import.js) later?

Yes I will in another PR. This one is just a draft to discuss wallets and API.
@Overtorment plz take a look

2021-07-06 18:27 UTC, Overtorment commented
sorry for the delay!
okay, Im conceptualy onboard with the change, and storing passphrase in a separate field. lets refactor aezeed to work the same way.

as for multisig, I've never seen an option to have passwords for cosigners. might be wrong tho.


PS. remind me, passphrase for BIP39 mnemonic seeds, they are not purely passphrases? there is no way to tell if given BIP39 seed needs a passphrase or not? with an incorrect passphrase it will just unwrap into empty wallet, right?

2021-07-06 18:28 UTC, Overtorment requested changes
conceptually lgtm

2021-07-07 06:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x1d93bmkqdpar6h0yeqxc0nzr8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7246)

2021-07-07 07:29 UTC, limpbrains commented
> PS. remind me, passphrase for BIP39 mnemonic seeds, they are not purely passphrases? there is no way to tell if given BIP39 seed needs a passphrase or not? with an incorrect passphrase it will just unwrap into empty wallet, right?

Correct

2021-07-07 08:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0m1m0gfxqq5qg81wt7hdvrd1hw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7247)

2021-07-10 11:29 UTC, Overtorment commented
is it ready for review & merge?

2021-07-10 12:57 UTC, limpbrains commented
> is it ready for review & merge?

Not yet. I need to figure out where to put code to migrate old aezeed wallets to new data structure. And maybe change some apis.

2021-07-12 09:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r7b20em2kdrmgkfc7ndbcd9vq4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7281)

2021-07-12 09:29 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p5erezy4kmu12h56n67mgnyhrg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7282)

2021-07-12 10:10 UTC, limpbrains commented
ready to be merged, I will start working on improving import screen in another PR

2021-07-12 14:03 UTC, Overtorment commented on class/app-storage.js
> +            // remove this code somewhere in year 2022
there is nothing more permanent then temporary solution kek

2021-07-12 14:48 UTC, limpbrains commented on class/app-storage.js
> +            // remove this code somewhere in year 2022
True :) I should probably add // TODO and FIXME

2021-07-16 16:07 UTC, Overtorment approved these changes
![image](https://user-images.githubusercontent.com/1913337/125976905-45946671-d3c1-4e5e-9fb5-4afd70521a66.png)
![image](https://user-images.githubusercontent.com/1913337/125976945-d621cea2-38e6-43bf-b3a1-aa4b58c26c98.png)

2021-07-16 16:07 UTC, Overtorment commented on tests/unit/hd-aezeed.test.js
> +    aezeed.setPassphrase();
extra line

2021-07-16 16:08 UTC, merged

2021-07-16 16:08 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

2021-07-16 16:12 UTC, Overtorment commented
very noice.
we could include it in next release.
as a workaround while there is no gui, we could accept text with semicolon on import screen (`seed:pass`)
unless we do that already..?

2021-07-16 16:16 UTC, limpbrains commented
> very noice.
> we could include it in next release.
> as a workaround while there is no gui, we could accept text with semicolon on import screen (`seed:pass`)
> unless we do that already..?

I'm going to deliver UI pretty soon

2021-07-16 17:17 UTC, limpbrains commented on class/wallets/abstract-hd-wallet.js
> -  getMnemonicToSeedHex() {
Looks like so, I can't remember why I removed it 😕