REF: Hierarchy navigator screen
BlueWallet/BlueWallet pull request #3168
Opened 2021-05-17 19:12 UTC by jaonoctus

## UI/UX Changes

![image](https://user-images.githubusercontent.com/7918067/118543134-463f6000-b72a-11eb-8858-bd7f8b6ae6f9.png)

## SignVerify directly from an address

![image](https://user-images.githubusercontent.com/7918067/118542866-f365a880-b729-11eb-8554-6a22aebef45c.png)

2021-05-18 02:20 UTC, marcosrdz commented on components/addresses/AddressItem.js
> +    flex: 6,
6? How does that behave on large screens?

2021-05-18 03:22 UTC, jaonoctus commented on components/addresses/AddressItem.js
> +    flex: 6,
I have not tested on larger devices

2021-05-18 13:11 UTC, ncoelho commented
Changed the labels and transaction to grow when needed.

<img width="1434" alt="Screenshot 2021-05-18 at 15 06 30" src="https://user-images.githubusercontent.com/1238429/118656886-3fc4ed00-b7eb-11eb-947d-5f14cf0cb157.png">

2021-05-19 07:08 UTC, ncoelho approved these changes

2021-05-19 11:07 UTC, limpbrains approved these changes

2021-05-19 15:41 UTC, Overtorment requested changes
mostly lgtm, but UI nuances should be discussed with @ncoelho

2021-05-19 15:41 UTC, Overtorment commented on components/addresses/AddressItem.js
> +    if (!isWatchOnly) {
we have `wallet.allowSignVerifyMessage()` for that

2021-05-19 15:41 UTC, Overtorment commented on components/addresses/AddressItem.js
> +    if (!isWatchOnly) {
cc @limpbrains

2021-05-19 15:41 UTC, Overtorment commented on components/addresses/AddressItem.js
> +        id: 'copyToClipboard',
tbh, "copy" & "share" makes no sense to me here since user can just tap address and go to receive screen where he can do same actions

2021-05-19 15:41 UTC, Overtorment commented on components/addresses/AddressItem.js
>                <Text style={[styles.index, stylesHook.index]}>{item.index + 1}</Text>{' '}
lets start from zero? makes more sense, since we should eventually allow exporting path for addresses, like `m/48'/0'/0'/2'/0/0` and they always start with zero.
that would be consistent

2021-05-19 15:41 UTC, Overtorment commented on components/addresses/AddressItem.js
> +              <Text style={[stylesHook.list, styles.balance, stylesHook.balance]}>{balance}</Text>
do we have to always display it, even if its `0 BTC`? its kind of tiresome to scroll through a bunch of addresses and they all show zero btc.

cc @ncoelho

2021-05-19 15:41 UTC, Overtorment commented on components/addresses/AddressItem.js
> +            <Text style={[stylesHook.list, styles.balance, stylesHook.balance]}>
same for transactions. do we have to show this text if address has 0 txs..?
cc @ncoelho

2021-05-19 15:53 UTC, jaonoctus commented on components/addresses/AddressItem.js
>                <Text style={[styles.index, stylesHook.index]}>{item.index + 1}</Text>{' '}
Agree. The original PR was starting with zero.

2021-05-19 17:45 UTC, marcosrdz commented on components/addresses/AddressItem.js
> +        id: 'copyToClipboard',
Those are shortcuts already in production. Doesnt require the receive modal to load.

2021-05-19 19:35 UTC, jaonoctus commented on components/addresses/AddressItem.js
> +        id: 'copyToClipboard',
Ideally these actions would be in a bottom modal similar to coinControl screen, right?

2021-05-20 01:31 UTC, marcosrdz commented on components/addresses/AddressItem.js
> +        id: 'copyToClipboard',
No. They use the standard tool tip to provide shortcuts when long pressing a row. 
I use other apps to track addresses, so being able to long press, copy, switch, rinse & repeat quickly is a time saver.

2021-05-20 01:32 UTC, marcosrdz commented on components/addresses/AddressItem.js
> +    flex: 8,
Still confused as to why such a large number. Usually we use 1.

2021-05-20 09:34 UTC, ncoelho commented on components/addresses/AddressItem.js
> +        id: 'copyToClipboard',
If more features are added that need interaction (like signing, private key, etc) we can then change to a modal. For now I think this is ok and shortcuts behaviour never hurts.

2021-05-20 09:36 UTC, ncoelho commented on components/addresses/AddressItem.js
> +              <Text style={[stylesHook.list, styles.balance, stylesHook.balance]}>{balance}</Text>
Yes, otherwise the layout changes between the rows, which is more annoying.

2021-05-20 09:40 UTC, ncoelho commented on components/addresses/AddressTypeBadge.js
> +  const badgeLabel = hasTransactions
Yes. Doesn't feel great there. There's some solutions:
1. Don't use the "used" label but keep the different title colors
2. Don't show "used" on change
3. Have a section title
4. Use tabs

For some reason option 2 makes more sense to me.

2021-05-20 09:57 UTC, ncoelho commented on components/addresses/AddressItem.js
> +            <Text style={[stylesHook.list, styles.balance, stylesHook.balance]}>
I think it is ok, we can revisit later

2021-05-21 08:01 UTC, marcosrdz approved these changes

2021-05-26 12:35 UTC, jaonoctus commented on components/addresses/AddressTypeBadge.js
> +  const badgeLabel = hasTransactions
@ncoelho I like the "tabs" solution better. Do you have any design in mind?

2021-05-26 15:53 UTC, ncoelho commented on components/addresses/AddressTypeBadge.js
> +  const badgeLabel = hasTransactions
Something like this, but probably means adding a new lib?

![Screenshot 2021-05-26 at 17 49 12](https://user-images.githubusercontent.com/1238429/119691305-c19bc280-be4a-11eb-8f7e-a15889beb1b6.png)

2021-05-26 16:15 UTC, jaonoctus commented on components/addresses/AddressTypeBadge.js
> +  const badgeLabel = hasTransactions
@ncoelho cool!

Not needed. The component could have a `currentTab` state, which will be `external` as default.

Once you click on the other tab, the state will toggle/switch the state to `internal`.

And the List will reactively filter and show the necessary addresses.

wdyt? I can send a new commit with these changes

2021-05-26 16:18 UTC, ncoelho commented on components/addresses/AddressTypeBadge.js
> +  const badgeLabel = hasTransactions
let's try it, It does simplify it I think

2021-05-31 20:27 UTC, jaonoctus commented on components/addresses/AddressItem.js
>                <Text style={[styles.index, stylesHook.index]}>{item.index + 1}</Text>{' '}
@marcosrdz why you have changed it to `item.index + 1` ?

2021-05-31 20:29 UTC, marcosrdz commented on components/addresses/AddressItem.js
>                <Text style={[styles.index, stylesHook.index]}>{item.index + 1}</Text>{' '}
List would start at 0. Instead of 1. Programmer friendly, instead of user friendly.

2021-05-31 23:21 UTC, jaonoctus commented on components/addresses/AddressTypeBadge.js
> +  const badgeLabel = hasTransactions
cc @ncoelho just need to add your :sparkles: BEAUTIFUL styles :sparkles: now.

3e987df

![image](https://user-images.githubusercontent.com/7918067/120248384-5f2d3280-c24d-11eb-9998-fc1ec649cccc.png)

2021-07-04 04:44 UTC, marcosrdz commented on components/addresses/AddressTypeBadge.js
> +  const badgeLabel = hasTransactions
https://reactnativeelements.com/docs/button_group

2021-07-04 22:02 UTC, jaonoctus commented on components/addresses/AddressTypeBadge.js
> +  const badgeLabel = hasTransactions
@marcosrdz  Already working after 9493c54

2021-07-05 18:29 UTC, Overtorment commented
is it ready for review & merge?

2021-07-05 18:35 UTC, Overtorment approved these changes

2021-07-05 21:47 UTC, jaonoctus commented
@Overtorment yessir

2021-07-06 09:37 UTC, merged