OPS: Upgrade RN 0.64.1
BlueWallet/BlueWallet pull request #3170
Opened 2021-05-18 02:56 UTC by marcosrdz

2021-05-18 03:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/eub8fdpkddqw42vn8hptrwef2c?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/rn64-1621307463.apk)

2021-05-18 03:11 UTC, marcosrdz commented on package.json
> +    "transformIgnorePatterns": [
https://github.com/facebook/react-native/issues/31190

2021-05-18 03:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pm33dvpx3cnh00qfn1e7pp6qg8?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/rn64-1621308291.apk)

2021-05-18 09:19 UTC, Overtorment requested changes
```
> Task :react-native-haptic-feedback:extractDeepLinksDebug
/Users/runner/work/BlueWallet/BlueWallet/node_modules/react-native-haptic-feedback/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger8350143561936519376.xml:5:5-74 Error:

	uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.facebook.react:react-native:0.64.1] /Users/runner/.gradle/caches/transforms-2/files-2.1/c0dd7102f7e7bec9829c84a85a9ea345/jetified-react-native-0.64.1/AndroidManifest.xml as the library might be using APIs not available in 16
> Task :react-native-haptic-feedback:processDebugAndroidTestManifest FAILED
	Suggestion: use a compatible library with a minSdk of at most 16,
[androidx.vectordrawable:vectordrawable-animated:1.0.0] /Users/runner/.gradle/caches/transforms-2/files-2.1/98c7b0116a0584aebef186ec65cd8f39/vectordrawable-animated-1.0.0/AndroidManifest.xml Warning:
		or increase this project's minSdk version to at least 21,
	Package name 'androidx.vectordrawable' used in: androidx.vectordrawable:vectordrawable-animated:1.0.0, androidx.vectordrawable:vectordrawable:1.0.1.
		or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)

```

2021-05-19 03:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xgrkpgqxnz181gfa3u9ec0xg7w?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/rn64-1621395363.apk)

2021-05-19 11:15 UTC, Overtorment commented
e2e still fails

2021-06-05 15:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gvwx1ffyqf99bx71bzekn5fbzr?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/rn64-1622907235.apk)

2021-06-06 06:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n91fyyq3qup2w7btpwtf38hz2w?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/rn64-1622962635.apk)

2021-06-06 09:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dm4memzuhx78mhxmjp38fxte9w?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/rn64-1622973080.apk)

2021-06-06 10:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e0n949bx6bjbbveat3agcbv864?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/rn64-1622974809.apk)

2021-06-18 16:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bthfbj42zjpwye25p5kwafrm0g?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/rn64-1624034772.apk)

2021-06-28 16:08 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5yzmcqd5g25050vz524mg70z4m?device=pixel4

[download apk](http://206.189.62.190:1488/rn64-1624896510.apk)

2021-07-02 02:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4y8a0gwkw6cp5hav0zk3p69c0w?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7174)

2021-07-02 03:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qmtqc5z9gy4jf3y02cy1tk4fnc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7177)

2021-07-02 17:10 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/964degeex83h73bxbhqkbtaq3g?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7184)

2021-07-02 18:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5t7am0kk5d1qxtveejaabt5evg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7186)

2021-07-02 19:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n4q4k6rmydmj7aw3kceg20ck5c?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7188)

2021-07-02 21:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8u6qw6kkx89fhu7d2xhyt6wtv0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7189)

2021-07-03 15:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/edegvjn08jt9fwu0c6q3pbkwvr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7192)

2021-07-03 17:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m3cyndx9f4rdw2td8muc83b3g4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7197)

2021-07-04 00:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dbctkw6y2bq6r6x7ykrp5231e8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7199)

2021-07-04 03:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/96wgnna80c107rd3t5nve49rng?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7200)

2021-07-04 04:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b7gzmzfch1rc1nn66p8adgd1vm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7201)

2021-07-04 04:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gyb3uezqqy6nuavba77ykceu0m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7202)

2021-07-04 09:57 UTC, Overtorment approved these changes
lgtm.

PS. sometimes i forget how shitty RN is under the hood
PPS. was jscore updated as well with this new RN version? i wonder if tor will stop hanging with this update

2021-07-04 09:57 UTC, Overtorment commented on .flowconfig
>  esproposal.optional_chaining=enable
we still cant remove flowconfig? we dont use flow

2021-07-04 09:57 UTC, Overtorment commented on metro.config.js
> +    //     /.*\.ProjectImports\.zip/,
dead code. candidate for removal next time you're refactoring around here

2021-07-04 11:11 UTC, marcosrdz commented on metro.config.js
> +    //     /.*\.ProjectImports\.zip/,
Need it for windows

2021-07-04 14:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rm17ufmvzgcg3jfv5758ye2k80?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7205)

2021-07-04 15:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/enxjemdx2dpcy255yvcd928bfg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7206)

2021-07-04 19:05 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5ckkd3cn6zfbhmxy3vxe817n5g?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7207)

2021-07-04 19:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9hmt4410ugrcyekz054c099t9w?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7208)

2021-07-05 01:45 UTC, marcosrdz commented on .flowconfig
>  esproposal.optional_chaining=enable
Will check

2021-07-05 13:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2j1m459mpt3k6xkuhkv16tyj20?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7213)

2021-07-05 17:49 UTC, Overtorment commented
@ncoelho @limpbrains last chance to weight in on this PR before I marge it. e2e issues seem to be resolved

2021-07-05 22:17 UTC, Overtorment commented
@marcosrdz conflicts

2021-07-05 22:20 UTC, marcosrdz commented
fixed

2021-07-05 22:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/c5akqgg4gkfjj5hccbh7mkf19w?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7224)

2021-07-06 09:38 UTC, merged