REF: storage write
BlueWallet/BlueWallet pull request #3213
Opened 2021-05-23 15:27 UTC by Overtorment

even tho i cant reproduce race condition on keystore write, I think its a good idea to add protection against it

2021-05-23 15:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mg6j9gaecfpxen0qk3p66rkxpm?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/ref-storage3-1621784508.apk)

2021-05-23 17:53 UTC, jaonoctus approved these changes

2021-05-23 18:09 UTC, marcosrdz approved these changes

2021-05-23 19:57 UTC, limpbrains requested changes

2021-05-23 19:57 UTC, limpbrains commented on class/app-storage.js
> +    savingInProgress = 1;
I don't think it is save to skip saving if another one is in process. 
Second saving should wait for the first one to complete and then be executed.
It is theoretically possible to lose data without it. Especially on a slow device.

2021-05-23 19:57 UTC, limpbrains commented on class/app-storage.js
> +      savingInProgress = 0;
What if exception happens outside of `try {}` ? Then `savingInProgress` will not be set to `0` and save function will be forever broken.
The whole logic of `saveToDisk` func should be inside that `try {}` so that in set `savingInProgress` to `0` in 100% cases.

2021-05-24 12:22 UTC, Overtorment commented
added fallback to realm.
now, critical data gets saved to the dedicated realm database file. this file is encrypted with the current device id https://github.com/react-native-device-info/react-native-device-info#getuniqueid
as far as I can tell this is quite secure for ios devices, and somewhat secure for android devices.

in an emergency when bw cant read keystore it reads same data from realm.

2021-05-24 12:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vdq96n8uyy9wu6ug1jh9kq9788?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/ref-storage3-1621859667.apk)

2021-05-24 17:19 UTC, limpbrains requested changes

2021-05-24 17:19 UTC, limpbrains commented on class/app-storage.js
> +      savingInProgress = 0;
`savingInProgress` could never reach 10 if it's value get nullified after successful run.

2021-05-25 11:34 UTC, Overtorment commented on class/app-storage.js
> +      savingInProgress = 0;
thats kind of the idea. ive put a check and alert as a last resort for a case when for some reason save requests piled up and can not run.

2021-05-25 13:07 UTC, limpbrains commented on class/app-storage.js
> +      savingInProgress = 0;
- there are 9 pending tasks in the queue
- first executed and `savingInProgress` nullified
- 8 new tasks created
- now there are 16 pending tasks, but `savingInProgress` == 8

2021-05-25 17:58 UTC, Overtorment commented on class/app-storage.js
> +      savingInProgress = 0;
tasks are kinda interchangeable - if you get one successful you don't need the other ones.
or how do you propose to handle it? instead of nullifying decrease the counter?

2021-05-25 19:15 UTC, limpbrains commented on class/app-storage.js
> +      savingInProgress = 0;
I mean queue is growing, but you can't see that. 
Yes decrease the counter.

Let's merge it, I will propose my solution later.
I thought of array of promises. When function starts it looks for pending promises in this array. If there are any it waits for them to resolve. Then it starts and add it's own promise to the array. And so on.

2021-05-25 19:15 UTC, limpbrains approved these changes

2021-05-26 10:27 UTC, Overtorment commented on class/app-storage.js
> +      savingInProgress = 0;
i wanted only to avoid _concurrent_ writes, and just some kind of alerting mechanism to notify user that something is completely fucked (which is not expected, really, we don't have any places in the app where saveToDisk would be firing a lot)

2021-05-26 21:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wh6hey8uq44mzumwy5hf52x3xm?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/ref-storage3-1622064139.apk)

2021-05-27 12:03 UTC, limpbrains approved these changes

2021-05-27 15:07 UTC, marcosrdz approved these changes

2021-05-27 20:55 UTC, merged

2021-05-27 20:55 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!