FIX: Re-order wallet bug #3341
BlueWallet/BlueWallet pull request #3342
Opened 2021-07-04 04:22 UTC by marcosrdz

2021-07-04 04:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4q66qpvrr056dazbuj5rgbwbz8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7203)

2021-07-05 17:52 UTC, Overtorment requested changes

2021-07-05 17:52 UTC, Overtorment commented on screen/wallets/list.js
> +    if (isFocused) {
if you invert the condition you will be able to return early, avoid many changed lines and added indentation (harder to read code)

2021-07-05 17:56 UTC, marcosrdz commented on screen/wallets/list.js
> +    if (isFocused) {
Done.

2021-07-05 18:10 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0xpkz18fa77wehbq2zyp6pu778?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7216)

2021-07-05 18:13 UTC, Overtorment approved these changes

2021-07-05 19:09 UTC, merged

2021-07-05 19:09 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!