ADD: isTorCapable
BlueWallet/BlueWallet pull request #3404
Opened 2021-07-18 16:34 UTC by marcosrdz

Removes the need to manual code adjustments on platforms that aren't compatible with react-native-tor

2021-07-18 16:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0w1pjrffqyrefth35522366w7m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7334)

2021-07-18 17:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g6v2nhxgx8d7qvry52btx0kunr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7335)

2021-07-18 17:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b0e33m8r3uzcrb817ztdypupbr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7337)

2021-07-18 18:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wv4khz6kkdh4h3hvn47b0hbnec?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7338)

2021-07-19 15:25 UTC, Overtorment requested changes

2021-07-19 15:25 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +          usingPeer.host.endsWith('.onion') ? torrific : global.net,
i think that can be reduced to

```
(usingPeer.host.endsWith('.onion') && isTorCapable) ? torrific : global.net,
```

2021-07-19 15:25 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +import { isTorCapable } from '../blue_modules/environment';
you corrected `require('./torrific');` below but added extra `../blue_modules/` here kek

2021-07-19 15:25 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +    ? new ElectrumClient(host.endsWith('.onion') ? torrific : global.net, global.tls, sslPort || tcpPort, host, sslPort ? 'tls' : 'tcp')
looks like it can also be simplified to reduce diff

2021-07-19 15:25 UTC, Overtorment commented on screen/settings/NetworkSettings.js
> +        {isTorCapable && <BlueListItem title={loc.settings.tor_settings} onPress={navigateToTorSettings} testID="TorSettings" chevron />}
i have a feeling that might crash with cryptic "cant render text outside of <Text> tag"

2021-07-19 17:21 UTC, marcosrdz commented on blue_modules/BlueElectrum.js
> +import { isTorCapable } from '../blue_modules/environment';
lol silly auto import

2021-07-19 17:36 UTC, marcosrdz commented on screen/settings/NetworkSettings.js
> +        {isTorCapable && <BlueListItem title={loc.settings.tor_settings} onPress={navigateToTorSettings} testID="TorSettings" chevron />}
it doesnt.

2021-07-19 17:36 UTC, marcosrdz commented on blue_modules/BlueElectrum.js
> +          usingPeer.host.endsWith('.onion') ? torrific : global.net,
fixed

2021-07-19 17:36 UTC, marcosrdz commented on blue_modules/BlueElectrum.js
> +    ? new ElectrumClient(host.endsWith('.onion') ? torrific : global.net, global.tls, sslPort || tcpPort, host, sslPort ? 'tls' : 'tcp')
fixed.

2021-07-19 17:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bt9d4r8h0epaftae838qdz3zf4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7344)

2021-07-19 18:13 UTC, Overtorment requested changes
tests fail.
also rebasing would not hurt, so a bunch of WIP commits wont appear in our git history

2021-07-19 19:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/urda4je389q8e8d2waeht3an40?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7346)

2021-07-20 10:44 UTC, Overtorment approved these changes
THANKS KФMЯAD KЯAKЕИ

2021-07-20 10:44 UTC, merged

2021-07-20 10:44 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!