ADD: UI for import wallet with passphrase
BlueWallet/BlueWallet pull request #3406
Opened 2021-07-18 18:39 UTC by limpbrains

It uses alert with input to ask for a passphrase
Currently it works with standard HD wallets + aezeed + slip39

https://user-images.githubusercontent.com/155891/126078571-5bd40b78-367f-45ff-9825-8b3637447b28.mp4

2021-07-18 18:48 UTC, ncoelho commented
I would do the alert before closing the view.

2021-07-18 18:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/73w3fwwypybvqt2xxz1hr3f1jg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7340)

2021-07-19 02:16 UTC, marcosrdz commented
Same comment as @ncoelho

2021-07-19 02:18 UTC, marcosrdz commented
Unless its modified so cancelling passphrase entry sends you back the import screen with the seed filled out

2021-07-19 08:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mp17r9aje6v642ec45trxd108w?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7343)

2021-07-20 09:52 UTC, limpbrains commented
I've spliced `processImportText` in 2 functions. Now the first one is asking and validating password, if needed, and the second one does the import

https://user-images.githubusercontent.com/155891/126302334-3d5a0213-dadd-4fad-81d3-ded75d68daf5.mp4

Now import can be cancelled and view closes after the alert

2021-07-20 10:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/a6yj6p1tc0dj1gy1qgq2t509nr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7351)

2021-07-20 11:05 UTC, Overtorment approved these changes
very nice and clean diff.
good to merge if @ncoelho is onboard product-wise

2021-07-20 12:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qp0y5a2pegu5qe4z20pzytqpy0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7354)

2021-07-20 13:08 UTC, ncoelho approved these changes

2021-07-20 13:53 UTC, Overtorment requested changes

2021-07-20 13:53 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> +  it.skip('selftest passes', async () => {
whats with the skips..?

2021-07-20 14:38 UTC, limpbrains commented on tests/e2e/bluewallet.spec.js
> +  it.skip('selftest passes', async () => {
To speed up the e2e tests by 10000%
fixed

2021-07-20 14:39 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> +  it.skip('selftest passes', async () => {
the build itself is building ~30min  :-(

2021-07-20 14:40 UTC, Overtorment approved these changes
@marcosrdz

2021-07-20 14:42 UTC, marcosrdz approved these changes

2021-07-20 14:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uq9gxe9xhhzmym0mr4y9huehxc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7356)

2021-07-20 15:47 UTC, merged

2021-07-20 15:47 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!