ADD: custom derivation path to HD wallets
BlueWallet/BlueWallet pull request #3452
Opened 2021-07-26 12:06 UTC by limpbrains

2021-07-26 12:25 UTC, Overtorment commented
btw feels like `getAccountNum()` deserves its own getter

2021-07-26 13:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vk7e16q92qqtf4vbe19618u0rg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7435)

2021-07-26 14:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/c2wdf8veth9fyeakbknxxafxw8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7439)

2021-07-27 15:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5bh71e7u5uenp77re9pak836r0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7466)

2021-07-28 12:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g5ny42qy81mmz6cnv724hap6wg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7474)

2021-07-29 11:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w5p0vdv5k7hwj43u5bknqmzwcr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7480)

2021-07-29 14:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q4nnwe7w9tpqgja410ddde7dac?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7483)

2021-07-29 15:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tpem9v540uq057kcze1m19hz4m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7484)

2021-07-31 10:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9g80eujdj4tmpawxevw9ftgfqr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7516)

2021-07-31 15:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nkjcrhuwvmtvmp4nj79qndyvxm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7517)

2021-08-01 08:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ne77pumyqhgnw4pekb3bdd7cgg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7524)

2021-08-01 09:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fheee8bnuaqzth8wtx0b409eyc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7525)

2021-08-01 11:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mdja415gqa1ctw1vmndu8abjkg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7526)

2021-08-01 12:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5pkj25ee4bhmna583w3m8khekw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7527)

2021-08-01 20:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8zzxh7mfuy467f9uak2khfx030?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7530)

2021-08-02 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-08-02 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-08-02 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-02 20:32 UTC, Overtorment requested changes
i really like that we are getting rid of placeholder-wallet, I never liked it.
for me, it makes more sense for the user to stay on the import screen and witness the import progress

2021-08-02 20:32 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> -    await element(by.id('AboutButton')).tap();
i think it was just testing that its possible to click that button and the app doesn't crash

2021-08-02 20:32 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> +  for (let c = 0; c <= 5; c++) {
as much as i want to speed up e2e, this is no way to go. implement enough backdoors for testing, and you end up testing backdoor code instead of real code.
we specifically need e2e test to make sure the user can type his mnemonic, go through the flow, and get his wallet imported.

ways to solve this:
1) we have a ticket to split test suite  into several suites, where in one suite we  don't relaunch/reinstall the app, and we always expect a wallet to exist (I think we re-import same bip84 a lot in current test suite...)
2) speed up discovery. write a test code that waits for the first discovered wallet, and taps it - that should cancel the rest of the discovery and save this tapped wallet
3) have testcases that go through all 9 circles of ~~hell~~ discovery just to test that, rest of the testcases use speeded-up flow..?

2021-08-02 20:34 UTC, Overtorment commented
given all objections are fixed, it still needs product blessing (@ncoelho).
afaik users are confused by password input, so that needs rework

2021-08-03 10:22 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-08-03 10:22 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-04 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-08-04 11:58 UTC, limpbrains commented on screen/wallets/importDiscovery.js
> +    if (wallets.length > 0) return; // TODO remove in prod
removed

2021-08-04 12:02 UTC, limpbrains commented on class/wallet-import.js
> +        }
We can't. Best way to distinguish Legacy and BRD wallet - compare number of transactions.

2021-08-04 12:07 UTC, limpbrains commented on screen/wallets/details.js
> +                    {derivationPath && (
null is safe here

2021-08-04 12:24 UTC, limpbrains commented on screen/wallets/importDiscovery.js
> +        if (wallets.length === 1) saveWallet(wallets[0]); // instantly save wallet if only one has been discovered
In current version this works for bip84 wallets only. I've added balance fetch after import for all wallet types in my branch.

2021-08-04 12:25 UTC, limpbrains commented on class/wallet-import.js
> +  importFunc()
Agree, this would be a nice feature to have

2021-08-04 12:29 UTC, limpbrains commented on tests/e2e/bluewallet.spec.js
> -    await element(by.id('AboutButton')).tap();
My mistake. Reverted

2021-08-04 12:31 UTC, limpbrains commented on tests/e2e/bluewallet.spec.js
> +  for (let c = 0; c <= 5; c++) {
I used the 3rd way. There is a new e2e tests which tests new import workflow.

2021-08-04 12:33 UTC, limpbrains commented on class/wallets/watch-only-wallet.js
> +    if (!this.isHd()) throw new Error('Not initialized');
No, because watch-only with single address should not have `getDerivationPath()`

2021-08-04 12:45 UTC, limpbrains commented on screen/wallets/importDiscovery.js
> +            onPress={() => saveWallet(wallets[selected].wallet)}
fixed

2021-08-04 13:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p06ky8uydhdw4j3nwahugtd47r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7565)

2021-08-05 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-08-05 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-06 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-08-06 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-07 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-08-07 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-08 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-08-08 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-09 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-08-09 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-09 14:35 UTC, marcosrdz commented
@limpbrains  conflicts

2021-08-09 19:24 UTC, limpbrains commented
@ncoelho do you think the current workflow is Ok, or something needs to be changed?

2021-08-09 19:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fnjaub4f2830b1xek4ny6zcdpw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7702)

2021-08-09 22:36 UTC, ncoelho commented
> @ncoelho do you think the current workflow is Ok, or something needs to be changed?

Gonna try to purpose some changes tomorrow. Need to mock them up

2021-08-10 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-08-10 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-11 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-08-11 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-12 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-08-12 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-12 13:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3xa5f4duufhtf0p4czhmcrt5z0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7740)

2021-08-12 16:00 UTC, marcosrdz approved these changes

2021-08-19 09:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/88j1eh514cgdgf5rtckd4vxz6w?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7824)

2021-08-19 11:42 UTC, limpbrains commented on class/wallet-import.js
> +  importFunc()
#3614

2021-08-19 11:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q3njun0h6ynaf48ybymf482zqr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7827)

2021-08-19 12:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mmpa2dzy18drh7gtqvjgt17cb8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7828)

2021-08-19 14:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dmt0gb2xh97gfqf2acf6vj1ang?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7834)

2021-08-19 14:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uhgzjzmbm2xnw2nq3uypbeb6v4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7837)

2021-08-19 15:05 UTC, limpbrains commented on class/wallet-import.js
> +  importFunc()
Done in this PR.

2021-08-28 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-29 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-30 07:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gmhku36ddwznnfq10cre8u87x0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8043)

2021-08-30 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-31 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-01 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-02 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-03 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-04 07:59 UTC, limpbrains commented
@ncoelho maybe you can describe these changes in words, so I can implement them and we finally merge this PR?

2021-09-04 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-04 15:57 UTC, ncoelho commented
> @ncoelho maybe you can describe these changes in words, so I can implement them and we finally merge this PR?

I was thinking of making the passphrase and the path search opt-in (with a checkbox/switch) and under advanced settings. 

The biggest issue we have nowadays is that users can't import their wallets because they don't know what a passphrase is. So this advanced flows are not really helping users importing, but create more problems. And this one in particular you need to know what derivation paths are to understand how to import a wallet. Makes it very complex.

Not sure what others think. 

Here's a suggestion:
<img width="375" alt="import" src="https://user-images.githubusercontent.com/1238429/132100679-9d1f8c14-2984-4976-b751-4e6a77adcad2.png">

2021-09-05 07:59 UTC, limpbrains commented
I think it will be clearer if we could label button as Skip on passphrase modal, if input is clear.
Or as I suggested in mocks:

<img width="100" alt="изображение" src="https://user-images.githubusercontent.com/155891/132119673-1c0fb9c9-60d7-484b-a0c1-39d0e5b88f71.png">

I totally agree that all these possibilities are confusing. Maybe we don't need these options on Import screen if Advanced mode is enabled? Just 2 different algos:
If Advanced mode is disabled:
- do not ask for passphrase
- import first found wallet, do not scan for different derivation paths.
- do not ask for custom derivation path

If Advanced mod is Enabled:
- ask for passphrase
- scan for all possible accounts

Lastly. What if we have offline mode + Advanced disabled. Maybe in this case we should jump to last screen immediately?

2021-09-05 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-05 16:05 UTC, ncoelho commented
> I think it will be clearer if we could label button as Skip on passphrase modal, if input is clear.
> 
> Or as I suggested in mocks:
> 
> 
> 
> <img width="100" alt="изображение" src="https://user-images.githubusercontent.com/155891/132119673-1c0fb9c9-60d7-484b-a0c1-39d0e5b88f71.png">
> 
> 
> 
> I totally agree that all these possibilities are confusing. Maybe we don't need these options on Import screen if Advanced mode is enabled? Just 2 different algos:
> 
> If Advanced mode is disabled:
> 
> - do not ask for passphrase
> 
> - import first found wallet, do not scan for different derivation paths.
> 
> - do not ask for custom derivation path
> 
> 
> 
> If Advanced mod is Enabled:
> 
> - ask for passphrase
> 
> - scan for all possible accounts
> 
> 
> 
> Lastly. What if we have offline mode + Advanced disabled. Maybe in this case we should jump to last screen immediately?

Let's try putting them under advanced mode enabled then, that is definitely better than doing it by default.

My suggestion to have opt-in is because it becomes obvious to whoever needs it they are there, there's a visible element. Advanced mode by itself doesn't give much clues to the user on the feature set change. 

Let's do it under advanced mode then, if you prefer to have the passphrase on a new screen, do it as well. 👍

2021-09-06 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-07 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-08 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-09 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-10 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-11 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-17 13:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dpbzme773fauj0a9q4c5kkunh4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8368)

2021-09-17 13:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bngtpar1a0nwpe9vba1v2xpvgm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8370)

2021-09-17 15:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b5eptukthyzdfqrbhbq889za50?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8373)

2021-09-17 15:38 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/38yw69xw0vedppnq8cxh57t8cc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8375)

2021-09-17 18:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0yy3e9qk4b4vb5tdgg8jytukac?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8379)

2021-09-18 08:22 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m1qj2nqpdbbh7kmw2grmag4dmg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8384)

2021-09-18 13:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ubqk070njg52ftqut2wk35rdz0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8386)

2021-09-18 13:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wdzuztjenhxycjuyhu2jqf2jv8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8387)

2021-09-19 11:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mntedamnpnyuwnxp3uwp6g9t7r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8395)

2021-09-20 14:29 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hdkfr7zwhj5kx6whudxvcw1fq4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8405)

2021-09-20 14:36 UTC, limpbrains commented
@ncoelho Take a look

- passphrase and accounts scanning available only in Advanced mode
- you can import wallet even in offline mode, using Custom derivation path feature

https://user-images.githubusercontent.com/155891/134020586-0421440e-3cf9-4bc0-8d69-aac2562306cd.mp4

2021-09-20 17:57 UTC, ncoelho commented
Tested, pure magic! 
ACK.

2021-09-20 18:10 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cjqaqhwvnb564y8qqmjuguf10r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8407)

2021-09-20 22:04 UTC, godSaysHODL commented
looks amazing! Owe you 200k sats in relation to https://github.com/BlueWallet/BlueWallet/issues/2240 @limpbrains 

Much more beautiful than my ms paint mockup 😁

2021-09-21 07:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z91tcatxtnmmz6rj3qtzbf4fy8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8410)

2021-09-21 12:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u0pqzmbuap2kv8farm3wkvqanr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8412)

2021-09-21 12:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xwztnag7q9uc1b9kav8ktkp5u8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8413)

2021-09-21 12:26 UTC, Overtorment requested changes
almost ready for merge

2021-09-21 12:26 UTC, Overtorment commented on class/wallets/watch-only-wallet.js
> +    if (!this.isHd()) throw new Error('Not initialized');
i have just pushed a testcase where this breaks

2021-09-21 12:26 UTC, Overtorment commented on components/WalletToImport.js
> +    // paddingVertical: 50,
dead code

2021-09-21 12:26 UTC, Overtorment commented on screen/wallets/importDiscovery.js
> +        subtitle = wallet.getDerivationPath?.();
i didnt know you can do that

2021-09-21 12:26 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> +    await device.pressBack();
might be worth moving to a helper func

2021-09-21 12:26 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> +    // await element(by.id('AboutButton')).tap();
dead code

2021-09-21 12:26 UTC, Overtorment commented on tests/e2e/bluewallet.spec.js
> +    await helperDeleteWallet('Imported HD Legacy (BIP44 P2PKH)');
we dont disable adv mode at the end of the test..?

the rest of tests succeeds probably because we use backdoored inport, otherwise tests used to fail for me because  you need to additionally scroll down the import screen, because of all extra buttons the button you need it not visible

2021-09-21 12:26 UTC, Overtorment commented on class/wallet-import.js
> +  async function* importGenerator() {
wow, last time i saw a generator in js was like 3 years ago, I think

2021-09-21 12:26 UTC, Overtorment commented on screen/wallets/import.js
> +
we show an option to add a bip39 password only in advanced mode?
cc @ncoelho

2021-09-21 12:26 UTC, Overtorment commented on class/wallet-import.js
> +      const next = await generator.next();
generators usage is pretty cool here

2021-09-21 13:26 UTC, limpbrains commented on tests/e2e/bluewallet.spec.js
> +    await helperDeleteWallet('Imported HD Legacy (BIP44 P2PKH)');
I think it succeeds because it is the last test. And adv mode doesn't really breaks anything.
Anyway I've added disabling adv mode at the end of the test

2021-09-21 13:27 UTC, limpbrains commented on class/wallet-import.js
> +  async function* importGenerator() {
It's first time I'm using it :)

2021-09-21 13:57 UTC, limpbrains commented on class/wallets/watch-only-wallet.js
> +    if (!this.isHd()) throw new Error('Not initialized');
Thanks, I was confused by it. I thought derivation path is useless for watch-only wallets.
I've fixed it.
Please, take a look

2021-09-21 14:24 UTC, limpbrains commented on class/wallets/watch-only-wallet.js
> +    if (!this.isHd()) throw new Error('Not initialized');
Looks like my fix is failing. According to `AbstractWallet.setSecret()` if you recovery wallet from JSON, like skeleton-electrum.txt it stores derivation path in the wallet. In this case that would be watch only wallet instance, not this._hdWalletInstance.

So I'm moving watchonly._derivationPath to watchonly._hdWalletInstance._derivationPath in watchonly.init()

Is it correct approach?
But now tests are failing because of some changes in PSBT.

2021-09-21 14:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9mbwy7v6b5u7zyqrnzmcbxknz8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8418)

2021-09-21 17:53 UTC, Overtorment commented
tests failed

2021-09-23 11:54 UTC, limpbrains commented on class/wallets/watch-only-wallet.js
> +    }
@Overtorment plz review this

2021-09-23 12:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bneaku2228uqf79kzd8pdumg04?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8443)

2021-09-23 12:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6e42gpga17my04q138wkfzzcq0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8442)

2021-09-23 12:51 UTC, Overtorment commented on class/wallets/watch-only-wallet.js
> +    }
lgtm

2021-09-23 12:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/96ugwy67g3hgdbv09f58jtnm40?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8444)

2021-09-23 12:57 UTC, ncoelho commented
@limpbrains no validation or error?

https://user-images.githubusercontent.com/1238429/134510781-afabaac9-42f8-4a43-bbf1-bcfd39864bb7.mov

2021-09-23 13:05 UTC, merged