REF: convert LegacyWallet to typescript
BlueWallet/BlueWallet pull request #3454
Opened 2021-07-26 13:42 UTC by demerzel3

## WIP

2021-07-26 13:57 UTC, Overtorment commented
id say dont rush converting everything to TS.
"f it works, don't touch it"

2021-07-29 21:52 UTC, demerzel3 commented
This is a way of filling the gaps that I left in the last PR as regard to `AbstractWallet`: some of the fields have underspecified types and some are just plain wrong (see `utxo` for example). Besides, I think that if we want to switch to typescript starting from the models would serve us well as an approach, so I see this as valuable work overall. It's also a great way for me to get familiar with the codebase.
Of course I don't want to break anything with this, I will make sure that all existing tests still pass and I will revert any unwanted change in behavior that I may have introduced with the types (as soon as I have a bit of time to continue working on it 😄)

2021-08-04 21:01 UTC, demerzel3 commented
@Overtorment I think this is ready for review now if you want to take a look, I've updated the main comment with a couple of notes.

2021-08-05 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2021-08-05 20:27 UTC, limpbrains approved these changes
I very much like it!

I believe we need to refactor BlueElectrum so that it will have manual connect() method, that we can run in tests if it is needed.

2021-08-10 14:54 UTC, Overtorment requested changes
ok i see your troubles with BlueElectrum.
the easiest solution would be (I just tested it, it works) to remove mandatory connection from BlueElectrum.js (basically socket connects as soon as module is required, lets change that),
and add connection to BlueApp.js right after BlueElectrum is required.

```
overtorment@laptop3 ~/Documents/BlueWallet (master) $ git diff BlueApp.js blue_modules/BlueElectrum.js
diff --git a/BlueApp.js b/BlueApp.js
index acdce2a0..4b0a1fcf 100644
--- a/BlueApp.js
+++ b/BlueApp.js
@@ -5,6 +5,7 @@ import loc from './loc';
 const prompt = require('./blue_modules/prompt');
 const currency = require('./blue_modules/currency');
 const BlueElectrum = require('./blue_modules/BlueElectrum'); // eslint-disable-line @typescript-eslint/no-unused-vars
+BlueElectrum.connectMain();
 const BlueApp = new AppStorage();
 // If attempt reaches 10, a wipe keychain option will be provided to the user.
 let unlockAttempt = 0;
diff --git a/blue_modules/BlueElectrum.js b/blue_modules/BlueElectrum.js
index 4ff7325f..599d9a57 100644
--- a/blue_modules/BlueElectrum.js
+++ b/blue_modules/BlueElectrum.js
@@ -183,8 +183,6 @@ async function connectMain() {
   }
 }
 
-connectMain();
-
 async function presentNetworkErrorAlert(usingPeer) {
   if (await isDisabled()) {
     console.log(
```


otherwise LGTM

2021-08-10 14:54 UTC, Overtorment commented on tests/integration/watch-only-wallet.test.js
> +import * as BlueElectrum from '../../blue_modules/BlueElectrum';
there might be a problem with this approach, as `require` caches the result,
so if module that's being required creates a connection (and also some variables in its scope),  this connection is reused every time someone requires this module.
this is how we ensured.

with `import` its a different deal afaik. everything is brand new and fresh when you import a module, so sockets and connections are duplicated.

not sure how it all works in this PR, need to finish reading the diff and try running it myself

2021-08-10 14:54 UTC, Overtorment commented on tests/integration/notifications.test.js
> +import assert from 'assert';
whats the purpose of changing `require` -> `import` ?

2021-08-10 14:54 UTC, Overtorment commented on tests/integration/lightning-custodian-wallet.test.js
> +import * as BlueElectrum from '../../blue_modules/BlueElectrum';
lightning custodial wallet doesnt need `BlueElectrum`, it works through REST API

2021-08-10 14:54 UTC, Overtorment commented on tests/setup.js
> +global.net = require('net'); // needed by Electrum client. For RN it is proviced in shim.js
good idea to move it here

2021-08-10 14:54 UTC, Overtorment commented on tests/integration/hodlhodl.test.js
> +import * as BlueElectrum from '../../blue_modules/BlueElectrum';
hodlhodl doesnt need `BlueElectrum`

2021-08-10 14:54 UTC, Overtorment commented on tests/integration/aopp.test.js
> +import * as BlueElectrum from '../../blue_modules/BlueElectrum'; // so it connects ASAP
AOPP doesnt need `BlueElectrum`

2021-08-10 18:54 UTC, demerzel3 commented on class/wallets/legacy-wallet.ts
> +  _txs_by_external_index: Transaction[] = []; // eslint-disable-line camelcase
Not sure what you mean here, they are used in `fetchTransactions` ([here](https://github.com/demerzel3/BlueWallet/blob/82299ebaea12010d5e26d1712b14621ecf8a1890/class/wallets/legacy-wallet.ts#L346)) and `getTransactions` ([here](https://github.com/demerzel3/BlueWallet/blob/82299ebaea12010d5e26d1712b14621ecf8a1890/class/wallets/legacy-wallet.ts#L352-L354)).

2021-08-10 19:06 UTC, demerzel3 commented on class/wallets/legacy-wallet.ts
> +  ): CreateTransactionResult<U> {
here `U` is anything that extends `CreateTransactionUtxo`, it is a way of expressing that the list of utxos that you pass in must at least have the same fields as `CreateTransactonUtxo`, but whatever extra attributes you pass in it will be kept intact in the result.

If `CreateTransactionUtxo` is this type:
```ts
type CreateTransactionUtxo = {
  txId: string
  value: number
}
```
Then you can do something like this and typescript won't complain:
```ts
// given the shape of the input `U` is inferred here to be: 
// {txId: string; value: number; foo: string}
const result = createTransaction(
    [{ txId: '123', value: 123, foo: 'foo' }], 
    ... whatever ...
)
// Since in the result `inputs` is of type `U[]` we can read `foo` without issues
console.log(result.inputs[0].foo)
```

2021-08-10 19:10 UTC, demerzel3 commented on class/wallets/legacy-wallet.ts
> +    }));
the existing code was fine but this is better because it changes the type of `address` from being optional (`string | undefined`) to always being present (`string`), which is a tad safer and saves some checks down the line.

2021-08-10 19:12 UTC, demerzel3 commented on typings/coinselect.d.ts
> +  export default function coinSelectSplit<U extends Utxo>(
Same as a previous comment, `U` gets inferred from the input to be anything that extends the `Utxo` type; whatever extra attribute the input has will be preserved in the result (as you can see `inputs` is of type `U[]` in the return type).

2021-08-10 19:15 UTC, demerzel3 commented on tests/integration/notifications.test.js
> +import assert from 'assert';
just consistency 🤷‍♂️

2021-08-10 19:21 UTC, demerzel3 commented on tests/integration/watch-only-wallet.test.js
> +import * as BlueElectrum from '../../blue_modules/BlueElectrum';
This is not my experience at all, as far as I know es6 modules are only evaluated once on the first import exactly like `require`, it shouldn't create any problem.

2021-08-10 20:16 UTC, demerzel3 commented
@Overtorment I moved `BlueElectrum` connection to `BlueApp` as per your suggestion and reverted the changes to the tests that didn't need `BlueElectrum` in the first place.

2021-08-10 21:21 UTC, Overtorment commented on tests/integration/watch-only-wallet.test.js
> +import * as BlueElectrum from '../../blue_modules/BlueElectrum';
nice

2021-08-10 21:26 UTC, Overtorment commented on tests/integration/hd-legacy-breadwallet.test.js
> +  await BlueElectrum.connectMain();
you sure we dont need both `connectMain` & `waitTillConnected` ?

2021-08-10 21:27 UTC, Overtorment commented on tests/integration/import.test.js
>    // awaiting for Electrum to be connected. For RN Electrum would naturally connect
not precisely correct comment anymore

2021-08-10 21:31 UTC, Overtorment commented
running all tests here: https://github.com/BlueWallet/BlueWallet/pull/3576

2021-08-10 21:31 UTC, Overtorment approved these changes

2021-08-11 10:26 UTC, merged