FIX: Remove existing release notes when applying Catalyst patches.
BlueWallet/BlueWallet pull request #3465
Opened 2021-07-28 20:37 UTC by marcosrdz

Builds would get release notes from old commits rather than the latest ones

2021-07-28 20:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fkbf1j8rnufy4j5z6139ueavd0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7478)

2021-07-28 21:38 UTC, Overtorment requested changes

2021-07-28 21:38 UTC, Overtorment commented on scripts/maccatalystpatches/applypatchesformaccatalyst.sh
> +rm release-notes.txt release-notes.json
how is this supposed to work?
those files should regenerate upon instal

2021-07-29 03:41 UTC, marcosrdz commented on scripts/maccatalystpatches/applypatchesformaccatalyst.sh
> +rm release-notes.txt release-notes.json
Those files dont get over written when npm install runs so one could end up deploying release note files that are inaccurate. Such as from WIP branches

2021-07-29 11:50 UTC, Overtorment approved these changes

2021-07-29 11:56 UTC, merged

2021-07-29 11:56 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!