ADD: Electrum connection toggle
BlueWallet/BlueWallet pull request #3470
Opened 2021-07-29 21:04 UTC by marcosrdz

![Simulator Screen Shot - iPhone 12 - 2021-07-29 at 17 00 27](https://user-images.githubusercontent.com/4793122/127565534-b289718a-dff2-4d87-8757-f206312cbf8e.png)

2021-07-29 21:04 UTC, marcosrdz commented
Useful for offline use.

2021-07-29 21:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mjgypgfgm33ap8ndftkb2adev8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7488)

2021-07-29 22:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/173dcf5ngmt8d45y15u4dnp1pc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7492)

2021-07-29 22:47 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vmgadwdvvn9jzpv4mggmtcayuw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7494)

2021-07-29 23:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3zmzddae5e2dk7x6yr6qxaf42r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7495)

2021-07-29 23:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qkwh2wj7afrw8ut6bc2hy3arhr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7497)

2021-07-30 07:02 UTC, limpbrains approved these changes

2021-07-30 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-07-30 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-07-30 12:32 UTC, Overtorment requested changes

2021-07-30 12:32 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +    const savedValue = await AsyncStorage.getItem(ELECTRUM_CONNECTION_ENABLED);
this is an unreadable mess because the flag should be inverted.
the default value is electrum enabled, right? so explicit write to flag should disable it.
`ELECTRUM_CONNECTION_DISABLED`

2021-07-30 12:32 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +      'Electrum connection disabled by user. Perhaps we are attempting to show this network error alert after the user disabled connections.',
this should never happen..?

2021-07-30 12:32 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +module.exports.ELECTRUM_CONNECTION_ENABLED = ELECTRUM_CONNECTION_ENABLED;
dont expose the flag, expose methods to modify it.
incapsulation, baby

2021-07-30 12:32 UTC, Overtorment commented on screen/settings/electrumSettings.js
>      return (
to make the diff smaller, is it possible to make another renderer that will return limited stuff..?
so you wont have to put a lot of existing stuff inside an IF statement (and increase indentation)

2021-07-30 13:54 UTC, marcosrdz commented on blue_modules/BlueElectrum.js
> +      'Electrum connection disabled by user. Perhaps we are attempting to show this network error alert after the user disabled connections.',
presentNetworkErrorAlert  - it can. there could be a race condition between the time it reports connection failure and the time you disabled electrum.

2021-07-30 14:10 UTC, marcosrdz commented
@Overtorment  changes applied

2021-07-30 14:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kccrc5p3uef1x9mqc9yv7xt8zc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7506)

2021-07-31 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-07-31 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-08-01 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-01 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-08-02 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-02 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-08-02 13:56 UTC, Overtorment requested changes

2021-08-02 13:56 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +    }
this could be simplified to

```
return !(await AsyncStorage.getItem(ELECTRUM_CONNECTION_DISABLED));
```

2021-08-02 13:56 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +  return AsyncStorage.setItem(ELECTRUM_CONNECTION_DISABLED, enabled ? '1' : '0');
istead of '0' either clear the variable or write ''

2021-08-02 13:59 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +  return AsyncStorage.setItem(ELECTRUM_CONNECTION_DISABLED, enabled ? '1' : '0');
plus it doesnt work as expceted. tested on appetize

2021-08-02 15:38 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8r75tuaegkeya99p24u64a43e0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7537)

2021-08-02 16:11 UTC, marcosrdz commented
@Overtorment  forgot to update code after text was changed to offline mode. fixed.

2021-08-03 10:22 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-03 10:22 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-08-03 11:27 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +    }
damit why cant you just write 

`savedValue = !!(await AsyncStorage.getItem(ELECTRUM_CONNECTION_DISABLED)`

2021-08-03 11:28 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +    }
`isDisabled = !!(await AsyncStorage.getItem(ELECTRUM_CONNECTION_DISABLED);`

2021-08-03 11:30 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +    }
```js
async function isDisabled() {
  try {
    return !!(await AsyncStorage.getItem(ELECTRUM_CONNECTION_DISABLED));
  } catch {
    return false;
  }
}
```

2021-08-03 11:40 UTC, Overtorment approved these changes

2021-08-04 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-05 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-06 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-07 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-08 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-09 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-10 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-08-10 14:35 UTC, merged