REF: Use new UIMenu
BlueWallet/BlueWallet pull request #3599
Opened 2021-08-16 04:43 UTC by marcosrdz

![Simulator Screen Shot - iPhone 12 - 2021-08-15 at 16 27 32](https://user-images.githubusercontent.com/4793122/129512372-b9d9c7d8-78b1-4105-aa5d-e9e9d0c44872.png)

2021-08-16 04:44 UTC, marcosrdz commented
iOS 13 introduced new UIMenu. Tooltip is reserved for TextInputs.

2021-08-16 04:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hm6jb1zbgrry2uq1qtc8xyb1bw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7782)

2021-08-16 05:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m117p1v26xzdgdcujxdr6d104c?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7783)

2021-08-16 05:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/myhb24rafrufu94339w2f0nvjw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7784)

2021-08-16 08:58 UTC, Overtorment commented
бля показалось что тут хуй написано
![image](https://user-images.githubusercontent.com/1913337/129538280-7674e918-0283-4c92-8697-5ea954b51502.png)

2021-08-16 09:23 UTC, Overtorment requested changes
сrashes upon launch.

also, provide a full list of replaced tooltips for QA

2021-08-16 09:23 UTC, Overtorment commented on BlueComponents.js
> +    if (id === 'walletBalanceVisibility') {
would be nice to refactor it into `BlueWalletNavigationHeader` class static constant, so there are no magic constants.

2021-08-16 09:23 UTC, Overtorment commented on BlueComponents.js
> +        </ToolTipMenu>
starrting now, lets split BlueComponents into separate component files every time we touch BlueComponents

2021-08-16 09:23 UTC, Overtorment commented on BlueComponents.js
> +    if (id === 'copyAmount') {
class constants plz

2021-08-16 09:23 UTC, Overtorment commented on BlueComponents.js
> +        </ToolTipMenu>
preferably TS

2021-08-16 09:23 UTC, Overtorment commented on components/TooltipMenu.js
> +const ToolTipMenu = props => {
is that a tootlip file for macos & windows ..?

2021-08-16 09:23 UTC, Overtorment commented on components/addresses/AddressItem.js
> +    if (id === 'copyToClipboard') {
class constants

2021-08-16 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2021-08-16 13:52 UTC, marcosrdz commented on components/TooltipMenu.js
> +const ToolTipMenu = props => {
Windows. Theres no tooltip available for Windows at the moment so this would allow the app to proceed rendering and not crash due to lack of compatibility

2021-08-16 13:52 UTC, marcosrdz commented on components/TooltipMenu.js
> +const ToolTipMenu = props => {
macOS uses TooltipMenu.ios.js

2021-08-16 16:10 UTC, marcosrdz commented on BlueComponents.js
> +    if (id === 'walletBalanceVisibility') {
Done

2021-08-16 16:10 UTC, marcosrdz commented on BlueComponents.js
> +        </ToolTipMenu>
Done

2021-08-16 16:10 UTC, marcosrdz commented on BlueComponents.js
> +    if (id === 'copyAmount') {
Done

2021-08-16 16:10 UTC, marcosrdz commented on components/addresses/AddressItem.js
> +    if (id === 'copyToClipboard') {
Done

2021-08-16 16:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jmrgj5hqwz7p3f45gbpuhn1ehr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7792)

2021-08-16 17:32 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ephvt1yf5qrpnpw08vnfn6vrgc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7793)

2021-08-16 17:37 UTC, marcosrdz commented
Tooltips used:

   CopyAmount
   CopyNote
    OpenInBlockExplorer
    ExpandNote
   CopyBlockExplorerLink
    CopyTXID
Share

These can be found by tap and holding Wallet balance, transaction row, QRCodes in Receive/XPub/Invoice

2021-08-16 19:26 UTC, marcosrdz commented
> сrashes upon launch.
> 
> 
> 
> also, provide a full list of replaced tooltips for QA

Crash resolved. Tooltips list provided

2021-08-16 19:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rmxex4d51v53gx141ekmhg0g80?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7794)

2021-08-16 21:36 UTC, marcosrdz commented
> бля показалось что тут хуй написано
> 
> ![image](https://user-images.githubusercontent.com/1913337/129538280-7674e918-0283-4c92-8697-5ea954b51502.png)
> 
> 

Privet

2021-08-17 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2021-08-17 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-08-17 10:49 UTC, Overtorment approved these changes

2021-08-17 13:38 UTC, limpbrains requested changes

2021-08-17 14:04 UTC, marcosrdz commented on components/TooltipMenu.ios.js
> +  children: PropTypes.node.isRequired,
Updated to isrequired

2021-08-17 14:18 UTC, limpbrains approved these changes

2021-08-17 22:24 UTC, brettl-03 commented
> Tooltips used:
> 
> CopyAmount
> CopyNote
> OpenInBlockExplorer
> ExpandNote
> CopyBlockExplorerLink
> CopyTXID
> Share
> 
> These can be found by tap and holding Wallet balance, transaction row, QRCodes in Receive/XPub/Invoice

Thanks @marcosrdz! 
So just to confirm and make sure, are the UIMenu updates / replaced tooltips that were implemented and I am to verify/test as part of this PR, are they exclusively for iOS changes then? Are there any changes made to the Android tooltips as well or?

2021-08-17 22:25 UTC, marcosrdz commented
just iOS

2021-08-17 23:14 UTC, marcosrdz commented
Build 1629209023 is being processed on TestFlight. U should see it out within the hour

2021-08-18 04:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/a0kmweymkmxajud01agbpuuk00?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7804)

2021-08-18 05:25 UTC, marcosrdz commented
Fixed a bug in build 1629261065 where tooltip wouldnt show for Copy Block explorer link

2021-08-18 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @brettl-03] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/brettl-03

2021-08-18 19:58 UTC, brettl-03 commented
Hey @marcosrdz! Quick question - what kind of action are we expecting to get from tapping on the "Expand Note" option in the tooltip menu? I have tried using it, and it's not doing anything, does this action only apply to certain circumstances or?

2021-08-18 19:59 UTC, marcosrdz commented
Its for large notes that get clipped

2021-08-18 20:00 UTC, marcosrdz commented
We currently dont have code to detect if a note is clipped so that option is currently always available

2021-08-18 20:02 UTC, brettl-03 commented
Awesome! Exactly the info I was looking for, thanks

2021-08-18 20:33 UTC, brettl-03 approved these changes
Testing passes: New iOS UIMenu for tooltips - tested on my iPhone Xr via TestFlight build 1629261065

The following UIMenu tooltips are present and functional within the app for iOS -
- [X] CopyAmount
- [X] CopyNote
- [X] OpenInBlockExplorer
- [X] ExpandNote
- [X] CopyBlockExplorerLink
- [X] CopyTXID
- [X] Share
Found by tap and holding... 
- [X] Wallet balance
- [X] Transaction row
- [X] QRCodes in Receive/XPub/Invoice

2021-08-18 20:34 UTC, merged

2021-08-18 20:34 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!