FIX: BugSnag would cycle through sendEvents in offline mode
BlueWallet/BlueWallet pull request #3700
Opened 2021-08-28 05:13 UTC by marcosrdz

2021-08-28 05:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xh0h9b75ehhzhm22bny46tq654?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8008)

2021-08-28 07:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xzp0dh44cveed5gcxfz7va8ah8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8011)

2021-08-28 09:25 UTC, Overtorment requested changes

2021-08-28 09:25 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +  if (await isDisabled()) return;
that feels wrong. in theory execution should not reach here in offline mode

2021-08-28 15:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1nmpavvwdfrvkvm7fvjyzdktkm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8023)

2021-08-29 09:05 UTC, Overtorment approved these changes

2021-08-29 09:17 UTC, merged

2021-08-29 09:17 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!