Polishing en.json
BlueWallet/BlueWallet pull request #3707
Opened 2021-08-29 15:41 UTC by mcsaeid

2021-08-29 16:25 UTC, marcosrdz approved these changes

2021-08-29 19:12 UTC, Overtorment requested changes
e2e tests failed because test checks this specific string:


`await expect(element(by.text('Not a valid LNDHub URI'))).toBeVisible();`

(test is in the file `tests/e2e/bluewallet.spec.js`)

2021-08-29 19:13 UTC, marcosrdz requested changes

2021-08-29 19:13 UTC, marcosrdz commented on loc/en.json
> +    "lightning_error_lndhub_uri": "Invalid LNDHub URI",
Update blue wallet.spec.js line 106

2021-08-29 20:26 UTC, mcsaeid commented on loc/en.json
> +    "lightning_error_lndhub_uri": "Invalid LNDHub URI",
Thanks for the help. It is done.

2021-08-29 20:50 UTC, Overtorment approved these changes

2021-08-30 02:33 UTC, marcosrdz approved these changes

2021-08-30 03:51 UTC, merged