ADD: lightning address send support (closes #3690)
BlueWallet/BlueWallet pull request #3717
Opened 2021-08-30 17:15 UTC by Overtorment

2021-08-30 17:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f95hct90u728vjmbav5g73xaqw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8061)

2021-08-30 17:37 UTC, marcosrdz requested changes

2021-08-30 17:37 UTC, marcosrdz commented on screen/lnd/lnurlPay.js
> +  }, [lnurl, pop]);
Don't think pop needs to be in useEffect dependencies as its not something we need to keep track of. what do u think @limpbrains  ?

2021-08-30 19:00 UTC, Overtorment commented on screen/lnd/lnurlPay.js
> +  }, [lnurl, pop]);
eslint complained that its not on deps list, so I added.
don't really understand whats going on here

2021-08-30 20:19 UTC, limpbrains commented on screen/lnd/lnurlPay.js
> +  }, [lnurl, pop]);
I think it is better to follow eslint `react-hooks/exhaustive-deps` rule and list all deps in array, like it is here. 
Especially if you don't know whats going on :)
I hope react-navigation doesn't mutate pop() too often

2021-08-30 20:27 UTC, limpbrains approved these changes
According to code `asdasd @domain` is a valid address. I guess it's ok.

2021-08-30 21:47 UTC, Overtorment commented
Good catch. Will patch it later

On Mon, 30 Aug 2021 at 21:27, Ivan ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> According to code asdasd @domain is a valid address. I guess it's ok.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BlueWallet/BlueWallet/pull/3717#pullrequestreview-742041613>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOTD6I3W3FRYNLDAU5IXHLT7PSULANCNFSM5DCJ4C4Q>
> .
>

2021-08-30 21:50 UTC, marcosrdz approved these changes

2021-08-30 21:51 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

2021-08-30 21:51 UTC, merged

2021-09-02 16:03 UTC, xanoni commented
nice, thank you