REF: Use NativeStack
BlueWallet/BlueWallet pull request #3774
Opened 2021-09-08 18:14 UTC by marcosrdz

2021-09-08 18:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zzh9maf214ggd7rgj5c8er4vx0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8194)

2021-09-09 01:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y2qed133579qzv5cnxxy351kbg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8195)

2021-09-09 02:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v95ev0vn9y44tz616yt211vf54?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8196)

2021-09-09 02:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n6bukgv8zynaaq3nq3peqy82h0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8197)

2021-09-09 02:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xdcm8ffbp1uazuh5dwtk29d4m0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8198)

2021-09-09 14:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/udjqyuvkutmh31jbwv8a0pm9d4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8206)

2021-09-09 14:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ztcp6mfbw8rbw7nwv74p2m7qdr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8209)

2021-09-09 17:29 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u0n4ga3uvw1behg3aatumw19tm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8212)

2021-09-09 17:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pkf0ehqfvhh268zw4jv7bq3jx8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8213)

2021-09-09 17:56 UTC, marcosrdz commented
Greatly improves table and macOS UX. Performance improvement for navigation on iOS and Android. Has what's needed for continuing Windows work. 

@ncoelho  please check for any styling issues

Currently looking at why e2e fails even though I am able to manually succeed the flow

2021-09-09 18:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tj6wrt58212jd7uw8nyktz03yg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8215)

2021-09-09 19:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e38hbjcut14z8cxkxj5n8m0d60?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8217)

2021-09-10 04:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yk6f90ceu0dfv747mf643kqghg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8221)

2021-09-10 04:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4kuf6ah5mm5y5pd3ptvheptcvg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8222)

2021-09-10 04:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b2xjz2txdtyh6xn5ve8a3zdwpc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8223)

2021-09-10 04:32 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ncw8cqt3t5xwfvkmd6zfz9wger?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8224)

2021-09-10 07:45 UTC, limpbrains approved these changes

2021-09-10 07:56 UTC, ncoelho requested changes
- [ ]  Lightning > refill with external wallet not loading. And freezes the app, after this error go to onchain wallet and send screen doesn't load.

- [ ] Confirmations element lost the style

![E-SV3w0UUAE5kvv](https://user-images.githubusercontent.com/1238429/132818992-cfa41b59-4ae9-46a3-b973-dbfd4588c0df.png)

- [ ] denomination lost the style (color) on send screen 
<img width="337" alt="Screenshot 2021-09-10 at 09 49 38" src="https://user-images.githubusercontent.com/1238429/132819400-466fc92b-9754-4511-ad69-55d7bcc6958d.png">

- [ ] There's a "color glitch" on moving from the list to the transaction screen on the navigation header.

https://user-images.githubusercontent.com/1238429/132819858-50aefa78-7dd7-41a1-8790-34a4b294dd6f.mov

- [ ] Status bar goes white on settings screen on android.

- [ ] When going from the wallet view to the main view, there's an abrupt change on the status bar color (light mode), I've seen other react apps to this change smoothly with a fade animation instead of an abrupt change. Details, but would be nice to see if it can be improved.

- [ ] there's a close (x) on the create wallet backup screen.

- [ ] there's a jump on initializing the app where the navigation bar loads only after everything.

- [ ] when going to the settings screen, it loads with the big title hidden :) only after scrolling it appears.

- [ ] Reoder screen header, looks weird. Something missing there, is it push or pull?

2021-09-10 07:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uqeev5ydurzakp67ewwvq0tdw0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8229)

2021-09-10 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-09-10 11:08 UTC, Overtorment requested changes

2021-09-10 11:08 UTC, Overtorment commented on screen/wallets/addMultisigStep2.js
> +  // }, [navigation, hasUnsavedChanges, cosigners]);
dead code. usually, its better to remove it.

2021-09-10 11:08 UTC, Overtorment commented on screen/wallets/hodlHodl.js
> +    if (e.data.closing === false) {
return early, and you will be able to revert to previous indentation, and less LOC will be marked as changed

2021-09-10 11:08 UTC, Overtorment commented on screen/wallets/reorderWallets.android.js
> +          }}
it appears that reordering code is duplicated in android & ios.
its better to isolate it in a separate func. you could even write tests for it.
also, if you're worried about it, you could add some safety checks in `setWalletsWithNewOrder()`, e.g. old array length equals new array length, and its greater than 0

2021-09-10 11:08 UTC, Overtorment commented on screen/wallets/viewEditMultisigCosigners.js
> +  // }, [isSaveButtonDisabled]);
dead code

2021-09-10 11:20 UTC, Overtorment commented
i also tested a bit on appetize and haven't found any issues

2021-09-10 12:31 UTC, marcosrdz commented on screen/send/psbtMultisig.js
> +      const receivedPSBT = bitcoin.Psbt.fromBase64(receivedPSBTBase64);
It was outside the try catch so if invalid data was fed it would crash the app instead of throwing an alert

2021-09-10 13:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/advqygqbg3m13x8tqtedq329hg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8237)

2021-09-10 21:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yy4wcd473efdkbvjg9huak5vag?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8244)

2021-09-10 22:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w49k97cmbkjzwpr84vv9n85ub0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8245)

2021-09-10 22:38 UTC, marcosrdz commented on screen/wallets/reorderWallets.android.js
> +          }}
It has different renders. I would wait for an updated package with a fix to merge em into 1 file. The android renders must be different from the Mac and iOS renders

2021-09-10 22:39 UTC, marcosrdz commented on screen/wallets/reorderWallets.android.js
> +          }}
Not only different renders but also different functions for when rows get moved

2021-09-11 01:12 UTC, marcosrdz commented on screen/wallets/addMultisigStep2.js
> +  // const hasUnsavedChanges = Boolean(cosigners.length > 0 && cosigners.length !== n);
Shall it be removed or kept commented for once the package supports it?

2021-09-11 03:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4znnar3rdhxm4uf1wv3x754aw4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8246)

2021-09-11 03:44 UTC, marcosrdz commented
> * [x ]   Lightning > refill with external wallet not loading. And freezes the app, after this error go to onchain wallet and send screen doesn't load.
> * [ ]  Confirmations element lost the style
> 
> ![E-SV3w0UUAE5kvv](https://user-images.githubusercontent.com/1238429/132818992-cfa41b59-4ae9-46a3-b973-dbfd4588c0df.png)
> 
> * [x ]  denomination lost the style (color) on send screen
> 
> <img alt="Screenshot 2021-09-10 at 09 49 38" width="337" src="https://user-images.githubusercontent.com/1238429/132819400-466fc92b-9754-4511-ad69-55d7bcc6958d.png">
> 
> * [ ]  There's a "color glitch" on moving from the list to the transaction screen on the navigation header.
> 
>  Screen.Recording.2021-09-10.at.09.52.01.mov 
> 
> * [ ]  Status bar goes white on settings screen on android.
> * [ ]  When going from the wallet view to the main view, there's an abrupt change on the status bar color (light mode), I've seen other react apps to this change smoothly with a fade animation instead of an abrupt change. Details, but would be nice to see if it can be improved.
> * [x ]  there's a close (x) on the create wallet backup screen.
> * [ ]  there's a jump on initializing the app where the navigation bar loads only after everything.

https://github.com/software-mansion/react-native-screens/pull/1029



> * [x ]  when going to the settings screen, it loads with the big title hidden :) only after scrolling it appears.
> * [ ]  Reoder screen header, looks weird. Something missing there, is it push or pull?
its a fullscreen modal so gestures don't hijack wallet reordering

> * [ x]  lightning invoice screen has both back and close icons.
> * [ ]  transaction success screen, success animation should be centered.

2021-09-11 03:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m75a32th9agtk3g9evbtyk1wxc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8247)

2021-09-11 04:35 UTC, marcosrdz commented on screen/settings/settings.js
> +      {Platform.OS === 'android' && <BlueHeaderDefaultSub leftText={loc.settings.header} />}
Ill add it but im guessing are referring to Viewcomponents on Flatlists

2021-09-11 04:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zzze8z59q8nghvj432yjcv45j0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8249)

2021-09-11 04:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/t14x81bnfh29cmgb6bmfn98guc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8248)

2021-09-11 11:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/a1w4jj2k5wktqb26a1521fufkm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8251)

2021-09-11 14:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nn8q6j18rnvv8fhg1j92p22uy4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8252)

2021-09-11 20:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/t9jv621qzg7dyh0tp9t7n7dz2c?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8256)

2021-09-12 05:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/868kdb23ympzkk3z2455r64bt0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8257)

2021-09-13 04:10 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fz1c4t49ddy9tzhn940019etzw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8264)

2021-09-13 04:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k662r87gnayt65m63q5429ny3w?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8266)

2021-09-13 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-09-13 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2021-09-13 12:21 UTC, Overtorment commented
because this pr has screens bump as well, travis fails.
is it possible to have this pr but without screens bump?

2021-09-13 14:27 UTC, marcosrdz commented
> because this pr has screens bump as well, travis fails.
> is it possible to have this pr but without screens bump?

Just lowered it to the one currently in use. e2e should pass

2021-09-13 14:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tj7t2nujzqqj309242kfdkjx48?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8277)

2021-09-13 14:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mxhqv6gmp08j49tcn8ezjfkwtg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8276)

2021-09-13 15:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0c0z1vuf7efmt7y00y3bpgqxar?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8279)

2021-09-13 16:46 UTC, ncoelho approved these changes

2021-09-13 17:43 UTC, merged