FIX: proper fee estimation for multisig wallets (closes #3811)
BlueWallet/BlueWallet pull request #3925
Opened 2021-09-27 18:25 UTC by Overtorment

2021-09-27 18:26 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +
@junderw can you pls take a look?

2021-09-27 18:26 UTC, Overtorment commented
@jaonoctus can you take a look as well pls?

2021-09-27 19:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ejaka4py8b30x23ftpngqn6cwg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8536)

2021-09-27 22:32 UTC, junderw commented on class/wallets/multisig-hd-wallet.js
> +
I don't think you should do `u.script || `

Even if an object referring to a utxo contained something called `script` it will not be what you are looking for in regards to segwit, and I doubt it will be what you're looking for in regards to non-segwit too.

2021-09-27 22:33 UTC, junderw commented on class/wallets/multisig-hd-wallet.js
> +
Other than that, the lengths to the right of || should be correct (or close enough, erring on the side of being less than a vbyte too large)

2021-09-27 22:40 UTC, junderw commented on class/wallets/multisig-hd-wallet.js
> +
I see you're using `u.script ||` for testing.

It might be better to add a `forTest: true` attribute.

in the code: `u.script && u.script.forTesting === true ? u.script : { length: ... }`
in the tests: `{ length: 107, forTesting: true }`

2021-09-27 23:14 UTC, jaonoctus commented
When I have multisig outputs, the fee is lower than expected.

## test 01
```
1 input (2/3 multisig)
1 output (segwit native)

electrum fee (1 sat/vByte): 146 sats
bluewallet fee (1 sat/vByte): 149 sats
```

## test 02
```
1 input (2/3 multisig)
1 output (2/3 multisig)

electrum fee (1 sat/vByte): 158 sats
bluewallet fee (1 sat/vByte): 149 sats
```

## test 03
```
2 inputs (2/3 multisig)
1 output (segwit native)

electrum fee (1 sat/vByte): 251 sats
bluewallet fee (1 sat/vByte): 254 sats
```

## test 04
```
2 inputs (2/3 multisig)
1 output (2/3 multisig)

electrum fee (1 sat/vByte): 263 sats
bluewallet fee (1 sat/vByte): 254 sats
```

## test 05
```
2 inputs (2/3 multisig)
2 output (1 segwit native, 1 2/3 multisig)

electrum fee (1 sat/vByte): 300 sats
bluewallet fee (1 sat/vByte): 288 sats
```

2021-09-28 00:36 UTC, junderw commented
I have tested using bitcoinjs-lib sizes of actual signed transactions.

See here to reproduce: https://gist.github.com/junderw/6e9610442c154cff408bcf077b3fbdab

Note: BW estimate is consistently over 4 vBytes larger than actual for p2sh. Other than that, segwit (which is easier to estimate) is within 0-1 range.

Results:

```
p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1574.7
Diff (negative is bad): 6.2999999999999545

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.1
Diff (negative is bad): 0.8999999999999773

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424.3
Diff (negative is bad): 0.6999999999999886

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1574.7
Diff (negative is bad): 6.2999999999999545

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459
Diff (negative is bad): 1

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424.2
Diff (negative is bad): 0.8000000000000114

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1574.8
Diff (negative is bad): 6.2000000000000455

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.3
Diff (negative is bad): 0.6999999999999886

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424.2
Diff (negative is bad): 0.8000000000000114

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1574.6
Diff (negative is bad): 6.400000000000091

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.4
Diff (negative is bad): 0.6000000000000227

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 423.9
Diff (negative is bad): 1.1000000000000227

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1573.5
Diff (negative is bad): 7.5

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.5
Diff (negative is bad): 0.5

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424.4
Diff (negative is bad): 0.6000000000000227

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1574.2
Diff (negative is bad): 6.7999999999999545

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.4
Diff (negative is bad): 0.6000000000000227

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424
Diff (negative is bad): 1

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1576.4
Diff (negative is bad): 4.599999999999909

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.1
Diff (negative is bad): 0.8999999999999773

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424
Diff (negative is bad): 1

p2sh-p2ms(14 of 15)
Expected: 1581
Actual: 1574.7
Diff (negative is bad): 6.2999999999999545

p2sh-p2wsh-p2ms(14 of 15)
Expected: 460
Actual: 459.1
Diff (negative is bad): 0.8999999999999773

p2wsh-p2ms(14 of 15)
Expected: 425
Actual: 424.1
Diff (negative is bad): 0.8999999999999773
```

2021-09-28 01:29 UTC, junderw approved these changes

2021-09-28 06:10 UTC, junderw requested changes
Actually, running the tests again for 2-of-3, I found that the signature sizes are for low R and low S.

low S is automatically done, but low R is not default, so if we want to stay above, 73 should be bumped to 74.

Please bump all 73 (signature estimate) to 74.

2021-09-28 10:05 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5ed7q0qwramd6c0m8e56g32th8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8558)

2021-09-28 10:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z1jbmduduvd2gbkamvc19p4vew?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8559)

2021-09-28 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2021-09-28 11:33 UTC, limpbrains approved these changes

2021-09-28 14:39 UTC, junderw approved these changes

2021-09-28 14:41 UTC, merged

2021-09-28 14:41 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

2021-09-28 15:26 UTC, Overtorment commented
merged. thanks all