FIX: 0 amounts in custom receive would result in undefined
BlueWallet/BlueWallet pull request #4179
Opened 2021-11-07 18:50 UTC by marcosrdz

2021-11-07 19:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/75ckd0cnrp0cqg1pa6g1gudg5r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9047)

2021-11-07 19:06 UTC, Overtorment requested changes

2021-11-07 19:06 UTC, Overtorment commented on screen/receive/details.js
> +    const properties = {};
so the problem is in extra spaces?
why not move this logic inside of `DeeplinkSchemaMatch.bip21encode`?
and add a unit test for that as well

2021-11-08 15:32 UTC, Overtorment requested changes

2021-11-08 15:32 UTC, Overtorment commented on class/deeplink-schema-match.js
> +    const argumentsArray = Array.from(arguments);
nice! wheres the unit test for that?

2021-11-08 15:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v3dew2yfn6ywuz7uqrtuj6q338?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9049)

2021-11-08 16:22 UTC, marcosrdz commented on screen/receive/details.js
> +    const properties = {};
Done

2021-11-08 16:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g288u7k6e2522h8yu3y2xrjbvw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9051)

2021-11-09 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-11-09 11:01 UTC, Overtorment approved these changes

2021-11-09 11:10 UTC, merged

2021-11-09 11:10 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!