Onblur
BlueWallet/BlueWallet pull request #4211
Opened 2021-11-14 15:58 UTC by marcosrdz

2021-11-14 16:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jepn128kbvddauywfcrtfgfue4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9095)

2021-11-14 18:45 UTC, limpbrains approved these changes

2021-11-15 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-11-15 21:19 UTC, limpbrains requested changes

2021-11-15 21:19 UTC, limpbrains commented on screen/wallets/import.js
> +    const valueWithSingleWhitespace = importText.replace(/^\s+|\s+$|(\r\n|\r|\n)|\s+(?=\s)/g, '');
@marcosrdz 

I guess now SLIP39 wallet import is broken. It requires a few seeds divided by '\n'

What is even this code for? It is better to have all text preparations in main import function and be tested.

2021-11-16 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-11-16 16:21 UTC, marcosrdz commented on screen/wallets/import.js
> +    const valueWithSingleWhitespace = importText.replace(/^\s+|\s+$|(\r\n|\r|\n)|\s+(?=\s)/g, '');
Reverted. This is so if the user uses the iOS OCR feature to "scan" their seed, any junk included gets filtered out.

2021-11-16 16:23 UTC, marcosrdz commented on screen/wallets/import.js
> +    const valueWithSingleWhitespace = importText.replace(/^\s+|\s+$|(\r\n|\r|\n)|\s+(?=\s)/g, '');
Not sure about moving it to the import function since this is UI adjustment rather than "business logic".

2021-11-16 16:35 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r4vv7vatek13xxr9ygh1z9dnur?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9102)

2021-11-16 16:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rhue8w162ezb5nn07gtd35xeb8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9103)

2021-11-16 17:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/eqg9rmnkw5nr2g3151tq3qz8n8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9105)

2021-11-17 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-11-17 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2021-11-18 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-11-18 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2021-11-19 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-11-19 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2021-11-19 12:28 UTC, limpbrains approved these changes

2021-11-20 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-11-21 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-11-22 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-11-22 10:58 UTC, Overtorment approved these changes

2021-11-22 10:59 UTC, merged