FIX: reject unknown segwit versions as invalid address
BlueWallet/BlueWallet pull request #4268
Opened 2021-12-05 13:25 UTC by Overtorment

@junderw can you pls take a look

2021-12-05 13:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j8x1m4yfezgw4vxu033uvpcn0r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9182)

2021-12-05 14:36 UTC, junderw commented on class/wallets/legacy-wallet.ts
> +      return decoded.version <= 1;
Segwit v0 checks are contained within `toOutputScript` so you are fine.

But you should also add some v1 checks.

1. The decoded data is 32 bytes exactly.
2. The 32 bytes is less than the field modulo.
3. The 32 bytes is a valid X point on the curve.

This check can be done easily by prepending 0x02 and using isPoint from some elliptic library.

```js
// example
const ecc = require('tiny-secp256k1'); // I notice you have 1.1.6 in dependencies
const decoded = bitcoin.address.fromBech32(address);
if (decoded.version > 1) return false;
if (decoded.version === 1 && !ecc.isPoint(Buffer.concat([
  Buffer.from([2]),
  decoded.data,
]))) return false;

return true;
```

2021-12-05 14:41 UTC, junderw requested changes
Should have more strict checks on v1 segwit.

But tbh, even the current PR is more strict than current, which is better than current.

2021-12-05 16:58 UTC, Overtorment commented on class/wallets/legacy-wallet.ts
> +      return decoded.version <= 1;
i thought lenght checks are already embedded? those asserts in my test case work fine:


```
    assert.ok(!w.isAddressValid('bc1pw5dgrnzv')); // v1, data length != 32
    assert.ok(!w.isAddressValid('bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7v8n0nx0muaewav253zgeav')); // v1, data length != 32
```

2021-12-05 17:12 UTC, junderw commented on class/wallets/legacy-wallet.ts
> +      return decoded.version <= 1;
Those are length 1 and 41. They are throwing due to the vague segwit rules.

Minimum and maximum segwit length is 2 and 40.

Your wallet will parse a 2 byte data or 40 byte data as a valid v1 address.

2021-12-05 17:13 UTC, junderw commented on class/wallets/legacy-wallet.ts
> +      return decoded.version <= 1;
```
> address.fromBech32('bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7v8n0nx0muaewav253zgeav').data.length
41
> address.fromBech32('bc1pw5dgrnzv').data.length
1
```

2021-12-05 17:13 UTC, junderw commented on class/wallets/legacy-wallet.ts
> +      return decoded.version <= 1;
https://github.com/bitcoinjs/bitcoinjs-lib/blob/93af5afe67dbc491e36bdfc8d48a00179093f7d1/ts_src/address.ts#L21-L22

2021-12-05 17:14 UTC, junderw commented on class/wallets/legacy-wallet.ts
> +      return decoded.version <= 1;
https://github.com/bitcoinjs/bitcoinjs-lib/blob/93af5afe67dbc491e36bdfc8d48a00179093f7d1/ts_src/address.ts#L35-L39

2021-12-05 18:52 UTC, Overtorment commented on class/wallets/legacy-wallet.ts
> +      return decoded.version <= 1;
fixed

2021-12-05 19:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/59z9y42d3h4xgtz37d6hbmung0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9184)

2021-12-05 23:28 UTC, junderw approved these changes
LGTM. Here are some extra failures.

```js
'bc1pllllllllllllllllllllllllllllllllllllllllllllallllscqlhrddu' // X is modulo P + 1 (invalid X, but 1 is valid, testing if wrapped modulo (P+1 mod P === 1) will pass)
'bc1pllllllllllllllllllllllllllllllllllllllllllllallllshqcgyklh' // X is modulo P - 1 (invalid X)
'bc1pqtllllllllllllllllllllllllllllllllllllllllllllhlll7zcsqylfl' // data length is 33 (valid point in compressed DER format (33 bytes))
'bc1plllllllllllllllllllllllllllllllllllllllllll0lllu9cegrnmx' // data is length 31 (valid X value with leading 0x00 trimmed)
```

These should all fail the new logic.

2021-12-05 23:32 UTC, junderw commented
This is how I generated these cases.
```js
> x.address.toBech32(Buffer.from('fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc30','hex'), 1, 'bc')
'bc1pllllllllllllllllllllllllllllllllllllllllllllallllscqlhrddu'
> x.address.toBech32(Buffer.from('fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2e','hex'), 1, 'bc')
'bc1pllllllllllllllllllllllllllllllllllllllllllllallllshqcgyklh'
> x.address.toBech32(Buffer.from('02fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2c','hex'), 1, 'bc')
'bc1pqtllllllllllllllllllllllllllllllllllllllllllllhlll7zcsqylfl'
> x.address.toBech32(Buffer.from('fffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2e','hex'), 1, 'bc')
'bc1plllllllllllllllllllllllllllllllllllllllllll0lllu9cegrnmx'
```

2021-12-05 23:33 UTC, merged

2021-12-05 23:33 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

2021-12-06 01:09 UTC, junderw commented
See #4270 for more tests

2021-12-06 13:08 UTC, Overtorment commented
thanks! added them in 3195977a0e5176b395f5358b91e8dbfa7327cda1