Add lnurl-auth support
BlueWallet/BlueWallet pull request #4315
Opened 2021-12-22 22:37 UTC by gocedoko

Motivation: I'm a BlueWallet user and I want to use it to authenticate on https://lnmarkets.com/

Specification:
https://github.com/fiatjaf/lnurl-rfc/blob/luds/04.md

I managed to test this PR only on an Android Simulator, but I think the changes are generic enough so that it should work the same across platforms.

From my testing, I could successfully authenticate on https://lightninglogin.live/ using two different lightning sub-wallets, and each of them was properly recognized/distinguished on the server across different login attempts.

The logic is that for each auth server, we infer a private key as a hash of the auth-server-URL using the wallet secret as the hashing key(seed):
```
const hmac = createHmac('sha256', wallet.secret);
hmac.write(lnurlObj.hostname);
```

After that we generate a signature of the challenge using the private key
```
const signatureObj = secp256k1.sign(Buffer.from(lnurlObj.query.k1, "hex"), privateKeyBuf);
const derSignature = secp256k1.signatureExport(signatureObj.signature);
```

And we return the signature + the public key to the server
`const response = await fetch(`${lnurlObj.href}&sig=${derSignature.toString('hex')}&key=${publicKey.toString('hex')}`);`

More testing on the other platforms as well as critique on the code are very welcome ^_^

2021-12-22 22:53 UTC, gocedoko commented on screen/lnd/lndCreateInvoice.js
> -    // calling the url
**url** is the name of the library needed to parse the lnurl, so a bit of unfortunate naming

2021-12-25 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-12-25 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-12-26 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-12-26 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-12-27 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2021-12-27 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-12-27 16:55 UTC, marcosrdz approved these changes

2021-12-27 16:59 UTC, marcosrdz commented
Please sync with master and run:

npm run lint:fix

2021-12-28 08:45 UTC, limpbrains requested changes
lnurl-rfc allows LN SERVICE to return `reason` if auth failed. Maybe we should show it, if available?
`{"status": "ERROR", "reason": "error details..."}` https://github.com/fiatjaf/lnurl-rfc/blob/luds/04.md

2021-12-28 08:45 UTC, limpbrains commented on screen/lnd/lnurlAuth.js
> +});
This needs to be localize

2021-12-28 08:45 UTC, limpbrains commented on screen/lnd/lnurlAuth.js
> +              <BlueText style={styles.alignSelfCenter}>with your LN wallet?</BlueText>
This needs to be localize

2021-12-28 08:45 UTC, limpbrains commented on screen/lnd/lnurlAuth.js
> +          <BlueText style={styles.alignSelfCenter}>{lnurlAuthMsgs(lnurlObj.hostname)[lnurlObj.query.action || 'auth'].s}</BlueText>
This needs to be localize

2021-12-28 08:45 UTC, limpbrains commented on screen/lnd/lnurlAuth.js
> +          <BlueText style={styles.alignSelfCenter}>{`Could not authenticate to ${lnurlObj.hostname}.`}</BlueText>
This needs to be localize

2021-12-28 09:25 UTC, limpbrains commented
Tested with LNMarkets, works good!

2021-12-28 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-12-29 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-12-29 14:34 UTC, gocedoko commented on screen/lnd/lnurlAuth.js
> +              <BlueText style={styles.alignSelfCenter}>with your LN wallet?</BlueText>
added localization

2021-12-29 14:34 UTC, gocedoko commented on screen/lnd/lnurlAuth.js
> +          <BlueText style={styles.alignSelfCenter}>{lnurlAuthMsgs(lnurlObj.hostname)[lnurlObj.query.action || 'auth'].s}</BlueText>
added localization

2021-12-29 14:34 UTC, gocedoko commented on screen/lnd/lnurlAuth.js
> +          <BlueText style={styles.alignSelfCenter}>{`Could not authenticate to ${lnurlObj.hostname}.`}</BlueText>
added localization

2021-12-29 14:36 UTC, gocedoko commented on screen/lnd/lnurlAuth.js
> +});
moved to the localization json file

2021-12-29 14:37 UTC, gocedoko commented
> lnurl-rfc allows LN SERVICE to return `reason` if auth failed. Maybe we should show it, if available? `{"status": "ERROR", "reason": "error details..."}` https://github.com/fiatjaf/lnurl-rfc/blob/luds/04.md

Done, message is now shown on the error screen. Tested by passing a wrong signature.

2021-12-29 15:07 UTC, limpbrains commented
@gocedoko please remove the third nesting level in en.json, `react-localization` doesn't support this. Only 2 levels. 
Also we are using Transifex, so leaving any comments in json files is useless. Better remove them.

2021-12-29 19:26 UTC, gocedoko commented
> @gocedoko please remove the third nesting level in en.json, `react-localization` doesn't support this. Only 2 levels. Also we are using Transifex, so leaving any comments in json files is useless. Better remove them.

Done. Thanks for the remarks.

2021-12-29 19:49 UTC, limpbrains approved these changes

2021-12-30 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2021-12-31 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-01 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-02 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-03 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-04 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-05 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-06 10:21 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-07 10:22 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-07 12:30 UTC, Overtorment requested changes
good job on this!
needs some brushing up, but overall LGTM

2022-01-07 12:30 UTC, Overtorment commented on loc/en.json
> +      "q": "Do you want to register an account at ",
i see 3 nesting levels, is this ok @limpbrains ?

2022-01-07 12:30 UTC, Overtorment commented on screen/lnd/lndCreateInvoice.js
> +        const resp = await fetch(parsedUrl, { method: 'GET' });
looks like if you rename `parsedUrl` back to `url` diff will be smaller

2022-01-07 12:30 UTC, Overtorment commented on screen/lnd/lnurlAuth.js
> +  const authenticate = useCallback(() => {
belongs to `class/lnurl.js`
also needs a unit test in `tests/unit/lnurl.test.js`

2022-01-07 12:30 UTC, Overtorment commented on screen/lnd/lnurlAuth.js
> +          onPress={() => navigate('SelectWallet', { onWalletSelect, chainType: Chain.OFFCHAIN })}
we have a helper for that, if that can make your life easier. example:

```
import selectWallet from '../../helpers/select-wallet';
...

const wallets2use = wallets.filter((w: AbstractWallet) => w.chain === Chain.ONCHAIN);
const wallet = await selectWallet(navigation.navigate, name, false, wallets2use, 'Onchain wallet is required to sign a message');
```

2022-01-07 12:30 UTC, Overtorment commented on screen/lnd/lnurlAuth.js
> +          onPress={() => navigate('SelectWallet', { onWalletSelect, chainType: Chain.OFFCHAIN })}
helper

2022-01-07 12:30 UTC, Overtorment commented on screen/lnd/lnurlAuth.js
> +    const hmac = createHmac('sha256', wallet.secret);
i have some doubts here. `secret` has username, password AND host. feels like authentication should be host-agnostic, in case user ports his LNDHUB to a new host with new address, so old logins should just work

2022-01-07 12:30 UTC, Overtorment commented on screen/lnd/lnurlAuth.js
> +        const response = await fetch(`${lnurlObj.href}&sig=${derSignature.toString('hex')}&key=${publicKey.toString('hex')}`);
in `tests/unit/lnurl.test.js` theres an example how to mock fetch request to test everything properly

2022-01-07 12:55 UTC, Overtorment commented on screen/lnd/lnurlAuth.js
> +  const authenticate = useCallback(() => {
just had a thought, that actual signing should be isolated in `class/wallets/lightning-custodian-wallet.js` in a polymorphism-friendly way, so that we can later add signing capabilities to other lightning wallet classes (e.g. class/wallets/lightning-ldk-wallet.ts, which is planned here: https://github.com/BlueWallet/rn-ldk/issues/3 )

2022-01-07 13:37 UTC, limpbrains commented on loc/en.json
> +      "q": "Do you want to register an account at ",
Not actually, but I thought I will refactor this later. 
Since it has been noted, @gocedoko , please fix

2022-01-10 21:23 UTC, gocedoko commented on screen/lnd/lnurlAuth.js
> +    const hmac = createHmac('sha256', wallet.secret);
Hmm, **this.secret** as an attribute does not contain the host, but getSecret() does.
I'll move this to `class/wallets/lightning-custodian-wallet.js` anyways.

from **class/wallets/lightning-custodian-wallet.js**
`this.secret = 'lndhub://' + json.login + ':' + json.password;`
but 
`getSecret() {
    return this.secret + '@' + this.baseURI;
  }
`

2022-01-19 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-20 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-21 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-22 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-23 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-24 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-26 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-27 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-28 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-29 10:18 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-30 10:18 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-01-31 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-02-01 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-02-02 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-02-03 10:18 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-02-04 10:16 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-02-05 10:16 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-02-06 10:18 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-02-07 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-02-08 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-02-09 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-02-09 19:23 UTC, Overtorment approved these changes
LGTM. lets fix conflicts & merge

2022-02-11 14:19 UTC, Overtorment commented
merged in https://github.com/BlueWallet/BlueWallet/pull/4493

2022-02-11 14:19 UTC, closed without merging

2022-02-20 12:31 UTC, Overtorment commented
just tested it, works great!

a question tho. we have ldk non-custodial lightning wallet type (still WIP), and auth worked with this wallet as well. but the signing process happened purely in js as implemented, using secret string in our own format (used to seed entropy to ldk native code), so this is detached from the actual node pubkey this ldk wallet has. how critical is that?

2022-02-20 15:31 UTC, limpbrains commented
> just tested it, works great!
> 
> a question tho. we have ldk non-custodial lightning wallet type (still WIP), and auth worked with this wallet as well. but the signing process happened purely in js as implemented, using secret string in our own format (used to seed entropy to ldk native code), so this is detached from the actual node pubkey this ldk wallet has. how critical is that?

I think this is even better. This way you can recover your auth profile from a ldk backup on another phone.

2022-02-20 19:17 UTC, Overtorment commented
@limpbrains ldk is seeded from the same secret we store in `this.secret`, so signature in native ldk's code will also be reproduceable