DEL: AOPP
BlueWallet/BlueWallet pull request #4431
Opened 2022-01-27 21:00 UTC by marcosrdz

2022-01-27 21:12 UTC, Overtorment commented on android/app/src/main/AndroidManifest.xml
> -          <data android:scheme="aopp" />
only aopp, the rest we need for safello.
also, there should be ios counterpart i think

2022-01-27 21:13 UTC, marcosrdz commented on android/app/src/main/AndroidManifest.xml
> -          <data android:scheme="aopp" />
Fixed

2022-01-27 21:16 UTC, Overtorment requested changes

2022-01-27 21:16 UTC, Overtorment commented on screen/wallets/signVerify.js
> +      newSignature = wallet.signMessage(message, address);
the default is true. is this what we want here? @limpbrains

2022-01-27 21:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f7hudgrwh0cuxfamfy19yu19w0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9452)

2022-01-27 21:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/chn31cwk7m3rmuccm7f88qb6gr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9453)

2022-01-27 21:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k9wk0dcbf1ub9a06qrbq8wvrgm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9454)

2022-01-28 07:31 UTC, limpbrains commented on screen/wallets/signVerify.js
> +      newSignature = wallet.signMessage(message, address);
Yes

2022-01-28 07:38 UTC, limpbrains commented on screen/wallets/signVerify.js
> +      newSignature = wallet.signMessage(message, address);
Actually, no, I was looking at Outdated code.
It should use segwit and be `newSignature = wallet.signMessage(message, address);`

2022-01-28 10:20 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2022-01-28 16:56 UTC, marcosrdz commented on screen/wallets/signVerify.js
> +      newSignature = wallet.signMessage(message, address);
Done

2022-01-28 17:10 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1j8fa4vhhqxrxu1xyec2rnyubw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9464)

2022-01-28 17:24 UTC, limpbrains approved these changes

2022-01-28 17:42 UTC, Overtorment approved these changes

2022-01-28 18:00 UTC, merged

2022-01-28 18:00 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!