OPS: Update to RN 67
BlueWallet/BlueWallet pull request #4467
Opened 2022-02-07 16:44 UTC by marcosrdz

2022-02-07 17:07 UTC, Overtorment requested changes

2022-02-07 17:07 UTC, Overtorment commented on .bundle/config
> +BUNDLE_PATH: "vendor/bundle"
this is new. whats this?

2022-02-07 17:07 UTC, Overtorment commented on .gitattributes
> -*.bat text eol=crlf
i think we need this file, or developers on ms windows have issues. is that ok that this file is being deleted?

2022-02-07 17:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2tkm0e8b1a4gta8kyv8ypj2030?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9517)

2022-02-07 19:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7924hgmr76ertd474qecygwt34?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9519)

2022-02-07 21:10 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w905u262y0uhmrz2pah4gqz1kg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9522)

2022-02-07 21:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k9h10hhn999e7hrj5envavmnxm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9523)

2022-02-09 19:38 UTC, Overtorment commented
is this a WIP  PR..?

2022-02-09 19:44 UTC, marcosrdz commented
Yup. Waiting on official new Tor release. The PR we were waiting for got merged but no tag has been made

2022-02-09 19:53 UTC, Overtorment commented
@gabidi  humbly waiting for a release 🙏🏻

2022-02-09 21:24 UTC, gabidi commented
Published :)

2022-02-09 21:27 UTC, marcosrdz commented
> Published :)

Just saw! Thank you!

2022-02-09 21:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xv6p94f5wajdcavfg1npr943h4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9534)

2022-02-09 22:08 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6z9knb987zmc1w5n4yyqc0zr50?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9539)

2022-02-10 20:03 UTC, marcosrdz commented on .gitattributes
> -*.bat text eol=crlf
It was removed on 0.67

2022-02-10 20:04 UTC, marcosrdz commented on .ruby-version
> +2.7.4
Yup. Following the upgrade helper RN guide.

https://react-native-community.github.io/upgrade-helper/

2022-02-10 20:04 UTC, marcosrdz commented on Gemfile
> +source 'https://rubygems.org'
Yup. Following the upgrade helper RN guide.

https://react-native-community.github.io/upgrade-helper/

2022-02-10 20:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v4ry9dngu5dxm9gu6y4m667fg8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9558)

2022-02-11 10:19 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-02-11 11:47 UTC, merged