FIX: electrs-esplora 'verbose transactions are currently unsupported'…
BlueWallet/BlueWallet pull request #4580
Opened 2022-03-13 19:29 UTC by Overtorment

… (closes #3985)

2022-03-13 19:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2362h6145q8pj0rzqz7epncp44?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9706)

2022-03-13 20:06 UTC, limpbrains requested changes

2022-03-13 20:06 UTC, limpbrains commented on blue_modules/BlueElectrum.js
> +        throw new Error(String(error?.message ?? error));
Why reconstruct exception. Just throw existing error

2022-03-13 20:06 UTC, limpbrains commented on blue_modules/BlueElectrum.js
> +          throw new Error(String(error?.message ?? error));
Same

2022-03-13 20:11 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +        throw new Error(String(error?.message ?? error));
i noticed that it is not a proper error object, for some reason its just a string (thus, this `error?.message ?? error` construct).

2022-03-14 05:28 UTC, limpbrains approved these changes

2022-03-14 05:34 UTC, merged

2022-03-14 05:34 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!