Limpbrains jest27 wip
BlueWallet/BlueWallet pull request #4754
Opened 2022-05-25 10:24 UTC by Overtorment

2022-05-25 10:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ke5aztcenqa9082cupb14uwm04?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10004)

2022-05-25 11:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2pw2am67dgpzqb9h0ncz9c76ym?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10005)

2022-05-25 12:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2qnf8vtejgjxz15bb7nu84vbug?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10006)

2022-05-25 12:19 UTC, Mack2208 approved these changes

2022-05-25 13:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uvgkemdpuwycqeqw0yybxnvvtw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10008)

2022-05-25 14:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wq83y47gbfvq60h15n3nfyy970?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10009)

2022-05-25 18:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2m8u864pq9x0xk6njg57kwdz3m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10015)

2022-05-25 18:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/11fgmrhmyk00whryckwg2ppd4m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10016)

2022-05-25 19:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dd623h6v5jctgwr06jejy95a0r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10017)

2022-05-25 20:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4h3v21f14c5rbymt7u7u40exf4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10019)

2022-05-25 21:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/grzqdmd6tq3gxrcmp8h8w4tjxm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10020)

2022-05-26 10:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yz6pzacm756f061j38xvq69qk0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10022)

2022-05-26 15:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5j0pft0f932rr5eaveum43hkm4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10023)

2022-05-26 18:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xqccwzjewwt5pvbfdxvkxcvwjw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10024)

2022-05-26 18:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/va7w52hzx52tqenpwdg5jwjk9c?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10025)

2022-05-26 19:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j0dybw56z5xqb465zh4gz7gtjw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10026)

2022-05-26 20:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gctw823rrz6y5x02cnnpjprcqr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10027)

2022-05-27 10:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7p3f8fvhv0jcgtddx30y9h3ddw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10028)

2022-05-27 10:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/19gj716r2wd03y3fab5t0gpbbm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10029)

2022-05-27 10:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/71cfja47tymj4ugwpq3jzb86jr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10030)

2022-05-27 10:47 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6td60wh16p16bm0vf8dhteqa68?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10032)

2022-05-27 14:40 UTC, limpbrains requested changes

2022-05-27 14:40 UTC, limpbrains commented on package.json
> +    "detox": "^19.6.9",
Need to lock this version

2022-05-27 14:40 UTC, limpbrains commented on tests/unit/hd-aezeed.test.js
> +  it.only('can import mnemonics and generate addresses and WIFs', async function () {
.only

2022-05-29 10:58 UTC, Overtorment commented on tests/unit/hd-aezeed.test.js
> +  it.only('can import mnemonics and generate addresses and WIFs', async function () {
good catch

2022-05-29 15:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1nr0gzpxcqvj3hz7u63ytpv68c?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10034)

2022-05-29 21:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rawph3h7y7rrgkvummhq5cue1m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10035)

2022-05-30 10:54 UTC, limpbrains commented on .circleci/config.yml
> +          no_output_timeout: 60m
you probably want to remove this

2022-05-30 10:56 UTC, limpbrains commented on package.json
> +    "detox": "^19.6.9",
and this

2022-05-30 12:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/af83knagyw9j711uayjrqfawqr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10037)

2022-05-30 13:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vpzdgq5cc2k3r5uryjjpqzpgp0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10038)

2022-05-30 16:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mcgge6vu2tv4htzbb25tp6er94?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10039)

2022-05-30 17:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/unqjhm5rja39tyx3jcjvycffrr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10043)

2022-06-01 18:46 UTC, limpbrains commented on .circleci/config.yml
> +          no_output_timeout: 60m
Yes

2022-06-02 19:10 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pm78v5uyq65ddz3588u9p17hfr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10061)

2022-06-03 13:33 UTC, limpbrains approved these changes
Awesome, now we can start migrating to jest 28!

2022-06-03 16:51 UTC, Overtorment commented
> Awesome, now we can start migrating to jest 28!

😲

2022-06-03 16:54 UTC, merged