REF: convert wallet class to typescript
BlueWallet/BlueWallet pull request #5001
Opened 2022-09-02 23:48 UTC by Overtorment

2022-09-03 00:00 UTC, Overtorment commented
@demerzel3 @limpbrains i refactored some classes to typescript, can you pls review?

2022-09-03 00:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wq7xedf4vkkm27zampnpighlbu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10417)

2022-09-03 00:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wvgiu4bs7dgi2pzyobx5it7nty?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10418)

2022-09-03 10:35 UTC, limpbrains approved these changes

2022-09-03 16:51 UTC, marcosrdz approved these changes

2022-09-05 21:38 UTC, demerzel3 requested changes

2022-09-05 21:38 UTC, demerzel3 commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    const txs: Record<string, any> = {};
I think you should be able to use `ElectrumHistory` in place of `any` here.

2022-09-05 21:38 UTC, demerzel3 commented on class/wallets/abstract-hd-electrum-wallet.ts
>              delete clonedTx.vin;
You can make this block typesafe by using some spreading instead of `Object.assign` and mutations:
```ts
            const { vin: txVin, vout: txVout, ...txRest } = tx;
            const clonedTx = { ...txRest, inputs: txVin.slice(0), outputs: txVout.slice(0) };
```

2022-09-05 21:38 UTC, demerzel3 commented on class/wallets/abstract-hd-electrum-wallet.ts
>              delete clonedTx.vout;
Same code applies here probably?
```
const { vin: txVin, vout: txVout, ...txRest } = tx;
const clonedTx = { ...txRest, inputs: txVin.slice(0), outputs: txVout.slice(0) };
```

2022-09-05 21:38 UTC, demerzel3 commented on class/wallets/abstract-hd-electrum-wallet.ts
> +      const outputData: any = {
You could avoid this `any` by building the object directly into the call to `addOutput` like so:
```ts
      psbt.addOutput({
        address: output.address,
        value: output.value,
        bip32Derivation:
          change && path && pubkey
            ? [
                {
                  masterFingerprint: masterFingerprintBuffer,
                  path,
                  pubkey,
                },
              ]
            : undefined,
      });
```

We need a lot of checks to make TS happy in this spot. Ideally the types and conditions should be configured such that when `change` is `true` we can know for sure that we also have `path` and `pubkey` properly defined.

2022-09-10 10:32 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
>        const xpub = this.constructor._zpubToXpub(this.getXpub());
converted to non-static instead, just to keep wallet stuff together

2022-09-10 10:33 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    for (const txdata of Object.values(txdatas) as ElectrumTransaction[]) {
there was some pure-js reason why we require instead of import BlueElectrum.
i think everything just breaks if you import it, and needs rewriting lol

2022-09-10 10:35 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    const txs: Record<string, any> = {};
fixed

2022-09-10 10:41 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
>              delete clonedTx.vin;
fixed

2022-09-10 10:50 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
>              delete clonedTx.vout;
fixed

2022-09-10 11:01 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +      const outputData: any = {
good one. fixed

2022-09-10 11:10 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    const path = <string>this._getDerivationPathByAddress(input.address);
added extra check

2022-09-10 11:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ik4whxukzavuqhj467un6pukou?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10437)

2022-09-10 20:19 UTC, demerzel3 commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    for (const txdata of Object.values(txdatas) as ElectrumTransaction[]) {
We already use `import` in `abstract-hd-wallet.ts`, not sure if using it here will have a different impact though.

Anyways, you could keep the `require` and still leverage the types by using `import type` like so:
```
// You can call this whatever, doesn't need to be `BlueElectrumNs`
import type BlueElectrumNs from '../../blue_modules/BlueElectrum';
const BlueElectrum: typeof BlueElectrumNs = require('../../blue_modules/BlueElectrum');
```

2022-09-10 20:31 UTC, demerzel3 commented on typings/coinselect.d.ts
> +  export type CoinselectReturnInput = {
Missed this one, should be `CoinSelectReturnInput` with capital `S`

2022-09-11 11:02 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    for (const txdata of Object.values(txdatas) as ElectrumTransaction[]) {
fixed

2022-09-11 11:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/um4qdfqlavt5ef6nv5cjfw33iy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10442)

2022-09-11 12:31 UTC, merged