FIX: LBP API call
BlueWallet/BlueWallet pull request #5042
Opened 2022-09-24 20:36 UTC by marcosrdz

2022-09-24 20:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bxx7yl6gka2g236com7wy4mtsi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10478)

2022-09-25 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-09-26 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-09-27 10:07 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-09-27 21:06 UTC, Overtorment requested changes
LGTM KEK

2022-09-27 21:06 UTC, Overtorment commented on models/fiatUnits.json
> +        "symbol": "$"
changing a bunch of unrelated line is just poor craftsmanship

2022-09-27 21:07 UTC, marcosrdz commented on models/fiatUnits.json
> +        "symbol": "$"
Alphabetic sorting

2022-09-27 21:09 UTC, Overtorment commented on models/fiatUnits.json
> +        "symbol": "$"
do you want to keep it or it was an accident?

2022-09-27 21:09 UTC, marcosrdz commented on models/fiatUnits.json
> +        "symbol": "$"
Keep

2022-09-27 21:21 UTC, Overtorment approved these changes

2022-09-27 21:30 UTC, merged

2022-09-27 21:30 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!