ADD: Export wallet notes
BlueWallet/BlueWallet pull request #5045
Opened 2022-09-25 17:07 UTC by marcosrdz

<img width="554" alt="Screen Shot 2022-09-25 at 1 05 59 PM" src="https://user-images.githubusercontent.com/4793122/192156050-7afe9a69-e990-4259-a0fc-b12fecf819fe.png">
![Simulator Screen Shot - iPhone 13 Pro - 2022-09-25 at 13 05 29](https://user-images.githubusercontent.com/4793122/192156051-a3b962ef-b2c5-4aa4-8070-a5c569a15cd9.png)

2022-09-25 17:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hebj7kiciwzagetdmpgx4bfhwa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10484)

2022-09-25 22:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/a45gsqzudtkvwqv7pic4ohmkzq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10485)

2022-09-26 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-09-27 10:07 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-09-27 20:56 UTC, Overtorment requested changes

2022-09-27 20:56 UTC, Overtorment commented on loc/en.json
> +    "details_export_notes": "Export Notes",
i think better wording is "export transactions with notes as a CSV file"

2022-09-27 20:56 UTC, Overtorment commented on loc/en.json
> +    "details_export_notes": "Export Notes",
because this is what people asked us to implement, a way to 1) backup notes 2) some csv they can use for accounting/tax purposes

2022-09-27 20:56 UTC, Overtorment commented on screen/wallets/details.js
> +import RNFS from 'react-native-fs';
why this line suddenly changes position?
unnecessary stuff shoulnd be in the diff

2022-09-27 20:56 UTC, Overtorment commented on screen/wallets/details.js
> +
rework this:

1) should export _all_ txs
2) besides hash & note each row should have value & date

2022-09-27 20:56 UTC, Overtorment commented on blue_modules/fs.js
> +};
all this should have ios/android case handling.

look at `const exportInternals = async () => {`
you can copypaste all the code from there.

in fact, after you do, you can refactor `exportInternals()` as well to use the unified `writeFileAndShare()` method youre working on

2022-09-27 21:13 UTC, marcosrdz commented on blue_modules/fs.js
> +};
Android does not have file exporting to user selected directory with PSBT files. It does have it for CSV files. Which is why its a different function

2022-09-27 21:13 UTC, marcosrdz commented on screen/wallets/details.js
> +
What if I only want it for 1 wallet and not all?

2022-09-27 21:27 UTC, Overtorment commented on blue_modules/fs.js
> +};
```
} else if (Platform.OS === 'android') {
      const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE, {
        title: loc.send.permission_storage_title,
        message: loc.send.permission_storage_message,
        buttonNeutral: loc.send.permission_storage_later,
        buttonNegative: loc._.cancel,
        buttonPositive: loc._.ok,
      });

      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('Storage Permission: Granted');
        const filePath = RNFS.DownloadDirectoryPath + `/${fileName}`;
        try {
          await RNFS.writeFile(filePath, contents);
          alert(loc.formatString(loc.send.txSaved, { filePath: fileName }));
        } catch (e) {
          console.log(e);
          alert(e.message);
        }
      } else {
        console.log('Storage Permission: Denied');
        Alert.alert(loc.send.permission_storage_title, loc.send.permission_storage_denied_message, [
          {
            text: loc.send.open_settings,
            onPress: () => {
              Linking.openSettings();
            },
            style: 'default',
          },
          { text: loc._.cancel, onPress: () => {}, style: 'cancel' },
        ]);
      }
    }
```

2022-09-27 21:28 UTC, Overtorment commented on screen/wallets/details.js
> +
well yeah, I mean for the current wallet, but all wallet's txs

2022-09-27 21:32 UTC, marcosrdz commented on screen/wallets/details.js
> +
Wouldn't Export History make more sense? Since its a csv and not a psbt/txn

2022-09-27 21:33 UTC, marcosrdz commented on blue_modules/fs.js
> +};
That doesnt let the Android user choose a destination for the file

2022-09-27 23:48 UTC, marcosrdz commented on loc/en.json
> +    "details_export_notes": "Export Notes",
Implemented

2022-09-28 00:05 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vu6jrudkhcslothvps2kkbm3qm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10503)

2022-09-28 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-09-28 12:52 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rblw5rgfxjrrpfdhit6xb2vpzq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10505)

2022-09-28 13:56 UTC, marcosrdz commented on blue_modules/fs.js
> +};
We create the file and save it in a temp directory. Then we share RN Share for the user to export a copy in their destination of choice. Then we delete the file in the temp directory AFTER the user saved the copy

2022-09-29 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-09-30 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-10-01 09:35 UTC, marcosrdz commented
@Overtorment any other changes request?

2022-10-01 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-10-01 11:16 UTC, Overtorment commented on blue_modules/fs.js
> +};
so whats the problem here? im missing the point

2022-10-01 11:16 UTC, Overtorment commented on loc/en.json
> +    "details_export_history": "Export History",
lgtm

2022-10-01 11:19 UTC, Overtorment commented on screen/wallets/details.js
> +    Object.keys(txMetadata).forEach(txid => {
should be all txs, no just the ones with a memo

2022-10-01 11:20 UTC, Overtorment commented on screen/wallets/details.js
> +          date: dayjs(transaction.received).format('l'),
which date format is that? should be absolute, so MS Excel can parse it

2022-10-01 11:22 UTC, Overtorment commented on screen/wallets/details.js
> +      ...notes.map(item => [item.date, item.receivedOrSent, item.hash, item.value, item.memo]),
accountants wont be grateful for this. they want positive or negative numbers in 'value' column.
make their MS Excel life easier

2022-10-01 11:25 UTC, Overtorment commented on loc/en.json
> +    "details_export_history": "Export History",
i would add ".. in CSV"

2022-10-01 14:22 UTC, marcosrdz commented on blue_modules/fs.js
> +};
The methods available in master are :

iOS: can select destination
Android: defaults to a directory user can't specify


This new method (only works with few extensions) grants Android the same ability as iOS.

2022-10-01 14:23 UTC, marcosrdz commented on loc/en.json
> +    "details_export_history": "Export History",
Thats gonna be visible when exporting. Do we wanna add extra wording?

2022-10-01 14:53 UTC, marcosrdz commented on screen/wallets/details.js
> +    Object.keys(txMetadata).forEach(txid => {
Fixed

2022-10-01 14:53 UTC, marcosrdz commented on screen/wallets/details.js
> +          date: dayjs(transaction.received).format('l'),
08/16/2018 8:02:18 PM

2022-10-01 14:54 UTC, marcosrdz commented on screen/wallets/details.js
> +      ...notes.map(item => [item.date, item.receivedOrSent, item.hash, item.value, item.memo]),
Spent: "-0.2" Received: "0.2"

2022-10-01 15:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/akydbvepvy5z4tuyo3ztykn7dq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10543)

2022-10-01 18:43 UTC, Overtorment commented on screen/wallets/details.js
>        if (transaction) {
`for (const tx of transactions) {`

2022-10-01 18:51 UTC, marcosrdz commented on screen/wallets/details.js
>        if (transaction) {
Fixed

2022-10-01 19:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5vpdrrfdena5aerabmwerrqarq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10546)

2022-10-02 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-10-03 10:07 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-10-03 10:07 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2022-10-04 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-10-04 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2022-10-04 10:18 UTC, limpbrains approved these changes

2022-10-05 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-10-06 10:07 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-10-07 10:07 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2022-10-07 17:48 UTC, Overtorment commented
got 


```
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'memo' of undefined
TypeError: Cannot read property 'memo' of undefined
```

when testing locally.
gona work a bit on this PR myself

2022-10-07 19:07 UTC, Overtorment commented
@marcosrdz  @limpbrains pls review. i refactored, simplified csv generation, removed extra fs function  (to reuse existing one)

2022-10-07 19:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5m5qb2ch4aqvw765i3pvpm5voa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10573)

2022-10-07 20:33 UTC, marcosrdz commented
Merge!

2022-10-07 20:33 UTC, Overtorment approved these changes
![image](https://user-images.githubusercontent.com/1913337/194648203-103087aa-62dd-40cd-8b14-87ae6f1aa073.png)

2022-10-08 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2022-10-08 22:02 UTC, limpbrains commented on screen/wallets/details.js
> +        '\n' + [dayjs(transaction.received).format(), transaction.hash, value, txMetadata[transaction.hash]?.memo?.trim() ?? ''].join(','); // CSV line
dayjs.format uses ISO8601 with timezone, right?

2022-10-08 22:03 UTC, limpbrains requested changes

2022-10-08 22:03 UTC, limpbrains commented on screen/wallets/details.js
> +      loc.transactions.details_received,
I don't think it is suitable for time column. Meaning can be completely different for different languages

2022-10-08 22:08 UTC, marcosrdz commented on screen/wallets/details.js
> +      loc.transactions.details_received,
True. What is recommended? "Date"?
As in hardcoded English?

2022-10-08 22:09 UTC, marcosrdz commented on screen/wallets/details.js
> +        '\n' + [dayjs(transaction.received).format(), transaction.hash, value, txMetadata[transaction.hash]?.memo?.trim() ?? ''].join(','); // CSV line
I'll hardcode that format for this function

2022-10-08 22:10 UTC, limpbrains commented on screen/wallets/details.js
> +      loc.transactions.details_received,
Date is better

2022-10-09 10:05 UTC, Overtorment commented on screen/wallets/details.js
> +        '\n' + [dayjs(transaction.received).format(), transaction.hash, value, txMetadata[transaction.hash]?.memo?.trim() ?? ''].join(','); // CSV line
i think its UTC by default..?
which is more preferable than american  mm/dd/yy

2022-10-09 10:05 UTC, Overtorment commented on screen/wallets/details.js
> +      loc.transactions.details_received,
we dont have `date` in locs, i looked.

2022-10-09 11:32 UTC, limpbrains commented on screen/wallets/details.js
> +        '\n' + [dayjs(transaction.received).format(), transaction.hash, value, txMetadata[transaction.hash]?.memo?.trim() ?? ''].join(','); // CSV line
My point - it should contain time zone, otherwise results will differ depending on local machine

2022-10-10 02:47 UTC, marcosrdz commented on screen/wallets/details.js
> +      loc.transactions.details_received,
I believe he means hardcoding "Date" in English.

2022-10-12 16:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yuzzmasymqdlc2ay3oebgv75e4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10607)

2022-10-12 16:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ilet7ptnxa6xjxr5bee6cll6a4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10608)

2022-10-12 17:04 UTC, marcosrdz commented
Nice

2022-10-12 18:26 UTC, merged