FIX: cant reliably pay lnurl invoices when current currency is fiat (…
BlueWallet/BlueWallet pull request #5130
Opened 2022-10-20 18:24 UTC by Overtorment

…closes #5120)

2022-10-20 18:30 UTC, limpbrains requested changes

2022-10-20 18:35 UTC, marcosrdz commented on screen/lnd/lnurlPay.js
> +      if (!newAmount) {
Looks lime if its undefined or null or then parseInt will return 0

2022-10-20 18:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/lry646nagrthk63qyyidlg5gci?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10632)

2022-10-20 23:20 UTC, Overtorment commented on screen/lnd/lnurlPay.js
> +      if (!newAmount) {
i think not, lnurl-pay was specifically created as a workaround for zero-amount invoices

2022-10-20 23:27 UTC, marcosrdz approved these changes

2022-10-21 07:13 UTC, limpbrains approved these changes

2022-10-21 07:24 UTC, merged

2022-10-21 07:24 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!