BIP47 basic support
BlueWallet/BlueWallet pull request #5225
Opened 2022-12-07 13:01 UTC by abhiShandy

fixes #2883 

<div style="flex-direction:row;">
<img src="https://user-images.githubusercontent.com/6998593/206185664-39d7f4e0-d296-4d5e-81d7-1958efaf844e.png" height="500"/>

<img src="https://user-images.githubusercontent.com/6998593/206186388-c0b86f4f-882f-4588-9f0f-75941158445c.png" height="500" />

<img src="https://user-images.githubusercontent.com/6998593/206185752-1ed3cc7a-c758-42b1-b4eb-5032635a9702.png" height="500"/>

</div>

2022-12-10 17:46 UTC, abhiShandy commented
wait for https://github.com/BlueWallet/BlueWallet/pull/5073 before merging

2022-12-10 18:29 UTC, Lauramith reviewed
Good

2022-12-11 20:26 UTC, abhiShandy commented
I am able to get tx history but the values are zero

<img src="https://user-images.githubusercontent.com/6998593/206927051-253c0b18-9a30-4439-9df1-c8d6195f53cc.png" height=500 />

2022-12-12 03:15 UTC, abhiShandy commented
Fixed the bug:

<img src="https://user-images.githubusercontent.com/6998593/206953033-2cc93252-d8c8-41a6-9da9-c3e18d5fd82b.png" height=500 />

Next, I have to update the total balance.

2022-12-29 18:53 UTC, Overtorment requested changes
needs more work, but still, very good work on his. 
despite many comments, this is pretty close to being merge-able, no major flaws.

this also lacks unit tests. even the lib being used has its own unit tests, we need to implement our own tests to make sure provided test vectors yield the same results. plus, several tests should be added to `screen/selftest.js` so they can run in runtime on e2e CI, as react-native is a very  picky environment, and with anything cryptography-related if it worked in nodejs unittests it doesnt guarantee that it will work in RN runtime.

probably integration tests would be nice as well, to make sure fresh imported wallet can discover all its funds, including the ones on payment code, but i can work on this test later.

2022-12-29 18:53 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +      this._balances_by_payment_code_index[str] = { c: 0, u: 0 };
looks like a bug.

i think you need to get the payment code first, and only then initialize `this.next_free_payment_code_address_index` and `this._balances_by_payment_code_index`

2022-12-29 18:53 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +  }
unused

2022-12-29 18:53 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +  }
overall good job figuring out how `abstract-hd-electrum-wallet.ts` works

2022-12-29 18:53 UTC, Overtorment commented on components/TransactionsNavigationHeader.js
> +        {this.state.wallet.isBIP47Enabled() && (
needs guard with a feature flag, not all wallets have this method

2022-12-29 18:53 UTC, Overtorment commented on screen/wallets/details.js
> +      wallet.switchBIP47(isBIP47Enabled);
probably time to rename the function.  its not a `setLabel` anymore. its  `save`  or smth

2022-12-29 18:53 UTC, Overtorment commented on screen/wallets/details.js
> +              <>
guard clause with allow feature flag

2022-12-29 18:53 UTC, Overtorment commented on screen/wallets/transactions.js
> +      await wallet.fetchBIP47SenderPaymentCodes(); // FIXME:
hmm. maybe its the right place for it.
we update senders payment codes so then fetchBalance and fetchTransactions calls could fetch what we have.

2022-12-29 18:53 UTC, Overtorment commented on screen/wallets/paymentCode.tsx
> +          <Text style={styles.paymentCodeText}>{paymentCode}</Text>
needs to be copypastable. we had a component for tap-to-copy somewhere i think

2022-12-29 18:53 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +
btw lets prefix all those private variables with `_` for consistency

2022-12-29 18:53 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    this.setBIP47PaymentCode();
cc @ncoelho

2022-12-29 18:53 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    this.setBIP47PaymentCode();
same

2022-12-29 18:59 UTC, Overtorment commented
me personally, i think once payment code is enabled, this button is a mistake:
![image](https://user-images.githubusercontent.com/1913337/209996716-82e973dc-9ae0-4494-986c-4cc5860c1a01.png)

if payment code is enabled, i would expect to find it on receive screen. something like a tab there, with default displaying regular address:


![image](https://user-images.githubusercontent.com/1913337/209997004-1cf706b1-a1a3-4f50-b3f8-aad38eec40b5.png)



cc @ncoelho

2022-12-29 19:01 UTC, ncoelho commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    this.setBIP47PaymentCode();
Yes, needs to be opt-in by the user. At least to start with. 

Users won't know what this is and services don't have support for it.

2022-12-29 19:42 UTC, ncoelho commented
Yep we discussed this issue.

Let's start with this approach (not mixing it with the receive feature) and iterate after.

2022-12-29 19:50 UTC, Overtorment commented
roger roger. if @ncoelho blessed it then this is how it should be

2022-12-30 22:36 UTC, abhiShandy commented on .prettierrc
> +{
it didn't work with Auto Formatter in VS Code

2022-12-30 22:38 UTC, abhiShandy commented on package.json
> +    "@spsina/bip47": "github:abhishandy/bip47#1abcd4c20a387e43ed55bacc52726690bf417559",
yes, my plan is to merge it with spsina/bip47 eventually

2023-01-10 15:31 UTC, limpbrains commented
It needs to be clear to the user, that we are using BIP47. Because there is now another standart, [bip-0351](https://github.com/bitcoin/bips/blob/master/bip-0351.mediawiki)

2023-02-10 01:45 UTC, abhiShandy commented on Navigation.js
> +      <PaymentCodeStack.Screen name="PaymentCode" component={PaymentCode} options={{ headerTitle: 'Payment Code (BIP47)' }} />
the default title is the name of the component "PaymentCode", so I use this

2023-02-10 01:57 UTC, abhiShandy commented on screen/wallets/paymentCode.tsx
> +          <Text style={styles.paymentCodeText}>{paymentCode}</Text>
changed

2023-02-10 02:02 UTC, abhiShandy commented on class/wallets/abstract-hd-electrum-wallet.ts
> +
done!

2023-02-25 13:24 UTC, Overtorment commented
i created a temp PR to run all CI jobs here: https://github.com/BlueWallet/BlueWallet/pull/5326

2023-02-26 11:12 UTC, Overtorment commented
e2e failed with:

```
 ERROR  Failed to fetch sender payment codes for wallet Imported Watch-only [TypeError: undefined is not a function]
```

looks like the steps to reproduce is just import zpub and try to open this watch-only wallet

2023-02-28 17:16 UTC, abhiShandy commented
> e2e failed with:
> 
> ```
>  ERROR  Failed to fetch sender payment codes for wallet Imported Watch-only [TypeError: undefined is not a function]
> ```
> 
> looks like the steps to reproduce is just import zpub and try to open this watch-only wallet

I'll look into it

2023-03-02 09:26 UTC, Overtorment reviewed
i started looking again and looks like not all issues addresses/questions answered..?

do you want me to take over? i think i have good enough understanding to finish it

2023-03-02 09:26 UTC, Overtorment commented on .prettierrc
> +{
we need to make it work. we cant maintain 2 configs for linters, can we?
existing one is in `.eslintrc`

2023-03-02 09:26 UTC, Overtorment commented on blue_modules/BlueElectrum.js
> +module.exports.multiGetTransactionHexByTxid = async function (txids, batchsize = 100) {
this can be deleted if you switched to `multiGetTransactionByTxid` ?

2023-03-02 09:26 UTC, Overtorment commented on class/app-storage.js
> +        await this.wallets[index].fetchBIP47SenderPaymentCodes();
this is probably why e2e test failed.
parent class needs a feature flag in a form of a simple getter, and this method should start with a simple check:


```js
if (!this.wallets[index].allowBIP47()) return;
```

2023-03-16 19:15 UTC, closed without merging