Enable lightning(offchain) wallet transactions to be exported to csv
BlueWallet/BlueWallet pull request #5400
Opened 2023-03-24 00:37 UTC by masikotimo

Summary of changes 

Enable exportation of wallet history. transactions to be done by both on-chain and off-chain

2023-03-24 00:49 UTC, marcosrdz requested changes

2023-03-24 00:49 UTC, marcosrdz commented on screen/wallets/details.js
> +                {walletTransactionsLength > 0 && (
Needs code to use the "payment_hash" property instead of txid.

2023-03-25 04:46 UTC, masikotimo commented on screen/wallets/details.js
> +                {walletTransactionsLength > 0 && (
@marcosrdz  so if i do this it could work out (wallet.chain === Chain.ONCHAIN || wallet.chain === Chain.OFFCHAIN ) without making deletions ?

2023-03-26 01:53 UTC, marcosrdz commented on screen/wallets/details.js
> +                {walletTransactionsLength > 0 && (
The change you made is correct but in you need to add what I pointed out. Line 435..if its off chain then lookout payment_hash and invoice_description

2023-03-26 07:57 UTC, masikotimo commented on screen/wallets/details.js
> +                {walletTransactionsLength > 0 && (
Thank you @marcosrdz , I appreciate your feedback greatly ,  so to clarify what you mean is I should have a check that does if its off chain then the csv should have payment_hash instead of txid and add  invoice_description too after the memo field? is that right 

I can add this check during the creation of the csv  here


`
let csvFile = [
      loc.transactions.date,
      loc.transactions.txid,
      `${loc.send.create_amount} (${BitcoinUnit.BTC})`,
      loc.send.create_memo,
    ].join(','); // CSV header
`

2023-03-26 09:11 UTC, Overtorment commented on screen/wallets/details.js
> +                {walletTransactionsLength > 0 && (
maybe dont touch the header, just where it writes actual lines to csv


```js
[new Date(transaction.received).toString(), transaction.hash, value, txMetadata[transaction.hash]?.memo?.trim() ?? ''].join(','); // CSV line
```

2023-03-26 10:00 UTC, masikotimo commented on screen/wallets/details.js
> +                {walletTransactionsLength > 0 && (
Alright let me do so , Thank you @Overtorment

2023-03-28 02:59 UTC, masikotimo commented on screen/wallets/details.js
> +        memo = transaction.description;
@marcosrdz is this okay ?

2023-04-01 22:50 UTC, marcosrdz approved these changes

2023-04-02 20:15 UTC, masikotimo commented
@Overtorment   that looks like a keystore format issue that's causing it to fail.

2023-04-11 10:46 UTC, masikotimo commented
> @Overtorment that looks like a keystore format issue that's causing it to fail.

@Overtorment  any feedback on this?

2023-04-14 11:52 UTC, Overtorment approved these changes
lgtm

2023-04-14 11:53 UTC, Overtorment commented
lets run full test suite & builds here: https://github.com/BlueWallet/BlueWallet/pull/5463

@masikotimo as soon as apk build is ready, can you pls test  this functionaklity? for both onchain & lightning wallets

2023-04-27 09:26 UTC, merged