Nav6
BlueWallet/BlueWallet pull request #5404
Opened 2023-03-26 16:24 UTC by marcosrdz

2023-03-26 16:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4e322wxtuwctosbfbn66mzyfvm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11049)

2023-03-26 18:46 UTC, Overtorment commented
some tests failed

2023-03-26 21:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wxbddlmit2ahdwzixgsgkg53gi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11056)

2023-03-27 00:13 UTC, marcosrdz commented
@limpbrains @Overtorment  i ts-ignored useNavigation in a commit so it passes CI. Either of you know what changes are needed to avoid using ts-ignore?

2023-03-27 11:04 UTC, limpbrains commented
@marcosrdz I believe there is not easy fix. You need to type [whole Navigation](https://reactnavigation.org/docs/typescript/). I tried to type one screen, but failed :)
This is definetly should be a separate task to do.

2023-04-12 17:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ootnptcby664fon4qgjn5xsyam?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11163)

2023-04-13 09:42 UTC, Overtorment commented
e2e still fails?

2023-04-27 09:31 UTC, Overtorment commented
@marcosrdz ^^^

2023-08-28 08:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qwjqscunsmpxyrk2h7vycnqp2m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11535)

2023-08-28 08:52 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/isx3xqhr24yv7vevjw4ahlzscu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11536)

2023-08-28 08:57 UTC, limpbrains commented
Can't run detox locally on this branch.
Getting 
```
    The app has crashed, see the details below:

    @Thread detox.primary(146):
    java.lang.RuntimeException: java.util.concurrent.ExecutionException: androidx.test.espresso.IdlingResourceTimeoutException: Wait for [com.wix.detox.reactnative.idlingresources.NetworkIdlingResource] to become idle timed out
    	at androidx.test.espresso.Espresso.onIdle(Espresso.java:15)
    	at com.wix.detox.TestEngineFacade.awaitIdle(TestEngineFacade.kt:12)
    	at com.wix.detox.adapters.server.ReadyActionHandler.handle(DetoxActionHandlers.kt:25)
    	at com.wix.detox.adapters.server.ActionsExecutor.executeAction$lambda-2$lambda-1(DetoxActionsDispatcher.kt:64)
    	at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$nk3cF8ntnfFqbJOcVqd04vjb5nY(Unknown Source:0)
    	at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda0.run(Unknown Source:8)
    	at android.os.Handler.handleCallback(Handler.java:942)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loopOnce(Looper.java:201)
    	at android.os.Looper.loop(Looper.java:288)
    	at com.wix.detox.adapters.server.ActionsExecutor._init_$lambda-0(DetoxActionsDispatcher.kt:50)
    	at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$Hi5vyewqQiQqk57AkJy_cHqNGKY(Unknown Source:0)
    	at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda1.run(Unknown Source:4)
    	at java.lang.Thread.run(Thread.java:1012)
    Caused by: java.util.concurrent.ExecutionException: androidx.test.espresso.IdlingResourceTimeoutException: Wait for [com.wix.detox.reactnative.idlingresources.NetworkIdlingResource] to become idle timed out
    	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
    	at androidx.test.espresso.Espresso.onIdle(Espresso.java:10
```

Strange
Maybe RN 72 will help

2023-09-22 02:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/esogfnvgviyhzm7yksvkljiiwm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11564)

2023-10-07 16:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/sle3wh3pn7pveybf5jqjgld74m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11613)

2023-10-07 17:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bjgnxmpf25xwfe4rod23xdp364?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11614)

2023-10-07 21:18 UTC, marcosrdz commented
@limpbrains  some screens were coded "incorrectly" and need to have their params modified to add "merge: true"

2023-10-07 21:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/l6t7tvrcabsqfcmseykpfhlymq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11615)

2023-10-07 22:11 UTC, limpbrains commented
Do you mean that every screen should be written assuming that ﻿route.params could be undefined?
I kinda don't like it

2023-10-07 22:26 UTC, marcosrdz commented
> Do you mean that every screen should be written assuming that ﻿route.params could be undefined?
> 
> I kinda don't like it 

https://stackoverflow.com/questions/67327642/what-does-merge-do-in-navigation-navigate-react-native

2023-10-07 22:52 UTC, limpbrains commented
Got it. I'm thinking, maybe, for qrcode scanner we should try to always use goBack()? 
Also, do you know any other screen that needs to be fixed?

2023-10-07 23:00 UTC, marcosrdz commented
> Got it. I'm thinking, maybe, for qrcode scanner we should try to always use goBack()? 
> Also, do you know any other screen that needs to be fixed? 

ScanQRCode onBarScanned should do a navigate to the sender screen with updated params along with the merge:true.

2023-11-03 03:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dcd6deqsncaoko6nvpvmkah6bq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11802)

2023-11-03 03:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f2jbexujjvosfqt327dalkyeye?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11803)

2023-11-03 03:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rmxae6xgglbimxi4hpntwkbo2u?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11804)

2023-11-10 04:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6upuwedfafefxe2zttixrmgbqu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11850)

2023-11-10 06:32 UTC, marcosrdz commented on package.json
> +    "react-native-image-picker": "5.2.0",
Older version wouldn't compile with any sdk past 32

2023-11-10 09:15 UTC, limpbrains requested changes

2023-11-10 09:15 UTC, limpbrains commented on scripts/react-native-camera-kit.patch
> +--- ../node_modules/react-native-camera-kit/android/src/main/java/com/rncamerakit/CKCamera.kt
I don't think patch is needed with latest version of camera kit

2023-11-10 09:15 UTC, limpbrains commented on screen/wallets/pleaseBackup.tsx
> +    navigation.getParent()?.pop();
? Might not be needed

2023-11-10 09:15 UTC, limpbrains commented on android/build.gradle
> +        kotlin_version = '1.7.21'
Why are decreasing kotlin version?

2023-11-10 09:18 UTC, marcosrdz commented on scripts/react-native-camera-kit.patch
> +--- ../node_modules/react-native-camera-kit/android/src/main/java/com/rncamerakit/CKCamera.kt
Its needed for v13. V14 is still beta

2023-11-10 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-10 10:56 UTC, marcosrdz commented on android/build.gradle
> +        kotlin_version = '1.7.21'
My bad. That was during the trial and error process

2023-11-10 10:56 UTC, marcosrdz commented on screen/wallets/pleaseBackup.tsx
> +    navigation.getParent()?.pop();
Nav 6 deprecated the "dangerously" part

2023-11-10 11:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2hz2e46cyc57u5yvlyv3gkwoza?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11851)

2023-11-10 14:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kfqysktykfmnnhygvrcnaixtvy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11852)

2023-11-10 16:07 UTC, limpbrains approved these changes

2023-11-10 16:07 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/sdh5rusr3suk7btzulasssumf4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11855)

2023-11-11 00:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wq3kgjgt7st4jqqp4zna4w5fne?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11859)

2023-11-11 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-11 11:32 UTC, Overtorment approved these changes

2023-11-11 11:33 UTC, merged