Catalyst
BlueWallet/BlueWallet pull request #5484
Opened 2023-04-24 17:30 UTC by marcosrdz

2023-04-24 17:49 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hp6gqvwhn5dqwx3mzgoogfe4ja?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11219)

2023-04-24 18:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/egpasmttjnw74csqdb4gdogzwq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11220)

2023-04-24 19:47 UTC, Overtorment requested changes

2023-04-24 19:47 UTC, Overtorment commented on scripts/maccatalystpatches/lightning-ldk-wallet.ts
> +import { BitcoinUnit, Chain } from '../../models/bitcoinUnits';
what exactly you had to fix in this class?

2023-04-24 19:47 UTC, Overtorment commented on scripts/maccatalystpatches/lightning-ldk-wallet.ts
> +import { BitcoinUnit, Chain } from '../../models/bitcoinUnits';
couldnt make a patch? 
next time i work on this class maccatalyst  builds will be fucked?

2023-04-24 19:47 UTC, Overtorment commented on scripts/maccatalystpatches/torrific.js
> +/**
same question

2023-04-24 19:53 UTC, marcosrdz commented on scripts/maccatalystpatches/lightning-ldk-wallet.ts
> +import { BitcoinUnit, Chain } from '../../models/bitcoinUnits';
I want to keep the rest of the codebase untouched but these files modified. Why? Rnldk and rn tor are not catalysts compatible thus importing crashes the app. By deleting the import and calls for these imports im able to keep the rest of the app as-is

2023-04-24 21:49 UTC, Overtorment commented on scripts/maccatalystpatches/lightning-ldk-wallet.ts
> +import { BitcoinUnit, Chain } from '../../models/bitcoinUnits';
maybe its better to do `cp` and then `patch` ? so when files change developer wont have to remember to replace  and edit them in `maccatalyst` folder?

2023-04-25 00:54 UTC, marcosrdz commented on scripts/maccatalystpatches/lightning-ldk-wallet.ts
> +import { BitcoinUnit, Chain } from '../../models/bitcoinUnits';
Doing a patch would require me to be in sync with the changes made on those files (line numbers would matter). Compared to simply replacing them with empty functions.

2023-04-25 01:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fnx2ysx4vaejypgjqx3mwudna4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11222)

2023-04-26 10:02 UTC, Overtorment commented on scripts/maccatalystpatches/lightning-ldk-wallet.ts
> +import { BitcoinUnit, Chain } from '../../models/bitcoinUnits';
ok yolo. lets merge.
and future pain in the ass it produces will be on you.

2023-04-26 10:03 UTC, merged