ADD: support multiple accounts from Keystone hw wallet (closes #5281)
BlueWallet/BlueWallet pull request #5489
Opened 2023-04-26 20:59 UTC by Overtorment

2023-04-26 21:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ayixibwcczu2wojdna5jl27uzq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11232)

2023-04-27 11:09 UTC, limpbrains requested changes

2023-04-27 15:53 UTC, Overtorment commented on class/wallet-import.js
> +      const json = JSON.parse(text);
fixed

2023-04-27 16:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/peojyjf5qlcx7ndbvllsfojiau?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11239)

2023-04-27 16:14 UTC, limpbrains approved these changes

2023-05-09 10:26 UTC, merged