OPS: Update RN
BlueWallet/BlueWallet pull request #5491
Opened 2023-04-28 02:39 UTC by marcosrdz

2023-04-28 02:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tumvnft3wyafol2wjoe666776e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11240)

2023-04-28 03:08 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dkilss6mxavqg2n6ujjjhjx4na?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11241)

2023-04-28 07:48 UTC, Overtorment commented
Tests failed

2023-04-30 10:03 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-04-30 21:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5ew3pgc2kd7n7lbtpdt7wmhvfu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11253)

2023-05-01 10:03 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-05-01 12:30 UTC, Overtorment requested changes
Tests failed

2023-05-01 12:30 UTC, Overtorment commented on package-lock.json
> +        "react-native": "^0.71.7",
Not pinned

2023-05-01 12:30 UTC, Overtorment commented on package.json
> +    "@types/react-native": "^0.71.6",
Not pinned

2023-05-01 12:40 UTC, marcosrdz commented on package.json
> +    "@types/react-native": "^0.71.6",
devDependency. none are pinned

2023-05-01 17:47 UTC, Overtorment commented
builds failing

2023-05-03 22:53 UTC, Overtorment approved these changes

2023-05-03 22:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n4d24um4kpahymr3fxzmch6xgy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11262)

2023-05-04 00:23 UTC, merged

2023-05-04 00:23 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!