first round: airdrop capability for coordination of multisigs
BlueWallet/BlueWallet pull request #5660
Opened 2023-08-17 17:32 UTC by setavenger

2023-08-18 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-18 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-08-19 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-19 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-08-20 10:03 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-20 10:03 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-08-21 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-21 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-08-22 09:56 UTC, limpbrains requested changes

2023-08-22 09:56 UTC, limpbrains commented on class/wallets/multisig-hd-wallet.js
> +    if (this._cosigners.indexOf('') !== -1) return '';
if '' (empty string) acts like a special value, it should be something like "OMG_SPECIAL_VALUE" otherwise it is confusing. Also it should be explained in comments

2023-08-22 09:56 UTC, limpbrains commented on class/deeplink-schema-match.js
> +            if (this.hasValidKeysForMultiSigZpub(file)) {
```
if (!file || !this.hasValidKeysForMultiSigZpub(file)) {
  return
}
```

2023-08-22 09:56 UTC, limpbrains commented on screen/wallets/addMultisigStep2.js
> +      }
Can this code be moved outside the condition since it is duplicated?

2023-08-22 09:56 UTC, limpbrains commented on screen/wallets/addMultisigStep2.js
> +                text: 'Skip', // todo use loc
don't forget to use loc

2023-08-22 09:58 UTC, limpbrains commented
@setavenger can you please share a video of how it is working?

2023-08-22 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-22 11:02 UTC, setavenger commented
@limpbrains Here are the example videos.

https://github.com/BlueWallet/BlueWallet/assets/34041358/4669f2fb-e428-4357-bf3e-b21c2e7d42f0

https://github.com/BlueWallet/BlueWallet/assets/34041358/3557f2a6-a47b-4e3d-8da0-ffdf306b3b8a

2023-08-23 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-24 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-24 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-08-25 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-25 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-08-25 15:27 UTC, limpbrains requested changes

2023-08-26 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-27 10:03 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-27 10:03 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-08-27 18:54 UTC, limpbrains commented
I think UI needs more polishing:

1. "You can add the keys is 'manage keys' later." I think this alert should be change to alert with OK / Cancel. So that user can decide if he actually wants it.
2. When cosigners list is not complete Send, Receive, Wallet settings screens are useless. Shows wrong qrcode, addresses list is empty. I suggest we hide Send, Receive, Wallet settings (3 dots on in the top-right screen corner) until wallet is ready. Also we can show explanation in transactions list. Something like we need N more keys to be activate the wallet. Please add them in Manage keys.
3. Wallet screen shows "Has no matching script" alert, this needs to be fixed
4. Airdrop only available on the iOS, maybe Skip button should be only visible on iOS?
5. Manage screen is empty, if there are no keys. If key can be added via airdrop, why can't I add it there manually ?

2023-08-27 19:41 UTC, limpbrains commented
Also, if Send / Receive screen will be shut down, I think it is better to throw an Error in getAddress function, instead of returning empty function.
Also, unit tests would be nice.

2023-08-27 20:57 UTC, limpbrains commented
Istead of checking cosigners list in different methods over and over, it is better to create new method for mswallet, like
isWalletHasAllTheKeys() {
 return this.cosigners.some(i => i === 'PLACEHOLDER')
}

And then you can use it everywhere

2023-08-28 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-28 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-08-28 10:07 UTC, limpbrains requested changes
some change

2023-08-29 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-29 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-08-30 22:56 UTC, Overtorment requested changes

2023-08-30 22:56 UTC, Overtorment commented on screen/wallets/transactions.js
> +      )}
maybe its worth hiding it all in a render function, smth like `renderReceiveAndSendButtons()`.
and make an early return in case of incomplete ms wallet, so we can avoid extra nesting thats hard to read

2023-08-30 22:56 UTC, Overtorment commented on class/wallet-gradient.js
> +      case 'INCOMPLETE_MULTISIG_WALLET':
maybe make it a `const` somewhere? so its easier to reuse

2023-08-30 22:56 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +      if (!bip39.validateMnemonic(key) && key !== 'PLACEHOLDER_COSIGNER') throw new Error('Not a valid mnemonic phrase');
maybe make `PLACEHOLDER_COSIGNER` a static const in the class so its easier to reuse

2023-08-30 22:56 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.js
> +      if (!bip39.validateMnemonic(key) && key !== 'PLACEHOLDER_COSIGNER') throw new Error('Not a valid mnemonic phrase');
or just const

2023-08-30 22:56 UTC, Overtorment commented on tests/unit/multisig-hd-wallet.test.js
> +
add assert for `numberOfPlaceHolders()`

2023-08-30 22:56 UTC, Overtorment commented on tests/unit/multisig-hd-wallet.test.js
> +
and `isWalletHasAllTheKeys`

2023-08-30 22:56 UTC, Overtorment commented on tests/unit/multisig-hd-wallet.test.js
> +  });
`replacePlaceHolderWithXpub` is worth having a test too

2023-08-30 22:56 UTC, Overtorment commented on ios/BlueWallet/Info.plist
> +        </dict>
i dont understand this, @marcosrdz is this good?
is this how we tell the  iOS that we can handle .txt or smth..?

2023-08-30 22:56 UTC, Overtorment commented on screen/wallets/addMultisigStep2.js
> +      if (cosigner[0] === 'PLACEHOLDER_COSIGNER' || cosigner[1] === '' || cosigner[2] === '') {
where do empty strings come from ?

2023-08-30 22:56 UTC, Overtorment commented on screen/wallets/addMultisigStep2.js
> +          w.addCosigner(cc[0], fp, cc[2], cc[3], false);
code comments needed about whats going on here and why

2023-08-30 22:56 UTC, Overtorment commented on screen/wallets/viewEditMultisigCosigners.js
> +    // todo why is MultisigHDWallet.isXpubForMultisig(importText) undefined
o_O

2023-08-30 22:56 UTC, Overtorment commented on screen/wallets/viewEditMultisigCosigners.js
> +    // }
whats wrong here?

2023-08-30 22:56 UTC, Overtorment commented on screen/wallets/viewEditMultisigCosigners.js
> +      // return setIsLoading(false);
dead code?

2023-08-30 22:56 UTC, Overtorment commented on screen/wallets/viewEditMultisigCosigners.js
> +      // return setIsLoading(false);
dead code?

2023-08-30 22:56 UTC, Overtorment commented on screen/wallets/viewEditMultisigCosigners.js
> +    // setAskPassphrase(false);
dead code?

2023-08-30 22:56 UTC, Overtorment commented on screen/wallets/viewEditMultisigCosigners.js
> +            {/* )} */}
dead code?

2023-08-30 22:56 UTC, Overtorment commented on screen/wallets/viewEditMultisigCosigners.js
> +            {/* <BlueButtonLink ref={openScannerButtonRef} disabled={isLoading} onPress={scanOrOpenFile} title={loc.wallets.import_scan_qr} /> */}
dead code?

2023-08-30 22:58 UTC, Overtorment commented
my biggest issue is UX.

i think if we allow airdrop _only_ when user is on ms creation screen (where he has a choice to create or export seed) - we will radically reduce & simplify the diff - we wont need the crippled (incomplete cosigners) ms wallet and criplet cosigners (placeholder cosigners)

2023-08-31 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-08-31 10:20 UTC, setavenger commented on class/deeplink-schema-match.js
> +      // todo is this the right point for this check?
in case we have several different types txt files that can be imported we probably want to read the content and then send it to the screen depending on the content

2023-08-31 11:27 UTC, Overtorment commented
also, is there a requirement to be compatible with other software?
i was thinking, maybe we can register new file extension for ms airdropb, to its not generic .txt of .json
for example `blabla.cosigner`

2023-08-31 11:32 UTC, setavenger commented
@Overtorment I used the file format which is exported when sharing the seed/xpub during MS creation and in manage keys view. If this is only for use within BlueWallet then we could probably register a new filetype. If other software uses this format it might make things difficult for other software to import the data.

2023-08-31 11:35 UTC, setavenger commented on screen/wallets/viewEditMultisigCosigners.js
> +    // }
needs some more polishing in order to be used, and you can still import seeds after getting the xpub

2023-08-31 11:36 UTC, setavenger commented on screen/wallets/viewEditMultisigCosigners.js
> +            {/* )} */}
will most likely be needed once mnemonics are properly integrated in the replacePlaceholder function, can remove it for now though

2023-08-31 11:37 UTC, setavenger commented on screen/wallets/viewEditMultisigCosigners.js
> +            {/* <BlueButtonLink ref={openScannerButtonRef} disabled={isLoading} onPress={scanOrOpenFile} title={loc.wallets.import_scan_qr} /> */}
yes there is no scanner option yet, will remove it

2023-09-01 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-09-01 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-02 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-09-02 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-03 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-09-03 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-04 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-09-05 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-09-05 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-06 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-09-06 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-07 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-09-07 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-08 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-09-08 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-09 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-09-09 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-10 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-09-10 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-10 10:02 UTC, closed without merging