Integration of Border Wallet Feature into BlueWallet
BlueWallet/BlueWallet pull request #5669
Opened 2023-08-25 21:44 UTC by yttsen9

**Description:**

Proposing the integration of the Border Wallet feature into BlueWallet. Border Wallet offers a unique and innovative approach to reliably and swiftly memorize Bitcoin seed phrases. By enhancing both user experience and security, it stands as a valuable addition to BlueWallet's existing functionalities.

For a comprehensive introduction to Border Wallet, please refer to [The Solution](https://www.borderwallets.com/docs/the-solution).

A [video](https://drive.google.com/file/d/1nMG4Wqsy_iJcYJlWEXsfTR9Xr8r9q-y9/view) of blue wallet border wallet implementation

**Features:**

1. **Creation of New Border Wallet:**
   - Generate an entropy grid mnemonic.
   - Choose a border pattern and checksum word. Supports both 12 and 24 seed phrases.
   - Automatically save the entropy grid mnemonic and its corresponding seed phrase.

2. **Recovery/Importation of Previous Border Wallet:**
   - Load an entropy grid from a PDF or input the entropy grid seed phrase to regenerate the entropy grid mnemonic.
   - Choose a border pattern.
   - Input the checksum word.

3. **Periodic Verification of Border Wallet Pattern and Seed Phrases:**
   - Load an entropy grid from a PDF or input the entropy grid seed phrase to regenerate the entropy grid mnemonic.
   - Choose a border pattern.
   - Input the checksum word.

**Benefits:**

- **Enhanced Security:** The Border Wallet's unique approach to seed phrase memorization adds an extra layer of security, making it harder for malicious actors to access users' wallets.
  
- **Improved User Experience:** The intuitive design and process of the Border Wallet make it user-friendly, especially for those new to the world of cryptocurrencies.

- **Reliability:** The Border Wallet's method ensures that users can reliably recall their seed phrases, reducing the risk of lost access to their wallets.

**Conclusion:**

The integration of the Border Wallet feature will undoubtedly augment the capabilities of BlueWallet, providing users with a more secure and efficient way to manage their Bitcoin seed phrases. I believe this addition aligns with BlueWallet's mission to offer the best user experience while ensuring top-notch security. I kindly request the team to consider this pull request and am open to any feedback or modifications required.

Thank you for your time and consideration.

2023-08-27 20:49 UTC, limpbrains requested changes

2023-08-27 20:49 UTC, limpbrains commented on loc/en.json
> +=======
please, cleanup this

2023-08-27 20:49 UTC, limpbrains commented on package-lock.json
> +>>>>>>> b89b2402 (add border wallet feature)
and this

2023-08-27 20:49 UTC, limpbrains commented on package.json
> +    "jspdf-autotable": "^3.5.31",
all new dependencies should be pined

2023-08-27 20:49 UTC, limpbrains commented on tests/e2e/bluewallet3.spec.js
> +      'zpub6rDWXE4wbwefeCrHWehXJheXnti5F9PbpamDUeB5eFbqaY89x3jq86JADBuXpnJnSvRVwqkaTnyMaZERUg4BpxD9V4tSZfKeYh1ozPdL1xK',
why are you changing variables it tests?

2023-08-27 20:49 UTC, limpbrains commented on screen/wallets/entropyGridTable.js
> +            <Table borderStyle={{ borderWidth: 1, borderColor: '#C1C0B9' }}>
no inline styles, please

2023-08-27 20:49 UTC, limpbrains commented on screen/wallets/entropyGrid.js
> +  const { wallet, entropyType, pageType, newGridSeed, newGridCells } = useRoute().params; // pageType: 0 - create / 1 - import / 2 - check
instead of memorizing these 0, 1, 2 values, it better to create an object, like
```
pageTypes = {
  create: 0,
  import: 1,
}

And use it as pageTypes.create here and everywhere

2023-08-27 20:49 UTC, limpbrains commented on screen/wallets/entropyGrid.js
> +window.btoa = base64.btoa;
what is this for? Better move all globals to shim.js and add comments why are they used

2023-08-27 20:49 UTC, limpbrains commented on screen/lnd/browser.js
> +      stateURL: url || 'https://wwww.duckduckgo.com/',
why?

2023-08-27 20:49 UTC, limpbrains commented on class/border-wallet-grid.js
> +  'account',
Wordlist can be found in bip39
take a look at blue_moduels/bip39

2023-08-27 20:49 UTC, limpbrains commented on android/gradle/wrapper/gradle-wrapper.properties
> +>>>>>>> b89b2402 (add border wallet feature)
clean this

2023-08-27 20:49 UTC, limpbrains commented on README.md
> +   - create entropy grid mnemonic
This is all cool, but you can't change BW original Readme

2023-08-27 23:42 UTC, yttsen9 commented on README.md
> +   - create entropy grid mnemonic
Reversed back to original READme.

2023-08-27 23:43 UTC, yttsen9 commented on loc/en.json
> +=======
Apologize for missing those conflicts, removed this.

2023-08-27 23:43 UTC, yttsen9 commented on package-lock.json
> +>>>>>>> b89b2402 (add border wallet feature)
removed

2023-08-27 23:43 UTC, yttsen9 commented on android/gradle/wrapper/gradle-wrapper.properties
> +>>>>>>> b89b2402 (add border wallet feature)
removed

2023-08-27 23:53 UTC, yttsen9 commented on package.json
> +    "jspdf-autotable": "^3.5.31",
pined all new dependencies, thanks for pointing out.

2023-08-28 00:21 UTC, yttsen9 commented
Appreciate your time a lot in reviewing this PR and sharing with me the details of fixed needed! @limpbrains , I notice the security/synk scan failed but I couldn't access to see the details when I log in, how may I resolve it?
<img width="1351" alt="image" src="https://github.com/BlueWallet/BlueWallet/assets/143107939/af2853d3-44ac-43bd-bfb8-816d3fab445c">

2023-08-28 00:28 UTC, yttsen9 commented on package.json
> +    "jspdf-autotable": "^3.5.31",
pined all new dependencies

2023-08-28 05:46 UTC, limpbrains commented
At first you need to resolve merge conflict.
Do not pin all dependencies in package.json, only new one you have added.
Restore package-lock.json.
I suggest the folowing:
- copy them from BlueWAllet master branch
- edit package.json and add your new dependencies only
- run npm install
- commit changes to the package.json

2023-08-28 08:35 UTC, ncoelho commented
I see this as a wallet backup option, not as a create wallet option. 

This feature can't leave on this place essentially.

It would also need to live under advanced mode flag, and not present to the regular user.

2023-08-28 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-28 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-08-28 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-08-28 12:53 UTC, yttsen9 commented on tests/e2e/bluewallet3.spec.js
> +      'zpub6rDWXE4wbwefeCrHWehXJheXnti5F9PbpamDUeB5eFbqaY89x3jq86JADBuXpnJnSvRVwqkaTnyMaZERUg4BpxD9V4tSZfKeYh1ozPdL1xK',
reverted it to the original keystone

2023-08-28 12:54 UTC, yttsen9 commented on screen/lnd/browser.js
> +      stateURL: url || 'https://wwww.duckduckgo.com/',
removed the additional "w"

2023-08-28 12:55 UTC, yttsen9 commented on class/border-wallet-grid.js
> +  'account',
thank you! rewrote the script to get the wordlist from bip39 lib.

2023-08-28 14:59 UTC, yttsen9 commented
> I see this as a wallet backup option, not as a create wallet option. Or does it have to be always created from scratch and can't be used to memorize existing seeds?
> 
> It would also need to live under advanced mode flag, and not present to the regular user.

Thank you for your review. How about we consider adding a 'Border Wallet' as an advanced and securer option during the wallet creation and import/ recover process?  Following are some thoughts and reasonings, happy to discuss and appreciate the community's feedback to optimize the UX to offer this feature to BlueWallet users.

- The Border Wallet feature doesn't support the conversion of existing seed phrases, making it exclusively useful for generating new wallets and working with previously created Border Wallet. Rather than relying on system-generated random seeds, it offers users a more convenient and non-custodial way to create, maintain, and recover their HD wallets.

- The current implementation also allows users to import a pre-existing Border Wallet seed phrase into Bluewallet: loading in entropy grid mnemonics, select pattern, enter checksum word, done.  This further supports the idea of incorporating the Border Wallet option in both the 'Create' and 'Import/Recover' steps.

- Sparrow wallet introduces Border Wallet at the wallet creation/ import step, [a video demo of this feature](https://www.youtube.com/watch?v=wHQrvCGVkTw) 

- Border Wallet utilizes a visual pattern, similar to a phone's unlock pattern, to secure the seed phrase. This approach offers a more user-friendly and secure way to manage Bitcoin, as it doesn't solely rely on memorizing/ writing down a 12-word seed phrase.


Best,

2023-08-29 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-29 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-08-29 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-08-30 14:52 UTC, yttsen9 commented
> At first you need to resolve merge conflict. Do not pin all dependencies in package.json, only new one you have added. Restore package-lock.json. I suggest the folowing:
> 
> * copy them from BlueWAllet master branch
> * edit package.json and add your new dependencies only
> * run npm install
> * commit changes to the package.json

@limpbrains Thanks for the instruction, the package.lock.json has been restored following your suggestion, could you let me know if anything is needed for the PR?

2023-08-30 14:54 UTC, yttsen9 commented
> > I see this as a wallet backup option, not as a create wallet option. Or does it have to be always created from scratch and can't be used to memorize existing seeds?
> > It would also need to live under advanced mode flag, and not present to the regular user.
> 
> Thank you for your review. How about we consider adding a 'Border Wallet' as an advanced and securer option during the wallet creation and import/ recover process? Following are some thoughts and reasonings, happy to discuss and appreciate the community's feedback to optimize the UX to offer this feature to BlueWallet users.
> 
> * The Border Wallet feature doesn't support the conversion of existing seed phrases, making it exclusively useful for generating new wallets and working with previously created Border Wallet. Rather than relying on system-generated random seeds, it offers users a more convenient and non-custodial way to create, maintain, and recover their HD wallets.
> * The current implementation also allows users to import a pre-existing Border Wallet seed phrase into Bluewallet: loading in entropy grid mnemonics, select pattern, enter checksum word, done.  This further supports the idea of incorporating the Border Wallet option in both the 'Create' and 'Import/Recover' steps.
> * Sparrow wallet introduces Border Wallet at the wallet creation/ import step, [a video demo of this feature](https://www.youtube.com/watch?v=wHQrvCGVkTw)
> * Border Wallet utilizes a visual pattern, similar to a phone's unlock pattern, to secure the seed phrase. This approach offers a more user-friendly and secure way to manage Bitcoin, as it doesn't solely rely on memorizing/ writing down a 12-word seed phrase.
> 
> Best,

Hi @ncoelho , would you mind providing feedback on the rationale and considerations outlined above? Your input would be greatly appreciated.

2023-08-30 14:59 UTC, yttsen9 commented on screen/wallets/entropyGrid.js
> +window.btoa = base64.btoa;
moved the globals to shim.js per comment

2023-08-30 16:00 UTC, limpbrains requested changes
BlueWallet has dark theme, please test your PR change fix it to support dark theme.
Please, add unit tests

2023-08-31 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-08-31 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-08-31 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-01 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-02 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-02 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-02 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-03 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-03 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-03 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-04 01:16 UTC, yttsen9 commented on class/border-wallet-grid.js
> +const crypto = require('isomorphic-webcrypto');
We needed crypto-subtle module in the isomorphic-webcrypto to generate grid entropy seed phrase, and the module is not in the current react-native-crypto.

2023-09-04 01:16 UTC, yttsen9 commented on android/app/build.gradle.original
> +apply plugin: "kotlin-android"
Removed.

2023-09-04 01:21 UTC, yttsen9 commented on class/border-wallet-grid.js
> +    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAMAAABThUXgAAAAAXNSR0IArs4c6QAAAdRQTFRFAAAAAAABAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
"data:image/png;base64" is an inlined image (png), encoded in base64. It can make a page faster: the browser doesn't have to query the server for the image data separately, saving a round trip.

2023-09-04 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-04 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-04 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-04 13:04 UTC, yttsen9 commented on ios/fastlane/metadata/ar-SA/release_notes.txt~b89b2402 (add border wallet feature)
> +../en-US/release_notes.txt
removed

2023-09-04 13:05 UTC, yttsen9 commented on screen/wallets/entropyGridOfFinalWord.js
> +  const showWarning = msg => Alert.alert('Warning', msg);
translation added

2023-09-04 13:06 UTC, yttsen9 commented on tests/unit/watch-only-wallet.test.js
> +  it.skip('can import wallet descriptor for BIP84 from Sparrow Wallet', async () => {
The previous changes were reverted and now the test will run

2023-09-04 13:06 UTC, yttsen9 commented on ios/fastlane/metadata/ar-SA/release_notes.txt~b89b2402 (add border wallet feature)
> +../en-US/release_notes.txt
removed

2023-09-04 13:07 UTC, yttsen9 commented on class/border-wallet-grid.js
> +  const entropy = crypto.getRandomValues(new Uint8Array(16));
Now used class/rng.js to compute randomBytes

2023-09-04 13:21 UTC, yttsen9 commented on package.json
> -    "react-native-document-picker": "https://github.com/BlueWallet/react-native-document-picker#857655cdddf17751c0fae1286a9121fda2a6d568",
changed to old version

2023-09-04 13:36 UTC, yttsen9 commented
> BlueWallet has dark theme, please test your PR change fix it to support dark theme. Please, add unit tests

![image](https://github.com/BlueWallet/BlueWallet/assets/143107939/f577a556-ae05-4537-8580-06e19cdd2678)
Unit tests have been added and achieved greater than average coverage

2023-09-05 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-05 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-05 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-06 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-06 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-06 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-07 03:44 UTC, yttsen9 commented
@limpbrains hope you are well! would you mind letting me know if had any follow-up questions about the updated code base? I tried to incorporate all the changes and feedback you kindly shared into the code

2023-09-07 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-07 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-07 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-08 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-08 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-08 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-09 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-09 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-09 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-10 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-10 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-10 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-11 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-11 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-11 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-12 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-12 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-12 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-13 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-13 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-14 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-09-14 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-14 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-14 10:44 UTC, Overtorment requested changes
all new files must be in typescript (i have just updated CONTRIBUTING.md)

i also dont like new dependencies for this feature.

and in general not sold on the idea of border wallets - not sure if they will ever do anyone any good.

2023-09-14 10:44 UTC, Overtorment commented on tests/unit/border-wallet.test.js
> +    const mnemonic = 'radio demand ghost glimpse rain slender fall struggle update kiss peanut inflict';
is this a mnemonic for the entropy grid?
if so, wheres the restoration using the pattern?

2023-09-14 10:44 UTC, Overtorment commented on screen/wallets/details.js
> +                    <SecondButton onPress={navigateToMnemonicChecker} testID="CheckMnenomic" title={loc.wallets.check_mnemonic} />
testID, but is there an e2e test..?

2023-09-14 10:44 UTC, Overtorment commented on tests/unit/border-wallet-grid.test.js
> +global.XMLHttpRequest = XMLHttpRequest;
where is this used? smells fishy

2023-09-14 10:44 UTC, Overtorment commented on tests/unit/border-wallet-grid.test.js
> +});
where do tests come from?

how can we be sure that our this implementation is interoperable with  the reference implementation?

2023-09-15 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-15 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-16 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-16 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-17 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-17 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-18 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-19 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-20 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-20 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-21 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-21 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-22 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-22 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-23 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-23 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-24 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-24 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-25 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-25 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-26 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-26 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-27 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-27 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-28 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-28 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-29 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-29 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-09-30 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-09-30 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-01 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-01 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-02 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-02 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-03 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-03 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-04 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-04 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-05 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-05 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-06 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-06 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-07 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-07 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-08 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-08 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-10 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-11 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-12 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-12 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-13 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-13 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-14 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-14 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-15 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-15 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-16 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-16 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-17 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-17 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-18 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-18 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-19 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-19 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-20 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-20 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-21 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-21 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-22 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-22 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-23 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-24 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-24 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-25 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-25 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-26 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-26 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-27 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-27 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-28 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-28 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-29 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-29 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-30 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-30 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-10-31 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-10-31 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-01 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-02 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-02 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-03 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-03 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-04 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-04 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-05 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-05 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-06 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-06 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-07 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-07 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-08 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-08 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-09 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-09 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-10 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-11 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-11 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-12 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-12 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-13 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-13 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-14 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-14 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-15 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-15 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-16 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-16 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-17 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-17 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-18 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-18 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-19 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-19 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-20 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-20 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-21 10:09 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-22 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-22 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-23 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-23 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-24 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-24 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-25 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-25 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-26 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-26 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-27 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

2023-11-27 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2023-11-27 19:16 UTC, closed without merging