OPS: Update RN Device Info
BlueWallet/BlueWallet pull request #5747
Opened 2023-10-19 18:46 UTC by marcosrdz

2023-10-19 19:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ycxdj6e6egzvgqpgjbw4vob36i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11670)

2023-10-19 19:58 UTC, Overtorment approved these changes

2023-10-20 01:36 UTC, marcosrdz commented
@Overtorment  @limpbrains  detox complains it can't install the app on emulator. I can seem to figure out why. locally It works.

2023-10-20 04:54 UTC, limpbrains requested changes

2023-10-20 04:54 UTC, limpbrains commented on blue_modules/analytics.js
> +  const uniqueID = await getUniqueId();
You probably can't use await at the root level of the module

2023-10-20 04:54 UTC, limpbrains commented on blue_modules/analytics.js
> +  const uniqueID = await getUniqueId();
com.facebook.react.common.JavascriptException: ReferenceError: Property 'await' doesn't exist, js engine: hermes, stack:

2023-10-20 14:28 UTC, marcosrdz commented on blue_modules/analytics.js
> +  const uniqueID = await getUniqueId();
Silly me

2023-10-20 14:47 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ixjakedb6eqv4wutem45voomp4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11676)

2023-10-21 05:57 UTC, limpbrains approved these changes

2023-10-21 06:00 UTC, merged

2023-10-21 06:00 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!