ADD: useAsyncPromise
BlueWallet/BlueWallet pull request #5756
Opened 2023-10-21 22:51 UTC by marcosrdz

2023-10-21 22:55 UTC, Overtorment requested changes

2023-10-21 22:55 UTC, Overtorment commented on class/useAsyncPromise.ts
> +function useAsyncPromise<T>(promise: Promise<T>): { data: T | null; error: Error | null; loading: boolean } {
File is added, but where is it used..?

2023-10-21 23:01 UTC, marcosrdz commented on class/useAsyncPromise.ts
> +function useAsyncPromise<T>(promise: Promise<T>): { data: T | null; error: Error | null; loading: boolean } {
on add.js

2023-10-21 23:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b5m4lrf2x5r6p7st2m26dwxtlu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11701)

2023-10-21 23:19 UTC, Overtorment requested changes
It's not a class tho? Prob better to move it to "hooks" folder

2023-10-21 23:20 UTC, marcosrdz commented
> It's not a class tho? Prob better to move it to "hooks" folder

Done

2023-10-21 23:24 UTC, Overtorment approved these changes

2023-10-21 23:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/heg2iykd4cq3otmfypgm457f5q?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11703)

2023-10-21 23:45 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/prl6jayhaejou6rnc7xkbdtrxq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11705)

2023-10-22 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2023-10-22 10:59 UTC, limpbrains commented on screen/wallets/add.js
> +  const isAdvancedOptionsEnabled = useAsyncPromise(isAdvancedModeEnabled());
isAdvancedModeEnabled function will be called once again, one component re-renders. I don't think it is expected

2023-10-22 11:06 UTC, merged

2023-10-22 11:06 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!