Fix open files
BlueWallet/BlueWallet pull request #5770
Opened 2023-10-24 15:11 UTC by setavenger

There was an issue opening files from the files app in iOS. This was fixed with a custom file reading package.

2023-10-24 17:28 UTC, Overtorment approved these changes
good call putting all the code in place instead of extra dep!

needs some brushing up, and im inclined to merge this ASAP, if @marcosrdz and @limpbrains agree with me

2023-10-24 17:28 UTC, Overtorment commented on class/deeplink-schema-match.js
> +    } else if (event.url.endsWith('.bwcosigner')) {
isolate in separate static checker method, similar to `isPossiblySignedPSBTFile()`

2023-10-24 17:28 UTC, Overtorment commented on class/deeplink-schema-match.js
> +        return;
android should be handled. cant tell users to fuckoff with importing cosigners only because  they dont use  ios

2023-10-24 17:28 UTC, Overtorment commented on ios/BlueWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +}
wtf is this? looks shady

2023-10-24 17:28 UTC, Overtorment commented on ios/BlueWallet/Info.plist
> +    </array>
indentation changed weirdly

2023-10-24 17:28 UTC, Overtorment commented on ios/BlueWallet/Info.plist
> +        </dict>
this block is repeated 2 times. is that anaccident or intended?

2023-10-24 17:28 UTC, Overtorment commented on tsconfig.json
> +    }
instead of here, can we put it in package.json, like we already have:

```
"bc-bech32": "file:blue_modules/bc-bech32",
```

2023-10-24 17:28 UTC, Overtorment commented on blue_modules/react-native-bw-file-access/README.md
> +# react-native-bw-file-access
good call adding sources to the repo instead of extra dep!

but lets clean this up so it actually looks nice for anyone reading the code

2023-10-24 17:28 UTC, Overtorment commented on blue_modules/react-native-bw-file-access/package.json
> +  },
cleanup so it looks nice

2023-10-24 17:28 UTC, Overtorment commented on blue_modules/react-native-bw-file-access/package.json
> +  }
dont need devDependencies here i think

2023-10-24 17:29 UTC, Overtorment requested changes
see prev comments

2023-10-24 17:32 UTC, marcosrdz commented on ios/BlueWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +}
Its the QR Code package for the watchOS app.

2023-10-24 17:33 UTC, Overtorment commented on ios/BlueWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +}
why it surfaced in this PR? shouldnt be here if its unrelated

2023-10-24 17:55 UTC, setavenger commented on ios/BlueWallet/Info.plist
> +        </dict>
One should be in `UTImportedTypeDeclarations` and one should be in `UTExportedTypeDeclarations`.

2023-10-24 19:50 UTC, limpbrains requested changes

2023-10-24 19:50 UTC, limpbrains commented on App.js
> +      console.log(url);
can this be removed?

2023-10-24 19:52 UTC, setavenger commented on App.js
> +      console.log(url);
yes

2023-10-24 20:00 UTC, setavenger commented
Can someone explain why DeepScan is suddenly flagging locations where I didn't even make changes?

2023-10-25 00:24 UTC, marcosrdz commented on ios/BlueWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +}
"xcshareddata". probably should be added to .gitignore as its local dev machine stuff

2023-10-25 09:53 UTC, limpbrains commented
> Can someone explain why DeepScan is suddenly flagging locations where I didn't even make changes?

It does this sometimes, ignore it

2023-10-25 09:53 UTC, limpbrains approved these changes

2023-10-25 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-10-26 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-10-27 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-10-28 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-10-29 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-10-30 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-10-31 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-01 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-02 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-03 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-04 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-05 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-06 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-07 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-08 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-08 10:11 UTC, setavenger commented on ios/BlueWallet/Info.plist
> +    </array>
I believe that this is just a git thing, file looks fine

2023-11-09 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-10 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-11 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-11 17:08 UTC, Overtorment commented on class/deeplink-schema-match.js
> +      readFileOutsideSandbox(decodeURI(event.url))
need to doublecheck this use case after this PR is merged.
iirc its for a case when BW opens a psbt file (for example after it was signed by coldcard)

2023-11-11 17:27 UTC, Overtorment requested changes
i dont see `package.json` in diff..?
otherwise LGTM, can merge.

pro tip: `git add -p` command allows you to selectively add changes to commit, so some  unnecessarty formatting wont be comitted

2023-11-11 17:27 UTC, Overtorment commented on tsconfig.json
> +    "resolveJsonModule": true,
should not be  in diff, but ok.

2023-11-12 02:56 UTC, setavenger commented
> i dont see `package.json` in diff..? otherwise LGTM, can merge.
No changes had to be made to the package.json for this to work. The module is defined locally in the project so nothing needs to be newly installed.

2023-11-12 14:41 UTC, merged