REF: Wallet Quick Actions code isolation
BlueWallet/BlueWallet pull request #5817
Opened 2023-11-11 16:57 UTC by marcosrdz

2023-11-11 16:58 UTC, Overtorment approved these changes

2023-11-11 17:00 UTC, Overtorment commented
linter & unit failed tho.
plus would not hurt to convert  to ts

2023-11-11 17:17 UTC, marcosrdz commented
> linter & unit failed tho. plus would not hurt to convert to ts

Converted to TSX

2023-11-11 17:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ixiifiiqnhryrrzgawwthoxdhy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11863)

2023-11-11 17:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ei3ie7l3omfrsmy7qsj2wohgju?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11864)

2023-11-11 17:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/32fopd6mtpyctlvupkoac5oygq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11865)

2023-11-11 23:30 UTC, Overtorment requested changes
E2E failed

2023-11-12 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-12 14:56 UTC, Overtorment approved these changes

2023-11-12 14:56 UTC, Overtorment commented on class/quick-actions.tsx
> +  DeviceQuickActions.setEnabled = async (enabled: boolean = true): Promise<void> => {
I think methods should be outside func body

2023-11-12 14:57 UTC, marcosrdz commented on class/quick-actions.tsx
> +  DeviceQuickActions.setEnabled = async (enabled: boolean = true): Promise<void> => {
Ill refactor those so they are modern and compatible with intellisense

2023-11-12 14:58 UTC, merged

2023-11-12 14:58 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!