FIX: Lightning wallet CSV export does not differentiate between paid …
BlueWallet/BlueWallet pull request #5846
Opened 2023-11-19 18:01 UTC by marcosrdz

…and expired invoices #5835

2023-11-19 18:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ahw735wxglohvaoqjxi6bih5l4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11920)

2023-11-20 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-11-20 20:48 UTC, Overtorment requested changes

2023-11-20 20:48 UTC, Overtorment commented on screen/wallets/details.js
> +        // Replace 'condition' with your specific condition
whats this comment?

2023-11-20 20:53 UTC, marcosrdz commented on screen/wallets/details.js
> +        // Replace 'condition' with your specific condition
My bad

2023-11-20 20:54 UTC, merged