OPS: Manual upload to Testflight
BlueWallet/BlueWallet pull request #5896
Opened 2023-12-08 21:56 UTC by marcosrdz

2023-12-08 22:23 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e45htsgezjq2enzgmwxfunzwem?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12141)

2023-12-08 23:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mjx55ecnii6anxzv57aifxopnu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12146)

2023-12-09 03:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/674x4ovvvjoqldkhafgjhnnviu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12151)

2023-12-09 06:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xmy3vyqy6e7qi7dqbjvksg6oq4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12153)

2023-12-09 06:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kclhorgoanangwcf2btykqwamm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12154)

2023-12-09 07:01 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bn4unu53xl7vupm6tfxhb5lg4m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12158)

2023-12-09 17:25 UTC, Overtorment requested changes

2023-12-09 17:25 UTC, Overtorment commented on .github/workflows/build-ios-release-pullrequest.yml
> +      - name: Display release-notes.txt
duplicate


```
      - name: Display release-notes.txt
        run: cat release-notes.txt

      - name: Display release-notes.json
        run: cat release-notes.json
```

2023-12-09 17:25 UTC, Overtorment commented on .github/workflows/build-ios-release-pullrequest.yml
> +          ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
remind me where `GIT_ACCESS_TOKEN` comes from? you created the token and put it in env vars?

2023-12-09 17:25 UTC, Overtorment commented on .github/workflows/build-ios-release-pullrequest.yml
> +          NEW_BUILD_NUMBER: ${{ env.NEW_BUILD_NUMBER }}
this makes no sense to me. provide env var from existing env var with the same name..?

2023-12-09 17:25 UTC, Overtorment commented on .github/workflows/build-ios-release-pullrequest.yml
> +          NEW_BUILD_NUMBER: ${{ env.NEW_BUILD_NUMBER }}
looked at docs.  no need to explicitly pass it, it should just be available  after youve set it in `$GITHUB_ENV` in prev step

2023-12-09 17:25 UTC, Overtorment commented on .github/workflows/build-ios-release-pullrequest.yml
> +          echo "LATEST_COMMIT_MESSAGE=${LATEST_COMMIT_MESSAGE}" >> $GITHUB_ENV
i think putting branch name in testflight release notes might be a better idea

2023-12-09 17:25 UTC, Overtorment commented on .github/workflows/build-ios-release-pullrequest.yml
> +          echo "LATEST_COMMIT_MESSAGE=${LATEST_COMMIT_MESSAGE}" >> $GITHUB_ENV
btw i dont see where `LATEST_COMMIT_MESSAGE` is used later

2023-12-09 17:25 UTC, Overtorment commented on .github/workflows/build-ios-release-pullrequest.yml
> +        run: echo "Uploading to TestFlight..."
wheres the actual upload..?

2023-12-10 22:23 UTC, closed without merging