REF: BlueListemItem to TSX
BlueWallet/BlueWallet pull request #5911
Opened 2023-12-14 22:48 UTC by marcosrdz

2023-12-15 02:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j665xdtlgoktuzucapt64qzosu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12222)

2023-12-15 02:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u5sbcttdwra6rkynu62xhm75uu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12223)

2023-12-15 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-12-15 23:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/lmdkeumybalgbl4k23mtoiqtnm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12228)

2023-12-16 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2023-12-16 17:21 UTC, Overtorment requested changes
conflict

2023-12-16 17:21 UTC, Overtorment commented on screen/send/coinControl.js
> +import { Avatar, Badge, Icon, ListItem as RNElementsListItem } from 'react-native-elements';
if you keep this ListItem as is, without renaming, and rename  our own ListItem to BlueListItem, the total diff will be smaller

2023-12-16 17:21 UTC, Overtorment commented on screen/send/details.js
> +import ListItem from '../../components/ListItem';
up to you, but here as well you can import it as `BlueListItem` and you wont have to change the whole file

2023-12-16 18:39 UTC, marcosrdz commented on screen/send/coinControl.js
> +import { Avatar, Badge, Icon, ListItem as RNElementsListItem } from 'react-native-elements';
i was under the impression that we wanted to remove the Blue prefix from components

2023-12-16 19:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rfwo4ly54yulmyacgcsynrhbqq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12233)

2023-12-16 19:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ww7nzsep4ppmtsxshjrg6foide?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12234)

2023-12-16 21:44 UTC, merged