ADD: Search for Wallet in Home screen
BlueWallet/BlueWallet pull request #6027
Opened 2024-01-20 18:06 UTC by marcosrdz

<img width="378" alt="Screenshot 2024-01-20 at 2 04 18 PM" src="https://github.com/BlueWallet/BlueWallet/assets/4793122/d6e8934c-4d33-4ab7-85cc-4ffb7449ffcb">

<img width="391" alt="Screenshot 2024-01-20 at 2 04 11 PM" src="https://github.com/BlueWallet/BlueWallet/assets/4793122/19f82484-74e2-4d92-a2d4-3c08616ac1ff">

2024-01-20 18:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vqewf4a2eaigd4hy22g3chwpti?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/216)

2024-01-20 18:28 UTC, Overtorment requested changes
when the search bar would become visible?

on pull down?

rememer btw when we had idea that on pull down you can see summary value of all your wallets? i like both ideas

2024-01-20 18:28 UTC, Overtorment commented on screen/wallets/list.js
> +  // Header Search Bar for Wallets
while youre at it, convert to ts

2024-01-20 18:28 UTC, Overtorment commented on react-native.config.js
> -
bad craftsmanship.

use `git add -p`

2024-01-20 18:30 UTC, Overtorment commented
> when the search bar would become visible?
> 
> on pull down?
> 
> rememer btw when we had idea that on pull down you can see summary value of all your wallets? i like both ideas

and btw, what if we wont limit search to wallet name only? search tx labels and amounts as well. say, i remember i made a tx 0f 0.666 and i want to find whichwallet, so i sype in search '666'. wqould be pretty cool

2024-01-20 18:30 UTC, marcosrdz commented
> when the search bar would become visible?
> 
> 
> 
> on pull down?
> 
> 
> 
> rememer btw when we had idea that on pull down you can see summary value of all your wallets? i like both ideas

Yup on pull down. standard platform behavior

2024-01-20 18:30 UTC, Overtorment commented
deepscan bitchin btw

2024-01-20 18:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2owagops5l5mxynyvhvfaq6a64?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/217)

2024-01-20 19:37 UTC, marcosrdz commented
> > when the search bar would become visible?
> 
> > 
> 
> > on pull down?
> 
> > 
> 
> > rememer btw when we had idea that on pull down you can see summary value of all your wallets? i like both ideas
> 
> 
> 
> and btw, what if we wont limit search to wallet name only? search tx labels and amounts as well. say, i remember i made a tx 0f 0.666 and i want to find whichwallet, so i sype in search '666'. wqould be pretty cool

Ill write enhancements in another PR

2024-01-20 21:59 UTC, marcosrdz commented
> deepscan bitchin btw

Fixed

2024-01-20 22:07 UTC, marcosrdz commented on screen/wallets/list.js
> +  // Header Search Bar for Wallets
That's plenty for this file. I can do that in another PR

2024-01-20 22:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4mxd74rn3ayju4tgkgj62gcqx4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/219)

2024-01-21 08:33 UTC, marcosrdz commented
> when the search bar would become visible?
> 
> 
> 
> on pull down?
> 
> 
> 
> rememer btw when we had idea that on pull down you can see summary value of all your wallets? i like both ideas

Valuable info should be displayed all the time. Pull down is for "tools" such as search, shortcuts or refresh.

2024-01-21 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-01-21 17:17 UTC, Overtorment approved these changes

2024-01-21 17:17 UTC, Overtorment commented on react-native.config.js
> -
hola pendejo

2024-01-21 17:25 UTC, merged

2024-01-21 17:25 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!