REF: UnlockWith to TSX
BlueWallet/BlueWallet pull request #6092
Opened 2024-02-04 16:27 UTC by marcosrdz

2024-02-04 16:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gvxa5kaa4oksxvtc3jhmyfng54?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/368)

2024-02-04 16:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hj7u55vffn7l5dvwna3bvrtztq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/367)

2024-02-04 17:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cd5ecpp2cnmojwz6q3xr4nqjzu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/369)

2024-02-05 00:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/up762ewqpskfadtwttexu5uqa4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/372)

2024-02-05 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-05 12:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hpp7rb74fuqmaysy5ttiian6ci?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/376)

2024-02-05 13:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fmmronmafvjiq7vmwbcsmtupf4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/378)

2024-02-06 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-07 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-08 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-08 20:44 UTC, Overtorment commented on UnlockWith.tsx
> -      let type; // Use `type` directly to hold the biometric type info
isnt `type` a reserver ts word btw..? @limpbrains do you know?

2024-02-08 20:46 UTC, Overtorment requested changes

2024-02-08 20:46 UTC, Overtorment commented on UnlockWith.tsx
> +      let type: string | boolean | undefined;
i think instead of `string` we can use exact string constants here, like

```
et type: 'Biometrics' | 'Blabla'  | boolean | undefined;
```

2024-02-09 01:34 UTC, marcosrdz commented on UnlockWith.tsx
> -      let type; // Use `type` directly to hold the biometric type info
shouldn't matter as its a local variable but changed nonetheless

2024-02-09 01:34 UTC, marcosrdz commented on UnlockWith.tsx
> +      let type: string | boolean | undefined;
resolved

2024-02-09 02:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wshkk4vhw33ltw2fnagzitlehu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/415)

2024-02-09 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-09 13:23 UTC, limpbrains commented on UnlockWith.styles.ts
Eslint can find unused style if you keep your styles in the same file as your component.
Unfortunaly this will not work if you put styles in another file :(

2024-02-09 13:24 UTC, limpbrains commented on UnlockWith.styles.ts
I'm not saying you should change it, I just like this feature

2024-02-09 16:07 UTC, marcosrdz commented on UnlockWith.styles.ts
Dang..you're right. Reverted.

2024-02-09 16:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hpdpzbg44uwb7mltojqqrl6pcm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/417)

2024-02-09 16:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/imqbep36lp33z326s6rdsdau3q?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/418)

2024-02-10 10:03 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-11 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-11 12:39 UTC, Overtorment approved these changes

2024-02-11 14:35 UTC, limpbrains requested changes
Also please use git mv

2024-02-11 14:35 UTC, limpbrains commented on UnlockWith.tsx
> +        // Assuming 'true' indicates generic biometrics support
It doesn't 
Check bitometrics.ts 
Actually Biometric.biometricType() will never return true.
I'm fixing this in my PR
https://github.com/BlueWallet/BlueWallet/pull/5947

I will remove UnlockWith.tsx from it, since you are working on it

2024-02-11 21:35 UTC, limpbrains commented on UnlockWith.tsx
> +}
Maybe worth movight types to biometrics.ts

2024-02-11 23:14 UTC, marcosrdz commented on UnlockWith.tsx
> +        // Assuming 'true' indicates generic biometrics support
Updated

2024-02-11 23:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7dz4tkfreq6242y4phgziydoum?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/444)

2024-02-12 00:22 UTC, limpbrains commented on UnlockWith.tsx
> +        // Assuming 'true' indicates generic biometrics support
Please remove the comment, it is misleading now

2024-02-12 01:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zkn7lu26pci2phpqle2jk5un6y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/445)

2024-02-12 04:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zoj63my4fsc42h7tcioc35trjy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/446)

2024-02-12 08:31 UTC, limpbrains approved these changes

2024-02-12 11:36 UTC, merged