feat: deeplink-schema-match typescript
BlueWallet/BlueWallet pull request #6124
Opened 2024-02-11 15:00 UTC by limpbrains

2024-02-11 15:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xhfib722ldzdt3htkchpwvrk3i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/433)

2024-02-11 15:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xbmgqrq6qpcgedpehiwf732lka?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/435)

2024-02-11 23:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p7tlbk6s4qyykdoyv4nozbxd5a?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/443)

2024-02-12 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-13 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-14 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-15 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-15 19:18 UTC, Overtorment commented on typings/bip21.d.ts
> +}
very noice! btw can this be published to npm so anyone  can install typings for bip21 package..?

2024-02-15 19:30 UTC, Overtorment requested changes
lgtm, but this commented out line bothers me

2024-02-15 19:30 UTC, Overtorment commented on class/deeplink-schema-match.ts
> +    // if (!uri) return {};
hmm, this guard clause was here for a reason, probably

2024-02-15 19:30 UTC, Overtorment commented on class/deeplink-schema-match.ts
> +    // if (!uri) return {};
was  added here:  https://github.com/BlueWallet/BlueWallet/commit/6565fd531dab5b8757061151e615ed0fcb4bd709

2024-02-16 12:57 UTC, limpbrains commented on typings/bip21.d.ts
> +}
IT is typed, but not good enought, doesn't export Options, doesn't have `pj`
I don't wan't to bother with it
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bip21/index.d.ts

2024-02-16 13:03 UTC, limpbrains commented on class/deeplink-schema-match.ts
> +    // if (!uri) return {};
I'm not a fan of "return something simular" in case of error. I would rather throw an error in this case

2024-02-16 13:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/neeq5du2n3zrnk5rc4y2fyrdyy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/471)

2024-02-16 13:52 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xix6cdvsvbjwuqrsif5niouesy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/474)

2024-02-17 12:44 UTC, Overtorment approved these changes

2024-02-17 16:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w4gqdkpcsnh7g535s5ef2yvxw4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/491)

2024-02-17 18:19 UTC, limpbrains commented
please, sir, can I merge?

2024-02-18 10:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ii64ajrrwtwdzkzkwmrx4b5cai?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/498)

2024-02-18 13:18 UTC, Overtorment commented
glados, wake up

2024-02-18 13:33 UTC, merged

2024-02-18 13:33 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

2024-02-18 13:36 UTC, Overtorment commented
fizxed glados in https://github.com/BlueWallet/GlaDOS/commit/bc369dda5f9390e36b4f6baa854249afea2f0a5b