feat: refactor BlueApp and storage-context to TS
BlueWallet/BlueWallet pull request #6127
Opened 2024-02-12 11:00 UTC by limpbrains

2024-02-13 23:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ab2nkqmxke7b3treorkum2qq4y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/451)

2024-02-16 13:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nx3w7czvmwiubqqymaj6gdhdze?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/473)

2024-02-16 14:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tbr5ybwtzodhkh3oowweeuwyim?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/475)

2024-02-16 14:16 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cd4yugsjcfb6k3lqh3kehipwhy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/476)

2024-02-18 14:52 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ffkl2zn5vtnpf6elabtjf5shmm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/504)

2024-02-24 16:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3chmbtj7euv7xvmshvuhi3e764?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/574)

2024-02-26 09:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/aryjkipxqckogbrxwrro2ruuvy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/609)

2024-02-29 22:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/sxt6vmwkhs7nbijn6n6tq4e2vu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/639)

2024-02-29 22:15 UTC, limpbrains commented
Nope, not ready yet

2024-02-29 22:52 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/eqtaljrsqrnisjrdiaxtqjeh5m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/643)

2024-03-02 09:09 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6fbqyrtw5nhxssc3x52s5zvylm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/671)

2024-03-02 14:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/67zcy5v3fvr4nmubsyog3ndryu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/673)

2024-03-06 07:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qmholipbwutjmbn2hs3ojbcrqm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/704)

2024-03-09 06:08 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pwc4sg3n4y4rseakn7rbktv6vy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/725)

2024-03-09 06:36 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qo4ds5szwru3ydqxwxh6ndw6s4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/726)

2024-03-09 11:03 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ozypqdn2e6qhstarhlv7jpvyy4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/728)

2024-03-09 11:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4yendlz7niuikhxxhgsogb5sse?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/730)

2024-03-09 14:46 UTC, limpbrains commented
@Overtorment @marcosrdz 
Fixed all the test, please review

2024-03-10 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-10 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-10 13:09 UTC, Overtorment commented on BlueApp.ts
> +        // @ts-ignore wtf is wallet.current? Does it even exist?
good question. probably need to dig into  `git blame` to see where its coming from & why

2024-03-10 13:16 UTC, Overtorment commented on BlueApp.ts
> +        return bTime - aTime;
original code had `sort_ts`, was that a bug?
i see it in `getTransactionsSliced()`, which is `screen` file, not a wallet class

2024-03-10 13:17 UTC, Overtorment commented
and man am i happy to have a e2e & unit tests suites

2024-03-10 17:02 UTC, limpbrains commented on class/wallets/watch-only-wallet.ts
> +type THDWallet = HDLegacyP2PKHWallet | HDSegwitP2SHWallet | HDSegwitBech32Wallet;
Then why I don't see HDSegwitElectrumSeedP2WPKHWallet in init function?

2024-03-10 17:03 UTC, limpbrains commented on class/wallets/watch-only-wallet.ts
> +    let hdWalletInstance: HDLegacyP2PKHWallet | HDSegwitP2SHWallet | HDSegwitBech32Wallet;
Right

2024-03-10 17:05 UTC, limpbrains commented on class/wallets/watch-only-wallet.ts
> +  getUtxo(...args: Parameters<THDWallet['getUtxo']>) {
This approach allows less copy-pasting. If parent.getUtxo changes we don't need to update anything here

2024-03-10 17:07 UTC, limpbrains commented on class/wallets/watch-only-wallet.ts
> +  masterFingerprint: number | false = false;
good

2024-03-10 17:11 UTC, limpbrains commented on class/wallets/watch-only-wallet.ts
> +  public readonly typeReadable = WatchOnlyWallet.typeReadable;
Yes. Before it was done it construnctor, but this approach doesn't work good in TS. 
Now if you do
```
if (WatchOnlyWallet.type === wallet.type) {
```
Type script will understand that wallet is an instance of WatchOnlyWallet

2024-03-10 17:13 UTC, limpbrains commented on class/wallets/watch-only-wallet.ts
> +      const masterFingerprint = this.getMasterFingerprint() || 0;
Done.

2024-03-10 17:17 UTC, limpbrains commented on class/wallets/types.ts
> +  | AbstractHDElectrumWallet // should it be here?
removed

2024-03-10 17:18 UTC, limpbrains commented on class/wallets/lightning-custodian-wallet.ts
> +    // this.balance_raw = json;
removed

2024-03-10 17:21 UTC, limpbrains commented on class/wallets/slip39-wallets.ts
> +  // @ts-ignore: this type mismatch
nope
```
class/wallets/slip39-wallets.ts:88:3 - error TS2416: Property 'setSecret' in type 'SLIP39LegacyP2PKHWallet' is not assignable to the same property in base type 'HDLegacyP2PKHWallet'.
  Type '(newSecret: string) => TWalletThis' is not assignable to type '(newSecret: string) => this'.
    Type 'TWalletThis' is not assignable to type 'this'.
      'this' could be instantiated with an arbitrary type which could be unrelated to 'TWalletThis'.
```

2024-03-10 17:22 UTC, limpbrains commented on class/wallets/lightning-custodian-wallet.ts
> +        // @ts-ignore: fixme wtf?
parseInt accepts string, but here is a number.
Is it here for a reason?

2024-03-10 17:25 UTC, limpbrains commented on class/wallets/lightning-custodian-wallet.ts
> +    // this.setBaseURI(); // no args to init with default value
? 
this.baseURI is already undefined by default.
I'm removing it

2024-03-10 17:28 UTC, limpbrains commented on class/wallets/lightning-custodian-wallet.ts
> +  // info_raw = false;
oops, reverted

2024-03-10 17:28 UTC, limpbrains commented on class/wallets/hd-legacy-breadwallet-wallet.ts
> +      if (AbstractHDElectrumWallet._getTransactionsFromHistories(histories).length > 0) {
Yeah, but TS doesn't support it

2024-03-10 17:29 UTC, limpbrains commented on blue_modules/storage-context.tsx
> +// @ts-ignore defaut value does not match the type
yeap

2024-03-10 17:32 UTC, limpbrains commented on BlueApp.ts
> +      this.cachedPassword = undefined; // maybe reset to false ?
IDK. that is why I'm asking. Looks like it should be false here, but I don't want to break something

2024-03-10 17:33 UTC, limpbrains commented on BlueApp.ts
> +      // @ts-ignore schema doesn't match Realm's schema type
Definitely

2024-03-10 17:34 UTC, limpbrains commented on BlueApp.ts
> +          if (wallet.type === LightningLdkWallet.type || wallet.type === LightningCustodianWallet.type) {
Well. I thought it would work. But it doesn't. Maybe my approach with TWallet is not entirely correct.
I suggest we merge it and then read TS docs :)

2024-03-10 17:37 UTC, limpbrains commented on BlueApp.ts
> +        return bTime - aTime;
Problem that it mutates txs for no reason. This mean types should be changed.
sort_ts is getTransactionsSliced is unrelated and should be refactored the same way, without mutating txs

2024-03-10 18:13 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bcudutkfipin555hi4bwmzzkhy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/745)

2024-03-10 19:08 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ixy7j6m42efd7oezyamfv5s2gm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/749)

2024-03-10 20:18 UTC, limpbrains commented on BlueApp.ts
> +        // @ts-ignore wtf is wallet.current? Does it even exist?
Introduced here https://github.com/BlueWallet/BlueWallet/commit/1e770f779b5229f81d6d0755260d9a426c7955f9#diff-841baddf3c6db8460d70a83323dd2722dc78082c9ac555c1ac6dd477de2b6381R429
@marcosrdz do you know what is it?
Some wallet is marked as a current? is it the same thing as selectedWalletID in storage-context now?

2024-03-11 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-11 15:58 UTC, limpbrains commented on BlueApp.ts
> +          if (wallet.type === LightningLdkWallet.type || wallet.type === LightningCustodianWallet.type) {
'fetchPendingTransactions' in wallet this is the right way to do it, fixed

2024-03-11 16:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2txiqgktc2dgck4knygxfsgjci?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/761)

2024-03-11 16:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4resrwv6a7o36afhbnajmd47hq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/763)

2024-03-12 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-13 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-14 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-15 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-15 20:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u3nqxzbyqhy54vh67tbobja5ey?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/801)

2024-03-16 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-17 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-17 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-18 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-18 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-19 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-19 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-19 19:52 UTC, Overtorment commented on class/wallets/watch-only-wallet.ts
> +  public readonly typeReadable = WatchOnlyWallet.typeReadable;
noice

2024-03-19 19:53 UTC, Overtorment commented on BlueApp.ts
> +      this.cachedPassword = undefined; // maybe reset to false ?
looks like both will work. no point changing it

2024-03-19 20:02 UTC, Overtorment commented on class/wallets/lightning-custodian-wallet.ts
> +        // @ts-ignore: fixme wtf?
aah, looks like  too much defensive programming. `parseInt` is not needed

2024-03-19 20:06 UTC, Overtorment commented on BlueApp.ts
> +        // @ts-ignore wtf is wallet.current? Does it even exist?
ok @marcosrdz doesnt remember. lets keep it with this comment, and maybe sort out later

2024-03-19 20:06 UTC, Overtorment commented on BlueApp.ts
> +      this.cachedPassword = undefined; // maybe reset to false ?
revert to `undefined`

2024-03-19 20:14 UTC, Overtorment commented on BlueApp.ts
> +      // @ts-ignore schema doesn't match Realm's schema type
ok lets merge and figure out later

2024-03-19 20:18 UTC, Overtorment commented on class/wallets/watch-only-wallet.ts
> +type THDWallet = HDLegacyP2PKHWallet | HDSegwitP2SHWallet | HDSegwitBech32Wallet;
aah this is only for watch-only wallet. i thought its gona be used across the app

2024-03-19 20:21 UTC, Overtorment commented on class/wallets/lightning-custodian-wallet.ts
> +    // this.setBaseURI(); // no args to init with default value
hmm, probably leftover from times where default value was initialized later to our default lndhub node

2024-03-19 20:22 UTC, Overtorment requested changes
lets do those couple of mostly cosmetic changes and good to merge

2024-03-20 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-20 18:11 UTC, limpbrains commented on class/wallets/lightning-custodian-wallet.ts
> +// };
removed

2024-03-20 18:11 UTC, limpbrains commented on class/wallets/lightning-custodian-wallet.ts
> +        // @ts-ignore: fixme wtf?
parseInt removed

2024-03-20 18:13 UTC, limpbrains commented on BlueApp.ts
> +      this.cachedPassword = undefined; // maybe reset to false ?
comment removed

2024-03-20 18:28 UTC, limpbrains commented
> lets do those couple of mostly cosmetic changes and good to merge

I believe it is ready

2024-03-20 18:59 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2ntsqicrvwmau4xsafefu4pl4e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/851)

2024-03-21 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-22 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-23 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-03-23 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-23 15:26 UTC, Overtorment commented
![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/950d2c02-8c65-4393-a1cd-2b0e095e7095)

![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/8adee761-4381-418c-9576-7745097501b0)

2024-03-23 15:34 UTC, Overtorment approved these changes

2024-03-23 15:35 UTC, merged