fix: refactor multisig-hd-wallet to TS
BlueWallet/BlueWallet pull request #6148
Opened 2024-02-17 17:14 UTC by limpbrains

2024-02-17 17:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/352hpjknolj6f2jq22ami5xjy4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/492)

2024-02-17 18:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x3wu62e6tofbezinenhi3cd2zq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/495)

2024-02-17 23:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/leofyhjxbx3ghjgz2ofaydpada?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/497)

2024-02-18 15:05 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xqbpmb7kxmtk5bnc7zsj4rta2m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/505)

2024-02-19 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-20 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-21 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-22 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-23 18:58 UTC, Overtorment requested changes

2024-02-23 18:58 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.ts
> +        throw new Error('Could not create p2wsh output');
or is it to make ts happy?

2024-02-23 18:58 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.ts
> +        const inputTx = bitcoin.Transaction.fromBuffer(inp.nonWitnessUtxo);
is it buffer here? o_O

2024-02-23 18:58 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.ts
> +        hash: input.txid,
`blue_modules/BlueElectrum.js:546`  suggests it should be camelCase.

type definition in `blue_modules/BlueElectrum.d.ts` too

2024-02-23 18:58 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.ts
> +        hash: input.txid,
the confusion probably comes from `CoinSelectReturnInput` that has lowercase `txid`.

but nature of `coinselect` is such that it doesnt care about most of the fields of inputs, it just passes them through, so if it was `txId` it will stay `txId` after coinselect selected utxos for you

2024-02-23 20:34 UTC, limpbrains commented on class/wallets/multisig-hd-wallet.ts
> +        throw new Error('Internal error: could not make p2sh address');
This is how bitcoinjs is typed. Also this this the approach we are using in other files that are already typed. 
So I suggest we keep it consistent. 
I'm qurious abouht this too

2024-02-23 20:40 UTC, limpbrains commented on class/wallets/multisig-hd-wallet.ts
> +        const inputTx = bitcoin.Transaction.fromBuffer(inp.nonWitnessUtxo);
yeap. And both options works :)

2024-02-23 20:41 UTC, limpbrains commented on class/wallets/multisig-hd-wallet.ts
> +        throw new Error('Could not create p2wsh output');
yes. same as previous check

2024-02-23 20:44 UTC, limpbrains commented on class/wallets/multisig-hd-wallet.ts
> +        hash: input.txid,
Do you think successfull tests is enought to get rid of camel case option?
Or maybe we should investigate deeper and fix it in another PR?

2024-02-24 10:00 UTC, limpbrains commented on class/wallets/multisig-hd-wallet.ts
> +        hash: input.txid,
all other wallets are using `input.txId` here, I think it is safe

2024-02-24 10:01 UTC, limpbrains commented on class/wallets/multisig-hd-wallet.ts
> +    const customPaths: { [key: string]: number } = {};
fixed

2024-02-24 10:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4bxtix5fye42ums6kbrrhq7xoq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/560)

2024-02-24 10:40 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.ts
> +        hash: input.txid,
i think we better switch to lowercase `txid` everywhere, for consistency, but in a separete PR.

looks like switching from `txId`  to `txid`here particularly will break the wallet, even if ts will be unhappy

2024-02-24 10:41 UTC, Overtorment commented on class/wallets/multisig-hd-wallet.ts
> +        hash: input.txid,
so maybe lets keep camelCase for now, and convert tests to ts as well

2024-02-24 11:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j62bw2oyed74ozqsnijngfna2e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/562)

2024-02-24 11:50 UTC, limpbrains commented on class/wallets/multisig-hd-wallet.ts
> +        hash: input.txid,
I've changed for now to input.txId || input.txid as is in abstract-hd-electrum-wallet.ts

2024-02-25 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-25 17:01 UTC, Overtorment approved these changes

2024-02-25 17:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3tvlzghsa3oed5ryuzfqioddj4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/594)

2024-02-25 21:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/s6v4yfaa55ngvvlr6so6dfkfpa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/599)

2024-02-25 21:36 UTC, merged

2024-02-25 21:36 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!