REF: LNNodeBar to TS
BlueWallet/BlueWallet pull request #6157
Opened 2024-02-20 01:21 UTC by Danswar

2024-02-20 05:35 UTC, marcosrdz approved these changes

2024-02-20 11:33 UTC, limpbrains requested changes

2024-02-20 11:33 UTC, limpbrains commented on components/LNNodeBar.tsx
> +  itemPriceUnit = BitcoinUnit.SATS
please run `npm run lint:fix` before commit

2024-02-20 23:53 UTC, Danswar commented on components/LNNodeBar.tsx
> +  itemPriceUnit = BitcoinUnit.SATS
hey @limpbrains, I did it, but it is complaining for a problem in a file I didn't touch in this PR 😖

<img width="945" alt="Screenshot 2024-02-20 at 20 52 00" src="https://github.com/BlueWallet/BlueWallet/assets/48102227/ecc77dd6-889b-46c7-ad97-a3de70cf4a66">

2024-02-21 01:10 UTC, Danswar commented on components/LNNodeBar.tsx
> +  itemPriceUnit = BitcoinUnit.SATS
dismiss the previous comment

2024-02-21 01:12 UTC, Danswar commented
@limpbrains Thanks for the comment. I think everything should go well this time.

2024-02-21 08:42 UTC, limpbrains approved these changes

2024-02-21 23:01 UTC, marcosrdz approved these changes

2024-02-21 23:01 UTC, merged