REF: SquareEnumaratedWords to TS
BlueWallet/BlueWallet pull request #6166
Opened 2024-02-22 01:25 UTC by Danswar

Component to Typescript + removing inline styles

2024-02-22 12:08 UTC, limpbrains requested changes

2024-02-22 12:08 UTC, limpbrains commented on components/SquareEnumeratedWords.tsx
> +  contentAlign?: ContentAlignType;
I'm looking at how this component is used in ﻿viewEditMultisigCosigners.tsx. ﻿`entries` and ﻿`contentAlign` props are always defined; ﻿`appendNumber` is always false. 

In my opinion, it's worth removing default values, marking all properties as required

2024-02-23 00:56 UTC, Danswar commented
@limpbrains I believe this is ready for a second look

2024-02-23 07:13 UTC, limpbrains approved these changes

2024-02-23 08:37 UTC, limpbrains commented
@marcosrdz build is failing, can you please take a look?

2024-02-23 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-24 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-25 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-26 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-27 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-28 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-29 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-02-29 21:46 UTC, Overtorment commented
builds failing probably due to env secrets not injected on CI, because of out sidecontributor

2024-02-29 21:46 UTC, merged