REF: SquareButton to TS
BlueWallet/BlueWallet pull request #6182
Opened 2024-02-25 15:46 UTC by Danswar

@limpbrains Would you like to take a look?

Based on the usage of this component, I removed some of the props that are no longer in use, the same goes for code bound to those props and always-overwritten styles.

2024-02-25 16:56 UTC, Overtorment approved these changes
lgtm

2024-02-26 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-02-26 12:03 UTC, limpbrains requested changes

2024-02-27 10:59 UTC, Danswar commented on components/SquareButton.tsx
> +      fontSize: 16,
solved

2024-02-27 10:59 UTC, Danswar commented on components/SquareButton.tsx
> +/* eslint react/prop-types: "off", react-native/no-inline-styles: "off" */
done

2024-02-27 11:00 UTC, Danswar commented on components/SquareButton.tsx
> +  const { title, onPress, style, testID = '' } = props;
OMG, done thanks!

2024-02-27 11:01 UTC, Danswar commented
@limpbrains fancy to have a second look? thanks for catching those details.

2024-02-27 11:53 UTC, limpbrains approved these changes
awesome work

2024-02-28 23:20 UTC, merged