add explanation for airdrop usage
BlueWallet/BlueWallet pull request #6195
Opened 2024-02-27 09:02 UTC by setavenger

2024-02-27 11:26 UTC, marcosrdz requested changes

2024-02-27 11:26 UTC, marcosrdz commented on loc/en.json
> +    "this_is_cosigners_xpub_airdrop": "If you share via airdrop the receivers have to be in the coordination screen.",
Please adjust to "AirDrop" as its a brand

2024-02-27 12:04 UTC, marcosrdz approved these changes

2024-02-27 16:14 UTC, Overtorment approved these changes

2024-02-28 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-02-28 12:08 UTC, limpbrains approved these changes

2024-02-28 12:34 UTC, merged