FIX: Crash due to actionsheet changes
BlueWallet/BlueWallet pull request #6271
Opened 2024-03-13 21:45 UTC by marcosrdz

2024-03-13 21:48 UTC, Overtorment requested changes

2024-03-13 21:48 UTC, Overtorment commented on screen/wallets/transactions.js
> +            scanQrHelper(navigate, onBarCodeRead);
this is not how scanQrHelper works. function signature is:

```
scanQrHelper(
  navigateFunc: (scr: string | any, params?: any) => void,
  currentScreenName: string,
  showFileImportButton = true,
  onDismiss?: () => void,
): Promise<string | null>
```

2024-03-13 22:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xdq5omxhkmg5s2ulqpftqcljy4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/778)

2024-03-13 22:20 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mbeuxby2rjyfc6ydvsklgl6xsi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/779)

2024-03-13 23:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cdotomi7ygsuodlvxksr4f7dcy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/784)

2024-03-14 01:56 UTC, merged

2024-03-14 01:56 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!