ADD: Save File Button
BlueWallet/BlueWallet pull request #6309
Opened 2024-03-22 00:55 UTC by marcosrdz

<img width="348" alt="Screenshot 2024-03-21 at 8 54 58 PM" src="https://github.com/BlueWallet/BlueWallet/assets/4793122/a9126855-7808-43ba-b27d-a9cab9f1e374">

iOS: Straight to share
Android: offer save/share

following each platform's expected behavior

2024-03-22 01:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/c7fwfqquk7ai5s5odmb6bg5hne?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/875)

2024-03-22 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-22 23:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/apsj7jjicmp7sfass7nk26wwwa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/881)

2024-03-23 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-23 17:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x54kj4w5ud57b5qlw53ywyowcq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/889)

2024-03-23 17:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y26jbeuq3gvijxvwynrij53chy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/890)

2024-03-23 21:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ohopwzniqwih4b3iabdns5cjbq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/899)

2024-03-24 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-24 20:32 UTC, Overtorment commented
just tested on my android, works pretty great

2024-03-24 21:07 UTC, Overtorment requested changes
CSV export is broken; needs refactoring

2024-03-24 21:07 UTC, Overtorment commented on blue_modules/fs.ts
> +    const filePath = RNFS.TemporaryDirectoryPath + `/${fileName}`;
camelcasing fileName was unnecessary tbh

2024-03-24 21:53 UTC, marcosrdz commented on components/SaveFileButton.tsx
> +};
that's cause every button might have its own style. so that's why u pass down the child button. 
also, android has different approach to files, iOS has its own too

2024-03-24 22:28 UTC, marcosrdz commented on components/SaveFileButton.tsx
> +};
Refactored

2024-03-24 22:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fpebitp226prilt23yladn77s4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/926)

2024-03-24 23:19 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/o77rgdigq6fq5jqlrgfmwesr6e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/928)

2024-03-25 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-26 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-27 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-28 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-28 20:42 UTC, Overtorment requested changes

2024-03-28 20:42 UTC, Overtorment commented on screen/wallets/details.js
> +                    <SaveFileButton fileName={`${wallet.getLabel().replace(' ', '-')}-history.csv`} fileContent={exportHistoryContent}>
que es aqui pendejo?

it should be 

```
fileContent={exportHistoryContent()}
```

you can cache it if youre worried about performance

2024-03-28 20:42 UTC, Overtorment commented on components/SaveFileButton.tsx
> +  fileContent: string | (() => string);
loco

2024-03-29 19:10 UTC, marcosrdz commented on screen/wallets/details.js
> +                    <SaveFileButton fileName={`${wallet.getLabel().replace(' ', '-')}-history.csv`} fileContent={exportHistoryContent}>
Done

2024-03-29 20:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4tg22ntw2el4jwtrrplvvgr2q4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1003)

2024-03-29 22:19 UTC, Overtorment requested changes
`FAIL tests/integration/App.test.js`

either test needs updating or smth wrong with the component

2024-03-30 01:46 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gtciiznzaavkmiasuqmhg4lcsu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1005)

2024-03-30 02:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/reeualeyxuiuxn3jk2p27u5jhm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1007)

2024-03-30 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-31 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-01 00:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/atjujgshj74ike23w75xchntsa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1044)

2024-04-01 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-02 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-02 17:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/edzx7mkogklnvzkt3t5exiv7lm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1051)

2024-04-02 22:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/743tyqlf3kdbczop7hurpfl7ri?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1053)

2024-04-03 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-03 13:45 UTC, Overtorment approved these changes
lgtm

2024-04-03 13:48 UTC, merged

2024-04-03 13:48 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

2024-04-09 20:15 UTC, limpbrains commented on components/SaveFileButton.tsx
> +      await fs.writeFileAndExport(fileName, fileContent, false, Platform.OS !== 'android').finally(() => {
fs.writeFileAndExport only accepts 3 parameters