REF: DefaultView to TSX and hook
BlueWallet/BlueWallet pull request #6315
Opened 2024-03-22 23:11 UTC by marcosrdz

2024-03-22 23:44 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fkamftaj3yzec6tmai4tqblz4y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/880)

2024-03-23 00:08 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j7crvncrb7v56jmjhesqe2m4wm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/882)

2024-03-23 01:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ial6fpfs4mhdxmfstt5s5fm2om?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/883)

2024-03-23 01:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bqu2yjldqr3celnlai3cglvma4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/884)

2024-03-23 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-23 15:47 UTC, Overtorment requested changes

2024-03-23 15:47 UTC, Overtorment commented on hooks/useOnAppLaunch.ts
> +  }, [STORAGE_KEY]); // No external dependencies
looks weird

2024-03-23 15:47 UTC, Overtorment commented on hooks/useOnAppLaunch.ts
> +  const getSelectedDefaultWallet = useCallback(async (): Promise<AbstractWallet | false> => {
with newest refactoring I think we better use TWallet here instead of AbstractWallet (and everywhere else), right, @limpbrains  ?

2024-03-23 15:47 UTC, Overtorment commented on hooks/useOnAppLaunch.ts
> +  ); // Include dependencies here
comment

2024-03-23 15:47 UTC, Overtorment commented on screen/settings/DefaultView.tsx
> +  // Add other screens here as needed
comment

2024-03-23 15:47 UTC, Overtorment commented on screen/settings/DefaultView.tsx
> +  const onWalletSelectValueChanged = async (wallet: { getID: () => string; getLabel: () => string; }) => {
warning

2024-03-23 16:11 UTC, marcosrdz commented on screen/settings/DefaultView.tsx
> +  const onWalletSelectValueChanged = async (wallet: { getID: () => string; getLabel: () => string; }) => {
Fixed

2024-03-23 16:14 UTC, Overtorment approved these changes

2024-03-23 16:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ir64fkmfkurmorzn5wwnqunlni?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/886)

2024-03-23 16:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/32h6t2bcbfekdvsnm7f7t6tuke?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/887)

2024-03-23 16:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xzwcetu23x46yfr4s2uk2lcnty?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/888)

2024-03-23 20:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7m7c67na4eweguordxyhwtzium?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/892)

2024-03-23 20:59 UTC, limpbrains approved these changes

2024-03-23 22:03 UTC, merged

2024-03-23 22:03 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!