REF: WalletButton to TSX
BlueWallet/BlueWallet pull request #6346
Opened 2024-03-27 23:54 UTC by marcosrdz

2024-03-28 00:29 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qy7o4ls7x5xbl6loy3dcc3oboe?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/975)

2024-03-28 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-28 20:55 UTC, Overtorment requested changes

2024-03-28 20:55 UTC, Overtorment commented on components/WalletButton.tsx
> +// Define the button details. Adjust image paths as necessary
comment

2024-03-28 20:55 UTC, Overtorment commented on components/WalletButton.tsx
> +    image: require('../img/addWallet/bitcoin.png'), // Adjust path as necessary
comment

2024-03-28 22:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xpsrqjolwtk7h2bnhlykpp5jfq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/986)

2024-03-29 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-30 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-31 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-03-31 23:37 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j6lttx2b264gmhcxusmfbrymoe?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1043)

2024-04-01 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-02 08:12 UTC, limpbrains approved these changes

2024-04-02 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-03 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-03 14:07 UTC, Overtorment requested changes
are you keeping it just for lulz..?

![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/e880a40f-3f91-4014-a416-953e2f9020c9)

2024-04-03 14:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ot5d5lmcvvcoupdwqwktifuj4i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1058)

2024-04-03 16:24 UTC, merged