REF: WalletsList TSX
BlueWallet/BlueWallet pull request #6413
Opened 2024-04-15 01:01 UTC by marcosrdz

2024-04-15 01:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5cspbvh6r7afziu5vsdkhs3agm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1184)

2024-04-15 10:03 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-16 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-17 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-18 08:05 UTC, limpbrains approved these changes

2024-04-18 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-18 18:42 UTC, Overtorment requested changes

2024-04-18 18:42 UTC, Overtorment commented on helpers/getIsLargeScreen.ts
> +  return Platform.OS === 'android' ? isTablet() : (width >= width / 2 && isTablet()) || isDesktop;
wtf is `width >= width / 2`
any positive number satisfies this

2024-04-18 18:42 UTC, Overtorment commented on helpers/getIsLargeScreen.ts
> +  return Platform.OS === 'android' ? isTablet() : (width >= width / 2 && isTablet()) || isDesktop;
also, why  the difference between android & ios? leave a comment explanation

2024-04-18 18:42 UTC, Overtorment commented on screen/wallets/WalletsList.tsx
> +  SET_LOADING = 'SET_LOADING',
btw, you dont have to set string values to enums, you can just list enums, and ts will assign them a sequential number under the hood

2024-04-18 18:42 UTC, Overtorment commented on screen/wallets/WalletsList.tsx
> +  SET_LOADING = 'SET_LOADING',
e.g.

```ts
enum ActionTypes {
  SET_LOADING,
  SET_WALLETS,
}
```

2024-04-18 19:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/alavtbkshpdataioljj4p2eruy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1216)

2024-04-18 22:33 UTC, marcosrdz commented on helpers/getIsLargeScreen.ts
> +  return Platform.OS === 'android' ? isTablet() : (width >= width / 2 && isTablet()) || isDesktop;
updated.

2024-04-18 22:33 UTC, marcosrdz commented on screen/wallets/WalletsList.tsx
> +  SET_LOADING = 'SET_LOADING',
done

2024-04-18 22:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/efaz5lw57cfr23bfedgv46fjw4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1223)

2024-04-18 23:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ixfaolifachqzw7kktzvvkairy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1226)

2024-04-19 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-19 15:25 UTC, marcosrdz commented on helpers/getIsLargeScreen.ts
> +  return Platform.OS === 'android' ? isTablet() : (width >= width / 2 && isTablet()) || isDesktop;
Used to have to differentiate before. No longer need to

2024-04-20 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-21 02:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/25vyqt3jf6h3pcz2r6uj3owdra?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1241)

2024-04-21 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-21 14:24 UTC, Overtorment approved these changes
lgtm

2024-04-21 14:24 UTC, merged