REF: SettingsContext
BlueWallet/BlueWallet pull request #6418
Opened 2024-04-18 01:06 UTC by marcosrdz

useSettings hook. First step on separating providers/context

2024-04-18 01:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z24dmttxdk7gmd4g5tdg75u5py?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1197)

2024-04-18 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-04-18 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-18 17:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qe4s4oko2tkj23rtkl4h3yfqi4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1211)

2024-04-18 18:22 UTC, Overtorment requested changes
mostly lgtm, but got some issues

2024-04-18 18:22 UTC, Overtorment commented on android/.settings/org.eclipse.buildship.core.prefs
> +show.executions.view=true
feels like this should not be committed?

2024-04-18 18:22 UTC, Overtorment commented on android/app/.classpath
> +	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-21/"/>
feels like this should not be committed?

2024-04-18 18:22 UTC, Overtorment commented on android/app/.project
> +	</filteredResources>
feels like this should not be committed?

2024-04-18 18:22 UTC, Overtorment commented on components/TransactionListItem.js
> +  const { txMetadata, wallets } = useContext(BlueStorageContext);
we now have `useSettings`. 

would it be better to refactor so instead of  `= useContext(BlueStorageContext)` we could write `useBlueApp` ?

2024-04-18 18:34 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bvlrlfu2biub67vtejheo7tzcy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1213)

2024-04-18 21:30 UTC, limpbrains approved these changes

2024-04-18 21:32 UTC, marcosrdz commented on components/TransactionListItem.js
> +  const { txMetadata, wallets } = useContext(BlueStorageContext);
Next step is useElectrum. Then useStorage/useBlueApp.

2024-04-18 22:09 UTC, Overtorment approved these changes

2024-04-18 22:41 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hzebasuxm3mlyw66gt4vmolyja?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1222)

2024-04-19 00:24 UTC, merged

2024-04-19 00:24 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!