Update TransactionsNavigationHeader.tsx
BlueWallet/BlueWallet pull request #6454
Opened 2024-04-23 22:59 UTC by marcosrdz

2024-04-23 23:22 UTC, Overtorment requested changes

2024-04-23 23:22 UTC, Overtorment commented on components/TransactionsNavigationHeader.tsx
> +    marginT: 50,
Typo..?

2024-04-23 23:29 UTC, marcosrdz commented on components/TransactionsNavigationHeader.tsx
> +    marginT: 50,
fixed

2024-04-23 23:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2m5lbgazmc3ed5t4x2ivs7r2me?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1283)

2024-04-23 23:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xulyh3rgzwsgrli3h3b3qtkjfm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1284)

2024-04-24 05:01 UTC, Overtorment approved these changes

2024-04-24 05:06 UTC, merged

2024-04-24 05:06 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!