REF: Use interaction manager for tx refresh
BlueWallet/BlueWallet pull request #6463
Opened 2024-04-26 02:13 UTC by marcosrdz

InteractionManager helps minimizing UI hangs

2024-04-26 02:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/iu2zgnuq7mtmw2xn7s5b6i445y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1306)

2024-04-26 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-27 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-28 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-04-28 19:02 UTC, Overtorment requested changes

2024-04-28 19:02 UTC, Overtorment commented on blue_modules/storage-context.tsx
> +          fetchWalletTransactions(lastSnappedTo),
unfortunately, cant parallelize those 3, they have to be sequential.

* fetch payment codes finds addresses from our payers 
* fetch balance finds all the used addresses AND fetches all balances for all addresses
* finally,  fetch txs gets all those addressesand fetches all their txs

2024-04-28 22:44 UTC, limpbrains requested changes

2024-04-28 22:44 UTC, limpbrains commented on blue_modules/storage-context.tsx
> +    await InteractionManager.runAfterInteractions(async () => {
await is not needed, `runAfterInteractions`
Instead of using callback, I prefer Promise:
```js
		await new Promise((resolve) => {
			InteractionManager.runAfterInteractions(() => resolve(null));
		});
```

2024-05-26 22:24 UTC, closed without merging