REF: BIP-47, improvements under the hood
BlueWallet/BlueWallet pull request #6466
Opened 2024-04-26 22:49 UTC by Overtorment

2024-04-26 23:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kalj2xkcoc4rcnmaf7voi3kzaq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1310)

2024-04-26 23:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4ukakot5abvlwm7xly2dtrizzq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1311)

2024-04-26 23:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zeztqhp44kkj3yzgly42ehpfda?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1312)

2024-04-27 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-04-27 16:34 UTC, limpbrains requested changes

2024-04-27 16:34 UTC, limpbrains commented on class/wallets/abstract-hd-electrum-wallet.ts
> +        hex: '6a4c50' + blindedPaymentCodeTemp, // no `address` here, its gonabe op_return
what is this hex value, comment would be nice

2024-04-27 16:34 UTC, limpbrains commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    assert(inputsTemp && inputsTemp[0] && inputsTemp[0].wif);
inputsTemp?.[0]?.wif

2024-04-27 16:34 UTC, limpbrains commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    outputNumber.writeUInt32LE(+inputsTemp[0].vout);
this should be already a number, no?
Why force?

2024-04-27 16:34 UTC, limpbrains commented on class/wallets/abstract-hd-electrum-wallet.ts
> +        hex: '6a4c50' + blindedPaymentCode, // no `address` here, its gonabe op_return
Probably should be a constant

2024-04-27 16:34 UTC, limpbrains commented on class/wallets/abstract-hd-electrum-wallet.ts
> +      if (histories[address] && histories[address].length > 0) {
Embrace optional chaining

2024-04-27 16:34 UTC, limpbrains commented on class/wallets/abstract-hd-electrum-wallet.ts
> +import assert from 'assert';
I like assert

2024-04-27 17:09 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +        hex: '6a4c50' + blindedPaymentCodeTemp, // no `address` here, its gonabe op_return
ah yes, its literally OP_RETURN oppcode

2024-04-27 21:21 UTC, Overtorment commented
@abhiShandy

2024-04-27 21:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6atljsmklkydqg5klczxsogf5i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1337)

2024-04-27 21:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ia4avjwd6u2lfapj6xhsyh3wuy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1338)

2024-04-28 01:56 UTC, abhiShandy reviewed
I have left a few suggestions.

2024-04-28 01:56 UTC, abhiShandy commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    const bobBip47 = BIP47Factory(ecc).fromPaymentCode(receiverPaymentCode);
Can we validate the paymentCode string before using it?

2024-04-28 07:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4rupzjbv3vtpt7bpzeeqcm52sq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1341)

2024-04-28 19:24 UTC, Overtorment commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    const bobBip47 = BIP47Factory(ecc).fromPaymentCode(receiverPaymentCode);
checksum is validated somewhere indise, it throws an exception if its not a valid PC

2024-04-28 20:50 UTC, abhiShandy commented on class/wallets/abstract-hd-electrum-wallet.ts
> +    const bobBip47 = BIP47Factory(ecc).fromPaymentCode(receiverPaymentCode);
alright. Do we need to unit test that?

2024-04-28 21:50 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fkvu6hti3ghtez7skfs4rbpw2a?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1397)

2024-04-29 10:23 UTC, merged