TST: run e2e tests on ubuntu-latest
BlueWallet/BlueWallet pull request #6477
Opened 2024-04-28 09:54 UTC by limpbrains

2024-04-28 10:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w4lw47kk4372m64fmxk2satprm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1351)

2024-04-28 10:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dzobxn54inojbpq4hs6q27myk4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1352)

2024-04-28 11:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2j7klct3i5momgra7h34bywiji?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1356)

2024-04-28 11:53 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cvnvozp7ettvf6363imzrqmxti?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1357)

2024-04-28 14:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gsbf2544u3p5dummsfsmrseai4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1360)

2024-04-28 14:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/eqsadqlraj3glrzmvhrw5kg7wq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1361)

2024-04-28 16:34 UTC, Overtorment commented
```

Invalid workflow file: .github/workflows/ci.yml#L62
You have an error in your yaml syntax on line 62

```

2024-04-28 22:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qklosxl5il2ghs4bk4puohricq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1400)

2024-04-28 22:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j4bnaisxq7seumpihrh24y24my?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1401)

2024-04-28 23:00 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/t7pcxeva54oskfe6rih5l2iege?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1402)

2024-04-28 23:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mr66w44tmpondbpg5avx2yoyv4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1403)

2024-04-28 23:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xj63vvgj2fwaqut5t3il5idigm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1404)

2024-04-28 23:42 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/agzsajkexgldvncmmvh2q3eicm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1405)

2024-04-29 09:18 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bheltkqirqwbece67ibawy6w6u?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1409)

2024-04-29 21:55 UTC, Overtorment commented on tests/e2e/bluewallet2.spec.js
> +    await element(by.id('chooseFee1')).tap();
is that on purpose to make it fail?

2024-04-29 22:06 UTC, limpbrains commented on tests/e2e/bluewallet2.spec.js
> +    await element(by.id('chooseFee1')).tap();
Yeah, testing artifact uploading

2024-04-29 23:55 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gs6j4gsap444a4744kt2homy7y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1423)

2024-04-30 17:51 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ed4nf5uflv7ie6fujubng5krvm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1426)

2024-04-30 18:21 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bcefrws7dpatwl5t5pduoxznhe?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1428)

2024-04-30 23:24 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7rc3py7fcep7t32yd7ur4girli?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1431)

2024-05-01 09:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/l2kk4ke3664fkrfrlw5kaluruq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1432)

2024-05-01 09:47 UTC, limpbrains commented
runs stable
~ 40 min average

2024-05-01 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-05-01 20:34 UTC, Overtorment requested changes
great job overal! just have some questions.
plus im kinda interested to compare old e2e on macos to this ubuntu-based back-to-back

2024-05-01 20:34 UTC, Overtorment commented on .github/workflows/ci.yml
> +      run: npm install || npm install
wut

2024-05-01 20:34 UTC, Overtorment commented on .github/workflows/ci.yml
> +        ln -s /mnt/.gradle /home/runner/
looks a bit fragile tbh

2024-05-01 20:34 UTC, Overtorment commented on .github/workflows/ci.yml
> +    - name: Run tests
so you threw away all test attempts you coded? in favor of `-R 3` key?
is the output redable? you like it?

2024-05-01 20:34 UTC, Overtorment commented on package.json
> +    "e2e:release-test": "detox test -c android.release",
i suppose you want these arguments to be CI-specific, while on localhost this npm command just runs plain single e2e  run..?

2024-05-01 20:34 UTC, Overtorment commented on .github/workflows/ci.yml
> +    - name: Create artifacts directory on /mnt
btw do we know whats this mount point..?

2024-05-01 20:34 UTC, Overtorment commented on .github/workflows/ci.yml
> +    - name: Create artifacts directory on /mnt
where does it point exactly?

2024-05-01 20:48 UTC, Overtorment commented
man i went through a bunch or recent PRs, and their e2es all take at least 80 min. sometimes 120, 200 min.
the difference is YUUUUUUUUUUUUGE

2024-05-01 20:49 UTC, Overtorment commented
why theres such a difference??

2024-05-01 21:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/niyobnv4wfnnfgpsmvsi277w3e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1439)

2024-05-01 22:31 UTC, limpbrains commented on .github/workflows/ci.yml
> +      run: npm install || npm install
because npm fails sometimes, like error 400 or something

2024-05-01 22:31 UTC, limpbrains commented on .github/workflows/ci.yml
> +        ln -s /mnt/.gradle /home/runner/
look ok to me

2024-05-01 22:32 UTC, limpbrains commented on .github/workflows/ci.yml
> +    - name: Run tests
-R 3 is simplier, that is why I'm choosing it

2024-05-01 22:35 UTC, limpbrains commented on package.json
> +    "e2e:release-test": "detox test -c android.release",
exectly. You don't ususally record a video on localhost, or run test 3 times

2024-05-01 22:36 UTC, limpbrains commented on .github/workflows/ci.yml
> +    - name: Create artifacts directory on /mnt
No idea. Found that people who have similar issues use it.
Some temporary storage, I assume

2024-05-01 23:04 UTC, limpbrains commented
> why theres such a difference??

Who knows 🤷
I think they just finally fixed virtualisation for Linux runners. For macos VM tools always have been poor 

Will see how arm runners will work

2024-05-02 12:27 UTC, Overtorment approved these changes

2024-05-02 12:37 UTC, merged

2024-05-02 12:37 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!