Add display bip47 counterparty in tx list
BlueWallet/BlueWallet pull request #6520
Opened 2024-05-05 19:28 UTC by Overtorment

![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/9bcf427a-ac73-4338-8dc6-5673f6961ef5)
![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/69b8e45b-a59f-48f4-8343-39a54478a64c)

2024-05-05 19:42 UTC, marcosrdz approved these changes

2024-05-05 19:55 UTC, marcosrdz commented
CI failed

2024-05-05 19:57 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dn4gzeyfrbxahparjlpxtlbn7i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1480)

2024-05-05 19:58 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/h3vrswaxw742sgi5jltj3s2za4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1481)

2024-05-05 21:30 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4j3ebyvfqumxwzsu2tz53y6kfa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1483)

2024-05-06 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-05-06 10:55 UTC, limpbrains requested changes

2024-05-06 10:55 UTC, limpbrains commented on loc/en.json
> +    "to": "To:",
It should be "From: {counterparty}". Because word order might be very different for different languages

2024-05-06 12:16 UTC, limpbrains approved these changes

2024-05-06 12:40 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4o7wbybcxc6rufyxoqs4zmmbiu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1492)

2024-05-06 12:56 UTC, merged

2024-05-06 12:56 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!