ADD: rename counterparty paymentcode
BlueWallet/BlueWallet pull request #6532
Opened 2024-05-08 18:14 UTC by Overtorment

In this PR I added an option to rename payment code locally,  so it looks like a human readable contact in your transactions.
edit happens ot tx details screen, right below where you can edit transaction memo.

also, in this PR:

* PC aliases are saved in BlueAppm, right next to tx metadata
* refactored types a bit (added ExtendedTransaction) 
* fixed debug export on engineer-backdoor on wallet details
* `transactions/details.tsx` to typescript
* added unit tests for BlueApp.getTransaction() and to tx_metadata & counterparty_metadata
* renamed some stuff and fixed lint warnings

![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/8f2c48bd-b52d-4df6-8171-efab6d5c88fb)
![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/611b049b-dddc-4d79-9314-ae817d4fe418)
![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/26e0de3f-57b0-4811-98d4-4e077b85090e)

2024-05-08 18:16 UTC, Overtorment commented on class/blue-app.ts
> +  public counterparty_metadata: TCounterpartyMetadata;
@limpbrains i was thinking long and hard  how to introduce `ContactList` class, but could not decide what would it do and how would it work with our storage, so settled for this. if you have good idea lmk

2024-05-08 18:21 UTC, Overtorment commented on screen/transactions/details.tsx
> +          // @ts-ignore TWallet and AbstractHD do not overlap ¯\_(ツ)_/¯
@limpbrains any ideas how to make it kosher ts-wise..?

2024-05-08 18:21 UTC, Overtorment commented on tests/unit/storage.test.js
> +      label: 'yegor letov',
ооооооо моя оборона

2024-05-08 18:38 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uecatdps7s5jsfvmiazznqnvfm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1514)

2024-05-08 19:06 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r6zvcin3nquu45u5h35vwjcf3q?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1516)

2024-05-09 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-05-09 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

2024-05-09 11:01 UTC, limpbrains requested changes

2024-05-09 11:01 UTC, limpbrains commented on screen/transactions/details.tsx
> +          // @ts-ignore TWallet and AbstractHD do not overlap ¯\_(ツ)_/¯
```js
if (wallet.allowBIP47() && wallet.isBIP47Enabled() && 'getBip47CounterpartyByTxid' in wallet) {
```

Doesn't look very nice, but it will work

2024-05-09 11:01 UTC, limpbrains commented on screen/transactions/details.tsx
> +                placeholder="Edit contact name"
localization

2024-05-09 11:47 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pggrgfy6g52ql3plb2ni6xteju?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1532)

2024-05-09 22:41 UTC, limpbrains approved these changes

2024-05-09 22:44 UTC, marcosrdz approved these changes

2024-05-09 22:44 UTC, merged

2024-05-09 22:44 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!