REF: Single source of truth for useIsLargeScreen
BlueWallet/BlueWallet pull request #6552
Opened 2024-05-13 17:08 UTC by marcosrdz

2024-05-13 23:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xiwauguxpw6c22bkdzmfyvjbu4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1574)

2024-05-14 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-05-14 21:25 UTC, Overtorment requested changes

2024-05-14 21:25 UTC, Overtorment commented on components/Context/LargeScreenProvider.tsx
> +import { isDesktop } from '../../blue_modules/environment';
feels like we should hide `isTablet` in `/blue_modules/environment` too

2024-05-14 21:25 UTC, Overtorment commented on components/Context/LargeScreenProvider.tsx
> +import { isDesktop } from '../../blue_modules/environment';
wdyt?

2024-05-14 23:02 UTC, marcosrdz commented on components/Context/LargeScreenProvider.tsx
> +import { isDesktop } from '../../blue_modules/environment';
addressed

2024-05-14 23:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/i6sjl3ak52hu4bpzfgytv44doe?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1578)

2024-05-15 00:14 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zdduu4p7msxfsosfzoczfq2qaa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1579)

2024-05-15 03:01 UTC, Emmanuelchinyere approved these changes

2024-05-15 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-05-15 12:02 UTC, Overtorment requested changes

2024-05-15 12:02 UTC, Overtorment commented on blue_modules/environment.ts
>  import { isTablet, getDeviceType } from 'react-native-device-info';
isTablet is a function here. Let's export simple Boolean, for consistency?

2024-05-15 12:05 UTC, marcosrdz commented on blue_modules/environment.ts
>  import { isTablet, getDeviceType } from 'react-native-device-info';
done

2024-05-15 12:08 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vjgytk75a3abepldqir34tpozm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1581)

2024-05-15 12:12 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rmyha7y2ea77qdlxmkorj3skpu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1582)

2024-05-15 12:31 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d7r5t36lpmkrjkydsfqvewp5fq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1583)

2024-05-15 14:38 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zcxlwwxjw6ql7zwbqvjbwkq54u?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1584)

2024-05-15 22:22 UTC, Overtorment approved these changes

2024-05-15 22:56 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gipjznjokvgbdikstkrqyggmrq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1589)

2024-05-16 02:15 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pxl2xl5dtawp5zz75vl6qq765i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1597)

2024-05-16 02:40 UTC, merged

2024-05-16 02:40 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!