ADD: BIP47 send to contacts
BlueWallet/BlueWallet pull request #6623
Opened 2024-05-27 22:00 UTC by Overtorment

2024-05-27 22:03 UTC, marcosrdz requested changes

2024-05-27 22:03 UTC, marcosrdz commented on screen/wallets/PaymentCodesList.tsx
> +  const navigation = useNavigation();
Use useExtendedNavigation

2024-05-27 22:14 UTC, Overtorment commented on screen/wallets/PaymentCodesList.tsx
> +  const navigation = useNavigation();
fixed

2024-05-27 22:15 UTC, marcosrdz approved these changes

2024-05-27 22:25 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6hiyejp7dzsjzepc662ny4cnwa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1785)

2024-05-27 22:39 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5sameoivhbqg5vtdyyfacscuje?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1786)

2024-05-27 23:26 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b2qpqqnbq43rjvzdmi2ds7ltny?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1787)

2024-05-28 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-05-28 14:04 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k2zqwarjcxvxk64zjdwpu4fnfy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1788)

2024-05-29 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-05-29 22:49 UTC, limpbrains approved these changes

2024-05-29 23:01 UTC, merged

2024-09-08 11:58 UTC, BenWestgate commented on screen/wallets/PaymentCodesList.tsx
>        setReload(Math.random());
Shouldn't a _cryptographically secure_ random number generator be used here? The output of `Math.random()` can be predicted from the initial seed and previous states.

2024-09-08 11:58 UTC, BenWestgate commented on screen/wallets/PaymentCodesList.tsx
>        setReload(Math.random());
Also lines 191 and 230. Please explain why `Math.random()` is used, it seems like this could allow linking different PayNym addresses together more easily.

2024-09-08 12:03 UTC, Overtorment commented on screen/wallets/PaymentCodesList.tsx
>        setReload(Math.random());
sir, you are looking at ui code. this  random is only needed so react knows something changed in the component and it needs to be re-rendered.