FIX: Default state was null and could need to crashes (race conditions)
BlueWallet/BlueWallet pull request #6631
Opened 2024-05-31 00:05 UTC by marcosrdz

2024-05-31 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-05-31 11:14 UTC, limpbrains commented
I have doubts about this solution. What if the function you are calling is a critical one, such as setting a password or saving a wallet? If it merely executes a stub function instead of performing its intended task, you could lose important data.

Additionally, if the stub function returns an empty string, the app may crash because it cannot parse it.

I don’t think this is a good approach. It would be better to address the specific issue causing the failure. Perhaps consider delaying the app's rendering while this variable is being initialized.

2024-05-31 13:52 UTC, marcosrdz commented
> I have doubts about this solution. What if the function you are calling is a critical one, such as setting a password or saving a wallet? If it merely executes a stub function instead of performing its intended task, you could lose important data.
> 
> 
> 
> Additionally, if the stub function returns an empty string, the app may crash because it cannot parse it.
> 
> 
> 
> I don’t think this is a good approach. It would be better to address the specific issue causing the failure. Perhaps consider delaying the app's rendering while this variable is being initialized.

True. This makes me think perhaps those critical functions shouldn't even by inside the Provider.

2024-05-31 16:29 UTC, limpbrains commented
I would say anything that doesn't need react context doesn't need to inside the Provider

2024-06-01 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-01 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-06-02 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-02 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-06-03 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-03 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-06-04 09:43 UTC, Overtorment requested changes
tests failed

2024-06-04 09:43 UTC, Overtorment commented on blue_modules/storage-context.tsx
> +
is there a better way then to provide a dummy state with all the fields thats not gona be actually used? feels like a waste, and like smart people probably figured out a solution

2024-06-04 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-05 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-05 21:54 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/h2dvuldij6yo5txy2pu2iilaim?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1885)

2024-06-06 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-06-06 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-07 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-06-07 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-08 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-06-08 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-08 11:27 UTC, limpbrains commented
Looks like new solution is just the same as old, with a few functions from BlueApp, right? 
So the issue remains - dummy functions that are not doing anything.
If this is the only solution, maybe add logging or throw an error inside the function, so we can know when dummy is being called?

2024-06-09 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-06-09 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-09 21:09 UTC, Overtorment approved these changes

2024-06-09 21:11 UTC, Overtorment commented on components/Context/StorageProvider.tsx
> +export const StorageContext = createContext<StorageContextType>(defaultContext);
not ts expert, but is it possible to throw away  `StorageContextType`
and just use `typeof defaultContext`, if we are going with using `defaultContext` anyway?

2024-06-09 21:13 UTC, marcosrdz commented on components/Context/StorageProvider.tsx
> +export const StorageContext = createContext<StorageContextType>(defaultContext);
defaultContext is an object. StorageContextType is the type

2024-06-09 21:15 UTC, Overtorment commented on components/Context/StorageProvider.tsx
> +export const StorageContext = createContext<StorageContextType>(defaultContext);
yeah so construction like this, it returns type? not sure, im bad at ts

`typeof defaultContext`

2024-06-10 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-10 14:04 UTC, closed without merging

2024-06-10 14:04 UTC, Overtorment commented
ok i dont really like the solution here. there must be a better way

2024-06-10 14:13 UTC, limpbrains commented
Could it be beause of some parts are now lazy-loaded?

2024-06-10 14:15 UTC, marcosrdz commented
> Could it be beause of some parts are now lazy-loaded?

Only the screens past WalletsList. Everything else is the same

2024-06-10 14:33 UTC, limpbrains commented
How do I replicate this issue?
I'm thinking, maybe only render `children` in StorageProvider only if everything is ready?
Something like
```jsx
<StorageContext.Provider value={value}>{value !== undefined && children}</StorageContext.Provider>
```