fix: upgrade slip39 dependency
BlueWallet/BlueWallet pull request #6639
Opened 2024-06-01 10:49 UTC by limpbrains

React native now has native BigInt support. We don't have to maintain our slip39-js fork anymore.
Also new version now includes "extendable backup flag" feature

closes #6603

2024-06-01 11:27 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xhspsbr47wg57pwwc24juqkn2q?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1818)

2024-06-01 21:44 UTC, Overtorment requested changes

2024-06-02 19:43 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/giztkccpga5rlmh6ymwsxjf5pm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1842)

2024-06-03 07:26 UTC, limpbrains commented on package.json
> +    "slip39": "0.1.9",
done

2024-06-03 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-06-04 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-06-04 10:47 UTC, Overtorment approved these changes

2024-06-04 10:51 UTC, merged

2024-06-04 10:51 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!