Receietab
BlueWallet/BlueWallet pull request #6671
Opened 2024-06-07 13:38 UTC by marcosrdz

2024-06-07 14:02 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/um3bhyhxylmlrcsaiom5qgmwgy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1899)

2024-06-07 17:17 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y73nxcruclwtunw3lvgyzo3eem?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1900)

2024-06-07 18:13 UTC, Overtorment requested changes

2024-06-07 18:13 UTC, Overtorment commented on screen/wallets/PaymentCodesList.tsx
> +      merge: true,
i'd suggest a slightly different workflow.

when this screen is called from SendDetails screen, pass a parameter that will mean that any tap on any contact will lead to `_navigateToSend()`. maybe open in a modal..?


and if the screen is just opened, then everything works as before - with a popup that offers to rename, etc.
place button that leads to contacts on WalletDetails screen (as it was originally)

2024-06-07 19:48 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z45ubh2o3bqitq4zbbwl63hsha?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1912)

2024-06-07 22:28 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rqcqzud4qx4tzflpil66fehgei?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1916)

2024-06-08 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-08 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-06-08 14:33 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/i4mmjh24mj6fhcdkruhxocewde?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1922)

2024-06-09 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-09 10:04 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-06-09 21:01 UTC, Overtorment requested changes
a bunch of tests failed

2024-06-10 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

2024-06-10 13:51 UTC, Overtorment requested changes
whoa a lot of tests failed

2024-06-10 13:52 UTC, marcosrdz commented
Yup. This relies on a another PR being merged

2024-06-10 15:11 UTC, GladosBlueWallet commented
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2kc67oi2he7oxdixyv6lbu7e6e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1961)

2024-06-10 16:12 UTC, Overtorment approved these changes

2024-06-10 16:12 UTC, Overtorment commented on navigation/DetailViewStackParamList.ts
> +      };
why this whole block is duplicated here and in `navigation/SendDetailsStackParamList.ts` ?
or are they different?

if they are the same, is there a way to unify them?

2024-06-10 16:12 UTC, Overtorment commented on navigation/DetailViewStackParamList.ts
> +      };
@marcosrdz

2024-06-10 16:14 UTC, marcosrdz commented on navigation/DetailViewStackParamList.ts
> +      };
One is for a stack. The other is for the screen directly. 

Meaning..one is for when its a modal and the other is when its directly to the screen

2024-06-10 16:18 UTC, Overtorment commented on navigation/DetailViewStackParamList.ts
> +      };
so its ok to have them both? can we unify somehow?

2024-06-10 16:19 UTC, marcosrdz commented on navigation/DetailViewStackParamList.ts
> +      };
Not that im aware of as they are different parameters. I could be wrong. Perhaps @limpbrains knows

2024-06-10 19:03 UTC, marcosrdz commented on navigation/DetailViewStackParamList.ts
> +      };
Done

2024-06-10 19:48 UTC, merged