Widgetkotlin
BlueWallet/BlueWallet pull request #6784
Opened 2024-07-11 02:39 UTC by marcosrdz

2024-07-12 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-07-13 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-07-14 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-07-15 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-07-16 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-07-16 11:14 UTC, Overtorment requested changes
did ios build fail..?

2024-07-16 11:14 UTC, Overtorment commented on android/app/src/androidTest/java/io/bluewallet/bluewallet/DetoxTest.java
> +public class    DetoxTest {
unnecessary change

2024-07-16 11:14 UTC, Overtorment commented on ios/BlueWalletTests/PriceViewTests.swift
> +@testable import BlueWallet
```
GitHub Actions
/ build

no such module 'BlueWallet'
```

2024-07-16 12:26 UTC, Overtorment requested changes
![image](https://github.com/user-attachments/assets/f6f0f8e6-fb36-41f4-bc6f-69495b0b98c1)

2024-07-16 14:34 UTC, Overtorment approved these changes

2024-07-16 14:36 UTC, merged