FIX: App crash when local node is down #7027
BlueWallet/BlueWallet pull request #7035
Opened 2024-09-08 23:09 UTC by marcosrdz

2024-09-09 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-09-10 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-09-11 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-09-12 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-09-13 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-09-14 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-09-15 10:01 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-09-15 17:10 UTC, Overtorment requested changes
shitpost quality pr

2024-09-15 17:10 UTC, Overtorment commented on blue_modules/BlueElectrum.ts
> +  const isOnline = await testConnection(
i suspect the issue is something else. `testConnection` uses the same mechanism to connect, so it should crash too.

plus its not even supposed to crash, connection is inside try-catch, and we handle bad connection pretty well, by having `onError` handler, offering dialog with retries, stop, or change electrum server.

2024-09-15 17:10 UTC, Overtorment commented on blue_modules/BlueElectrum.ts
> -        // most likely got a timeout from electrum ping. lets reconnect
useful coment gone

2024-09-15 17:10 UTC, Overtorment commented on blue_modules/BlueElectrum.ts
> -    // Must be running on Android
useful coment gone

2024-09-15 17:10 UTC, Overtorment commented on blue_modules/BlueElectrum.ts
> +        if (electrumImplementation === 'electrs' && semVerToInt(electrumVersion) >= semVerToInt('0.9.0')) {
switch-case is way more readable. bad.

2024-09-15 17:10 UTC, Overtorment commented on blue_modules/BlueElectrum.ts
> +    connectionAttempt += 1;
change for a sake of change. did chatgpt refactor this file?

2024-09-15 17:10 UTC, closed without merging

2024-09-15 17:10 UTC, Overtorment commented
closing as root cause of crashes is unclear