ADD: Debug messages for useWatch
BlueWallet/BlueWallet pull request #7302
Opened 2024-11-12 02:17 UTC by marcosrdz

2024-11-12 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-11-12 13:22 UTC, Overtorment requested changes
too big diff, 24 files changed.
looks like it has some other prs..?
conflicts

2024-11-17 21:43 UTC, marcosrdz commented
@Overtorment  its definitely  not feature for feature complete as the old app but at least now it can sync

2024-11-18 10:19 UTC, Overtorment requested changes
* integration tests faile
* looks like this PR can be slpit into several: i noticed ruby cache istouched here, currency js, on top of watchos swift code

2026-07-27 08:09 UTC, closed without merging