REF: Notifications Token handling
BlueWallet/BlueWallet pull request #7307
Opened 2024-11-13 05:36 UTC by marcosrdz

2024-11-13 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-11-13 14:50 UTC, Overtorment requested changes
notifications actually started working for me.
alli had to do was to go to RECEIVE screen and then app threw a dialog and requested permissions (for some reason permission dialogue was thrown twice).

do we even need this PR anymore? tbh this pr looks like a bunch of scattered code.
if only there were code comments to help me understad why this or that chunk of code was written in the first place...

2024-11-13 14:50 UTC, Overtorment commented on blue_modules/notifications.js
> +        await fetch(`${baseURI}/invalidateToken`, {
hijo de puta, que es `/invalidateToken`, pendejo?
tu no puedo commit LLM code siempre

2024-11-13 19:43 UTC, marcosrdz commented
> RECEIVE

yes we should. it allows generating new token and handles "blocked" Status

2024-11-14 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-11-15 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-11-15 17:30 UTC, Overtorment requested changes
just tested build *38109 and if you keepturning notifications in the app off an on, it keeps issuing a new token every time.

token should stay the same during the lifetime of an app (with the exception when user forcefully turns off notificaions for BW in OS settings, in that case GC server will  get an error trying to push tosuch tomen and will clenanup this token and all subscriptions from the database; btw this also happens when app is deleted)

2024-11-15 21:25 UTC, marcosrdz commented
> just tested build *38109 and if you keepturning notifications in the app off an on, it keeps issuing a new token every time.
> 
> 
> 
> token should stay the same during the lifetime of an app (with the exception when user forcefully turns off notificaions for BW in OS settings, in that case GC server will  get an error trying to push tosuch tomen and will clenanup this token and all subscriptions from the database; btw this also happens when app is deleted) 
> 
> 

That means the user will still get notifications be it silently if they still have a valid token even though the toggled it off. That would defeat the purpose

2024-11-16 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-11-17 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-11-18 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-11-18 10:39 UTC, Overtorment commented
waiting for a fresh testflight build to test it

2024-11-18 17:23 UTC, Overtorment requested changes
just tested *6447. it still acquires new token every time you disable and enable the pushes

e2e failed as well btw

2024-11-20 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-11-21 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-11-22 10:06 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-11-23 10:05 UTC, GladosBlueWallet commented
Wake the fuck up samurai, we have PRs to merge

![image](https://user-images.githubusercontent.com/1913337/127044132-147fa451-6dc1-454f-907a-9292033047f2.png)

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

2024-11-23 20:58 UTC, Overtorment approved these changes
lgtm

2024-11-23 20:59 UTC, merged

2024-11-23 20:59 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!