REF: Currency.ts DefaultPreference
BlueWallet/BlueWallet pull request #7332
Opened 2024-11-18 21:43 UTC by marcosrdz

DefaultPreference uses truly native preference read/write which will eliminate the need to sync from asyncstorage in JS. Makes extensions such as watchOS and widgets easier to deal with

2024-11-23 21:54 UTC, Overtorment requested changes
mostly lgtm

2024-11-23 21:54 UTC, Overtorment commented on ios/BlueWallet.xcodeproj/xcshareddata/xcschemes/BlueWalletWatch (Notification).xcscheme
> +use
doesnt feel right, like this  file is broken

2024-11-23 23:39 UTC, Overtorment approved these changes

2024-11-24 00:34 UTC, merged

2024-11-24 00:34 UTC, GladosBlueWallet commented
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!